/**********************************************************************
 * Extern for ReactStripeElements
 * Generated by http://jmmk.github.io/javascript-externs-generator
 * Generated with the web app using: 
 *
 * Loaded JavaScripts:
 * https://github.com/facebook/react/releases/download/v15.6.2/react.min.js
 * https://unpkg.com/react-stripe-elements@1.6.0/dist/react-stripe-elements.js
 * 
 * Enter the JavaScript object you want to extern:
 * ReactStripeElements
 **********************************************************************/

var ReactStripeElements = {
  "CardCVCElement": {
    "contextTypes": {
      "addElementsLoadListener": function () {},
      "registerElement": function () {},
      "unregisterElement": function () {}
    },
    "defaultProps": {
      "className": {},
      "elementRef": {},
      "id": {},
      "onBlur": function () {},
      "onChange": function () {},
      "onFocus": function () {},
      "onReady": function () {}
    },
    "propTypes": {
      "className": {
        "isRequired": function () {}
      },
      "elementRef": {
        "isRequired": function () {}
      },
      "id": {
        "isRequired": function () {}
      },
      "onBlur": {
        "isRequired": function () {}
      },
      "onChange": {
        "isRequired": function () {}
      },
      "onFocus": {
        "isRequired": function () {}
      },
      "onReady": {
        "isRequired": function () {}
      }
    }
  },
  "CardElement": {
    "contextTypes": {
      "addElementsLoadListener": function () {},
      "registerElement": function () {},
      "unregisterElement": function () {}
    },
    "defaultProps": {
      "className": {},
      "elementRef": {},
      "id": {},
      "onBlur": function () {},
      "onChange": function () {},
      "onFocus": function () {},
      "onReady": function () {}
    },
    "propTypes": {
      "className": {
        "isRequired": function () {}
      },
      "elementRef": {
        "isRequired": function () {}
      },
      "id": {
        "isRequired": function () {}
      },
      "onBlur": {
        "isRequired": function () {}
      },
      "onChange": {
        "isRequired": function () {}
      },
      "onFocus": {
        "isRequired": function () {}
      },
      "onReady": {
        "isRequired": function () {}
      }
    }
  },
  "CardExpiryElement": {
    "contextTypes": {
      "addElementsLoadListener": function () {},
      "registerElement": function () {},
      "unregisterElement": function () {}
    },
    "defaultProps": {
      "className": {},
      "elementRef": {},
      "id": {},
      "onBlur": function () {},
      "onChange": function () {},
      "onFocus": function () {},
      "onReady": function () {}
    },
    "propTypes": {
      "className": {
        "isRequired": function () {}
      },
      "elementRef": {
        "isRequired": function () {}
      },
      "id": {
        "isRequired": function () {}
      },
      "onBlur": {
        "isRequired": function () {}
      },
      "onChange": {
        "isRequired": function () {}
      },
      "onFocus": {
        "isRequired": function () {}
      },
      "onReady": {
        "isRequired": function () {}
      }
    }
  },
  "CardNumberElement": {
    "contextTypes": {
      "addElementsLoadListener": function () {},
      "registerElement": function () {},
      "unregisterElement": function () {}
    },
    "defaultProps": {
      "className": {},
      "elementRef": {},
      "id": {},
      "onBlur": function () {},
      "onChange": function () {},
      "onFocus": function () {},
      "onReady": function () {}
    },
    "propTypes": {
      "className": {
        "isRequired": function () {}
      },
      "elementRef": {
        "isRequired": function () {}
      },
      "id": {
        "isRequired": function () {}
      },
      "onBlur": {
        "isRequired": function () {}
      },
      "onChange": {
        "isRequired": function () {}
      },
      "onFocus": {
        "isRequired": function () {}
      },
      "onReady": {
        "isRequired": function () {}
      }
    }
  },
  "Elements": {
    "childContextTypes": {
      "addElementsLoadListener": function () {},
      "getRegisteredElements": function () {},
      "registerElement": function () {},
      "unregisterElement": function () {}
    },
    "contextTypes": {
      "addStripeLoadListener": {
        "isRequired": function () {}
      },
      "stripe": {
        "isRequired": function () {}
      },
      "tag": function () {}
    },
    "defaultProps": {
      "children": {}
    }
  },
  "PaymentRequestButtonElement": {
    "contextTypes": {
      "addElementsLoadListener": function () {},
      "registerElement": function () {},
      "unregisterElement": function () {}
    },
    "defaultProps": {
      "className": {},
      "elementRef": {},
      "id": {},
      "onBlur": function () {},
      "onClick": function () {},
      "onFocus": function () {},
      "onReady": function () {}
    },
    "propTypes": {
      "className": {
        "isRequired": function () {}
      },
      "elementRef": {
        "isRequired": function () {}
      },
      "id": {
        "isRequired": function () {}
      },
      "onBlur": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      },
      "onFocus": {
        "isRequired": function () {}
      },
      "onReady": {
        "isRequired": function () {}
      },
      "paymentRequest": function () {}
    }
  },
  "PostalCodeElement": {
    "contextTypes": {
      "addElementsLoadListener": function () {},
      "registerElement": function () {},
      "unregisterElement": function () {}
    },
    "defaultProps": {
      "className": {},
      "elementRef": {},
      "id": {},
      "onBlur": function () {},
      "onChange": function () {},
      "onFocus": function () {},
      "onReady": function () {}
    },
    "propTypes": {
      "className": {
        "isRequired": function () {}
      },
      "elementRef": {
        "isRequired": function () {}
      },
      "id": {
        "isRequired": function () {}
      },
      "onBlur": {
        "isRequired": function () {}
      },
      "onChange": {
        "isRequired": function () {}
      },
      "onFocus": {
        "isRequired": function () {}
      },
      "onReady": {
        "isRequired": function () {}
      }
    }
  },
  "StripeProvider": {
    "childContextTypes": {
      "addStripeLoadListener": {
        "isRequired": function () {}
      },
      "stripe": {
        "isRequired": function () {}
      },
      "tag": function () {}
    },
    "defaultProps": {
      "apiKey": {},
      "children": {},
      "stripe": {}
    },
    "propTypes": {
      "apiKey": {
        "isRequired": function () {}
      },
      "children": {
        "isRequired": function () {}
      },
      "stripe": {
        "isRequired": function () {}
      }
    }
  },
  "injectStripe": function () {}
};
ReactStripeElements.CardCVCElement.prototype = {
  "_setupEventListeners": function () {},
  "componentDidMount": function () {},
  "componentWillReceiveProps": function () {},
  "componentWillUnmount": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactStripeElements.CardElement.prototype = {
  "_setupEventListeners": function () {},
  "componentDidMount": function () {},
  "componentWillReceiveProps": function () {},
  "componentWillUnmount": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactStripeElements.CardExpiryElement.prototype = {
  "_setupEventListeners": function () {},
  "componentDidMount": function () {},
  "componentWillReceiveProps": function () {},
  "componentWillUnmount": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactStripeElements.CardNumberElement.prototype = {
  "_setupEventListeners": function () {},
  "componentDidMount": function () {},
  "componentWillReceiveProps": function () {},
  "componentWillUnmount": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactStripeElements.Elements.prototype = {
  "forceUpdate": function () {},
  "getChildContext": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactStripeElements.PaymentRequestButtonElement.prototype = {
  "componentDidMount": function () {},
  "componentWillReceiveProps": function () {},
  "componentWillUnmount": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactStripeElements.PostalCodeElement.prototype = {
  "_setupEventListeners": function () {},
  "componentDidMount": function () {},
  "componentWillReceiveProps": function () {},
  "componentWillUnmount": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactStripeElements.StripeProvider.prototype = {
  "componentWillReceiveProps": function () {},
  "forceUpdate": function () {},
  "getChildContext": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactStripeElements
/**********************************************************************/