/**********************************************************************
 * Extern for ReactStripeElements
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactStripeElements = {
    "AuBankAccountElement": {
        "contextTypes": {
            "addElementsLoadListener": {
                "isRequired": function () {}
            },
            "registerElement": {
                "isRequired": function () {}
            },
            "unregisterElement": {
                "isRequired": function () {}
            }
        },
        "defaultProps": {
            "className": {},
            "id": {},
            "onBlur": function () {},
            "onChange": function () {},
            "onFocus": function () {},
            "onReady": function () {}
        },
        "displayName": {},
        "propTypes": {
            "className": {
                "isRequired": function () {}
            },
            "id": {
                "isRequired": function () {}
            },
            "onBlur": {
                "isRequired": function () {}
            },
            "onChange": {
                "isRequired": function () {}
            },
            "onFocus": {
                "isRequired": function () {}
            },
            "onReady": {
                "isRequired": function () {}
            }
        }
    },
    "CardCVCElement": {
        "contextTypes": {
            "addElementsLoadListener": {
                "isRequired": function () {}
            },
            "registerElement": {
                "isRequired": function () {}
            },
            "unregisterElement": {
                "isRequired": function () {}
            }
        },
        "defaultProps": {
            "className": {},
            "id": {},
            "onBlur": function () {},
            "onChange": function () {},
            "onFocus": function () {},
            "onReady": function () {}
        },
        "displayName": {},
        "propTypes": {
            "className": {
                "isRequired": function () {}
            },
            "id": {
                "isRequired": function () {}
            },
            "onBlur": {
                "isRequired": function () {}
            },
            "onChange": {
                "isRequired": function () {}
            },
            "onFocus": {
                "isRequired": function () {}
            },
            "onReady": {
                "isRequired": function () {}
            }
        }
    },
    "CardCvcElement": {
        "contextTypes": {
            "addElementsLoadListener": {
                "isRequired": function () {}
            },
            "registerElement": {
                "isRequired": function () {}
            },
            "unregisterElement": {
                "isRequired": function () {}
            }
        },
        "defaultProps": {
            "className": {},
            "id": {},
            "onBlur": function () {},
            "onChange": function () {},
            "onFocus": function () {},
            "onReady": function () {}
        },
        "displayName": {},
        "propTypes": {
            "className": {
                "isRequired": function () {}
            },
            "id": {
                "isRequired": function () {}
            },
            "onBlur": {
                "isRequired": function () {}
            },
            "onChange": {
                "isRequired": function () {}
            },
            "onFocus": {
                "isRequired": function () {}
            },
            "onReady": {
                "isRequired": function () {}
            }
        }
    },
    "CardElement": {
        "contextTypes": {
            "addElementsLoadListener": {
                "isRequired": function () {}
            },
            "registerElement": {
                "isRequired": function () {}
            },
            "unregisterElement": {
                "isRequired": function () {}
            }
        },
        "defaultProps": {
            "className": {},
            "id": {},
            "onBlur": function () {},
            "onChange": function () {},
            "onFocus": function () {},
            "onReady": function () {}
        },
        "displayName": {},
        "propTypes": {
            "className": {
                "isRequired": function () {}
            },
            "id": {
                "isRequired": function () {}
            },
            "onBlur": {
                "isRequired": function () {}
            },
            "onChange": {
                "isRequired": function () {}
            },
            "onFocus": {
                "isRequired": function () {}
            },
            "onReady": {
                "isRequired": function () {}
            }
        }
    },
    "CardExpiryElement": {
        "contextTypes": {
            "addElementsLoadListener": {
                "isRequired": function () {}
            },
            "registerElement": {
                "isRequired": function () {}
            },
            "unregisterElement": {
                "isRequired": function () {}
            }
        },
        "defaultProps": {
            "className": {},
            "id": {},
            "onBlur": function () {},
            "onChange": function () {},
            "onFocus": function () {},
            "onReady": function () {}
        },
        "displayName": {},
        "propTypes": {
            "className": {
                "isRequired": function () {}
            },
            "id": {
                "isRequired": function () {}
            },
            "onBlur": {
                "isRequired": function () {}
            },
            "onChange": {
                "isRequired": function () {}
            },
            "onFocus": {
                "isRequired": function () {}
            },
            "onReady": {
                "isRequired": function () {}
            }
        }
    },
    "CardNumberElement": {
        "contextTypes": {
            "addElementsLoadListener": {
                "isRequired": function () {}
            },
            "registerElement": {
                "isRequired": function () {}
            },
            "unregisterElement": {
                "isRequired": function () {}
            }
        },
        "defaultProps": {
            "className": {},
            "id": {},
            "onBlur": function () {},
            "onChange": function () {},
            "onFocus": function () {},
            "onReady": function () {}
        },
        "displayName": {},
        "propTypes": {
            "className": {
                "isRequired": function () {}
            },
            "id": {
                "isRequired": function () {}
            },
            "onBlur": {
                "isRequired": function () {}
            },
            "onChange": {
                "isRequired": function () {}
            },
            "onFocus": {
                "isRequired": function () {}
            },
            "onReady": {
                "isRequired": function () {}
            }
        }
    },
    "Elements": {
        "childContextTypes": {
            "addElementsLoadListener": {
                "isRequired": function () {}
            },
            "elements": {
                "isRequired": function () {}
            },
            "getRegisteredElements": {
                "isRequired": function () {}
            },
            "registerElement": {
                "isRequired": function () {}
            },
            "unregisterElement": {
                "isRequired": function () {}
            }
        },
        "contextTypes": {
            "addStripeLoadListener": {
                "isRequired": function () {}
            },
            "stripe": {
                "isRequired": function () {}
            },
            "tag": {
                "isRequired": function () {}
            }
        },
        "defaultProps": {
            "children": {}
        }
    },
    "FpxBankElement": {
        "contextTypes": {
            "addElementsLoadListener": {
                "isRequired": function () {}
            },
            "registerElement": {
                "isRequired": function () {}
            },
            "unregisterElement": {
                "isRequired": function () {}
            }
        },
        "defaultProps": {
            "className": {},
            "id": {},
            "onBlur": function () {},
            "onChange": function () {},
            "onFocus": function () {},
            "onReady": function () {}
        },
        "displayName": {},
        "propTypes": {
            "className": {
                "isRequired": function () {}
            },
            "id": {
                "isRequired": function () {}
            },
            "onBlur": {
                "isRequired": function () {}
            },
            "onChange": {
                "isRequired": function () {}
            },
            "onFocus": {
                "isRequired": function () {}
            },
            "onReady": {
                "isRequired": function () {}
            }
        }
    },
    "IbanElement": {
        "contextTypes": {
            "addElementsLoadListener": {
                "isRequired": function () {}
            },
            "registerElement": {
                "isRequired": function () {}
            },
            "unregisterElement": {
                "isRequired": function () {}
            }
        },
        "defaultProps": {
            "className": {},
            "id": {},
            "onBlur": function () {},
            "onChange": function () {},
            "onFocus": function () {},
            "onReady": function () {}
        },
        "displayName": {},
        "propTypes": {
            "className": {
                "isRequired": function () {}
            },
            "id": {
                "isRequired": function () {}
            },
            "onBlur": {
                "isRequired": function () {}
            },
            "onChange": {
                "isRequired": function () {}
            },
            "onFocus": {
                "isRequired": function () {}
            },
            "onReady": {
                "isRequired": function () {}
            }
        }
    },
    "IdealBankElement": {
        "contextTypes": {
            "addElementsLoadListener": {
                "isRequired": function () {}
            },
            "registerElement": {
                "isRequired": function () {}
            },
            "unregisterElement": {
                "isRequired": function () {}
            }
        },
        "defaultProps": {
            "className": {},
            "id": {},
            "onBlur": function () {},
            "onChange": function () {},
            "onFocus": function () {},
            "onReady": function () {}
        },
        "displayName": {},
        "propTypes": {
            "className": {
                "isRequired": function () {}
            },
            "id": {
                "isRequired": function () {}
            },
            "onBlur": {
                "isRequired": function () {}
            },
            "onChange": {
                "isRequired": function () {}
            },
            "onFocus": {
                "isRequired": function () {}
            },
            "onReady": {
                "isRequired": function () {}
            }
        }
    },
    "PaymentRequestButtonElement": {
        "contextTypes": {
            "addElementsLoadListener": {
                "isRequired": function () {}
            },
            "registerElement": {
                "isRequired": function () {}
            },
            "unregisterElement": {
                "isRequired": function () {}
            }
        },
        "defaultProps": {
            "className": {},
            "id": {},
            "onBlur": function () {},
            "onClick": function () {},
            "onFocus": function () {},
            "onReady": function () {}
        },
        "propTypes": {
            "className": {
                "isRequired": function () {}
            },
            "id": {
                "isRequired": function () {}
            },
            "onBlur": {
                "isRequired": function () {}
            },
            "onClick": {
                "isRequired": function () {}
            },
            "onFocus": {
                "isRequired": function () {}
            },
            "onReady": {
                "isRequired": function () {}
            },
            "paymentRequest": {
                "isRequired": function () {}
            }
        }
    },
    "StripeProvider": {
        "childContextTypes": {
            "addStripeLoadListener": {
                "isRequired": function () {}
            },
            "stripe": {
                "isRequired": function () {}
            },
            "tag": {
                "isRequired": function () {}
            }
        },
        "defaultProps": {
            "apiKey": {},
            "children": {},
            "stripe": {
                // Note that these are dynamically injected.
                // They aren't picked up by externs generation and need to be manually preserved.
                // https://github.com/stripe/react-stripe-elements/blob/v6.0.1/src/components/inject.js#L98-L108
                "createToken": function () {},
                "createSource": function () {},
                "createPaymentMethod": function () {},
                "handleCardPayment": function () {},
                "handleCardSetup": function () {}
            }
        },
        "propTypes": {
            "apiKey": {
                "isRequired": function () {}
            },
            "children": {
                "isRequired": function () {}
            },
            "stripe": {
                "isRequired": function () {}
            }
        }
    },
    "injectStripe": function () {}
};
ReactStripeElements.AuBankAccountElement.prototype = {
    "_setupEventListeners": function () {},
    "componentDidMount": function () {},
    "componentDidUpdate": function () {},
    "componentWillUnmount": function () {},
    "forceUpdate": function () {},
    "isReactComponent": function () {},
    "render": function () {},
    "setState": function () {}
};
ReactStripeElements.CardCVCElement.prototype = {
    "_setupEventListeners": function () {},
    "componentDidMount": function () {},
    "componentDidUpdate": function () {},
    "componentWillUnmount": function () {},
    "forceUpdate": function () {},
    "isReactComponent": function () {},
    "render": function () {},
    "setState": function () {}
};
ReactStripeElements.CardCvcElement.prototype = {
    "_setupEventListeners": function () {},
    "componentDidMount": function () {},
    "componentDidUpdate": function () {},
    "componentWillUnmount": function () {},
    "forceUpdate": function () {},
    "isReactComponent": function () {},
    "render": function () {},
    "setState": function () {}
};
ReactStripeElements.CardElement.prototype = {
    "_setupEventListeners": function () {},
    "componentDidMount": function () {},
    "componentDidUpdate": function () {},
    "componentWillUnmount": function () {},
    "forceUpdate": function () {},
    "isReactComponent": function () {},
    "render": function () {},
    "setState": function () {}
};
ReactStripeElements.CardExpiryElement.prototype = {
    "_setupEventListeners": function () {},
    "componentDidMount": function () {},
    "componentDidUpdate": function () {},
    "componentWillUnmount": function () {},
    "forceUpdate": function () {},
    "isReactComponent": function () {},
    "render": function () {},
    "setState": function () {}
};
ReactStripeElements.CardNumberElement.prototype = {
    "_setupEventListeners": function () {},
    "componentDidMount": function () {},
    "componentDidUpdate": function () {},
    "componentWillUnmount": function () {},
    "forceUpdate": function () {},
    "isReactComponent": function () {},
    "render": function () {},
    "setState": function () {}
};
ReactStripeElements.Elements.prototype = {
    "forceUpdate": function () {},
    "getChildContext": function () {},
    "isReactComponent": function () {},
    "render": function () {},
    "setState": function () {}
};
ReactStripeElements.FpxBankElement.prototype = {
    "_setupEventListeners": function () {},
    "componentDidMount": function () {},
    "componentDidUpdate": function () {},
    "componentWillUnmount": function () {},
    "forceUpdate": function () {},
    "isReactComponent": function () {},
    "render": function () {},
    "setState": function () {}
};
ReactStripeElements.IbanElement.prototype = {
    "_setupEventListeners": function () {},
    "componentDidMount": function () {},
    "componentDidUpdate": function () {},
    "componentWillUnmount": function () {},
    "forceUpdate": function () {},
    "isReactComponent": function () {},
    "render": function () {},
    "setState": function () {}
};
ReactStripeElements.IdealBankElement.prototype = {
    "_setupEventListeners": function () {},
    "componentDidMount": function () {},
    "componentDidUpdate": function () {},
    "componentWillUnmount": function () {},
    "forceUpdate": function () {},
    "isReactComponent": function () {},
    "render": function () {},
    "setState": function () {}
};
ReactStripeElements.PaymentRequestButtonElement.prototype = {
    "componentDidMount": function () {},
    "componentDidUpdate": function () {},
    "componentWillUnmount": function () {},
    "forceUpdate": function () {},
    "isReactComponent": function () {},
    "render": function () {},
    "setState": function () {}
};
ReactStripeElements.StripeProvider.prototype = {
    "_register": function () {},
    "componentDidUpdate": function () {},
    "forceUpdate": function () {},
    "getChildContext": function () {},
    "isReactComponent": function () {},
    "render": function () {},
    "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactStripeElements
/**********************************************************************/
