var XXH = {
        "h32": {
            "seed": {
                "_low": {},
                "_high": {},
                "remainder": function () {},
                "fromBits": function () {},
                "fromNumber": function () {},
                "fromString": function () {},
                "toNumber": function () {},
                "toString": function () {},
                "add": function () {},
                "subtract": function () {},
                "multiply": function () {},
                "div": function () {},
                "not": function () {},
                "negate": function () {},
                "eq": function () {},
                "equals": function () {},
                "gt": function () {},
                "greaterThan": function () {},
                "lt": function () {},
                "lessThan": function () {},
                "or": function () {},
                "and": function () {},
                "xor": function () {},
                "shiftr": function () {},
                "shiftRight": function () {},
                "shiftl": function () {},
                "shiftLeft": function () {},
                "rotl": function () {},
                "rotateLeft": function () {},
                "rotr": function () {},
                "rotateRight": function () {},
                "clone": function () {},
                "xxh_update": function () {}
            },
            "v1": {
                "_low": {},
                "_high": {},
                "remainder": function () {},
                "fromBits": function () {},
                "fromNumber": function () {},
                "fromString": function () {},
                "toNumber": function () {},
                "toString": function () {},
                "add": function () {},
                "subtract": function () {},
                "multiply": function () {},
                "div": function () {},
                "not": function () {},
                "negate": function () {},
                "eq": function () {},
                "equals": function () {},
                "gt": function () {},
                "greaterThan": function () {},
                "lt": function () {},
                "lessThan": function () {},
                "or": function () {},
                "and": function () {},
                "xor": function () {},
                "shiftr": function () {},
                "shiftRight": function () {},
                "shiftl": function () {},
                "shiftLeft": function () {},
                "rotl": function () {},
                "rotateLeft": function () {},
                "rotr": function () {},
                "rotateRight": function () {},
                "clone": function () {},
                "xxh_update": function () {}
            },
            "v2": {
                "_low": {},
                "_high": {},
                "remainder": function () {},
                "fromBits": function () {},
                "fromNumber": function () {},
                "fromString": function () {},
                "toNumber": function () {},
                "toString": function () {},
                "add": function () {},
                "subtract": function () {},
                "multiply": function () {},
                "div": function () {},
                "not": function () {},
                "negate": function () {},
                "eq": function () {},
                "equals": function () {},
                "gt": function () {},
                "greaterThan": function () {},
                "lt": function () {},
                "lessThan": function () {},
                "or": function () {},
                "and": function () {},
                "xor": function () {},
                "shiftr": function () {},
                "shiftRight": function () {},
                "shiftl": function () {},
                "shiftLeft": function () {},
                "rotl": function () {},
                "rotateLeft": function () {},
                "rotr": function () {},
                "rotateRight": function () {},
                "clone": function () {},
                "xxh_update": function () {}
            },
            "v3": {
                "_low": {},
                "_high": {},
                "remainder": function () {},
                "fromBits": function () {},
                "fromNumber": function () {},
                "fromString": function () {},
                "toNumber": function () {},
                "toString": function () {},
                "add": function () {},
                "subtract": function () {},
                "multiply": function () {},
                "div": function () {},
                "not": function () {},
                "negate": function () {},
                "eq": function () {},
                "equals": function () {},
                "gt": function () {},
                "greaterThan": function () {},
                "lt": function () {},
                "lessThan": function () {},
                "or": function () {},
                "and": function () {},
                "xor": function () {},
                "shiftr": function () {},
                "shiftRight": function () {},
                "shiftl": function () {},
                "shiftLeft": function () {},
                "rotl": function () {},
                "rotateLeft": function () {},
                "rotr": function () {},
                "rotateRight": function () {},
                "clone": function () {},
                "xxh_update": function () {}
            },
            "v4": {
                "_low": {},
                "_high": {},
                "remainder": function () {},
                "fromBits": function () {},
                "fromNumber": function () {},
                "fromString": function () {},
                "toNumber": function () {},
                "toString": function () {},
                "add": function () {},
                "subtract": function () {},
                "multiply": function () {},
                "div": function () {},
                "not": function () {},
                "negate": function () {},
                "eq": function () {},
                "equals": function () {},
                "gt": function () {},
                "greaterThan": function () {},
                "lt": function () {},
                "lessThan": function () {},
                "or": function () {},
                "and": function () {},
                "xor": function () {},
                "shiftr": function () {},
                "shiftRight": function () {},
                "shiftl": function () {},
                "shiftLeft": function () {},
                "rotl": function () {},
                "rotateLeft": function () {},
                "rotr": function () {},
                "rotateRight": function () {},
                "clone": function () {},
                "xxh_update": function () {}
            },
            "total_len": {},
            "memsize": {},
            "memory": function () {},
            "init": function () {},
            "update": function () {},
            "digest": function () {}
        }
}
