var BABYLON = {
    "EffectFallbacks": function () {},
    "EffectCreationOptions": function () {},
    "Effect": function () {},
    "KeyboardEventTypes": function () {},
    "KeyboardInfo": function () {},
    "KeyboardInfoPre": function () {},
    "PointerEventTypes": function () {},
    "PointerInfoBase": function () {},
    "PointerInfoPre": function () {},
    "PointerInfo": function () {},
    "ToGammaSpace": {},
    "ToLinearSpace": {},
    "Epsilon": {},
    "Color3": function () {},
    "Color4": function () {},
    "Vector2": function () {},
    "Vector3": function () {},
    "Vector4": function () {},
    "Size": function () {},
    "Quaternion": function () {},
    "Matrix": function () {},
    "Plane": function () {},
    "Viewport": function () {},
    "Frustum": function () {},
    "Space": {
        "0": {},
        "1": {},
        "2": {},
        "LOCAL": {},
        "WORLD": {},
        "BONE": {}
    },
    "Axis": function () {},
    "BezierCurve": function () {},
    "Orientation": {
        "0": {},
        "1": {},
        "CW": {},
        "CCW": {}
    },
    "Angle": function () {},
    "Arc2": function () {},
    "Path2": function () {},
    "Path3D": function () {},
    "Curve3": function () {},
    "PositionNormalVertex": function () {},
    "PositionNormalTextureVertex": function () {},
    "Tmp": function () {},
    "Scalar": function () {},
    "expandToProperty": function () {},
    "serialize": function () {},
    "serializeAsTexture": function () {},
    "serializeAsColor3": function () {},
    "serializeAsFresnelParameters": function () {},
    "serializeAsVector2": function () {},
    "serializeAsVector3": function () {},
    "serializeAsMeshReference": function () {},
    "serializeAsColorCurves": function () {},
    "serializeAsColor4": function () {},
    "serializeAsImageProcessingConfiguration": function () {},
    "serializeAsQuaternion": function () {},
    "serializeAsCameraReference": function () {},
    "SerializationHelper": function () {},
    "Deferred": function () {},
    "EventState": function () {},
    "Observer": function () {},
    "MultiObserver": function () {},
    "Observable": function () {},
    "SmartArray": function () {},
    "SmartArrayNoDuplicate": function () {},
    "ColorGradient": function () {},
    "Color3Gradient": function () {},
    "FactorGradient": function () {},
    "LoadFileError": function () {},
    "RetryStrategy": function () {},
    "Tools": function () {},
    "PerfCounter": function () {},
    "className": function () {},
    "AsyncLoop": function () {},
    "PromisePolyfill": function () {},
    "WorkerPool": function () {},
    "_AlphaState": function () {},
    "_DepthCullingState": function () {},
    "_StencilState": function () {},
    "InstancingAttributeInfo": function () {},
    "RenderTargetCreationOptions": function () {},
    "DepthTextureCreationOptions": function () {},
    "EngineCapabilities": function () {},
    "Engine": function () {},
    "Node": function () {},
    "BoundingSphere": function () {},
    "BoundingBox": function () {},
    "BoundingInfo": function () {},
    "TransformNode": function () {},
    "AbstractMesh": function () {},
    "Light": function () {},
    "Camera": function () {},
    "RenderingManager": function () {},
    "RenderingGroup": function () {},
    "SceneComponentConstants": function () {},
    "Stage": function () {},
    "AbstractScene": function () {},
    "RenderingGroupInfo": function () {},
    "Scene": function () {},
    "KeepAssets": function () {},
    "AssetContainer": function () {},
    "Buffer": function () {},
    "VertexBuffer": function () {},
    "DummyInternalTextureTracker": function () {},
    "InternalTexture": function () {},
    "BaseTexture": function () {},
    "Texture": function () {},
    "_CreationDataStorage": function () {},
    "_InstancesBatch": function () {},
    "Mesh": function () {},
    "BaseSubMesh": function () {},
    "SubMesh": function () {},
    "MaterialDefines": function () {},
    "Material": function () {},
    "UniformBuffer": function () {},
    "VertexData": function () {},
    "Geometry": function () {},
    "_PrimitiveGeometry": function () {},
    "RibbonGeometry": function () {},
    "BoxGeometry": function () {},
    "SphereGeometry": function () {},
    "DiscGeometry": function () {},
    "CylinderGeometry": function () {},
    "TorusGeometry": function () {},
    "GroundGeometry": function () {},
    "TiledGroundGeometry": function () {},
    "PlaneGeometry": function () {},
    "TorusKnotGeometry": function () {},
    "PerformanceMonitor": function () {},
    "RollingAverage": function () {},
    "MaterialHelper": function () {},
    "PushMaterial": function () {},
    "StandardMaterialDefines": function () {},
    "StandardMaterial": function () {},
    "SphericalPolynomial": function () {},
    "SphericalHarmonics": function () {},
    "CubeMapToSphericalPolynomialTools": function () {},
    "PBRBaseMaterial": function () {},
    "PBRBaseSimpleMaterial": function () {},
    "PBRMaterial": function () {},
    "PBRMetallicRoughnessMaterial": function () {},
    "PBRSpecularGlossinessMaterial": function () {},
    "CameraInputTypes": {
        "FreeCameraMouseInput": function () {},
        "FreeCameraKeyboardMoveInput": function () {},
        "ArcRotateCameraKeyboardMoveInput": function () {},
        "ArcRotateCameraMouseWheelInput": function () {},
        "ArcRotateCameraPointersInput": function () {},
        "FreeCameraTouchInput": function () {},
        "FreeCameraGamepadInput": function () {},
        "ArcRotateCameraGamepadInput": function () {},
        "FreeCameraDeviceOrientationInput": function () {},
        "ArcRotateCameraVRDeviceOrientationInput": function () {},
        "FreeCameraVirtualJoystickInput": function () {}
    },
    "CameraInputsManager": function () {},
    "TargetCamera": function () {},
    "FreeCameraMouseInput": function () {},
    "FreeCameraKeyboardMoveInput": function () {},
    "FreeCameraInputsManager": function () {},
    "FreeCamera": function () {},
    "ArcRotateCameraKeyboardMoveInput": function () {},
    "ArcRotateCameraMouseWheelInput": function () {},
    "ArcRotateCameraPointersInput": function () {},
    "ArcRotateCameraInputsManager": function () {},
    "ArcRotateCamera": function () {},
    "HemisphericLight": function () {},
    "ShadowLight": function () {},
    "PointLight": function () {},
    "DirectionalLight": function () {},
    "SpotLight": function () {},
    "AnimationPropertiesOverride": function () {},
    "AnimationRange": function () {},
    "AnimationEvent": function () {},
    "PathCursor": function () {},
    "AnimationKeyInterpolation": {
        "1": {},
        "STEP": {}
    },
    "Animation": function () {},
    "TargetedAnimation": function () {},
    "AnimationGroup": function () {},
    "RuntimeAnimation": function () {},
    "Animatable": function () {},
    "EasingFunction": function () {},
    "CircleEase": function () {},
    "BackEase": function () {},
    "BounceEase": function () {},
    "CubicEase": function () {},
    "ElasticEase": function () {},
    "ExponentialEase": function () {},
    "PowerEase": function () {},
    "QuadraticEase": function () {},
    "QuarticEase": function () {},
    "QuinticEase": function () {},
    "SineEase": function () {},
    "BezierCurveEase": function () {},
    "Condition": function () {},
    "ValueCondition": function () {},
    "PredicateCondition": function () {},
    "StateCondition": function () {},
    "Action": function () {},
    "ActionEvent": function () {},
    "ActionManager": function () {},
    "InterpolateValueAction": function () {},
    "SwitchBooleanAction": function () {},
    "SetStateAction": function () {},
    "SetValueAction": function () {},
    "IncrementValueAction": function () {},
    "PlayAnimationAction": function () {},
    "StopAnimationAction": function () {},
    "DoNothingAction": function () {},
    "CombineAction": function () {},
    "ExecuteCodeAction": function () {},
    "SetParentAction": function () {},
    "SpriteManager": function () {},
    "Sprite": function () {},
    "SpriteSceneComponent": function () {},
    "IntersectionInfo": function () {},
    "PickingInfo": function () {},
    "Ray": function () {},
    "Collider": function () {},
    "CollisionWorker": {},
    "WorkerTaskType": {
        "0": {},
        "1": {},
        "2": {},
        "INIT": {},
        "UPDATE": {},
        "COLLIDE": {}
    },
    "WorkerReplyType": {
        "0": {},
        "1": {},
        "SUCCESS": {},
        "UNKNOWN_ERROR": {}
    },
    "CollisionCoordinatorWorker": function () {},
    "CollisionCoordinatorLegacy": function () {},
    "Particle": function () {},
    "BaseParticleSystem": function () {},
    "ParticleSystem": function () {},
    "BoxParticleEmitter": function () {},
    "CylinderParticleEmitter": function () {},
    "CylinderDirectedParticleEmitter": function () {},
    "ConeParticleEmitter": function () {},
    "SphereParticleEmitter": function () {},
    "SphereDirectedParticleEmitter": function () {},
    "HemisphericParticleEmitter": function () {},
    "PointParticleEmitter": function () {},
    "SubEmitterType": {
        "0": {},
        "1": {},
        "ATTACHED": {},
        "END": {}
    },
    "SubEmitter": function () {},
    "ShaderMaterial": function () {},
    "GroundMesh": function () {},
    "InstancedMesh": function () {},
    "LinesMesh": function () {},
    "StringDictionary": function () {},
    "Debug": {
        "SkeletonViewer": function () {},
        "AxesViewer": function () {},
        "BoneAxesViewer": function () {},
        "PhysicsViewer": function () {}
    },
    "RayHelper": function () {},
    "DebugLayer": function () {},
    "BoundingBoxRenderer": function () {},
    "GPUParticleSystem": function () {},
    "SolidParticle": function () {},
    "ModelShape": function () {},
    "DepthSortedParticle": function () {},
    "SolidParticleSystem": function () {},
    "MeshBuilder": function () {},
    "DracoCompression": function () {},
    "AudioEngine": function () {},
    "Sound": function () {},
    "SoundTrack": function () {},
    "Analyser": function () {},
    "WeightedSound": function () {},
    "AudioSceneComponent": function () {},
    "PlaySoundAction": function () {},
    "StopSoundAction": function () {},
    "CubeTexture": function () {},
    "RawCubeTexture": function () {},
    "RenderTargetTexture": function () {},
    "MultiRenderTarget": function () {},
    "MirrorTexture": function () {},
    "RefractionTexture": function () {},
    "DynamicTexture": function () {},
    "VideoTexture": function () {},
    "RawTexture": function () {},
    "RawTexture3D": function () {},
    "PostProcessManager": function () {},
    "PostProcess": function () {},
    "PassPostProcess": function () {},
    "ShadowGenerator": function () {},
    "ShadowGeneratorSceneComponent": function () {},
    "DefaultLoadingScreen": function () {},
    "SceneLoaderProgressEvent": function () {},
    "SceneLoader": function () {},
    "FilesInput": function () {},
    "Tags": function () {},
    "AndOrNotEvaluator": function () {},
    "Database": function () {},
    "FresnelParameters": function () {},
    "MultiMaterial": function () {},
    "FreeCameraTouchInput": function () {},
    "TouchCamera": function () {},
    "ProceduralTexture": function () {},
    "ProceduralTextureSceneComponent": function () {},
    "CustomProceduralTexture": function () {},
    "FreeCameraGamepadInput": function () {},
    "ArcRotateCameraGamepadInput": function () {},
    "GamepadManager": function () {},
    "StickValues": function () {},
    "Gamepad": function () {},
    "GenericPad": function () {},
    "Xbox360Button": {
        "0": {},
        "1": {},
        "2": {},
        "3": {},
        "4": {},
        "5": {},
        "6": {},
        "7": {},
        "8": {},
        "9": {},
        "A": {},
        "B": {},
        "X": {},
        "Y": {},
        "Start": {},
        "Back": {},
        "LB": {},
        "RB": {},
        "LeftStick": {},
        "RightStick": {}
    },
    "Xbox360Dpad": {
        "0": {},
        "1": {},
        "2": {},
        "3": {},
        "Up": {},
        "Down": {},
        "Left": {},
        "Right": {}
    },
    "Xbox360Pad": function () {},
    "PoseEnabledControllerType": {
        "0": {},
        "1": {},
        "2": {},
        "3": {},
        "4": {},
        "5": {},
        "VIVE": {},
        "OCULUS": {},
        "WINDOWS": {},
        "GEAR_VR": {},
        "DAYDREAM": {},
        "GENERIC": {}
    },
    "PoseEnabledControllerHelper": function () {},
    "PoseEnabledController": function () {},
    "WebVRController": function () {},
    "OculusTouchController": function () {},
    "ViveController": function () {},
    "GenericController": function () {},
    "WindowsMotionController": function () {},
    "GearVRController": function () {},
    "DaydreamController": function () {},
    "GamepadSystemSceneComponent": function () {},
    "FollowCamera": function () {},
    "ArcFollowCamera": function () {},
    "UniversalCamera": function () {},
    "GamepadCamera": function () {},
    "PostProcessRenderPipelineManager": function () {},
    "PostProcessRenderPipelineManagerSceneComponent": function () {},
    "PostProcessRenderEffect": function () {},
    "PostProcessRenderPipeline": function () {},
    "DepthRenderer": function () {},
    "DepthRendererSceneComponent": function () {},
    "GeometryBufferRenderer": function () {},
    "GeometryBufferRendererSceneComponent": function () {},
    "SSAORenderingPipeline": function () {},
    "SSAO2RenderingPipeline": function () {},
    "LensRenderingPipeline": function () {},
    "StandardRenderingPipeline": function () {},
    "FxaaPostProcess": function () {},
    "ChromaticAberrationPostProcess": function () {},
    "GrainPostProcess": function () {},
    "SharpenPostProcess": function () {},
    "BlurPostProcess": function () {},
    "DepthOfFieldBlurPostProcess": function () {},
    "DepthOfFieldMergePostProcessOptions": function () {},
    "DepthOfFieldMergePostProcess": function () {},
    "CircleOfConfusionPostProcess": function () {},
    "DepthOfFieldEffectBlurLevel": {
        "0": {},
        "1": {},
        "2": {},
        "Low": {},
        "Medium": {},
        "High": {}
    },
    "DepthOfFieldEffect": function () {},
    "BloomMergePostProcess": function () {},
    "ExtractHighlightsPostProcess": function () {},
    "BloomEffect": function () {},
    "DefaultRenderingPipeline": function () {},
    "ImageProcessingConfigurationDefines": function () {},
    "ImageProcessingConfiguration": function () {},
    "ColorGradingTexture": function () {},
    "ColorCurves": function () {},
    "RefractionPostProcess": function () {},
    "BlackAndWhitePostProcess": function () {},
    "ConvolutionPostProcess": function () {},
    "FilterPostProcess": function () {},
    "VolumetricLightScatteringPostProcess": function () {},
    "ColorCorrectionPostProcess": function () {},
    "TonemappingOperator": {
        "0": {},
        "1": {},
        "2": {},
        "3": {},
        "Hable": {},
        "Reinhard": {},
        "HejiDawson": {},
        "Photographic": {}
    },
    "TonemapPostProcess": function () {},
    "DisplayPassPostProcess": function () {},
    "HighlightsPostProcess": function () {},
    "ImageProcessingPostProcess": function () {},
    "Bone": function () {},
    "BoneIKController": function () {},
    "BoneLookController": function () {},
    "Skeleton": function () {},
    "HDRTools": function () {},
    "HDRCubeTexture": function () {},
    "PanoramaToCubeMapTools": function () {},
    "Polygon": function () {},
    "PolygonMeshBuilder": function () {},
    "CSG": function () {},
    "LensFlare": function () {},
    "LensFlareSystemSceneComponent": function () {},
    "LensFlareSystem": function () {},
    "PhysicsJoint": function () {},
    "DistanceJoint": function () {},
    "MotorEnabledJoint": function () {},
    "HingeJoint": function () {},
    "Hinge2Joint": function () {},
    "PhysicsImpostor": function () {},
    "PhysicsEngine": function () {},
    "PhysicsHelper": function () {},
    "PhysicsRadialExplosionEvent": function () {},
    "PhysicsGravitationalFieldEvent": function () {},
    "PhysicsUpdraftEvent": function () {},
    "PhysicsVortexEvent": function () {},
    "PhysicsRadialImpulseFalloff": {
        "0": {},
        "1": {},
        "Constant": {},
        "Linear": {}
    },
    "PhysicsUpdraftMode": {
        "0": {},
        "1": {},
        "Center": {},
        "Perpendicular": {}
    },
    "CannonJSPlugin": function () {},
    "OimoJSPlugin": function () {},
    "PhysicsEngineSceneComponent": function () {},
    "DDSTools": function () {},
    "TGATools": function () {},
    "KhronosTextureContainer": function () {},
    "EnvironmentTextureTools": function () {},
    "UtilityLayerRenderer": function () {},
    "PointerDragBehavior": function () {},
    "MultiPointerScaleBehavior": function () {},
    "SixDofDragBehavior": function () {},
    "AttachToBoxBehavior": function () {},
    "FadeInOutBehavior": function () {},
    "Gizmo": function () {},
    "AxisDragGizmo": function () {},
    "AxisScaleGizmo": function () {},
    "PlaneRotationGizmo": function () {},
    "PositionGizmo": function () {},
    "RotationGizmo": function () {},
    "ScaleGizmo": function () {},
    "BoundingBoxGizmo": function () {},
    "GizmoManager": function () {},
    "MorphTarget": function () {},
    "MorphTargetManager": function () {},
    "Octree": function () {},
    "OctreeBlock": function () {},
    "OctreeSceneComponent": function () {},
    "AnaglyphPostProcess": function () {},
    "AnaglyphArcRotateCamera": function () {},
    "AnaglyphFreeCamera": function () {},
    "AnaglyphGamepadCamera": function () {},
    "AnaglyphUniversalCamera": function () {},
    "StereoscopicInterlacePostProcess": function () {},
    "StereoscopicArcRotateCamera": function () {},
    "StereoscopicFreeCamera": function () {},
    "StereoscopicGamepadCamera": function () {},
    "StereoscopicUniversalCamera": function () {},
    "VRDistortionCorrectionPostProcess": function () {},
    "FreeCameraDeviceOrientationInput": function () {},
    "ArcRotateCameraVRDeviceOrientationInput": function () {},
    "VRCameraMetrics": function () {},
    "WebVRFreeCamera": function () {},
    "DeviceOrientationCamera": function () {},
    "VRDeviceOrientationFreeCamera": function () {},
    "VRDeviceOrientationArcRotateCamera": function () {},
    "VRDeviceOrientationGamepadCamera": function () {},
    "VRExperienceHelper": function () {},
    "JoystickAxis": {
        "0": {},
        "1": {},
        "2": {},
        "X": {},
        "Y": {},
        "Z": {}
    },
    "VirtualJoystick": function () {},
    "VirtualJoysticksCamera": function () {},
    "FreeCameraVirtualJoystickInput": function () {},
    "SimplificationSettings": function () {},
    "SimplificationQueue": function () {},
    "SimplificationType": {
        "0": {},
        "QUADRATIC": {}
    },
    "SimplicationQueueSceneComponent": function () {},
    "MeshLODLevel": function () {},
    "SceneOptimization": function () {},
    "TextureOptimization": function () {},
    "HardwareScalingOptimization": function () {},
    "ShadowsOptimization": function () {},
    "PostProcessesOptimization": function () {},
    "LensFlaresOptimization": function () {},
    "CustomOptimization": function () {},
    "ParticlesOptimization": function () {},
    "RenderTargetsOptimization": function () {},
    "MergeMeshesOptimization": function () {},
    "SceneOptimizerOptions": function () {},
    "SceneOptimizer": function () {},
    "OutlineRenderer": function () {},
    "EdgesRenderer": function () {},
    "LineEdgesRenderer": function () {},
    "EffectLayerSceneComponent": function () {},
    "EffectLayer": function () {},
    "HighlightLayer": function () {},
    "GlowLayer": function () {},
    "AssetTaskState": {
        "0": {},
        "1": {},
        "2": {},
        "3": {},
        "INIT": {},
        "RUNNING": {},
        "DONE": {},
        "ERROR": {}
    },
    "AbstractAssetTask": function () {},
    "AssetsProgressEvent": function () {},
    "MeshAssetTask": function () {},
    "TextFileAssetTask": function () {},
    "BinaryFileAssetTask": function () {},
    "ImageAssetTask": function () {},
    "TextureAssetTask": function () {},
    "CubeTextureAssetTask": function () {},
    "HDRCubeTextureAssetTask": function () {},
    "AssetsManager": function () {},
    "SceneSerializer": function () {},
    "ReflectionProbe": function () {},
    "LayerSceneComponent": function () {},
    "Layer": function () {},
    "TextureTools": function () {},
    "FramingBehavior": function () {},
    "BouncingBehavior": function () {},
    "AutoRotationBehavior": function () {},
    "NullEngineOptions": function () {},
    "NullEngine": function () {},
    "EngineInstrumentation": function () {},
    "SceneInstrumentation": function () {},
    "_TimeToken": function () {},
    "BackgroundMaterial": function () {},
    "EnvironmentHelper": function () {},
    "ParticleSystemSet": function () {},
    "ParticleHelper": function () {},
    "VideoDome": function () {},
    "PhotoDome": function () {},
    "NoiseProceduralTexture": function () {},
    "VideoRecorder": function () {}
}
