/**********************************************************************
 * Extern for DayPicker
 * Generated by http://jmmk.github.io/javascript-externs-generator
 * Additional API methods added by hand, see end of file.
 **********************************************************************/
var DayPicker = {
  "DateUtils": {
    "addDayToRange": function () {},
    "addMonths": function () {},
    "clone": function () {},
    "getWeekNumber": function () {},
    "isDayAfter": function () {},
    "isDayBefore": function () {},
    "isDayBetween": function () {},
    "isDayInRange": function () {},
    "isFutureDay": function () {},
    "isPastDay": function () {},
    "isSameDay": function () {}
  },
  "LocaleUtils": {
    "formatDay": function () {},
    "formatMonthTitle": function () {},
    "formatWeekdayLong": function () {},
    "formatWeekdayShort": function () {},
    "getFirstDayOfWeek": function () {},
    "getMonths": function () {}
  },
  "ModifiersUtils": {
    "dayMatchesModifier": function () {},
    "getModifiersForDay": function () {}
  },
  "NavbarPropTypes": {
    "className": {
      "isRequired": function () {}
    },
    "classNames": {
      "isRequired": function () {}
    },
    "dir": {
      "isRequired": function () {}
    },
    "labels": {
      "isRequired": function () {}
    },
    "onNextClick": {
      "isRequired": function () {}
    },
    "onPreviousClick": {
      "isRequired": function () {}
    },
    "showNextButton": {
      "isRequired": function () {}
    },
    "showPreviousButton": {
      "isRequired": function () {}
    }
  },
  "PropTypes": {
    "ModifierPropType": {
      "isRequired": function () {}
    },
    "default": {
      "PropTypes": {
        "PropTypes": {},
        "any": {
          "isRequired": function () {}
        },
        "array": {
          "isRequired": function () {}
        },
        "arrayOf": function () {},
        "bool": {
          "isRequired": function () {}
        },
        "checkPropTypes": function () {},
        "element": {
          "isRequired": function () {}
        },
        "func": {
          "isRequired": function () {}
        },
        "instanceOf": function () {},
        "node": {
          "isRequired": function () {}
        },
        "number": {
          "isRequired": function () {}
        },
        "object": {
          "isRequired": function () {}
        },
        "objectOf": function () {},
        "oneOf": function () {},
        "oneOfType": function () {},
        "shape": function () {},
        "string": {
          "isRequired": function () {}
        },
        "symbol": {
          "isRequired": function () {}
        }
      },
      "after": {
        "isRequired": function () {}
      },
      "any": {
        "isRequired": function () {}
      },
      "array": {
        "isRequired": function () {}
      },
      "arrayOf": function () {},
      "before": {
        "isRequired": function () {}
      },
      "bool": {
        "isRequired": function () {}
      },
      "checkPropTypes": function () {},
      "element": {
        "isRequired": function () {}
      },
      "func": {
        "isRequired": function () {}
      },
      "instanceOf": function () {},
      "localeUtils": {
        "isRequired": function () {}
      },
      "node": {
        "isRequired": function () {}
      },
      "number": {
        "isRequired": function () {}
      },
      "object": {
        "isRequired": function () {}
      },
      "objectOf": function () {},
      "oneOf": function () {},
      "oneOfType": function () {},
      "range": {
        "isRequired": function () {}
      },
      "shape": function () {},
      "string": {
        "isRequired": function () {}
      },
      "symbol": {
        "isRequired": function () {}
      }
    }
  },
  "VERSION": {},
  "WeekdayPropTypes": {
    "className": {
      "isRequired": function () {}
    },
    "locale": {
      "isRequired": function () {}
    },
    "localeUtils": {
      "isRequired": function () {}
    },
    "weekday": {
      "isRequired": function () {}
    },
    "weekdaysLong": {
      "isRequired": function () {}
    },
    "weekdaysShort": {
      "isRequired": function () {}
    }
  },
  "defaultProps": {
    "canChangeMonth": {},
    "captionElement": {
      "$$typeof": {},
      "_owner": {},
      "_store": {},
      "key": {},
      "props": {
        "classNames": {
          "body": {},
          "caption": {},
          "container": {},
          "day": {},
          "disabled": {},
          "footer": {},
          "interactionDisabled": {},
          "month": {},
          "navBar": {},
          "navButtonNext": {},
          "navButtonPrev": {},
          "outside": {},
          "selected": {},
          "today": {},
          "todayButton": {},
          "week": {},
          "weekNumber": {},
          "weekday": {},
          "weekdays": {},
          "weekdaysRow": {}
        }
      },
      "ref": {},
      "type": {
        "propTypes": {
          "classNames": function () {},
          "date": {
            "isRequired": function () {}
          },
          "locale": {
            "isRequired": function () {}
          },
          "localeUtils": {
            "isRequired": function () {}
          },
          "months": {
            "isRequired": function () {}
          },
          "onClick": {
            "isRequired": function () {}
          }
        }
      }
    },
    "classNames": {
      "body": {},
      "caption": {},
      "container": {},
      "day": {},
      "disabled": {},
      "footer": {},
      "interactionDisabled": {},
      "month": {},
      "navBar": {},
      "navButtonNext": {},
      "navButtonPrev": {},
      "outside": {},
      "selected": {},
      "today": {},
      "todayButton": {},
      "week": {},
      "weekNumber": {},
      "weekday": {},
      "weekdays": {},
      "weekdaysRow": {}
    },
    "enableOutsideDays": {},
    "fixedWeeks": {},
    "initialMonth": {},
    "labels": {
      "nextMonth": {},
      "previousMonth": {}
    },
    "locale": {},
    "localeUtils": {
      "default": {
        "formatDay": function () {},
        "formatMonthTitle": function () {},
        "formatWeekdayLong": function () {},
        "formatWeekdayShort": function () {},
        "getFirstDayOfWeek": function () {},
        "getMonths": function () {}
      },
      "formatDay": function () {},
      "formatMonthTitle": function () {},
      "formatWeekdayLong": function () {},
      "formatWeekdayShort": function () {},
      "getFirstDayOfWeek": function () {},
      "getMonths": function () {}
    },
    "navbarElement": {
      "$$typeof": {},
      "_owner": {},
      "_store": {},
      "key": {},
      "props": {
        "classNames": {
          "body": {},
          "caption": {},
          "container": {},
          "day": {},
          "disabled": {},
          "footer": {},
          "interactionDisabled": {},
          "month": {},
          "navBar": {},
          "navButtonNext": {},
          "navButtonPrev": {},
          "outside": {},
          "selected": {},
          "today": {},
          "todayButton": {},
          "week": {},
          "weekNumber": {},
          "weekday": {},
          "weekdays": {},
          "weekdaysRow": {}
        },
        "dir": {},
        "labels": {
          "nextMonth": {},
          "previousMonth": {}
        },
        "showNextButton": {},
        "showPreviousButton": {}
      },
      "ref": {},
      "type": {
        "defaultProps": {
          "classNames": {
            "body": {},
            "caption": {},
            "container": {},
            "day": {},
            "disabled": {},
            "footer": {},
            "interactionDisabled": {},
            "month": {},
            "navBar": {},
            "navButtonNext": {},
            "navButtonPrev": {},
            "outside": {},
            "selected": {},
            "today": {},
            "todayButton": {},
            "week": {},
            "weekNumber": {},
            "weekday": {},
            "weekdays": {},
            "weekdaysRow": {}
          },
          "dir": {},
          "labels": {
            "nextMonth": {},
            "previousMonth": {}
          },
          "showNextButton": {},
          "showPreviousButton": {}
        },
        "propTypes": {
          "className": {
            "isRequired": function () {}
          },
          "classNames": {
            "isRequired": function () {}
          },
          "dir": {
            "isRequired": function () {}
          },
          "labels": {
            "isRequired": function () {}
          },
          "onNextClick": {
            "isRequired": function () {}
          },
          "onPreviousClick": {
            "isRequired": function () {}
          },
          "showNextButton": {
            "isRequired": function () {}
          },
          "showPreviousButton": {
            "isRequired": function () {}
          }
        }
      }
    },
    "numberOfMonths": {},
    "pagedNavigation": {},
    "renderDay": function () {},
    "reverseMonths": {},
    "showWeekNumbers": {},
    "tabIndex": {},
    "weekdayElement": {
      "$$typeof": {},
      "_owner": {},
      "_store": {},
      "key": {},
      "props": {},
      "ref": {},
      "type": {
        "propTypes": {
          "className": {
            "isRequired": function () {}
          },
          "locale": {
            "isRequired": function () {}
          },
          "localeUtils": {
            "isRequired": function () {}
          },
          "weekday": {
            "isRequired": function () {}
          },
          "weekdaysLong": {
            "isRequired": function () {}
          },
          "weekdaysShort": {
            "isRequired": function () {}
          }
        }
      }
    }
  },
  "propTypes": {
    "canChangeMonth": {
      "isRequired": function () {}
    },
    "captionElement": {
      "isRequired": function () {}
    },
    "className": {
      "isRequired": function () {}
    },
    "classNames": {
      "isRequired": function () {}
    },
    "containerProps": {
      "isRequired": function () {}
    },
    "dir": {
      "isRequired": function () {}
    },
    "disabledDays": {
      "isRequired": function () {}
    },
    "enableOutsideDays": {
      "isRequired": function () {}
    },
    "firstDayOfWeek": {
      "isRequired": function () {}
    },
    "fixedWeeks": {
      "isRequired": function () {}
    },
    "fromMonth": {
      "isRequired": function () {}
    },
    "initialMonth": {
      "isRequired": function () {}
    },
    "labels": function () {},
    "locale": {
      "isRequired": function () {}
    },
    "localeUtils": {
      "isRequired": function () {}
    },
    "modifiers": {
      "isRequired": function () {}
    },
    "modifiersStyles": {
      "isRequired": function () {}
    },
    "month": {
      "isRequired": function () {}
    },
    "months": {
      "isRequired": function () {}
    },
    "navbarElement": {
      "isRequired": function () {}
    },
    "numberOfMonths": {
      "isRequired": function () {}
    },
    "onBlur": {
      "isRequired": function () {}
    },
    "onCaptionClick": {
      "isRequired": function () {}
    },
    "onDayClick": {
      "isRequired": function () {}
    },
    "onDayFocus": {
      "isRequired": function () {}
    },
    "onDayKeyDown": {
      "isRequired": function () {}
    },
    "onDayMouseEnter": {
      "isRequired": function () {}
    },
    "onDayMouseLeave": {
      "isRequired": function () {}
    },
    "onDayTouchEnd": {
      "isRequired": function () {}
    },
    "onDayTouchStart": {
      "isRequired": function () {}
    },
    "onFocus": {
      "isRequired": function () {}
    },
    "onKeyDown": {
      "isRequired": function () {}
    },
    "onMonthChange": {
      "isRequired": function () {}
    },
    "onWeekClick": {
      "isRequired": function () {}
    },
    "pagedNavigation": {
      "isRequired": function () {}
    },
    "renderDay": {
      "isRequired": function () {}
    },
    "reverseMonths": {
      "isRequired": function () {}
    },
    "selectedDays": {
      "isRequired": function () {}
    },
    "showWeekNumbers": {
      "isRequired": function () {}
    },
    "tabIndex": {
      "isRequired": function () {}
    },
    "toMonth": {
      "isRequired": function () {}
    },
    "todayButton": {
      "isRequired": function () {}
    },
    "weekdayElement": {
      "isRequired": function () {}
    },
    "weekdaysLong": {
      "isRequired": function () {}
    },
    "weekdaysShort": {
      "isRequired": function () {}
    }
  }
};
DayPicker.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {},
  // Following methods added by hand:
  "getDayNodes": function () {},
  "getNextNavigableMonth": function () {},
  "getPreviousNavigableMonth": function () {},
  "allowPreviousMonth": function () {},
  "allowNextMonth": function () {},
  "allowMonth": function (d) {},
  "allowYearChange": function () {},
  "showNextMonth": function (callback) {},
  "showPreviousMonth": function (callback) {},
  "showNextYear": function () {},
  "showPreviousYear": function () {},
  "focusFirstDayOfMonth": function () {},
  "focusLastDayOfMonth": function () {},
  "focusPreviousDay": function (dayNode) {},
  "focusNextDay": function (dayNode) {},
  "focusNextWeek": function (dayNode) {},
  "focusPreviousWeek": function (dayNode) {},
  "handleKeyDown": function (e) {},
  "handleDayKeyDown": function (e) {},
  "handleDayClick": function (e) {},
  "handleOutsideDayClick": function (e) {},
  "renderNavbar": function () {},
  "renderDayInMonth": function (day, month) {}
};