// Generated via:
// http://jmmk.github.io/javascript-externs-generator/

var rangy = {
  "version": {},
  "initialized": {},
  "isBrowser": {},
  "supported": {},
  "util": {},
  "features": {},
  "modules": {},
  "config": {},
  "fail": function () {},
  "warn": function () {},
  "init": function () {},
  "addInitListener": function () {},
  "addShimListener": function () {},
  "createMissingNativeApi": function () {},
  "shim": function () {},
  "createModule": function () {},
  "createCoreModule": function () {},
  "RangePrototype": function () {},
  "rangePrototype": {},
  "selectionPrototype": {},
  "dom": {},
  "DOMException": function () {},
  "DomRange": {
    "START_TO_START": {},
    "START_TO_END": {},
    "END_TO_END": {},
    "END_TO_START": {},
    "NODE_BEFORE": {},
    "NODE_AFTER": {},
    "NODE_BEFORE_AND_AFTER": {},
    "NODE_INSIDE": {},
    "rangeProperties": {},
    "RangeIterator": function () {},
    "copyComparisonConstants": function () {},
    "createPrototypeRange": function () {},
    "inspect": function () {},
    "toHtml": function () {},
    "getRangeDocument": function () {},
    "rangesEqual": function () {}
  },
  "WrappedRange": {
    "START_TO_START": {},
    "START_TO_END": {},
    "END_TO_END": {},
    "END_TO_START": {},
    "NODE_BEFORE": {},
    "NODE_AFTER": {},
    "NODE_BEFORE_AND_AFTER": {},
    "NODE_INSIDE": {}
  },
  "createNativeRange": function () {},
  "createRange": function () {},
  "createRangyRange": function () {},
  "createIframeRange": function () {},
  "createIframeRangyRange": function () {},
  "isSelectionValid": function () {},
  "getNativeSelection": function () {},
  "getSelection": function () {},
  "getIframeSelection": function () {},
  "Selection": {
    "detachAll": function () {},
    "inspect": function () {},
    "isDirectionBackward": function () {}
  },
  "innerText": function () {},
  "createWordIterator": function () {},
  "noMutation": {
    "createEntryPointFunction": function () {}
  },
  "textRange": {}
};
rangy.DOMException.prototype = {
  "INDEX_SIZE_ERR": function () {},
  "HIERARCHY_REQUEST_ERR": function () {},
  "WRONG_DOCUMENT_ERR": function () {},
  "NO_MODIFICATION_ALLOWED_ERR": function () {},
  "NOT_FOUND_ERR": function () {},
  "NOT_SUPPORTED_ERR": function () {},
  "INVALID_STATE_ERR": function () {},
  "INVALID_NODE_TYPE_ERR": function () {},
  "toString": function () {}
};
rangy.DomRange.prototype = {
  "setStart": function () {},
  "setEnd": function () {},
  "setStartAndEnd": function () {},
  "setBoundary": function () {},
  "setStartBefore": function () {},
  "setStartAfter": function () {},
  "setEndBefore": function () {},
  "setEndAfter": function () {},
  "collapse": function () {},
  "selectNodeContents": function () {},
  "selectNode": function () {},
  "extractContents": function () {},
  "deleteContents": function () {},
  "canSurroundContents": function () {},
  "splitBoundaries": function () {},
  "splitBoundariesPreservingPositions": function () {},
  "normalizeBoundaries": function () {},
  "collapseToPoint": function () {},
  "START_TO_START": function () {},
  "START_TO_END": function () {},
  "END_TO_END": function () {},
  "END_TO_START": function () {},
  "NODE_BEFORE": function () {},
  "NODE_AFTER": function () {},
  "NODE_BEFORE_AND_AFTER": function () {},
  "NODE_INSIDE": function () {},
  "compareBoundaryPoints": function () {},
  "insertNode": function () {},
  "cloneContents": function () {},
  "surroundContents": function () {},
  "cloneRange": function () {},
  "toString": function () {},
  "compareNode": function () {},
  "comparePoint": function () {},
  "createContextualFragment": function () {},
  "toHtml": function () {},
  "intersectsNode": function () {},
  "isPointInRange": function () {},
  "intersectsRange": function () {},
  "intersectsOrTouchesRange": function () {},
  "intersection": function () {},
  "union": function () {},
  "containsNode": function () {},
  "containsNodeContents": function () {},
  "containsRange": function () {},
  "containsNodeText": function () {},
  "getNodes": function () {},
  "getDocument": function () {},
  "collapseBefore": function () {},
  "collapseAfter": function () {},
  "getBookmark": function () {},
  "moveToBookmark": function () {},
  "getName": function () {},
  "equals": function () {},
  "isValid": function () {},
  "inspect": function () {},
  "detach": function () {},
  "select": function () {},
  "moveStart": function () {},
  "moveEnd": function () {},
  "move": function () {},
  "trimStart": function () {},
  "trimEnd": function () {},
  "trim": function () {},
  "expand": function () {},
  "text": function () {},
  "selectCharacters": function () {},
  "toCharacterRange": function () {},
  "findText": function () {},
  "pasteHtml": function () {}
};
rangy.DomRange.RangeIterator.prototype = {
  "_current": function () {},
  "_next": function () {},
  "_first": function () {},
  "_last": function () {},
  "isSingleCharacterDataNode": function () {},
  "reset": function () {},
  "hasNext": function () {},
  "next": function () {},
  "remove": function () {},
  "isPartiallySelectedSubtree": function () {},
  "getSubtreeIterator": function () {},
  "detach": function () {}
};
rangy.WrappedRange.prototype = {
  "setStart": function () {},
  "setEnd": function () {},
  "setStartAndEnd": function () {},
  "setBoundary": function () {},
  "setStartBefore": function () {},
  "setStartAfter": function () {},
  "setEndBefore": function () {},
  "setEndAfter": function () {},
  "collapse": function () {},
  "selectNodeContents": function () {},
  "selectNode": function () {},
  "extractContents": function () {},
  "deleteContents": function () {},
  "canSurroundContents": function () {},
  "splitBoundaries": function () {},
  "splitBoundariesPreservingPositions": function () {},
  "normalizeBoundaries": function () {},
  "collapseToPoint": function () {},
  "START_TO_START": function () {},
  "START_TO_END": function () {},
  "END_TO_END": function () {},
  "END_TO_START": function () {},
  "NODE_BEFORE": function () {},
  "NODE_AFTER": function () {},
  "NODE_BEFORE_AND_AFTER": function () {},
  "NODE_INSIDE": function () {},
  "cloneContents": function () {},
  "surroundContents": function () {},
  "cloneRange": function () {},
  "refresh": function () {},
  "toString": function () {},
  "compareBoundaryPoints": function () {},
  "createContextualFragment": function () {},
  "getName": function () {},
  "insertNode": function () {},
  "compareNode": function () {},
  "comparePoint": function () {},
  "toHtml": function () {},
  "intersectsNode": function () {},
  "isPointInRange": function () {},
  "intersectsRange": function () {},
  "intersectsOrTouchesRange": function () {},
  "intersection": function () {},
  "union": function () {},
  "containsNode": function () {},
  "containsNodeContents": function () {},
  "containsRange": function () {},
  "containsNodeText": function () {},
  "getNodes": function () {},
  "getDocument": function () {},
  "collapseBefore": function () {},
  "collapseAfter": function () {},
  "getBookmark": function () {},
  "moveToBookmark": function () {},
  "equals": function () {},
  "isValid": function () {},
  "inspect": function () {},
  "detach": function () {},
  "select": function () {},
  "moveStart": function () {},
  "moveEnd": function () {},
  "move": function () {},
  "trimStart": function () {},
  "trimEnd": function () {},
  "trim": function () {},
  "expand": function () {},
  "text": function () {},
  "selectCharacters": function () {},
  "toCharacterRange": function () {},
  "findText": function () {},
  "pasteHtml": function () {}
};
