/**********************************************************************
 * Extern for Mousetrap
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Mousetrap = {
  "addKeycodes": function () {},
  "bind": function () {},
  "handleKey": function () {},
  "init": function () {},
  "reset": function () {},
  "stopCallback": function () {},
  "target": function () {},
  "trigger": function () {},
  "unbind": function () {}
};
Mousetrap.prototype = {
  "bind": function () {},
  "handleKey": function () {},
  "reset": function () {},
  "stopCallback": function () {},
  "trigger": function () {},
  "unbind": function () {}
};
/**********************************************************************
 * End Generated Extern for Mousetrap
/**********************************************************************/
