/**********************************************************************
 * Extern for ZeroEx
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ZeroEx = {
  "ExchangeContractErrs": {
    "BatchOrdersMustHaveAtLeastOneItem": {},
    "BatchOrdersMustHaveSameExchangeAddress": {},
    "FillBalanceAllowanceError": {},
    "InsufficientMakerAllowance": {},
    "InsufficientMakerBalance": {},
    "InsufficientMakerFeeAllowance": {},
    "InsufficientMakerFeeBalance": {},
    "InsufficientRemainingFillAmount": {},
    "InsufficientTakerAllowance": {},
    "InsufficientTakerBalance": {},
    "InsufficientTakerFeeAllowance": {},
    "InsufficientTakerFeeBalance": {},
    "MultipleMakersInSingleCancelBatchDisallowed": {},
    "MultipleTakerTokensInFillUpToDisallowed": {},
    "OrderAlreadyCancelledOrFilled": {},
    "OrderCancelAmountZero": {},
    "OrderCancelExpired": {},
    "OrderFillAmountZero": {},
    "OrderFillExpired": {},
    "OrderFillRoundingError": {},
    "OrderRemainingFillAmountZero": {},
    "TransactionSenderIsNotFillOrderTaker": {}
  },
  "ExchangeEvents": {
    "LogCancel": {},
    "LogError": {},
    "LogFill": {}
  },
  "TokenEvents": {
    "Approval": {},
    "Transfer": {}
  },
  "ZeroEx": {
    "NULL_ADDRESS": {},
    "generatePseudoRandomSalt": function () {},
    "getOrderHashHex": function () {},
    "isValidOrderHash": function () {},
    "isValidSignature": function () {},
    "toBaseUnitAmount": function () {},
    "toUnitAmount": function () {}
  },
  "ZeroExError": {
    "ContractDoesNotExist": {},
    "ContractNotDeployedOnNetwork": {},
    "ExchangeContractDoesNotExist": {},
    "InsufficientAllowanceForTransfer": {},
    "InsufficientBalanceForTransfer": {},
    "InsufficientEthBalanceForDeposit": {},
    "InsufficientWEthBalanceForWithdrawal": {},
    "InvalidJump": {},
    "InvalidSignature": {},
    "NoNetworkId": {},
    "OutOfGas": {},
    "UnhandledError": {},
    "UserHasNoAssociatedAddress": {},
    "ZrxNotInTokenRegistry": {}
  }
};
ZeroEx.ZeroEx.prototype = {
  "_getTokenTransferProxyAddressAsync": function () {},
  "awaitTransactionMinedAsync": function () {},
  "etherToken": {
      "depositAsync": function() {},
      "getContractAddressAsync": function() {},
      "withdrawAsync": function() {}
  },
  "exchange": {
      "batchCancelOrdersAsync": function () {},
      "batchFillOrKillAsync": function () {},
      "batchFillOrdersAsync": function () {},
      "cancelOrderAsync": function () {},
      "fillOrKillOrderAsync": function () {},
      "fillOrderAsync": function () {},
      "fillOrdersUpToAsync": function () {},
      "getCanceledTakerAmountAsync": function () {},
      "getContractAddressAsync": function () {},
      "getFilledTakerAmountAsync": function () {},
      "getLogsAsync": function () {},
      "getUnavailableTakerAmountAsync": function () {},
      "getZRXTokenAddressAsync": function () {},
      "isRoundingErrorAsync": function () {},
      "subscribeAsync": function () {},
      "throwLogErrorsAsErrors": function () {},
      "unsubscribe": function () {},
      "unsubscribeAll": function () {},
      "validateCancelOrderThrowIfInvalidAsync": function () {},
      "validateFillOrKillOrderThrowIfInvalidAsync": function () {},
      "validateFillOrderThrowIfInvalidAsync": function () {},
      "validateOrderFillableOrThrowAsync": function () {}
  },
  "getAvailableAddressesAsync": function () {},
  "proxy": {
      "getAuthorizedAddressesAsync": function () {},
      "getContractAddressAsync": function () {},
      "isAuthorizedAsync": function () {}
  },
  "setProviderAsync": function () {},
  "signOrderHashAsync": function () {},
  "token": {
      "getAllowanceAsync": function () {},
      "getBalanceAsync": function () {},
      "getLogsAsync": function () {},
      "getProxyAllowanceAsync": function () {},
      "setAllowanceAsync": function () {},
      "setProxyAllowanceAsync": function () {},
      "setUnlimitedAllowanceAsync": function () {},
      "setUnlimitedProxyAllowanceAsync": function () {},
      "subscribe": function () {},
      "transferAsync": function () {},
      "transferFromAsync": function () {},
      "unsubscribe": function () {},
      "unsubscribeAll": function () {}
  },
  "tokenRegistry": {
      "getContractAddressAsync": function () {},
      "getTokenAddressByNameIfExistsAsync": function () {},
      "getTokenAddressBySymbolIfExistsAsync": function () {},
      "getTokenAddressesAsync": function () {},
      "getTokenByNameIfExistsAsync": function () {},
      "getTokenBySymbolIfExistsAsync": function () {},
      "getTokenIfExistsAsync": function () {},
      "getTokensAsync": function () {}
  }
};
/**********************************************************************
 * End Generated Extern for ZeroEx
/**********************************************************************/
