/**********************************************************************
 * Extern for commonmark
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var commonmark = {
        "version": {},
        "Node": function () {},
        "Parser": function () {},
        "HtmlRenderer": function () {},
        "XmlRenderer": function () {}
    };
commonmark.Node.prototype = {
    "appendChild": function () {},
    "prependChild": function () {},
    "unlink": function () {},
    "insertAfter": function () {},
    "insertBefore": function () {},
    "walker": function () {}
};
commonmark.HtmlRenderer.prototype = {
    "text": function () {},
    "html_inline": function () {},
    "html_block": function () {},
    "softbreak": function () {},
    "linebreak": function () {},
    "link": function () {},
    "image": function () {},
    "emph": function () {},
    "strong": function () {},
    "paragraph": function () {},
    "heading": function () {},
    "code": function () {},
    "code_block": function () {},
    "thematic_break": function () {},
    "block_quote": function () {},
    "list": function () {},
    "item": function () {},
    "custom_inline": function () {},
    "custom_block": function () {},
    "out": function () {},
    "tag": function () {},
    "attrs": function () {},
    "render": function () {},
    "lit": function () {},
    "cr": function () {}
};
/**********************************************************************
 * End Generated Extern for commonmark
 /**********************************************************************/
