jQuery.prototype.selectize = function() {};
var Selectize = {
  load: function(fn){},
  setTextboxValue: function(value){},
  getValue: function(){},
  setValue: function(value, silent){},
  setActiveItem: function(item, e){},
  setActiveOption: function(o, scroll, animate){},
  selectAll: function(){},
  hideInput: function(){},
  showInput: function(){},  
  focus: function(){},
  blur: function(dest){},
  getScoreFunction: function(query){},
  getSearchOptions: function(){},
  search: function(query){},
  registerOption: function(data){},
  registerOptionGroup: function(data){},
  addOptionGroup: function(id, data){},
  removeOptionGroup: function(id){},
  clearOptionGroups: function(){},
  updateOption: function(value, data){},
  removeOption: function(value, silent){},
  getOption: function(value){},
  getAdjacentOption: function($option, direction) {},
  getElementWithValue: function(value, $els) {},
  getItem: function(value) {},
  addItems: function(values, silent) {},
  addItem: function(value, silent){},
  removeItem: function(value, silent){},
  createItem: function(input, triggerDropdown){},
  refreshItems: function(){},
  refreshState: function(){},
  refreshClasses: function() {},
  isFull: function(){},
  updateOriginalInput: function(opts) {},
  updatePlaceholder: function() {},
  open: function(){},
  close: function(){},
  positionDropdown: function(){},
  clear: function(silent){},
  deleteSelection: function(e){},
  advanceSelection: function(direction, e){},
  advanceCaret: function(direction, e) {},
  setCaret: function(i) {},
  lock: function() {},
  unlock: function() {},
  disable: function(){},
  enable: function() {},
  destroy: function(){},
  render: function(templateName, data){},
  clearCache: function(templateName)  {},
  clearOptions: function(){},
  clearOptionGroups: function(){},
  addOption: function(a){},
  refreshOptions: function(a){}
}
