/**********************************************************************
 * Extern for NumericInput
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var NumericInput = {
  "propTypes": {
    "step": {
      "isRequired": function () {}
    },
    "min": {
      "isRequired": function () {}
    },
    "max": {
      "isRequired": function () {}
    },
    "precision": {
      "isRequired": function () {}
    },
    "maxLength": {
      "isRequired": function () {}
    },
    "parse": {
      "isRequired": function () {}
    },
    "format": {
      "isRequired": function () {}
    },
    "className": {
      "isRequired": function () {}
    },
    "disabled": {
      "isRequired": function () {}
    },
    "readOnly": {
      "isRequired": function () {}
    },
    "required": {
      "isRequired": function () {}
    },
    "noValidate": {
      "isRequired": function () {}
    },
    "style": {
      "isRequired": function () {}
    },
    "type": {
      "isRequired": function () {}
    },
    "pattern": {
      "isRequired": function () {}
    },
    "onFocus": {
      "isRequired": function () {}
    },
    "onBlur": {
      "isRequired": function () {}
    },
    "onKeyDown": {
      "isRequired": function () {}
    },
    "onChange": {
      "isRequired": function () {}
    },
    "onInvalid": {
      "isRequired": function () {}
    },
    "onValid": {
      "isRequired": function () {}
    },
    "onInput": {
      "isRequired": function () {}
    },
    "onSelect": {
      "isRequired": function () {}
    },
    "size": {
      "isRequired": function () {}
    },
    "value": {
      "isRequired": function () {}
    },
    "defaultValue": {
      "isRequired": function () {}
    },
    "mobile": function () {}
  },
  "defaultProps": {
    "step": {},
    "min": {},
    "max": {},
    "precision": {},
    "parse": {},
    "format": {},
    "mobile": {},
    "style": {}
  },
  "style": {
    "wrap": {
      "position": {},
      "display": {}
    },
    "wrap.hasFormControl": {
      "display": {}
    },
    "arrowUp": {
      "position": {},
      "top": {},
      "left": {},
      "width": {},
      "height": {},
      "borderWidth": {},
      "borderColor": {},
      "borderStyle": {},
      "margin": {}
    },
    "arrowDown": {
      "position": {},
      "top": {},
      "left": {},
      "width": {},
      "height": {},
      "borderWidth": {},
      "borderColor": {},
      "borderStyle": {},
      "margin": {}
    },
    "plus": {
      "position": {},
      "top": {},
      "left": {},
      "width": {},
      "height": {},
      "background": {},
      "margin": {}
    },
    "minus": {
      "position": {},
      "top": {},
      "left": {},
      "width": {},
      "height": {},
      "background": {},
      "margin": {}
    },
    "btn": {
      "position": {},
      "right": {},
      "width": {},
      "borderColor": {},
      "borderStyle": {},
      "textAlign": {},
      "cursor": {},
      "transition": {},
      "background": {},
      "boxShadow": {}
    },
    "btnUp": {
      "top": {},
      "bottom": {},
      "borderRadius": {},
      "borderWidth": {}
    },
    "btnUp.mobile": {
      "width": {},
      "bottom": {},
      "boxShadow": {},
      "borderRadius": {},
      "borderWidth": {}
    },
    "btnDown": {
      "top": {},
      "bottom": {},
      "borderRadius": {},
      "borderWidth": {}
    },
    "btnDown.mobile": {
      "width": {},
      "bottom": {},
      "left": {},
      "top": {},
      "right": {},
      "boxShadow": {},
      "borderRadius": {},
      "borderWidth": {}
    },
    "btn:hover": {
      "background": {}
    },
    "btn:active": {
      "background": {},
      "boxShadow": {}
    },
    "btn:disabled": {
      "opacity": {},
      "boxShadow": {},
      "cursor": {}
    },
    "input": {
      "paddingRight": {},
      "boxSizing": {}
    },
    "input:not(.form-control)": {
      "border": {},
      "borderRadius": {},
      "paddingLeft": {},
      "display": {},
      "WebkitAppearance": {},
      "lineHeight": {}
    },
    "input.mobile": {
      "paddingLeft": {},
      "paddingRight": {},
      "textAlign": {}
    },
    "input:focus": {},
    "input:disabled": {
      "color": {},
      "textShadow": {}
    }
  },
  "SPEED": {},
  "DELAY": {}
};
NumericInput.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
/**********************************************************************
 * End Generated Extern for NumericInput
/**********************************************************************/
