/**********************************************************************
 * Extern for PoseGroup
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var PoseGroup = {
  "defaultProps": {
    "enterPose": {},
    "exitPose": {},
    "flipMove": {},
    "preEnterPose": {},
    "singleChildOnly": {}
  },
  "getDerivedStateFromProps": function () {}
};
PoseGroup.prototype = {
  "componentWillMount": function () {},
  "componentWillReceiveProps": function () {},
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "removeFromChildren": function () {},
  "render": function () {},
  "setState": function () {},
  "shouldComponentUpdate": function () {}
};
/**********************************************************************
 * End Generated Extern for PoseGroup
/**********************************************************************/

/**********************************************************************
 * Extern for posed
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var posed = function () {};
/**********************************************************************
 * End Generated Extern for posed
/**********************************************************************/
