var ReactTestUtils = {};

ReactTestUtils.act = function () {};
ReactTestUtils.mockComponent = function () {};
ReactTestUtils.isElement = function () {};
ReactTestUtils.isElementOfType = function () {};
ReactTestUtils.isDOMComponent = function () {};
ReactTestUtils.isCompositeComponent = function () {};
ReactTestUtils.isCompositeComponentWithType = function () {};
ReactTestUtils.findAllInRenderedTree = function () {};
ReactTestUtils.scryRenderedDOMComponentsWithClass = function () {};
ReactTestUtils.findRenderedDOMComponentWithClass = function () {};
ReactTestUtils.scryRenderedDOMComponentsWithTag = function () {};
ReactTestUtils.findRenderedDOMComponentWithTag = function () {};
ReactTestUtils.scryRenderedComponentsWithType = function () {};
ReactTestUtils.findRenderedComponentWithType = function () {};
ReactTestUtils.renderIntoDocument = function () {};

// http://facebook.github.io/react/docs/events.html
ReactTestUtils.Simulate = {};

ReactTestUtils.Simulate.copy;
ReactTestUtils.Simulate.cut;
ReactTestUtils.Simulate.paste;
ReactTestUtils.Simulate.compositionEnd;
ReactTestUtils.Simulate.compositionStart;
ReactTestUtils.Simulate.compositionUpdate;
ReactTestUtils.Simulate.keyDown;
ReactTestUtils.Simulate.keyPress;
ReactTestUtils.Simulate.keyUp;
ReactTestUtils.Simulate.focus;
ReactTestUtils.Simulate.blur;
ReactTestUtils.Simulate.change;
ReactTestUtils.Simulate.input;
ReactTestUtils.Simulate.invalid;
ReactTestUtils.Simulate.submit;
ReactTestUtils.Simulate.click;
ReactTestUtils.Simulate.contextMenu;
ReactTestUtils.Simulate.doubleClick;
ReactTestUtils.Simulate.drag;
ReactTestUtils.Simulate.dragEnd;
ReactTestUtils.Simulate.dragEnter;
ReactTestUtils.Simulate.dragExit;
ReactTestUtils.Simulate.dragLeave;
ReactTestUtils.Simulate.dragOver;
ReactTestUtils.Simulate.dragStart;
ReactTestUtils.Simulate.drop;
ReactTestUtils.Simulate.mouseDown;
ReactTestUtils.Simulate.mouseEnter;
ReactTestUtils.Simulate.mouseLeave;
ReactTestUtils.Simulate.mouseMove;
ReactTestUtils.Simulate.mouseUp;
ReactTestUtils.Simulate.select;
ReactTestUtils.Simulate.touchCancel;
ReactTestUtils.Simulate.touchEnd;
ReactTestUtils.Simulate.touchMove;
ReactTestUtils.Simulate.touchStart;
ReactTestUtils.Simulate.scroll;
ReactTestUtils.Simulate.wheel;
ReactTestUtils.Simulate.abort;
ReactTestUtils.Simulate.canPlay;
ReactTestUtils.Simulate.canPlayThrough;
ReactTestUtils.Simulate.durationChange;
ReactTestUtils.Simulate.emptied;
ReactTestUtils.Simulate.encrypted;
ReactTestUtils.Simulate.ended;
ReactTestUtils.Simulate.error;
ReactTestUtils.Simulate.loadedData;
ReactTestUtils.Simulate.loadedMetadata;
ReactTestUtils.Simulate.loadStart;
ReactTestUtils.Simulate.pause;
ReactTestUtils.Simulate.play;
ReactTestUtils.Simulate.playing;
ReactTestUtils.Simulate.progress;
ReactTestUtils.Simulate.rateChange;
ReactTestUtils.Simulate.seeked;
ReactTestUtils.Simulate.seeking;
ReactTestUtils.Simulate.stalled;
ReactTestUtils.Simulate.suspend;
ReactTestUtils.Simulate.timeUpdate;
ReactTestUtils.Simulate.volumeChange;
ReactTestUtils.Simulate.waiting;
ReactTestUtils.Simulate.animationStart;
ReactTestUtils.Simulate.animationEnd;
ReactTestUtils.Simulate.animationIteration;
ReactTestUtils.Simulate.transitionEnd;
ReactTestUtils.Simulate.toggle;
