// generated with http://jmmk.github.io/javascript-externs-generator
// to regenerate from the tool:
// first https://unpkg.com/react@16.13.1/umd/react.production.min.js
// then https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js
// then https://unpkg.com/react-bootstrap@1.3.0/dist/react-bootstrap.min.js
// and enter ReactBootstrap as the javascript object to extern

/**********************************************************************
 * Extern for ReactBootstrap
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactBootstrap = {
  "Accordion": {
    "$$typeof": {},
    "Collapse": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Toggle": {
      "$$typeof": {},
      "render": function () {}
    },
    "displayName": {},
    "render": function () {}
  },
  "AccordionCollapse": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "AccordionContext": {
    "$$typeof": {},
    "Consumer": {},
    "Provider": {
      "$$typeof": {},
      "_context": {}
    },
    "_calculateChangedBits": {},
    "_currentValue": {},
    "_currentValue2": {},
    "_threadCount": {},
    "displayName": {}
  },
  "AccordionToggle": {
    "$$typeof": {},
    "render": function () {}
  },
  "Alert": {
    "$$typeof": {},
    "Heading": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Link": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "closeLabel": {},
      "show": {},
      "transition": {
        "$$typeof": {},
        "defaultProps": {
          "appear": {},
          "in": {},
          "mountOnEnter": {},
          "timeout": {},
          "unmountOnExit": {}
        },
        "displayName": {},
        "render": function () {}
      }
    },
    "displayName": {},
    "render": function () {}
  },
  "Badge": {
    "$$typeof": {},
    "defaultProps": {
      "pill": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Breadcrumb": {
    "$$typeof": {},
    "Item": {
      "$$typeof": {},
      "defaultProps": {
        "active": {},
        "linkProps": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "label": {},
      "listProps": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "BreadcrumbItem": {
    "$$typeof": {},
    "defaultProps": {
      "active": {},
      "linkProps": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Button": {
    "$$typeof": {},
    "defaultProps": {
      "active": {},
      "disabled": {},
      "variant": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "ButtonGroup": {
    "$$typeof": {},
    "defaultProps": {
      "role": {},
      "toggle": {},
      "vertical": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "ButtonToolbar": {
    "$$typeof": {},
    "defaultProps": {
      "role": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Card": {
    "$$typeof": {},
    "Body": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Footer": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Header": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Img": {
      "$$typeof": {},
      "defaultProps": {
        "variant": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "ImgOverlay": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Link": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Subtitle": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Text": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Title": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "body": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "CardColumns": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "CardDeck": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "CardGroup": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "CardImg": {
    "$$typeof": {},
    "defaultProps": {
      "variant": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Carousel": {
    "$$typeof": {},
    "Caption": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Item": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "controls": {},
      "defaultActiveIndex": {},
      "fade": {},
      "indicators": {},
      "interval": {},
      "keyboard": {},
      "nextIcon": {
        "$$typeof": {},
        "_owner": {},
        "key": {},
        "props": {
          "aria-hidden": {},
          "className": {}
        },
        "ref": {},
        "type": {}
      },
      "nextLabel": {},
      "pause": {},
      "prevIcon": {
        "$$typeof": {},
        "_owner": {},
        "key": {},
        "props": {
          "aria-hidden": {},
          "className": {}
        },
        "ref": {},
        "type": {}
      },
      "prevLabel": {},
      "slide": {},
      "touch": {},
      "wrap": {}
    },
    "displayName": {},
    "propTypes": {
      "activeIndex": {
        "isRequired": function () {}
      },
      "as": {
        "isRequired": function () {}
      },
      "bsPrefix": {
        "isRequired": function () {}
      },
      "controls": {
        "isRequired": function () {}
      },
      "fade": {
        "isRequired": function () {}
      },
      "indicators": {
        "isRequired": function () {}
      },
      "interval": {
        "isRequired": function () {}
      },
      "keyboard": {
        "isRequired": function () {}
      },
      "nextIcon": {
        "isRequired": function () {}
      },
      "nextLabel": {
        "isRequired": function () {}
      },
      "onSelect": {
        "isRequired": function () {}
      },
      "onSlid": {
        "isRequired": function () {}
      },
      "onSlide": {
        "isRequired": function () {}
      },
      "pause": {
        "isRequired": function () {}
      },
      "prevIcon": {
        "isRequired": function () {}
      },
      "prevLabel": {
        "isRequired": function () {}
      },
      "slide": {
        "isRequired": function () {}
      },
      "touch": {
        "isRequired": function () {}
      },
      "wrap": {
        "isRequired": function () {}
      }
    },
    "render": function () {}
  },
  "CarouselItem": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "CloseButton": {
    "$$typeof": {},
    "defaultProps": {
      "label": {}
    },
    "displayName": {},
    "propTypes": {
      "label": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      }
    },
    "render": function () {}
  },
  "Col": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "Collapse": {
    "$$typeof": {},
    "defaultProps": {
      "appear": {},
      "getDimensionValue": function () {},
      "in": {},
      "mountOnEnter": {},
      "timeout": {},
      "unmountOnExit": {}
    },
    "render": function () {}
  },
  "Container": {
    "$$typeof": {},
    "defaultProps": {
      "fluid": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Dropdown": {
    "$$typeof": {},
    "Divider": {
      "$$typeof": {},
      "defaultProps": {
        "role": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Header": {
      "$$typeof": {},
      "defaultProps": {
        "role": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Item": {
      "$$typeof": {},
      "defaultProps": {
        "as": {
          "$$typeof": {},
          "displayName": {},
          "render": function () {}
        },
        "disabled": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "ItemText": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Menu": {
      "$$typeof": {},
      "defaultProps": {
        "alignRight": {},
        "flip": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Toggle": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "navbar": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "DropdownButton": {
    "$$typeof": {},
    "displayName": {},
    "propTypes": {
      "bsPrefix": {
        "isRequired": function () {}
      },
      "disabled": {
        "isRequired": function () {}
      },
      "href": {
        "isRequired": function () {}
      },
      "id": {
        "isRequired": function () {}
      },
      "menuRole": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      },
      "renderMenuOnMount": {
        "isRequired": function () {}
      },
      "rootCloseEvent": {
        "isRequired": function () {}
      },
      "size": {
        "isRequired": function () {}
      },
      "title": {
        "isRequired": function () {}
      },
      "variant": {
        "isRequired": function () {}
      }
    },
    "render": function () {}
  },
  "Fade": {
    "$$typeof": {},
    "defaultProps": {
      "appear": {},
      "in": {},
      "mountOnEnter": {},
      "timeout": {},
      "unmountOnExit": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Figure": {
    "$$typeof": {},
    "Caption": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Image": {
      "$$typeof": {},
      "defaultProps": {
        "fluid": {}
      },
      "displayName": {},
      "propTypes": {
        "bsPrefix": {
          "isRequired": function () {}
        },
        "fluid": {
          "isRequired": function () {}
        },
        "rounded": {
          "isRequired": function () {}
        },
        "roundedCircle": {
          "isRequired": function () {}
        },
        "thumbnail": {
          "isRequired": function () {}
        }
      },
      "render": function () {}
    },
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "Form": {
    "$$typeof": {},
    "Check": {
      "$$typeof": {},
      "Input": {
        "$$typeof": {},
        "displayName": {},
        "render": function () {}
      },
      "Label": {
        "$$typeof": {},
        "displayName": {},
        "render": function () {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Control": {
      "$$typeof": {},
      "Feedback": {
        "$$typeof": {},
        "displayName": {},
        "propTypes": {
          "as": {
            "isRequired": function () {}
          },
          "tooltip": {
            "isRequired": function () {}
          },
          "type": {
            "isRequired": function () {}
          }
        },
        "render": function () {}
      },
      "displayName": {},
      "render": function () {}
    },
    "File": {
      "$$typeof": {},
      "Input": {
        "$$typeof": {},
        "displayName": {},
        "render": function () {}
      },
      "Label": {
        "$$typeof": {},
        "displayName": {},
        "render": function () {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Group": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Label": {
      "$$typeof": {},
      "defaultProps": {
        "column": {},
        "srOnly": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Row": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Switch": {
      "$$typeof": {},
      "Input": {
        "$$typeof": {},
        "displayName": {},
        "render": function () {}
      },
      "Label": {
        "$$typeof": {},
        "displayName": {},
        "render": function () {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Text": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "inline": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "FormCheck": {
    "$$typeof": {},
    "Input": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Label": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "displayName": {},
    "render": function () {}
  },
  "FormControl": {
    "$$typeof": {},
    "Feedback": {
      "$$typeof": {},
      "displayName": {},
      "propTypes": {
        "as": {
          "isRequired": function () {}
        },
        "tooltip": {
          "isRequired": function () {}
        },
        "type": {
          "isRequired": function () {}
        }
      },
      "render": function () {}
    },
    "displayName": {},
    "render": function () {}
  },
  "FormFile": {
    "$$typeof": {},
    "Input": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Label": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "displayName": {},
    "render": function () {}
  },
  "FormGroup": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "FormLabel": {
    "$$typeof": {},
    "defaultProps": {
      "column": {},
      "srOnly": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "FormText": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "Image": {
    "$$typeof": {},
    "defaultProps": {
      "fluid": {},
      "rounded": {},
      "roundedCircle": {},
      "thumbnail": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "InputGroup": {
    "$$typeof": {},
    "Append": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Checkbox": function () {},
    "Prepend": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Radio": function () {},
    "Text": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Jumbotron": {
    "$$typeof": {},
    "defaultProps": {
      "fluid": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "ListGroup": {
    "$$typeof": {},
    "Item": {
      "$$typeof": {},
      "defaultProps": {
        "active": {},
        "disabled": {},
        "variant": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "horizontal": {},
      "variant": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "ListGroupItem": {
    "$$typeof": {},
    "defaultProps": {
      "active": {},
      "disabled": {},
      "variant": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Media": {
    "$$typeof": {},
    "Body": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Modal": {
    "$$typeof": {},
    "BACKDROP_TRANSITION_DURATION": {},
    "Body": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Dialog": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Footer": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Header": {
      "$$typeof": {},
      "defaultProps": {
        "closeButton": {},
        "closeLabel": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "TRANSITION_DURATION": {},
    "Title": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "animation": {},
      "autoFocus": {},
      "backdrop": {},
      "dialogAs": {
        "$$typeof": {},
        "displayName": {},
        "render": function () {}
      },
      "enforceFocus": {},
      "keyboard": {},
      "restoreFocus": {},
      "show": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "ModalBody": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "ModalDialog": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "ModalFooter": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "ModalTitle": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "Nav": {
    "$$typeof": {},
    "Item": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Link": {
      "$$typeof": {},
      "defaultProps": {
        "as": {
          "$$typeof": {},
          "displayName": {},
          "render": function () {}
        },
        "disabled": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "fill": {},
      "justify": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "NavDropdown": {
    "$$typeof": {},
    "Divider": {
      "$$typeof": {},
      "defaultProps": {
        "role": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Header": {
      "$$typeof": {},
      "defaultProps": {
        "role": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Item": {
      "$$typeof": {},
      "defaultProps": {
        "as": {
          "$$typeof": {},
          "displayName": {},
          "render": function () {}
        },
        "disabled": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "ItemText": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "displayName": {},
    "propTypes": {
      "active": {
        "isRequired": function () {}
      },
      "bsPrefix": {
        "isRequired": function () {}
      },
      "disabled": {
        "isRequired": function () {}
      },
      "id": {
        "isRequired": function () {}
      },
      "menuRole": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      },
      "renderMenuOnMount": {
        "isRequired": function () {}
      },
      "rootCloseEvent": {
        "isRequired": function () {}
      },
      "title": {
        "isRequired": function () {}
      }
    },
    "render": function () {}
  },
  "NavItem": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "NavLink": {
    "$$typeof": {},
    "defaultProps": {
      "as": {
        "$$typeof": {},
        "displayName": {},
        "render": function () {}
      },
      "disabled": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Navbar": {
    "$$typeof": {},
    "Brand": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Collapse": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Text": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Toggle": {
      "$$typeof": {},
      "defaultProps": {
        "label": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "collapseOnSelect": {},
      "expand": {},
      "variant": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "NavbarBrand": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "Overlay": {
    "defaultProps": {
      "placement": {},
      "rootClose": {},
      "show": {},
      "transition": {
        "$$typeof": {},
        "defaultProps": {
          "appear": {},
          "in": {},
          "mountOnEnter": {},
          "timeout": {},
          "unmountOnExit": {}
        },
        "displayName": {},
        "render": function () {}
      }
    }
  },
  "OverlayTrigger": {
    "defaultProps": {
      "defaultShow": {},
      "trigger": {}
    }
  },
  "PageItem": {
    "$$typeof": {},
    "defaultProps": {
      "active": {},
      "activeLabel": {},
      "disabled": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Pagination": {
    "$$typeof": {},
    "Ellipsis": {
      "displayName": {}
    },
    "First": {
      "displayName": {}
    },
    "Item": {
      "$$typeof": {},
      "defaultProps": {
        "active": {},
        "activeLabel": {},
        "disabled": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Last": {
      "displayName": {}
    },
    "Next": {
      "displayName": {}
    },
    "Prev": {
      "displayName": {}
    },
    "render": function () {}
  },
  "Popover": {
    "$$typeof": {},
    "Content": {
      "$$typeof": {},
      "render": function () {}
    },
    "Title": {
      "$$typeof": {},
      "render": function () {}
    },
    "defaultProps": {
      "placement": {}
    },
    "render": function () {}
  },
  "PopoverContent": {
    "$$typeof": {},
    "render": function () {}
  },
  "PopoverTitle": {
    "$$typeof": {},
    "render": function () {}
  },
  "ProgressBar": {
    "$$typeof": {},
    "defaultProps": {
      "animated": {},
      "isChild": {},
      "max": {},
      "min": {},
      "srOnly": {},
      "striped": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "ResponsiveEmbed": {
    "$$typeof": {},
    "defaultProps": {
      "aspectRatio": {}
    },
    "render": function () {}
  },
  "Row": {
    "$$typeof": {},
    "defaultProps": {
      "noGutters": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "SafeAnchor": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "Spinner": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "SplitButton": {
    "$$typeof": {},
    "defaultProps": {
      "toggleLabel": {},
      "type": {}
    },
    "displayName": {},
    "propTypes": {
      "bsPrefix": {
        "isRequired": function () {}
      },
      "disabled": {
        "isRequired": function () {}
      },
      "href": {
        "isRequired": function () {}
      },
      "id": {
        "isRequired": function () {}
      },
      "menuRole": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      },
      "renderMenuOnMount": {
        "isRequired": function () {}
      },
      "rootCloseEvent": {
        "isRequired": function () {}
      },
      "size": {
        "isRequired": function () {}
      },
      "target": {
        "isRequired": function () {}
      },
      "title": {
        "isRequired": function () {}
      },
      "toggleLabel": {
        "isRequired": function () {}
      },
      "type": {
        "isRequired": function () {}
      },
      "variant": {
        "isRequired": function () {}
      }
    },
    "render": function () {}
  },
  "Tab": {
    "Container": function () {},
    "Content": {
      "$$typeof": {},
      "render": function () {}
    },
    "Pane": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    }
  },
  "TabContainer": function () {},
  "TabContent": {
    "$$typeof": {},
    "render": function () {}
  },
  "TabPane": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "Table": {
    "$$typeof": {},
    "render": function () {}
  },
  "Tabs": {
    "defaultProps": {
      "mountOnEnter": {},
      "unmountOnExit": {},
      "variant": {}
    },
    "displayName": {}
  },
  "ThemeProvider": function () {},
  "Toast": {
    "$$typeof": {},
    "Body": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Header": {
      "$$typeof": {},
      "defaultProps": {
        "closeButton": {},
        "closeLabel": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "displayName": {},
    "render": function () {}
  },
  "ToastBody": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "ToastHeader": {
    "$$typeof": {},
    "defaultProps": {
      "closeButton": {},
      "closeLabel": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "ToggleButton": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "ToggleButtonGroup": {
    "$$typeof": {},
    "Button": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "type": {}
    },
    "render": function () {}
  },
  "Tooltip": {
    "$$typeof": {},
    "defaultProps": {
      "placement": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "useAccordionToggle": function () {}
};
ReactBootstrap.Tab.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactBootstrap
/**********************************************************************/
