// generated with http://jmmk.github.io/javascript-externs-generator
// to regenerate from the tool:
// first https://unpkg.com/react@16.8.6/umd/react.production.min.js
// then https://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js
// then https://unpkg.com/react-bootstrap@1.0.0-beta.9/dist/react-bootstrap.min.js
// and enter ReactBootstrap as the javascript object to extern

/**********************************************************************
 * Extern for ReactBootstrap
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactBootstrap = {
  "Accordion": {
    "$$typeof": {},
    "Collapse": {
      "$$typeof": {},
      "render": function () {}
    },
    "Toggle": {
      "$$typeof": {},
      "render": function () {}
    },
    "render": function () {}
  },
  "Alert": {
    "$$typeof": {},
    "Heading": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Link": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "closeLabel": {},
      "show": {},
      "transition": {
        "defaultProps": {
          "appear": {},
          "in": {},
          "mountOnEnter": {},
          "timeout": {},
          "unmountOnExit": {}
        }
      }
    },
    "displayName": {},
    "render": function () {}
  },
  "Badge": {
    "$$typeof": {},
    "defaultProps": {
      "pill": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Breadcrumb": {
    "$$typeof": {},
    "Item": {
      "$$typeof": {},
      "defaultProps": {
        "active": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "label": {},
      "listProps": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "BreadcrumbItem": {
    "$$typeof": {},
    "defaultProps": {
      "active": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Button": {
    "$$typeof": {},
    "defaultProps": {
      "active": {},
      "disabled": {},
      "type": {},
      "variant": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "ButtonGroup": {
    "$$typeof": {},
    "defaultProps": {
      "role": {},
      "toggle": {},
      "vertical": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "ButtonToolbar": {
    "$$typeof": {},
    "defaultProps": {
      "role": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Card": {
    "$$typeof": {},
    "Body": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Footer": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Header": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Img": {
      "$$typeof": {},
      "defaultProps": {
        "variant": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "ImgOverlay": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Link": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Subtitle": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Text": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Title": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "body": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "CardColumns": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "CardDeck": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "CardGroup": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "CardImg": {
    "$$typeof": {},
    "defaultProps": {
      "variant": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Carousel": {
    "$$typeof": {},
    "Caption": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Item": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "CarouselItem": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "CloseButton": {
    "$$typeof": {},
    "defaultProps": {
      "label": {}
    },
    "displayName": {},
    "propTypes": {
      "label": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      }
    },
    "render": function () {}
  },
  "Col": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "Collapse": {
    "defaultProps": {
      "appear": {},
      "dimension": {},
      "getDimensionValue": function () {},
      "in": {},
      "mountOnEnter": {},
      "timeout": {},
      "unmountOnExit": {}
    }
  },
  "Container": {
    "$$typeof": {},
    "defaultProps": {
      "fluid": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Dropdown": {
    "$$typeof": {},
    "Divider": {
      "$$typeof": {},
      "defaultProps": {
        "role": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Header": {
      "$$typeof": {},
      "defaultProps": {
        "role": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Item": {
      "$$typeof": {},
      "defaultProps": {
        "as": function () {},
        "disabled": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Menu": {
      "$$typeof": {},
      "defaultProps": {
        "alignRight": {},
        "flip": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Toggle": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "propTypes": {},
      "render": function () {}
    },
    "defaultProps": {
      "navbar": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "DropdownButton": {
    "$$typeof": {},
    "displayName": {},
    "propTypes": {
      "bsPrefix": {
        "isRequired": function () {}
      },
      "disabled": {
        "isRequired": function () {}
      },
      "href": {
        "isRequired": function () {}
      },
      "id": {
        "isRequired": function () {}
      },
      "menuRole": {
        "isRequired": function () {}
      },
      "onClick": {
        "isRequired": function () {}
      },
      "rootCloseEvent": {
        "isRequired": function () {}
      },
      "size": {
        "isRequired": function () {}
      },
      "title": {
        "isRequired": function () {}
      },
      "variant": {
        "isRequired": function () {}
      }
    },
    "render": function () {}
  },
  "DropdownItem": {
    "$$typeof": {},
    "defaultProps": {
      "as": function () {},
      "disabled": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Fade": {
    "defaultProps": {
      "appear": {},
      "in": {},
      "mountOnEnter": {},
      "timeout": {},
      "unmountOnExit": {}
    }
  },
  "Figure": {
    "$$typeof": {},
    "Caption": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Image": {
      "$$typeof": {},
      "defaultProps": {
        "fluid": {}
      },
      "displayName": {},
      "propTypes": {
        "bsPrefix": {
          "isRequired": function () {}
        },
        "fluid": {
          "isRequired": function () {}
        },
        "rounded": {
          "isRequired": function () {}
        },
        "roundedCircle": {
          "isRequired": function () {}
        },
        "thumbnail": {
          "isRequired": function () {}
        }
      },
      "render": function () {}
    },
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "Form": {
    "$$typeof": {},
    "Check": {
      "$$typeof": {},
      "Input": {
        "$$typeof": {},
        "defaultProps": {
          "type": {}
        },
        "displayName": {},
        "render": function () {}
      },
      "Label": {
        "$$typeof": {},
        "defaultProps": {
          "type": {}
        },
        "displayName": {},
        "render": function () {}
      },
      "defaultProps": {
        "disabled": {},
        "inline": {},
        "isInvalid": {},
        "isValid": {},
        "title": {},
        "type": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Control": {
      "$$typeof": {},
      "Feedback": {
        "$$typeof": {},
        "defaultProps": {
          "type": {}
        },
        "displayName": {},
        "propTypes": {
          "as": {
            "isRequired": function () {}
          },
          "type": {
            "isRequired": function () {}
          }
        },
        "render": function () {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Group": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Label": {
      "$$typeof": {},
      "defaultProps": {
        "column": {},
        "srOnly": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Row": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Text": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "inline": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "FormCheck": {
    "$$typeof": {},
    "Input": {
      "$$typeof": {},
      "defaultProps": {
        "type": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Label": {
      "$$typeof": {},
      "defaultProps": {
        "type": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {
      "disabled": {},
      "inline": {},
      "isInvalid": {},
      "isValid": {},
      "title": {},
      "type": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "FormControl": {
    "$$typeof": {},
    "Feedback": {
      "$$typeof": {},
      "defaultProps": {
        "type": {}
      },
      "displayName": {},
      "propTypes": {
        "as": {
          "isRequired": function () {}
        },
        "type": {
          "isRequired": function () {}
        }
      },
      "render": function () {}
    },
    "displayName": {},
    "render": function () {}
  },
  "FormGroup": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "FormLabel": {
    "$$typeof": {},
    "defaultProps": {
      "column": {},
      "srOnly": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "FormText": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "Image": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "InputGroup": {
    "$$typeof": {},
    "Append": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Checkbox": function () {},
    "Prepend": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Radio": function () {},
    "Text": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "Jumbotron": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "ListGroup": {
    "$$typeof": {},
    "ControlledComponent": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "propTypes": {},
      "render": function () {}
    },
    "Item": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "propTypes": {},
      "render": function () {}
    },
    "deferControlTo": function () {},
    "propTypes": {
      "defaultActiveKey": function () {},
      "innerRef": function () {}
    },
    "render": function () {}
  },
  "ListGroupItem": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "Media": {
    "$$typeof": {},
    "Body": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "displayName": {},
    "render": function () {}
  },
  "Modal": {
    "$$typeof": {},
    "BACKDROP_TRANSITION_DURATION": {},
    "Body": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Dialog": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Footer": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Header": {
      "$$typeof": {},
      "defaultProps": {
        "closeButton": {},
        "closeLabel": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "TRANSITION_DURATION": {},
    "Title": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "ModalBody": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "ModalDialog": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "ModalFooter": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "ModalTitle": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "Nav": {
    "$$typeof": {},
    "Item": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Link": {
      "$$typeof": {},
      "defaultProps": {
        "as": function () {},
        "disabled": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "_Nav": {},
    "defaultProps": {
      "fill": {},
      "justify": {}
    },
    "displayName": {},
    "render": function () {}
  },
  "NavDropdown": {
    "Divider": {
      "$$typeof": {},
      "defaultProps": {
        "role": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Header": {
      "$$typeof": {},
      "defaultProps": {
        "role": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "Item": {
      "$$typeof": {},
      "defaultProps": {
        "as": function () {},
        "disabled": {}
      },
      "displayName": {},
      "render": function () {}
    }
  },
  "NavItem": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "Navbar": {
    "$$typeof": {},
    "Brand": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Collapse": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    },
    "Text": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Toggle": {
      "$$typeof": {},
      "defaultProps": {
        "label": {}
      },
      "displayName": {},
      "render": function () {}
    },
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "NavbarBrand": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "Overlay": {
    "defaultProps": {
      "placement": {},
      "rootClose": {},
      "show": {},
      "transition": {
        "defaultProps": {
          "appear": {},
          "in": {},
          "mountOnEnter": {},
          "timeout": {},
          "unmountOnExit": {}
        }
      }
    }
  },
  "OverlayTrigger": {
    "defaultProps": {
      "defaultOverlayShown": {},
      "trigger": {}
    }
  },
  "PageItem": {
    "defaultProps": {
      "active": {},
      "activeLabel": {},
      "disabled": {}
    }
  },
  "Pagination": {
    "$$typeof": {},
    "Ellipsis": {
      "displayName": {}
    },
    "First": {
      "displayName": {}
    },
    "Item": {
      "defaultProps": {
        "active": {},
        "activeLabel": {},
        "disabled": {}
      }
    },
    "Last": {
      "displayName": {}
    },
    "Next": {
      "displayName": {}
    },
    "Prev": {
      "displayName": {}
    },
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "Popover": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "ProgressBar": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "ResponsiveEmbed": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "Row": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "SafeAnchor": function () {},
  "Spinner": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "SplitButton": {
    "defaultProps": {
      "toggleLabel": {}
    }
  },
  "Tab": {
    "Container": {
      "$$typeof": {},
      "ControlledComponent": {
        "getDerivedStateFromProps": function () {}
      },
      "deferControlTo": function () {},
      "propTypes": {
        "defaultActiveKey": function () {},
        "innerRef": function () {}
      },
      "render": function () {}
    },
    "Content": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "propTypes": {},
      "render": function () {}
    },
    "Pane": {
      "$$typeof": {},
      "displayName": {},
      "render": function () {}
    }
  },
  "TabContainer": {
    "$$typeof": {},
    "ControlledComponent": {
      "getDerivedStateFromProps": function () {}
    },
    "deferControlTo": function () {},
    "propTypes": {
      "defaultActiveKey": function () {},
      "innerRef": function () {}
    },
    "render": function () {}
  },
  "TabContent": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "TabPane": {
    "$$typeof": {},
    "displayName": {},
    "render": function () {}
  },
  "Table": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "Tabs": {
    "$$typeof": {},
    "ControlledComponent": {
      "defaultProps": {
        "mountOnEnter": {},
        "unmountOnExit": {},
        "variant": {}
      }
    },
    "deferControlTo": function () {},
    "propTypes": {
      "defaultActiveKey": function () {},
      "innerRef": function () {}
    },
    "render": function () {}
  },
  "ThemeProvider": function () {},
  "Toast": {
    "$$typeof": {},
    "Body": {
      "$$typeof": {},
      "defaultProps": {},
      "displayName": {},
      "render": function () {}
    },
    "Header": {
      "defaultProps": {
        "closeButton": {},
        "closeLabel": {}
      },
      "displayName": {}
    },
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  },
  "ToastBody": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "render": function () {}
  },
  "ToastHeader": {
    "defaultProps": {
      "closeButton": {},
      "closeLabel": {}
    },
    "displayName": {}
  },
  "ToggleButton": {
    "$$typeof": {},
    "render": function () {}
  },
  "ToggleButtonGroup": {
    "$$typeof": {},
    "Button": {
      "$$typeof": {},
      "render": function () {}
    },
    "ControlledComponent": {
      "defaultProps": {
        "type": {}
      }
    },
    "deferControlTo": function () {},
    "propTypes": {
      "defaultValue": function () {},
      "innerRef": function () {}
    },
    "render": function () {}
  },
  "Tooltip": {
    "$$typeof": {},
    "defaultProps": {},
    "displayName": {},
    "propTypes": {},
    "render": function () {}
  }
};
ReactBootstrap.Alert.defaultProps.transition.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.Collapse.prototype = {
  "_getScrollDimensionValue": function () {},
  "constructor": function () {},
  "forceUpdate": function () {},
  "getDimension": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.Dropdown.Item.defaultProps.as.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "handleClick": function () {},
  "handleKeyDown": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.DropdownItem.defaultProps.as.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "handleClick": function () {},
  "handleKeyDown": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.Fade.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.Nav.Link.defaultProps.as.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "handleClick": function () {},
  "handleKeyDown": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.NavDropdown.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.NavDropdown.Item.defaultProps.as.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "handleClick": function () {},
  "handleKeyDown": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.Overlay.defaultProps.transition.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.OverlayTrigger.prototype = {
  "componentWillUnmount": function () {},
  "constructor": function () {},
  "forceUpdate": function () {},
  "getChildProps": function () {},
  "handleMouseOverOut": function () {},
  "hide": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {},
  "show": function () {}
};
ReactBootstrap.Pagination.Ellipsis.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.Pagination.First.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.Pagination.Last.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.Pagination.Next.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.Pagination.Prev.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.SafeAnchor.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "handleClick": function () {},
  "handleKeyDown": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.SplitButton.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.Tab.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.Tab.Container.ControlledComponent.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "getKey": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.TabContainer.ControlledComponent.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "getKey": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.Tabs.ControlledComponent.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "renderTab": function () {},
  "setState": function () {}
};
ReactBootstrap.ThemeProvider.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
ReactBootstrap.ToggleButtonGroup.ControlledComponent.prototype = {
  "constructor": function () {},
  "forceUpdate": function () {},
  "getValues": function () {},
  "handleToggle": function () {},
  "isReactComponent": function () {},
  "render": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactBootstrap
/**********************************************************************/
