/**********************************************************************
 * Extern for Chessground
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Chessground = {
  "controller": function () {},
  "view": function () {},
  "fen": {
    "initial": {},
    "read": function () {},
    "write": function () {}
  },
  "util": {
    "files": {},
    "ranks": {},
    "invRanks": {},
    "allPos": {},
    "allKeys": {},
    "invKeys": {},
    "pos2key": function () {},
    "key2pos": function () {},
    "invertKey": function () {},
    "opposite": function () {},
    "translate": function () {},
    "containsX": function () {},
    "distance": function () {},
    "eventPosition": function () {},
    "partialApply": function () {},
    "partial": function () {},
    "transformProp": function () {},
    "isTrident": function () {},
    "requestAnimationFrame": function () {},
    "isRightButton": function () {},
    "memo": function () {}
  },
  "configure": function () {},
  "anim": function () {},
  "board": {
    "reset": function () {},
    "toggleOrientation": function () {},
    "setPieces": function () {},
    "setCheck": function () {},
    "selectSquare": function () {},
    "setSelected": function () {},
    "isDraggable": function () {},
    "canMove": function () {},
    "userMove": function () {},
    "dropNewPiece": function () {},
    "apiMove": function () {},
    "apiNewPiece": function () {},
    "playPremove": function () {},
    "playPredrop": function () {},
    "unsetPremove": function () {},
    "unsetPredrop": function () {},
    "cancelMove": function () {},
    "stop": function () {},
    "getKeyAtDomPos": function () {},
    "getMaterialDiff": function () {},
    "getScore": function () {}
  },
  "drag": {
    "start": function () {},
    "move": function () {},
    "end": function () {},
    "cancel": function () {},
    "processDrag": function () {}
  }
};
/**********************************************************************
 * End Generated Extern for Chessground
/**********************************************************************/