/**********************************************************************
 * Extern for vl
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var vl = {
  "compile": function () {},
  "extractTransforms": function () {},
  "normalize": function () {},
  "version": {}
};
/**********************************************************************
 * End Generated Extern for vl
/**********************************************************************/