/**********************************************************************
 * Extern for vegaLite
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var vegaLite = {
  "compile": function () {},
  "extractTransforms": function () {},
  "normalize": function () {},
  "version": {}
};
/**********************************************************************
 * End Generated Extern for vegaLite
/**********************************************************************/