// Generated by http://www.dotnetwise.com/Code/Externs/
//
var proj4 = {
  "Point": {
    "fromMGRS": function () {}
  },
  "Proj": {
    "projections": {
      "add": function () {},
      "get": function () {},
      "start": function () {}
    }
  },
  "WGS84": {
    "a": {},
    "axis": {},
    "b": {},
    "datum": {
      "a": {},
      "b": {},
      "datum_params": {},
      "datum_type": {},
      "ep2": {},
      "es": {}
    },
    "datumCode": {},
    "datumName": {},
    "datum_params": {},
    "e": {},
    "ellps": {},
    "ep2": {},
    "es": {},
    "forward": function () {},
    "init": function () {},
    "inverse": function () {},
    "k0": {},
    "names": {},
    "projName": {},
    "rf": {},
    "sphere": {},
    "title": {},
    "units": {}
  },
  "defaultDatum": {},
  "defs": {
    "EPSG:102113": {
      "a": {},
      "b": {},
      "datumCode": {},
      "k0": {},
      "lat_ts": {},
      "long0": {},
      "no_defs": {},
      "projName": {},
      "title": {},
      "units": {},
      "x0": {},
      "y0": {}
    },
    "EPSG:3785": {
      "a": {},
      "b": {},
      "datumCode": {},
      "k0": {},
      "lat_ts": {},
      "long0": {},
      "no_defs": {},
      "projName": {},
      "title": {},
      "units": {},
      "x0": {},
      "y0": {}
    },
    "EPSG:3857": {
      "a": {},
      "b": {},
      "datumCode": {},
      "k0": {},
      "lat_ts": {},
      "long0": {},
      "no_defs": {},
      "projName": {},
      "title": {},
      "units": {},
      "x0": {},
      "y0": {}
    },
    "EPSG:4269": {
      "a": {},
      "b": {},
      "datumCode": {},
      "ellps": {},
      "projName": {},
      "title": {},
      "units": {}
    },
    "EPSG:4326": {
      "axis": {},
      "datumCode": {},
      "datumName": {},
      "datum_params": {},
      "ellps": {},
      "k0": {},
      "projName": {},
      "title": {},
      "units": {}
    },
    "EPSG:900913": {
      "a": {},
      "b": {},
      "datumCode": {},
      "k0": {},
      "lat_ts": {},
      "long0": {},
      "no_defs": {},
      "projName": {},
      "title": {},
      "units": {},
      "x0": {},
      "y0": {}
    },
    "GOOGLE": {
      "a": {},
      "b": {},
      "datumCode": {},
      "k0": {},
      "lat_ts": {},
      "long0": {},
      "no_defs": {},
      "projName": {},
      "title": {},
      "units": {},
      "x0": {},
      "y0": {}
    },
    "WGS84": {
      "axis": {},
      "datumCode": {},
      "datumName": {},
      "datum_params": {},
      "ellps": {},
      "k0": {},
      "projName": {},
      "title": {},
      "units": {}
    }
  },
  "mgrs": {
    "forward": function () {},
    "inverse": function () {},
    "toPoint": function () {}
  },
  "toPoint": function () {},
  "transform": function () {},
  "version": {}
};
proj4.Point.prototype = {
  "toMGRS": function () {}
};
