// Generated via http://jmmk.github.io/javascript-externs-generator/

// Loaded JavaScripts:
// https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.js
// https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-with-addons.js
// https://cdnjs.cloudflare.com/ajax/libs/react-virtualized/9.7.5/react-virtualized.js

// Reference JavaScript object: ReactVirtualized
/**********************************************************************
 * Extern for ReactVirtualized
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactVirtualized = {
  "ArrowKeyStepper": {
    "defaultProps": {
      "disabled": {},
      "mode": {},
      "scrollToColumn": {},
      "scrollToRow": {}
    }
  },
  "AutoSizer": {
    "defaultProps": {
      "onResize": function () {}
    }
  },
  "CellMeasurer": {
    "__internalCellMeasurerFlag": {}
  },
  "CellMeasurerCache": function () {},
  "Collection": {
    "defaultProps": {
      "aria-label": {},
      "cellGroupRenderer": function () {}
    }
  },
  "Column": {
    "defaultProps": {
      "cellDataGetter": function () {},
      "cellRenderer": function () {},
      "flexGrow": {},
      "flexShrink": {},
      "headerRenderer": function () {},
      "style": {}
    }
  },
  "ColumnSizer": function () {},
  "Grid": {
    "defaultProps": {
      "aria-label": {},
      "cellRangeRenderer": function () {},
      "estimatedColumnSize": {},
      "estimatedRowSize": {},
      "getScrollbarSize": function () {},
      "noContentRenderer": function () {},
      "onScroll": function () {},
      "onSectionRendered": function () {},
      "overscanColumnCount": {},
      "overscanIndicesGetter": function () {},
      "overscanRowCount": {},
      "role": {},
      "scrollToAlignment": {},
      "scrollToColumn": {},
      "scrollToRow": {},
      "scrollingResetTimeInterval": {},
      "style": {},
      "tabIndex": {}
    }
  },
  "InfiniteLoader": {
    "defaultProps": {
      "minimumBatchSize": {},
      "rowCount": {},
      "threshold": {}
    }
  },
  "List": {
    "defaultProps": {
      "estimatedRowSize": {},
      "noRowsRenderer": function () {},
      "onRowsRendered": function () {},
      "onScroll": function () {},
      "overscanIndicesGetter": function () {},
      "overscanRowCount": {},
      "scrollToAlignment": {},
      "scrollToIndex": {},
      "style": {}
    }
  },
  "Masonry": {
    "defaultProps": {
      "autoHeight": {},
      "keyMapper": function () {},
      "onCellsRendered": function () {},
      "onScroll": function () {},
      "overscanByPixels": {},
      "role": {},
      "scrollingResetTimeInterval": {},
      "style": {},
      "tabIndex": {}
    }
  },
  "MultiGrid": {
    "defaultProps": {
      "fixedColumnCount": {},
      "fixedRowCount": {},
      "style": {},
      "styleBottomLeftGrid": {},
      "styleBottomRightGrid": {},
      "styleTopLeftGrid": {},
      "styleTopRightGrid": {}
    }
  },
  "ScrollSync": function () {},
  "SortDirection": {
    "ASC": {},
    "DESC": {}
  },
  "SortIndicator": function () {},
  "Table": {
    "defaultProps": {
      "disableHeader": {},
      "estimatedRowSize": {},
      "headerHeight": {},
      "headerRowRenderer": function () {},
      "headerStyle": {},
      "noRowsRenderer": function () {},
      "onRowsRendered": function () {},
      "onScroll": function () {},
      "overscanIndicesGetter": function () {},
      "overscanRowCount": {},
      "rowRenderer": function () {},
      "rowStyle": {},
      "scrollToAlignment": {},
      "scrollToIndex": {},
      "style": {}
    }
  },
  "WindowScroller": {
    "defaultProps": {
      "onResize": function () {},
      "onScroll": function () {}
    }
  },
  "accessibilityOverscanIndicesGetter": function () {},
  "createMasonryCellPositioner": function () {},
  "defaultCellRangeRenderer": function () {},
  "defaultOverscanIndicesGetter": function () {},
  "defaultTableCellDataGetter": function () {},
  "defaultTableCellRenderer": function () {},
  "defaultTableHeaderRenderer": function () {},
  "defaultTableHeaderRowRenderer": function () {},
  "defaultTableRowRenderer": function () {}
};
ReactVirtualized.ArrowKeyStepper.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.AutoSizer.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.CellMeasurer.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.Collection.prototype = {
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.Column.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.ColumnSizer.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.Grid.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.InfiniteLoader.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.List.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.Masonry.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.MultiGrid.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.ScrollSync.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.Table.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
ReactVirtualized.WindowScroller.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactVirtualized
/**********************************************************************/