/**********************************************************************
 * Extern for Select
 * Generated by http://jmmk.github.io/javascript-externs-generator
 * 
 * Loaded JavaScripts:
 * https://unpkg.com/react@16.2.0/umd/react.production.min.js
 * https://unpkg.com/prop-types@15.5.10/prop-types.js
 * https://unpkg.com/classnames@2.2.5/index.js
 * https://unpkg.com/react-input-autosize@2.2.1/dist/react-input-autosize.js
 * https://unpkg.com/react-select@2.3.0/dist/react-select.js
 **********************************************************************/
var Select = {
  "Async": {
    "defaultProps": {
      "cacheOptions": {},
      "defaultOptions": {}
    }
  },
  "AsyncCreatable": {
    "defaultProps": {
      "cacheOptions": {},
      "defaultOptions": {}
    }
  },
  "Creatable": {
    "defaultProps": {
      "defaultInputValue": {},
      "defaultMenuIsOpen": {},
      "defaultValue": {}
    }
  },
  "SelectBase": {
    "defaultProps": {
      "backspaceRemovesValue": {},
      "blurInputOnSelect": {},
      "captureMenuScroll": {},
      "closeMenuOnScroll": {},
      "closeMenuOnSelect": {},
      "components": {},
      "controlShouldRenderValue": {},
      "escapeClearsValue": {},
      "filterOption": function () { },
      "formatGroupLabel": function () { },
      "getOptionLabel": function () { },
      "getOptionValue": function () { },
      "isDisabled": {},
      "isLoading": {},
      "isMulti": {},
      "isOptionDisabled": function () { },
      "isRtl": {},
      "isSearchable": {},
      "loadingMessage": function () { },
      "maxMenuHeight": {},
      "menuIsOpen": {},
      "menuPlacement": {},
      "menuPosition": {},
      "menuShouldBlockScroll": {},
      "menuShouldScrollIntoView": {},
      "minMenuHeight": {},
      "noOptionsMessage": function () { },
      "openMenuOnClick": {},
      "openMenuOnFocus": {},
      "options": {},
      "pageSize": {},
      "placeholder": {},
      "screenReaderStatus": function () { },
      "styles": {},
      "tabIndex": {},
      "tabSelectsValue": {}
    }
  },
  "components": {
    "ClearIndicator": function () { },
    "Control": function () { },
    "CrossIcon": function () { },
    "DownChevron": function () { },
    "DropdownIndicator": function () { },
    "Group": function () { },
    "GroupHeading": function () { },
    "IndicatorSeparator": function () { },
    "IndicatorsContainer": function () { },
    "Input": function () { },
    "LoadingIndicator": {
      "defaultProps": {
        "size": {}
      }
    },
    "LoadingMessage": {
      "defaultProps": {
        "children": {}
      }
    },
    "Menu": function () { },
    "MenuList": function () { },
    "MenuPortal": {
      "childContextTypes": {
        "getPortalPlacement": {
          "isRequired": function () { }
        }
      }
    },
    "MultiValue": {
      "defaultProps": {
        "cropWithEllipsis": {}
      }
    },
    "MultiValueContainer": function () { },
    "MultiValueLabel": function () { },
    "MultiValueRemove": function () { },
    "NoOptionsMessage": {
      "defaultProps": {
        "children": {}
      }
    },
    "Option": function () { },
    "Placeholder": function () { },
    "SelectContainer": function () { },
    "SingleValue": function () { },
    "ValueContainer": function () { }
  },
  "createFilter": function () { },
  "defaultProps": {
    "defaultInputValue": {},
    "defaultMenuIsOpen": {},
    "defaultValue": {}
  },
  "defaultTheme": {
    "borderRadius": {},
    "colors": {
      "danger": {},
      "dangerLight": {},
      "neutral0": {},
      "neutral10": {},
      "neutral20": {},
      "neutral30": {},
      "neutral40": {},
      "neutral5": {},
      "neutral50": {},
      "neutral60": {},
      "neutral70": {},
      "neutral80": {},
      "neutral90": {},
      "primary": {},
      "primary25": {},
      "primary50": {},
      "primary75": {}
    },
    "spacing": {
      "baseUnit": {},
      "controlHeight": {},
      "menuGutter": {}
    }
  },
  "mergeStyles": function () { }
};
Select.prototype = {
  "forceUpdate": function () { },
  "isReactComponent": function () { },
  "setState": function () { }
};
Select.Async.prototype = {
  "forceUpdate": function () { },
  "isReactComponent": function () { },
  "setState": function () { }
};
Select.AsyncCreatable.prototype = {
  "forceUpdate": function () { },
  "isReactComponent": function () { },
  "setState": function () { }
};
Select.Creatable.prototype = {
  "forceUpdate": function () { },
  "isReactComponent": function () { },
  "setState": function () { }
};
Select.SelectBase.prototype = {
  "forceUpdate": function () { },
  "isReactComponent": function () { },
  "setState": function () { }
};
Select.components.MenuPortal.prototype = {
  "forceUpdate": function () { },
  "isReactComponent": function () { },
  "setState": function () { }
};
Select.components.MultiValue.prototype = {
  "forceUpdate": function () { },
  "isReactComponent": function () { },
  "setState": function () { }
};
Select.components.MultiValueRemove.prototype = {
  "forceUpdate": function () { },
  "isReactComponent": function () { },
  "setState": function () { }
};
Select.components.ValueContainer.prototype = {
  "forceUpdate": function () { },
  "isReactComponent": function () { },
  "setState": function () { }
};
/**********************************************************************
 * End Generated Extern for Select
/**********************************************************************/