var Select = {
    "displayName": {},
    "propTypes": {
        "addLabelText": function () {},
        "allowCreate": function () {},
        "asyncOptions": function () {},
        "autoload": function () {},
        "backspaceRemoves": function () {},
        "cacheAsyncResults": function () {},
        "className": function () {},
        "clearAllText": function () {},
        "clearValueText": function () {},
        "clearable": function () {},
        "delimiter": function () {},
        "disabled": function () {},
        "filterOption": function () {},
        "filterOptions": function () {},
        "ignoreCase": function () {},
        "inputProps": function () {},
        "isLoading": function () {},
        "labelKey": function () {},
        "matchPos": function () {},
        "matchProp": function () {},
        "multi": function () {},
        "name": function () {},
        "newOptionCreator": function () {},
        "noResultsText": function () {},
        "onBlur": function () {},
        "onChange": function () {},
        "onFocus": function () {},
        "onInputChange": function () {},
        "onOptionLabelClick": function () {},
        "optionComponent": function () {},
        "optionRenderer": function () {},
        "options": function () {},
        "placeholder": function () {},
        "searchable": function () {},
        "searchingText": function () {},
        "searchPromptText": function () {},
        "singleValueComponent": function () {},
        "value": function () {},
        "valueComponent": function () {},
        "valueKey": function () {},
        "valueRenderer": function () {}
    },
    "getDefaultProps": function () {},
    "defaultProps": {
        "addLabelText": {},
        "allowCreate": {},
        "asyncOptions": {},
        "autoload": {},
        "backspaceRemoves": {},
        "cacheAsyncResults": {},
        "className": {},
        "clearAllText": {},
        "clearValueText": {},
        "clearable": {},
        "delimiter": {},
        "disabled": {},
        "ignoreCase": {},
        "inputProps": function () {},
        "isLoading": {},
        "labelKey": {},
        "matchPos": {},
        "matchProp": {},
        "name": {},
        "newOptionCreator": {},
        "noResultsText": {},
        "onChange": {},
        "onInputChange": {},
        "onOptionLabelClick": {},
        "optionComponent": function () {},
        "options": {},
        "placeholder": {},
        "searchable": {},
        "searchingText": {},
        "searchPromptText": {},
        "singleValueComponent": function () {},
        "value": {},
        "valueComponent": function () {},
        "valueKey": {}
    }
}
