var PIXI = {
    "VERSION": {},
    "PI_2": {},
    "RAD_TO_DEG": {},
    "DEG_TO_RAD": {},
    "TARGET_FPMS": {},
    "RENDERER_TYPE": {
        "UNKNOWN": {},
        "WEBGL": {},
        "CANVAS": {}
    },
    "BLEND_MODES": {
        "NORMAL": {},
        "ADD": {},
        "MULTIPLY": {},
        "SCREEN": {},
        "OVERLAY": {},
        "DARKEN": {},
        "LIGHTEN": {},
        "COLOR_DODGE": {},
        "COLOR_BURN": {},
        "HARD_LIGHT": {},
        "SOFT_LIGHT": {},
        "DIFFERENCE": {},
        "EXCLUSION": {},
        "HUE": {},
        "SATURATION": {},
        "COLOR": {},
        "LUMINOSITY": {}
    },
    "SCALE_MODES": {
        "DEFAULT": {},
        "LINEAR": {},
        "NEAREST": {}
    },
    "RETINA_PREFIX": function () {},
    "RESOLUTION": {},
    "FILTER_RESOLUTION": {},
    "DEFAULT_RENDER_OPTIONS": {
        "view": function () {},
        "resolution": {},
        "antialias": {},
        "forceFXAA": {},
        "autoResize": {},
        "transparent": {},
        "backgroundColor": {},
        "clearBeforeRender": {},
        "preserveDrawingBuffer": {}
    },
    "SHAPES": {
        "POLY": {},
        "RECT": {},
        "CIRC": {},
        "ELIP": {},
        "RREC": {}
    },
    "SPRITE_BATCH_SIZE": {},
    "Point": function () {},
    "Matrix": function () {},
    "Circle": function () {},
    "Ellipse": function () {},
    "Polygon": function () {},
    "Rectangle": function () {},
    "RoundedRectangle": function () {},
    "utils": {
        "_uid": {},
        "_saidHello": {},
        "pluginTarget": {
            "mixin": function () {}
        },
        "async": {
            "noConflict": function () {},
            "nextTick": function () {},
            "setImmediate": function () {},
            "each": function () {},
            "forEach": function () {},
            "eachSeries": function () {},
            "forEachSeries": function () {},
            "eachLimit": function () {},
            "forEachLimit": function () {},
            "map": function () {},
            "mapSeries": function () {},
            "mapLimit": function () {},
            "reduce": function () {},
            "inject": function () {},
            "foldl": function () {},
            "reduceRight": function () {},
            "foldr": function () {},
            "filter": function () {},
            "filterSeries": function () {},
            "select": function () {},
            "selectSeries": function () {},
            "reject": function () {},
            "rejectSeries": function () {},
            "detect": function () {},
            "detectSeries": function () {},
            "some": function () {},
            "any": function () {},
            "every": function () {},
            "all": function () {},
            "sortBy": function () {},
            "auto": function () {},
            "retry": function () {},
            "waterfall": function () {},
            "parallel": function () {},
            "parallelLimit": function () {},
            "series": function () {},
            "iterator": function () {},
            "apply": function () {},
            "concat": function () {},
            "concatSeries": function () {},
            "whilst": function () {},
            "doWhilst": function () {},
            "until": function () {},
            "doUntil": function () {},
            "queue": function () {},
            "priorityQueue": function () {},
            "cargo": function () {},
            "log": function () {},
            "dir": function () {},
            "memoize": function () {},
            "unmemoize": function () {},
            "times": function () {},
            "timesSeries": function () {},
            "seq": function () {},
            "compose": function () {},
            "applyEach": function () {},
            "applyEachSeries": function () {},
            "forever": function () {}
        },
        "uuid": function () {},
        "hex2rgb": function () {},
        "hex2string": function () {},
        "rgb2hex": function () {},
        "canUseNewCanvasBlendModes": function () {},
        "getNextPowerOfTwo": function () {},
        "isPowerOfTwo": function () {},
        "getResolutionOfUrl": function () {},
        "sayHello": function () {},
        "isWebGLSupported": function () {},
        "TextureCache": function () {},
        "BaseTextureCache": function () {}
    },
    "math": {
        "Point": function () {},
        "Matrix": function () {},
        "Circle": function () {},
        "Ellipse": function () {},
        "Polygon": function () {},
        "Rectangle": function () {},
        "RoundedRectangle": function () {}
    },
    "ticker": {
        "shared": {
            "_tick": function () {},
            "_emitter": {
                "_events": {},
                "listeners": function () {},
                "emit": function () {},
                "on": function () {},
                "once": function () {},
                "removeListener": function () {},
                "removeAllListeners": function () {},
                "off": function () {},
                "addListener": function () {},
                "setMaxListeners": function () {}
            },
            "_requestId": function () {},
            "_maxElapsedMS": {},
            "autoStart": {},
            "deltaTime": {},
            "elapsedMS": {},
            "lastTime": {},
            "speed": {},
            "started": {},
            "_requestIfNeeded": function () {},
            "_cancelIfNeeded": function () {},
            "_startIfPossible": function () {},
            "add": function () {},
            "addOnce": function () {},
            "remove": function () {},
            "start": function () {},
            "stop": function () {},
            "update": function () {}
        },
        "Ticker": function () {}
    },
    "DisplayObject": function () {},
    "Container": function () {},
    "Sprite": function () {},
    "ParticleContainer": function () {},
    "SpriteRenderer": function () {},
    "ParticleRenderer": function () {},
    "Text": function () {},
    "Graphics": function () {},
    "GraphicsData": function () {},
    "GraphicsRenderer": function () {},
    "Texture": function () {},
    "BaseTexture": function () {},
    "RenderTexture": function () {},
    "VideoBaseTexture": function () {},
    "TextureUvs": function () {},
    "CanvasRenderer": function () {},
    "CanvasGraphics": {
        "renderGraphics": function () {},
        "renderGraphicsMask": function () {},
        "updateGraphicsTint": function () {}
    },
    "CanvasBuffer": function () {},
    "WebGLRenderer": function () {},
    "ShaderManager": function () {},
    "Shader": function () {},
    "ObjectRenderer": function () {},
    "RenderTarget": function () {},
    "AbstractFilter": function () {},
    "autoDetectRenderer": function () {},
    "extras": {
        "MovieClip": function () {},
        "TilingSprite": function () {},
        "BitmapText": function () {}
    },
    "filters": {
        "AbstractFilter": function () {},
        "FXAAFilter": function () {},
        "SpriteMaskFilter": function () {},
        "AsciiFilter": function () {},
        "BloomFilter": function () {},
        "BlurFilter": function () {},
        "BlurXFilter": function () {},
        "BlurYFilter": function () {},
        "BlurDirFilter": function () {},
        "ColorMatrixFilter": function () {},
        "ColorStepFilter": function () {},
        "ConvolutionFilter": function () {},
        "CrossHatchFilter": function () {},
        "DisplacementFilter": function () {},
        "DotScreenFilter": function () {},
        "GrayFilter": function () {},
        "DropShadowFilter": function () {},
        "InvertFilter": function () {},
        "NoiseFilter": function () {},
        "NormalMapFilter": function () {},
        "PixelateFilter": function () {},
        "RGBSplitFilter": function () {},
        "ShockwaveFilter": function () {},
        "SepiaFilter": function () {},
        "SmartBlurFilter": function () {},
        "TiltShiftFilter": function () {},
        "TiltShiftXFilter": function () {},
        "TiltShiftYFilter": function () {},
        "TwistFilter": function () {}
    },
    "interaction": {
        "InteractionData": function () {},
        "InteractionManager": function () {},
        "interactiveTarget": {
            "interactive": {},
            "buttonMode": {},
            "interactiveChildren": {},
            "defaultCursor": {},
            "_over": {},
            "_touchDown": {}
        }
    },
    "loaders": {
        "Loader": function () {},
        "bitmapFontParser": function () {},
        "spritesheetParser": function () {},
        "textureParser": function () {},
        "Resource": function () {}
    },
    "mesh": {
        "Mesh": function () {},
        "Rope": function () {},
        "MeshRenderer": function () {},
        "MeshShader": function () {}
    },
    "loader": {
        "baseUrl": {},
        "progress": {},
        "loading": {},
        "_progressChunk": {},
        "_beforeMiddleware": function () {},
        "_afterMiddleware": {
            "0": function () {},
            "1": function () {},
            "2": function () {},
            "3": function () {}
        },
        "_boundLoadResource": function () {},
        "_boundOnLoad": function () {},
        "_buffer": function () {},
        "_numToLoad": {},
        "_queue": {
            "tasks": function () {},
            "concurrency": {},
            "saturated": function () {},
            "empty": function () {},
            "drain": function () {},
            "started": {},
            "paused": {},
            "push": function () {},
            "kill": function () {},
            "unshift": function () {},
            "process": function () {},
            "length": function () {},
            "running": function () {},
            "idle": function () {},
            "pause": function () {},
            "resume": function () {}
        },
        "resources": function () {},
        "constructor": function () {},
        "enqueue": function () {},
        "add": function () {},
        "_handleBaseUrl": function () {},
        "pre": function () {},
        "before": function () {},
        "use": function () {},
        "after": function () {},
        "reset": function () {},
        "load": function () {},
        "_loadResource": function () {},
        "_onComplete": function () {},
        "_onLoad": function () {},
        "_runMiddleware": function () {},
        "_events": {},
        "listeners": function () {},
        "emit": function () {},
        "on": function () {},
        "once": function () {},
        "removeListener": function () {},
        "removeAllListeners": function () {},
        "off": function () {},
        "addListener": function () {},
        "setMaxListeners": function () {}
    },
    "SpriteBatch": function () {},
    "AssetLoader": function () {}
}
