var PIXI = {
  "VERSION": {},
  "PI_2": {},
  "RAD_TO_DEG": {},
  "DEG_TO_RAD": {},
  "TARGET_FPMS": {},
  "RENDERER_TYPE": {
    "UNKNOWN": {},
    "WEBGL": {},
    "CANVAS": {}
  },
  "BLEND_MODES": {
    "NORMAL": {},
    "ADD": {},
    "MULTIPLY": {},
    "SCREEN": {},
    "OVERLAY": {},
    "DARKEN": {},
    "LIGHTEN": {},
    "COLOR_DODGE": {},
    "COLOR_BURN": {},
    "HARD_LIGHT": {},
    "SOFT_LIGHT": {},
    "DIFFERENCE": {},
    "EXCLUSION": {},
    "HUE": {},
    "SATURATION": {},
    "COLOR": {},
    "LUMINOSITY": {}
  },
  "DRAW_MODES": {
    "POINTS": {},
    "LINES": {},
    "LINE_LOOP": {},
    "LINE_STRIP": {},
    "TRIANGLES": {},
    "TRIANGLE_STRIP": {},
    "TRIANGLE_FAN": {}
  },
  "SCALE_MODES": {
    "DEFAULT": {},
    "LINEAR": {},
    "NEAREST": {}
  },
  "RETINA_PREFIX": {},
  "RESOLUTION": {},
  "FILTER_RESOLUTION": {},
  "DEFAULT_RENDER_OPTIONS": {
    "view": {},
    "resolution": {},
    "antialias": {},
    "forceFXAA": {},
    "autoResize": {},
    "transparent": {},
    "backgroundColor": {},
    "clearBeforeRender": {},
    "preserveDrawingBuffer": {},
    "roundPixels": {}
  },
  "SHAPES": {
    "POLY": {},
    "RECT": {},
    "CIRC": {},
    "ELIP": {},
    "RREC": {}
  },
  "SPRITE_BATCH_SIZE": {},
  "Point": function () {},
  "Matrix": {
    "IDENTITY": {},
    "TEMP_MATRIX": {}
  },
  "GroupD8": {
    "E": {},
    "SE": {},
    "S": {},
    "SW": {},
    "W": {},
    "NW": {},
    "N": {},
    "NE": {},
    "MIRROR_VERTICAL": {},
    "MIRROR_HORIZONTAL": {},
    "uX": function () {},
    "uY": function () {},
    "vX": function () {},
    "vY": function () {},
    "inv": function () {},
    "add": function () {},
    "sub": function () {},
    "rotate180": function () {},
    "isSwapWidthHeight": function () {},
    "byDirection": function () {},
    "matrixAppendRotationInv": function () {}
  },
  "Circle": function () {},
  "Ellipse": function () {},
  "Polygon": function () {},
  "Rectangle": {
    "EMPTY": {}
  },
  "RoundedRectangle": function () {},
  "utils": {
    "_uid": {},
    "_saidHello": {},
    "EventEmitter": {
      "prefixed": {}
    },
    "pluginTarget": {
      "mixin": function () {}
    },
    "async": {
      "noConflict": function () {},
      "nextTick": function () {},
      "setImmediate": function () {},
      "each": function () {},
      "forEach": function () {},
      "eachSeries": function () {},
      "forEachSeries": function () {},
      "eachLimit": function () {},
      "forEachLimit": function () {},
      "eachOf": function () {},
      "forEachOf": function () {},
      "eachOfSeries": function () {},
      "forEachOfSeries": function () {},
      "eachOfLimit": function () {},
      "forEachOfLimit": function () {},
      "map": function () {},
      "mapSeries": function () {},
      "mapLimit": function () {},
      "reduce": function () {},
      "foldl": function () {},
      "inject": function () {},
      "reduceRight": function () {},
      "foldr": function () {},
      "transform": function () {},
      "filter": function () {},
      "select": function () {},
      "filterLimit": function () {},
      "selectLimit": function () {},
      "filterSeries": function () {},
      "selectSeries": function () {},
      "reject": function () {},
      "rejectLimit": function () {},
      "rejectSeries": function () {},
      "some": function () {},
      "any": function () {},
      "someLimit": function () {},
      "every": function () {},
      "all": function () {},
      "everyLimit": function () {},
      "detect": function () {},
      "detectSeries": function () {},
      "detectLimit": function () {},
      "sortBy": function () {},
      "auto": function () {},
      "retry": function () {},
      "waterfall": function () {},
      "parallel": function () {},
      "parallelLimit": function () {},
      "series": function () {},
      "iterator": function () {},
      "apply": function () {},
      "concat": function () {},
      "concatSeries": function () {},
      "whilst": function () {},
      "doWhilst": function () {},
      "until": function () {},
      "doUntil": function () {},
      "during": function () {},
      "doDuring": function () {},
      "queue": function () {},
      "priorityQueue": function () {},
      "cargo": function () {},
      "log": function () {},
      "dir": function () {},
      "memoize": function () {},
      "unmemoize": function () {},
      "times": function () {},
      "timesSeries": function () {},
      "timesLimit": function () {},
      "seq": function () {},
      "compose": function () {},
      "applyEach": function () {},
      "applyEachSeries": function () {},
      "forever": function () {},
      "ensureAsync": function () {},
      "constant": function () {},
      "asyncify": function () {},
      "wrapSync": function () {}
    },
    "uid": function () {},
    "hex2rgb": function () {},
    "hex2string": function () {},
    "rgb2hex": function () {},
    "canUseNewCanvasBlendModes": function () {},
    "getNextPowerOfTwo": function () {},
    "isPowerOfTwo": function () {},
    "getResolutionOfUrl": function () {},
    "sayHello": function () {},
    "isWebGLSupported": function () {},
    "sign": function () {},
    "removeItems": function () {},
    "TextureCache": {},
    "BaseTextureCache": {},
    "uuid": function () {}
  },
  "ticker": {
    "shared": {},
    "Ticker": function () {}
  },
  "DisplayObject": function () {},
  "Container": function () {},
  "Sprite": {
    "fromFrame": function () {},
    "fromImage": function () {}
  },
  "ParticleContainer": function () {},
  "SpriteRenderer": function () {},
  "ParticleRenderer": function () {},
  "Text": {
    "fontPropertiesCache": {},
    "fontPropertiesCanvas": {},
    "fontPropertiesContext": {}
  },
  "Graphics": function () {},
  "GraphicsData": function () {},
  "GraphicsRenderer": function () {},
  "Texture": {
    "fromImage": function () {},
    "fromFrame": function () {},
    "fromCanvas": function () {},
    "fromVideo": function () {},
    "fromVideoUrl": function () {},
    "addTextureToCache": function () {},
    "removeTextureFromCache": function () {},
    "EMPTY": {}
  },
  "BaseTexture": {
    "fromImage": function () {},
    "fromCanvas": function () {}
  },
  "RenderTexture": function () {},
  "VideoBaseTexture": {
    "fromVideo": function () {},
    "fromUrl": function () {},
    "fromUrls": function () {}
  },
  "TextureUvs": function () {},
  "CanvasRenderer": {
    "__plugins": {
      "interaction": function () {},
      "accessibility": function () {}
    },
    "registerPlugin": function () {}
  },
  "CanvasGraphics": {
    "renderGraphics": function () {},
    "renderGraphicsMask": function () {},
    "updateGraphicsTint": function () {}
  },
  "CanvasBuffer": function () {},
  "WebGLRenderer": {
    "__plugins": {
      "sprite": function () {},
      "particle": function () {},
      "graphics": function () {},
      "interaction": function () {},
      "mesh": function () {},
      "accessibility": function () {}
    },
    "registerPlugin": function () {},
    "glContextId": {}
  },
  "WebGLManager": function () {},
  "ShaderManager": {
    "__plugins": {
      "meshShader": function () {}
    },
    "registerPlugin": function () {}
  },
  "Shader": function () {},
  "TextureShader": {
    "defaultVertexSrc": {},
    "defaultFragmentSrc": {}
  },
  "PrimitiveShader": function () {},
  "ComplexPrimitiveShader": function () {},
  "ObjectRenderer": function () {},
  "RenderTarget": function () {},
  "AbstractFilter": function () {},
  "FXAAFilter": function () {},
  "SpriteMaskFilter": function () {},
  "autoDetectRenderer": function () {},
  "extras": {
    "MovieClip": {
      "fromFrames": function () {},
      "fromImages": function () {}
    },
    "TilingSprite": {
      "fromFrame": function () {},
      "fromImage": function () {}
    },
    "BitmapText": {
      "fonts": {}
    }
  },
  "filters": {
    "AsciiFilter": function () {},
    "BloomFilter": function () {},
    "BlurFilter": function () {},
    "BlurXFilter": function () {},
    "BlurYFilter": function () {},
    "BlurDirFilter": function () {},
    "ColorMatrixFilter": function () {},
    "ColorStepFilter": function () {},
    "ConvolutionFilter": function () {},
    "CrossHatchFilter": function () {},
    "DisplacementFilter": function () {},
    "DotScreenFilter": function () {},
    "GrayFilter": function () {},
    "DropShadowFilter": function () {},
    "InvertFilter": function () {},
    "NoiseFilter": function () {},
    "PixelateFilter": function () {},
    "RGBSplitFilter": function () {},
    "ShockwaveFilter": function () {},
    "SepiaFilter": function () {},
    "SmartBlurFilter": function () {},
    "TiltShiftFilter": function () {},
    "TiltShiftXFilter": function () {},
    "TiltShiftYFilter": function () {},
    "TwistFilter": function () {}
  },
  "interaction": {
    "InteractionData": function () {},
    "InteractionManager": function () {},
    "interactiveTarget": {
      "interactive": {},
      "buttonMode": {},
      "interactiveChildren": {},
      "defaultCursor": {},
      "_over": {},
      "_touchDown": {}
    }
  },
  "loaders": {
    "Loader": {
      "_pixiMiddleware": {},
      "addPixiMiddleware": function () {}
    },
    "bitmapFontParser": function () {},
    "spritesheetParser": function () {},
    "textureParser": function () {},
    "Resource": {
      "LOAD_TYPE": {
        "XHR": {},
        "IMAGE": {},
        "AUDIO": {},
        "VIDEO": {}
      },
      "XHR_READY_STATE": {
        "UNSENT": {},
        "OPENED": {},
        "HEADERS_RECEIVED": {},
        "LOADING": {},
        "DONE": {}
      },
      "XHR_RESPONSE_TYPE": {
        "DEFAULT": {},
        "BUFFER": {},
        "BLOB": {},
        "DOCUMENT": {},
        "JSON": {},
        "TEXT": {}
      },
      "_loadTypeMap": {
        "gif": {},
        "png": {},
        "bmp": {},
        "jpg": {},
        "jpeg": {},
        "tif": {},
        "tiff": {},
        "webp": {},
        "tga": {}
      },
      "_xhrTypeMap": {
        "xhtml": {},
        "html": {},
        "htm": {},
        "xml": {},
        "tmx": {},
        "tsx": {},
        "svg": {},
        "gif": {},
        "png": {},
        "bmp": {},
        "jpg": {},
        "jpeg": {},
        "tif": {},
        "tiff": {},
        "webp": {},
        "tga": {},
        "json": {},
        "text": {},
        "txt": {},
        "fnt": {}
      },
      "setExtensionLoadType": function () {},
      "setExtensionXhrType": function () {}
    }
  },
  "mesh": {
    "Mesh": {
      "DRAW_MODES": {
        "TRIANGLE_MESH": {},
        "TRIANGLES": {}
      }
    },
    "Plane": function () {},
    "Rope": function () {},
    "MeshRenderer": function () {},
    "MeshShader": function () {}
  },
  "accessibility": {
    "accessibleTarget": {
      "accessible": {},
      "accessibleTitle": {},
      "tabIndex": {},
      "_accessibleActive": {},
      "_accessibleDiv": {}
    },
    "AccessibilityManager": function () {}
  },
  "loader": {},
  "SpriteBatch": function () {},
  "AssetLoader": function () {}
};
PIXI.Point.prototype = {
  "clone": function () {},
  "copy": function () {},
  "equals": function () {},
  "set": function () {}
};
PIXI.Matrix.prototype = {
  "fromArray": function () {},
  "set": function () {},
  "toArray": function () {},
  "apply": function () {},
  "applyInverse": function () {},
  "translate": function () {},
  "scale": function () {},
  "rotate": function () {},
  "append": function () {},
  "setTransform": function () {},
  "prepend": function () {},
  "invert": function () {},
  "identity": function () {},
  "clone": function () {},
  "copy": function () {}
};
PIXI.Circle.prototype = {
  "clone": function () {},
  "contains": function () {},
  "getBounds": function () {}
};
PIXI.Ellipse.prototype = {
  "clone": function () {},
  "contains": function () {},
  "getBounds": function () {}
};
PIXI.Polygon.prototype = {
  "clone": function () {},
  "contains": function () {}
};
PIXI.Rectangle.prototype = {
  "clone": function () {},
  "contains": function () {}
};
PIXI.RoundedRectangle.prototype = {
  "clone": function () {},
  "contains": function () {}
};
PIXI.utils.EventEmitter.prototype = {
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.ticker.Ticker.prototype = {
  "_requestIfNeeded": function () {},
  "_cancelIfNeeded": function () {},
  "_startIfPossible": function () {},
  "add": function () {},
  "addOnce": function () {},
  "remove": function () {},
  "start": function () {},
  "stop": function () {},
  "update": function () {}
};
PIXI.DisplayObject.prototype = {
  "constructor": function () {},
  "updateTransform": function () {},
  "displayObjectUpdateTransform": function () {},
  "getBounds": function () {},
  "getLocalBounds": function () {},
  "toGlobal": function () {},
  "toLocal": function () {},
  "renderWebGL": function () {},
  "renderCanvas": function () {},
  "generateTexture": function () {},
  "setParent": function () {},
  "setTransform": function () {},
  "destroy": function () {},
  "_cacheAsBitmap": function () {},
  "_originalRenderWebGL": function () {},
  "_originalRenderCanvas": function () {},
  "_originalUpdateTransform": function () {},
  "_originalHitTest": function () {},
  "_originalDestroy": function () {},
  "_cachedSprite": function () {},
  "_renderCachedWebGL": function () {},
  "_initCachedDisplayObject": function () {},
  "_renderCachedCanvas": function () {},
  "_initCachedDisplayObjectCanvas": function () {},
  "_getCachedBounds": function () {},
  "_destroyCachedDisplayObject": function () {},
  "_cacheAsBitmapDestroy": function () {},
  "name": function () {},
  "getGlobalPosition": function () {},
  "interactive": function () {},
  "buttonMode": function () {},
  "interactiveChildren": function () {},
  "defaultCursor": function () {},
  "_over": function () {},
  "_touchDown": function () {},
  "accessible": function () {},
  "accessibleTitle": function () {},
  "tabIndex": function () {},
  "_accessibleActive": function () {},
  "_accessibleDiv": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.Container.prototype = {
  "constructor": function () {},
  "onChildrenChange": function () {},
  "addChild": function () {},
  "addChildAt": function () {},
  "swapChildren": function () {},
  "getChildIndex": function () {},
  "setChildIndex": function () {},
  "getChildAt": function () {},
  "removeChild": function () {},
  "removeChildAt": function () {},
  "removeChildren": function () {},
  "generateTexture": function () {},
  "updateTransform": function () {},
  "containerUpdateTransform": function () {},
  "getBounds": function () {},
  "containerGetBounds": function () {},
  "getLocalBounds": function () {},
  "renderWebGL": function () {},
  "_renderWebGL": function () {},
  "_renderCanvas": function () {},
  "renderCanvas": function () {},
  "destroy": function () {},
  "getChildByName": function () {},
  "displayObjectUpdateTransform": function () {},
  "toGlobal": function () {},
  "toLocal": function () {},
  "setParent": function () {},
  "setTransform": function () {},
  "_cacheAsBitmap": function () {},
  "_originalRenderWebGL": function () {},
  "_originalRenderCanvas": function () {},
  "_originalUpdateTransform": function () {},
  "_originalHitTest": function () {},
  "_originalDestroy": function () {},
  "_cachedSprite": function () {},
  "_renderCachedWebGL": function () {},
  "_initCachedDisplayObject": function () {},
  "_renderCachedCanvas": function () {},
  "_initCachedDisplayObjectCanvas": function () {},
  "_getCachedBounds": function () {},
  "_destroyCachedDisplayObject": function () {},
  "_cacheAsBitmapDestroy": function () {},
  "name": function () {},
  "getGlobalPosition": function () {},
  "interactive": function () {},
  "buttonMode": function () {},
  "interactiveChildren": function () {},
  "defaultCursor": function () {},
  "_over": function () {},
  "_touchDown": function () {},
  "accessible": function () {},
  "accessibleTitle": function () {},
  "tabIndex": function () {},
  "_accessibleActive": function () {},
  "_accessibleDiv": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.Sprite.prototype = {
  "constructor": function () {},
  "_onTextureUpdate": function () {},
  "_renderWebGL": function () {},
  "getBounds": function () {},
  "getLocalBounds": function () {},
  "containsPoint": function () {},
  "_renderCanvas": function () {},
  "destroy": function () {},
  "setTexture": function () {},
  "onChildrenChange": function () {},
  "addChild": function () {},
  "addChildAt": function () {},
  "swapChildren": function () {},
  "getChildIndex": function () {},
  "setChildIndex": function () {},
  "getChildAt": function () {},
  "removeChild": function () {},
  "removeChildAt": function () {},
  "removeChildren": function () {},
  "generateTexture": function () {},
  "updateTransform": function () {},
  "containerUpdateTransform": function () {},
  "containerGetBounds": function () {},
  "renderWebGL": function () {},
  "renderCanvas": function () {},
  "getChildByName": function () {},
  "displayObjectUpdateTransform": function () {},
  "toGlobal": function () {},
  "toLocal": function () {},
  "setParent": function () {},
  "setTransform": function () {},
  "_cacheAsBitmap": function () {},
  "_originalRenderWebGL": function () {},
  "_originalRenderCanvas": function () {},
  "_originalUpdateTransform": function () {},
  "_originalHitTest": function () {},
  "_originalDestroy": function () {},
  "_cachedSprite": function () {},
  "_renderCachedWebGL": function () {},
  "_initCachedDisplayObject": function () {},
  "_renderCachedCanvas": function () {},
  "_initCachedDisplayObjectCanvas": function () {},
  "_getCachedBounds": function () {},
  "_destroyCachedDisplayObject": function () {},
  "_cacheAsBitmapDestroy": function () {},
  "name": function () {},
  "getGlobalPosition": function () {},
  "interactive": function () {},
  "buttonMode": function () {},
  "interactiveChildren": function () {},
  "defaultCursor": function () {},
  "_over": function () {},
  "_touchDown": function () {},
  "accessible": function () {},
  "accessibleTitle": function () {},
  "tabIndex": function () {},
  "_accessibleActive": function () {},
  "_accessibleDiv": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.ParticleContainer.prototype = {
  "constructor": function () {},
  "setProperties": function () {},
  "updateTransform": function () {},
  "renderWebGL": function () {},
  "onChildrenChange": function () {},
  "renderCanvas": function () {},
  "destroy": function () {},
  "addChild": function () {},
  "addChildAt": function () {},
  "swapChildren": function () {},
  "getChildIndex": function () {},
  "setChildIndex": function () {},
  "getChildAt": function () {},
  "removeChild": function () {},
  "removeChildAt": function () {},
  "removeChildren": function () {},
  "generateTexture": function () {},
  "containerUpdateTransform": function () {},
  "getBounds": function () {},
  "containerGetBounds": function () {},
  "getLocalBounds": function () {},
  "_renderWebGL": function () {},
  "_renderCanvas": function () {},
  "getChildByName": function () {},
  "displayObjectUpdateTransform": function () {},
  "toGlobal": function () {},
  "toLocal": function () {},
  "setParent": function () {},
  "setTransform": function () {},
  "_cacheAsBitmap": function () {},
  "_originalRenderWebGL": function () {},
  "_originalRenderCanvas": function () {},
  "_originalUpdateTransform": function () {},
  "_originalHitTest": function () {},
  "_originalDestroy": function () {},
  "_cachedSprite": function () {},
  "_renderCachedWebGL": function () {},
  "_initCachedDisplayObject": function () {},
  "_renderCachedCanvas": function () {},
  "_initCachedDisplayObjectCanvas": function () {},
  "_getCachedBounds": function () {},
  "_destroyCachedDisplayObject": function () {},
  "_cacheAsBitmapDestroy": function () {},
  "name": function () {},
  "getGlobalPosition": function () {},
  "interactive": function () {},
  "buttonMode": function () {},
  "interactiveChildren": function () {},
  "defaultCursor": function () {},
  "_over": function () {},
  "_touchDown": function () {},
  "accessible": function () {},
  "accessibleTitle": function () {},
  "tabIndex": function () {},
  "_accessibleActive": function () {},
  "_accessibleDiv": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.SpriteRenderer.prototype = {
  "constructor": function () {},
  "onContextChange": function () {},
  "render": function () {},
  "flush": function () {},
  "renderBatch": function () {},
  "start": function () {},
  "destroy": function () {},
  "stop": function () {}
};
PIXI.ParticleRenderer.prototype = {
  "constructor": function () {},
  "onContextChange": function () {},
  "start": function () {},
  "render": function () {},
  "generateBuffers": function () {},
  "uploadVertices": function () {},
  "uploadPosition": function () {},
  "uploadRotation": function () {},
  "uploadUvs": function () {},
  "uploadAlpha": function () {},
  "destroy": function () {},
  "stop": function () {},
  "flush": function () {}
};
PIXI.Text.prototype = {
  "constructor": function () {},
  "updateText": function () {},
  "updateTexture": function () {},
  "renderWebGL": function () {},
  "_renderCanvas": function () {},
  "determineFontProperties": function () {},
  "wordWrap": function () {},
  "getBounds": function () {},
  "destroy": function () {},
  "setText": function () {},
  "setStyle": function () {},
  "_onTextureUpdate": function () {},
  "_renderWebGL": function () {},
  "getLocalBounds": function () {},
  "containsPoint": function () {},
  "setTexture": function () {},
  "onChildrenChange": function () {},
  "addChild": function () {},
  "addChildAt": function () {},
  "swapChildren": function () {},
  "getChildIndex": function () {},
  "setChildIndex": function () {},
  "getChildAt": function () {},
  "removeChild": function () {},
  "removeChildAt": function () {},
  "removeChildren": function () {},
  "generateTexture": function () {},
  "updateTransform": function () {},
  "containerUpdateTransform": function () {},
  "containerGetBounds": function () {},
  "renderCanvas": function () {},
  "getChildByName": function () {},
  "displayObjectUpdateTransform": function () {},
  "toGlobal": function () {},
  "toLocal": function () {},
  "setParent": function () {},
  "setTransform": function () {},
  "_cacheAsBitmap": function () {},
  "_originalRenderWebGL": function () {},
  "_originalRenderCanvas": function () {},
  "_originalUpdateTransform": function () {},
  "_originalHitTest": function () {},
  "_originalDestroy": function () {},
  "_cachedSprite": function () {},
  "_renderCachedWebGL": function () {},
  "_initCachedDisplayObject": function () {},
  "_renderCachedCanvas": function () {},
  "_initCachedDisplayObjectCanvas": function () {},
  "_getCachedBounds": function () {},
  "_destroyCachedDisplayObject": function () {},
  "_cacheAsBitmapDestroy": function () {},
  "name": function () {},
  "getGlobalPosition": function () {},
  "interactive": function () {},
  "buttonMode": function () {},
  "interactiveChildren": function () {},
  "defaultCursor": function () {},
  "_over": function () {},
  "_touchDown": function () {},
  "accessible": function () {},
  "accessibleTitle": function () {},
  "tabIndex": function () {},
  "_accessibleActive": function () {},
  "_accessibleDiv": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.Graphics.prototype = {
  "constructor": function () {},
  "clone": function () {},
  "lineStyle": function () {},
  "moveTo": function () {},
  "lineTo": function () {},
  "quadraticCurveTo": function () {},
  "bezierCurveTo": function () {},
  "arcTo": function () {},
  "arc": function () {},
  "beginFill": function () {},
  "endFill": function () {},
  "drawRect": function () {},
  "drawRoundedRect": function () {},
  "drawCircle": function () {},
  "drawEllipse": function () {},
  "drawPolygon": function () {},
  "clear": function () {},
  "generateTexture": function () {},
  "_renderWebGL": function () {},
  "_renderCanvas": function () {},
  "getBounds": function () {},
  "containsPoint": function () {},
  "updateLocalBounds": function () {},
  "drawShape": function () {},
  "destroy": function () {},
  "onChildrenChange": function () {},
  "addChild": function () {},
  "addChildAt": function () {},
  "swapChildren": function () {},
  "getChildIndex": function () {},
  "setChildIndex": function () {},
  "getChildAt": function () {},
  "removeChild": function () {},
  "removeChildAt": function () {},
  "removeChildren": function () {},
  "updateTransform": function () {},
  "containerUpdateTransform": function () {},
  "containerGetBounds": function () {},
  "getLocalBounds": function () {},
  "renderWebGL": function () {},
  "renderCanvas": function () {},
  "getChildByName": function () {},
  "displayObjectUpdateTransform": function () {},
  "toGlobal": function () {},
  "toLocal": function () {},
  "setParent": function () {},
  "setTransform": function () {},
  "_cacheAsBitmap": function () {},
  "_originalRenderWebGL": function () {},
  "_originalRenderCanvas": function () {},
  "_originalUpdateTransform": function () {},
  "_originalHitTest": function () {},
  "_originalDestroy": function () {},
  "_cachedSprite": function () {},
  "_renderCachedWebGL": function () {},
  "_initCachedDisplayObject": function () {},
  "_renderCachedCanvas": function () {},
  "_initCachedDisplayObjectCanvas": function () {},
  "_getCachedBounds": function () {},
  "_destroyCachedDisplayObject": function () {},
  "_cacheAsBitmapDestroy": function () {},
  "name": function () {},
  "getGlobalPosition": function () {},
  "interactive": function () {},
  "buttonMode": function () {},
  "interactiveChildren": function () {},
  "defaultCursor": function () {},
  "_over": function () {},
  "_touchDown": function () {},
  "accessible": function () {},
  "accessibleTitle": function () {},
  "tabIndex": function () {},
  "_accessibleActive": function () {},
  "_accessibleDiv": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.GraphicsData.prototype = {
  "clone": function () {},
  "destroy": function () {}
};
PIXI.GraphicsRenderer.prototype = {
  "constructor": function () {},
  "onContextChange": function () {},
  "destroy": function () {},
  "render": function () {},
  "updateGraphics": function () {},
  "switchMode": function () {},
  "buildRectangle": function () {},
  "buildRoundedRectangle": function () {},
  "quadraticBezierCurve": function () {},
  "buildCircle": function () {},
  "buildLine": function () {},
  "buildComplexPoly": function () {},
  "buildPoly": function () {},
  "start": function () {},
  "stop": function () {},
  "flush": function () {}
};
PIXI.Texture.prototype = {
  "constructor": function () {},
  "update": function () {},
  "onBaseTextureLoaded": function () {},
  "onBaseTextureUpdated": function () {},
  "destroy": function () {},
  "clone": function () {},
  "_updateUvs": function () {},
  "setFrame": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.BaseTexture.prototype = {
  "constructor": function () {},
  "update": function () {},
  "loadSource": function () {},
  "_sourceLoaded": function () {},
  "destroy": function () {},
  "dispose": function () {},
  "updateSourceImage": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.RenderTexture.prototype = {
  "constructor": function () {},
  "resize": function () {},
  "clear": function () {},
  "renderWebGL": function () {},
  "renderCanvas": function () {},
  "destroy": function () {},
  "getImage": function () {},
  "getBase64": function () {},
  "getCanvas": function () {},
  "getPixels": function () {},
  "getPixel": function () {},
  "update": function () {},
  "onBaseTextureLoaded": function () {},
  "onBaseTextureUpdated": function () {},
  "clone": function () {},
  "_updateUvs": function () {},
  "setFrame": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.VideoBaseTexture.prototype = {
  "constructor": function () {},
  "_onUpdate": function () {},
  "_onPlayStart": function () {},
  "_onPlayStop": function () {},
  "_onCanPlay": function () {},
  "destroy": function () {},
  "update": function () {},
  "loadSource": function () {},
  "_sourceLoaded": function () {},
  "dispose": function () {},
  "updateSourceImage": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.TextureUvs.prototype = {
  "set": function () {}
};
PIXI.CanvasRenderer.prototype = {
  "constructor": function () {},
  "initPlugins": function () {},
  "destroyPlugins": function () {},
  "render": function () {},
  "destroy": function () {},
  "renderDisplayObject": function () {},
  "resize": function () {},
  "_mapBlendModes": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.CanvasRenderer.__plugins.interaction.prototype = {
  "setTargetElement": function () {},
  "addEvents": function () {},
  "removeEvents": function () {},
  "update": function () {},
  "dispatchEvent": function () {},
  "mapPositionToPoint": function () {},
  "processInteractive": function () {},
  "onMouseDown": function () {},
  "processMouseDown": function () {},
  "onMouseUp": function () {},
  "processMouseUp": function () {},
  "onMouseMove": function () {},
  "processMouseMove": function () {},
  "onMouseOut": function () {},
  "processMouseOverOut": function () {},
  "onTouchStart": function () {},
  "processTouchStart": function () {},
  "onTouchEnd": function () {},
  "processTouchEnd": function () {},
  "onTouchMove": function () {},
  "processTouchMove": function () {},
  "getTouchData": function () {},
  "returnTouchData": function () {},
  "destroy": function () {}
};
PIXI.CanvasRenderer.__plugins.accessibility.prototype = {
  "activate": function () {},
  "deactivate": function () {},
  "updateAccessibleObjects": function () {},
  "update": function () {},
  "capHitArea": function () {},
  "addChild": function () {},
  "_onClick": function () {},
  "_onFocus": function () {},
  "_onFocusOut": function () {},
  "_onKeyDown": function () {},
  "_onMouseMove": function () {},
  "destroy": function () {}
};
PIXI.CanvasBuffer.prototype = {
  "clear": function () {},
  "resize": function () {},
  "destroy": function () {}
};
PIXI.WebGLRenderer.prototype = {
  "constructor": function () {},
  "initPlugins": function () {},
  "destroyPlugins": function () {},
  "_createContext": function () {},
  "_initContext": function () {},
  "render": function () {},
  "renderDisplayObject": function () {},
  "setObjectRenderer": function () {},
  "setRenderTarget": function () {},
  "resize": function () {},
  "updateTexture": function () {},
  "destroyTexture": function () {},
  "handleContextLost": function () {},
  "handleContextRestored": function () {},
  "destroy": function () {},
  "_mapGlModes": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.WebGLRenderer.__plugins.sprite.prototype = {
  "constructor": function () {},
  "onContextChange": function () {},
  "render": function () {},
  "flush": function () {},
  "renderBatch": function () {},
  "start": function () {},
  "destroy": function () {},
  "stop": function () {}
};
PIXI.WebGLRenderer.__plugins.particle.prototype = {
  "constructor": function () {},
  "onContextChange": function () {},
  "start": function () {},
  "render": function () {},
  "generateBuffers": function () {},
  "uploadVertices": function () {},
  "uploadPosition": function () {},
  "uploadRotation": function () {},
  "uploadUvs": function () {},
  "uploadAlpha": function () {},
  "destroy": function () {},
  "stop": function () {},
  "flush": function () {}
};
PIXI.WebGLRenderer.__plugins.graphics.prototype = {
  "constructor": function () {},
  "onContextChange": function () {},
  "destroy": function () {},
  "render": function () {},
  "updateGraphics": function () {},
  "switchMode": function () {},
  "buildRectangle": function () {},
  "buildRoundedRectangle": function () {},
  "quadraticBezierCurve": function () {},
  "buildCircle": function () {},
  "buildLine": function () {},
  "buildComplexPoly": function () {},
  "buildPoly": function () {},
  "start": function () {},
  "stop": function () {},
  "flush": function () {}
};
PIXI.WebGLRenderer.__plugins.interaction.prototype = {
  "setTargetElement": function () {},
  "addEvents": function () {},
  "removeEvents": function () {},
  "update": function () {},
  "dispatchEvent": function () {},
  "mapPositionToPoint": function () {},
  "processInteractive": function () {},
  "onMouseDown": function () {},
  "processMouseDown": function () {},
  "onMouseUp": function () {},
  "processMouseUp": function () {},
  "onMouseMove": function () {},
  "processMouseMove": function () {},
  "onMouseOut": function () {},
  "processMouseOverOut": function () {},
  "onTouchStart": function () {},
  "processTouchStart": function () {},
  "onTouchEnd": function () {},
  "processTouchEnd": function () {},
  "onTouchMove": function () {},
  "processTouchMove": function () {},
  "getTouchData": function () {},
  "returnTouchData": function () {},
  "destroy": function () {}
};
PIXI.WebGLRenderer.__plugins.mesh.prototype = {
  "constructor": function () {},
  "onContextChange": function () {},
  "render": function () {},
  "_initWebGL": function () {},
  "flush": function () {},
  "start": function () {},
  "destroy": function () {},
  "stop": function () {}
};
PIXI.WebGLRenderer.__plugins.accessibility.prototype = {
  "activate": function () {},
  "deactivate": function () {},
  "updateAccessibleObjects": function () {},
  "update": function () {},
  "capHitArea": function () {},
  "addChild": function () {},
  "_onClick": function () {},
  "_onFocus": function () {},
  "_onFocusOut": function () {},
  "_onKeyDown": function () {},
  "_onMouseMove": function () {},
  "destroy": function () {}
};
PIXI.WebGLManager.prototype = {
  "onContextChange": function () {},
  "destroy": function () {}
};
PIXI.ShaderManager.prototype = {
  "constructor": function () {},
  "initPlugins": function () {},
  "destroyPlugins": function () {},
  "onContextChange": function () {},
  "setAttribs": function () {},
  "setShader": function () {},
  "destroy": function () {}
};
PIXI.ShaderManager.__plugins.meshShader.prototype = {
  "constructor": function () {},
  "init": function () {},
  "cacheUniformLocations": function () {},
  "cacheAttributeLocations": function () {},
  "compile": function () {},
  "syncUniform": function () {},
  "syncUniforms": function () {},
  "initSampler2D": function () {},
  "destroy": function () {},
  "_glCompile": function () {}
};
PIXI.Shader.prototype = {
  "init": function () {},
  "cacheUniformLocations": function () {},
  "cacheAttributeLocations": function () {},
  "compile": function () {},
  "syncUniform": function () {},
  "syncUniforms": function () {},
  "initSampler2D": function () {},
  "destroy": function () {},
  "_glCompile": function () {}
};
PIXI.TextureShader.prototype = {
  "constructor": function () {},
  "init": function () {},
  "cacheUniformLocations": function () {},
  "cacheAttributeLocations": function () {},
  "compile": function () {},
  "syncUniform": function () {},
  "syncUniforms": function () {},
  "initSampler2D": function () {},
  "destroy": function () {},
  "_glCompile": function () {}
};
PIXI.PrimitiveShader.prototype = {
  "constructor": function () {},
  "init": function () {},
  "cacheUniformLocations": function () {},
  "cacheAttributeLocations": function () {},
  "compile": function () {},
  "syncUniform": function () {},
  "syncUniforms": function () {},
  "initSampler2D": function () {},
  "destroy": function () {},
  "_glCompile": function () {}
};
PIXI.ComplexPrimitiveShader.prototype = {
  "constructor": function () {},
  "init": function () {},
  "cacheUniformLocations": function () {},
  "cacheAttributeLocations": function () {},
  "compile": function () {},
  "syncUniform": function () {},
  "syncUniforms": function () {},
  "initSampler2D": function () {},
  "destroy": function () {},
  "_glCompile": function () {}
};
PIXI.ObjectRenderer.prototype = {
  "constructor": function () {},
  "start": function () {},
  "stop": function () {},
  "flush": function () {},
  "render": function () {},
  "onContextChange": function () {},
  "destroy": function () {}
};
PIXI.RenderTarget.prototype = {
  "clear": function () {},
  "attachStencilBuffer": function () {},
  "activate": function () {},
  "calculateProjection": function () {},
  "resize": function () {},
  "destroy": function () {}
};
PIXI.AbstractFilter.prototype = {
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.FXAAFilter.prototype = {
  "constructor": function () {},
  "applyFilter": function () {},
  "getShader": function () {},
  "syncUniform": function () {}
};
PIXI.SpriteMaskFilter.prototype = {
  "constructor": function () {},
  "applyFilter": function () {},
  "getShader": function () {},
  "syncUniform": function () {}
};
PIXI.extras.MovieClip.prototype = {
  "constructor": function () {},
  "stop": function () {},
  "play": function () {},
  "gotoAndStop": function () {},
  "gotoAndPlay": function () {},
  "update": function () {},
  "destroy": function () {},
  "_onTextureUpdate": function () {},
  "_renderWebGL": function () {},
  "getBounds": function () {},
  "getLocalBounds": function () {},
  "containsPoint": function () {},
  "_renderCanvas": function () {},
  "setTexture": function () {},
  "onChildrenChange": function () {},
  "addChild": function () {},
  "addChildAt": function () {},
  "swapChildren": function () {},
  "getChildIndex": function () {},
  "setChildIndex": function () {},
  "getChildAt": function () {},
  "removeChild": function () {},
  "removeChildAt": function () {},
  "removeChildren": function () {},
  "generateTexture": function () {},
  "updateTransform": function () {},
  "containerUpdateTransform": function () {},
  "containerGetBounds": function () {},
  "renderWebGL": function () {},
  "renderCanvas": function () {},
  "getChildByName": function () {},
  "displayObjectUpdateTransform": function () {},
  "toGlobal": function () {},
  "toLocal": function () {},
  "setParent": function () {},
  "setTransform": function () {},
  "_cacheAsBitmap": function () {},
  "_originalRenderWebGL": function () {},
  "_originalRenderCanvas": function () {},
  "_originalUpdateTransform": function () {},
  "_originalHitTest": function () {},
  "_originalDestroy": function () {},
  "_cachedSprite": function () {},
  "_renderCachedWebGL": function () {},
  "_initCachedDisplayObject": function () {},
  "_renderCachedCanvas": function () {},
  "_initCachedDisplayObjectCanvas": function () {},
  "_getCachedBounds": function () {},
  "_destroyCachedDisplayObject": function () {},
  "_cacheAsBitmapDestroy": function () {},
  "name": function () {},
  "getGlobalPosition": function () {},
  "interactive": function () {},
  "buttonMode": function () {},
  "interactiveChildren": function () {},
  "defaultCursor": function () {},
  "_over": function () {},
  "_touchDown": function () {},
  "accessible": function () {},
  "accessibleTitle": function () {},
  "tabIndex": function () {},
  "_accessibleActive": function () {},
  "_accessibleDiv": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.extras.TilingSprite.prototype = {
  "constructor": function () {},
  "_onTextureUpdate": function () {},
  "_renderWebGL": function () {},
  "_renderCanvas": function () {},
  "getBounds": function () {},
  "containsPoint": function () {},
  "destroy": function () {},
  "getLocalBounds": function () {},
  "setTexture": function () {},
  "onChildrenChange": function () {},
  "addChild": function () {},
  "addChildAt": function () {},
  "swapChildren": function () {},
  "getChildIndex": function () {},
  "setChildIndex": function () {},
  "getChildAt": function () {},
  "removeChild": function () {},
  "removeChildAt": function () {},
  "removeChildren": function () {},
  "generateTexture": function () {},
  "updateTransform": function () {},
  "containerUpdateTransform": function () {},
  "containerGetBounds": function () {},
  "renderWebGL": function () {},
  "renderCanvas": function () {},
  "getChildByName": function () {},
  "displayObjectUpdateTransform": function () {},
  "toGlobal": function () {},
  "toLocal": function () {},
  "setParent": function () {},
  "setTransform": function () {},
  "_cacheAsBitmap": function () {},
  "_originalRenderWebGL": function () {},
  "_originalRenderCanvas": function () {},
  "_originalUpdateTransform": function () {},
  "_originalHitTest": function () {},
  "_originalDestroy": function () {},
  "_cachedSprite": function () {},
  "_renderCachedWebGL": function () {},
  "_initCachedDisplayObject": function () {},
  "_renderCachedCanvas": function () {},
  "_initCachedDisplayObjectCanvas": function () {},
  "_getCachedBounds": function () {},
  "_destroyCachedDisplayObject": function () {},
  "_cacheAsBitmapDestroy": function () {},
  "name": function () {},
  "getGlobalPosition": function () {},
  "interactive": function () {},
  "buttonMode": function () {},
  "interactiveChildren": function () {},
  "defaultCursor": function () {},
  "_over": function () {},
  "_touchDown": function () {},
  "accessible": function () {},
  "accessibleTitle": function () {},
  "tabIndex": function () {},
  "_accessibleActive": function () {},
  "_accessibleDiv": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.extras.BitmapText.prototype = {
  "constructor": function () {},
  "updateText": function () {},
  "updateTransform": function () {},
  "getLocalBounds": function () {},
  "validate": function () {},
  "setText": function () {},
  "onChildrenChange": function () {},
  "addChild": function () {},
  "addChildAt": function () {},
  "swapChildren": function () {},
  "getChildIndex": function () {},
  "setChildIndex": function () {},
  "getChildAt": function () {},
  "removeChild": function () {},
  "removeChildAt": function () {},
  "removeChildren": function () {},
  "generateTexture": function () {},
  "containerUpdateTransform": function () {},
  "getBounds": function () {},
  "containerGetBounds": function () {},
  "renderWebGL": function () {},
  "_renderWebGL": function () {},
  "_renderCanvas": function () {},
  "renderCanvas": function () {},
  "destroy": function () {},
  "getChildByName": function () {},
  "displayObjectUpdateTransform": function () {},
  "toGlobal": function () {},
  "toLocal": function () {},
  "setParent": function () {},
  "setTransform": function () {},
  "_cacheAsBitmap": function () {},
  "_originalRenderWebGL": function () {},
  "_originalRenderCanvas": function () {},
  "_originalUpdateTransform": function () {},
  "_originalHitTest": function () {},
  "_originalDestroy": function () {},
  "_cachedSprite": function () {},
  "_renderCachedWebGL": function () {},
  "_initCachedDisplayObject": function () {},
  "_renderCachedCanvas": function () {},
  "_initCachedDisplayObjectCanvas": function () {},
  "_getCachedBounds": function () {},
  "_destroyCachedDisplayObject": function () {},
  "_cacheAsBitmapDestroy": function () {},
  "name": function () {},
  "getGlobalPosition": function () {},
  "interactive": function () {},
  "buttonMode": function () {},
  "interactiveChildren": function () {},
  "defaultCursor": function () {},
  "_over": function () {},
  "_touchDown": function () {},
  "accessible": function () {},
  "accessibleTitle": function () {},
  "tabIndex": function () {},
  "_accessibleActive": function () {},
  "_accessibleDiv": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.filters.AsciiFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.BloomFilter.prototype = {
  "constructor": function () {},
  "applyFilter": function () {},
  "getShader": function () {},
  "syncUniform": function () {}
};
PIXI.filters.BlurFilter.prototype = {
  "constructor": function () {},
  "applyFilter": function () {},
  "getShader": function () {},
  "syncUniform": function () {}
};
PIXI.filters.BlurXFilter.prototype = {
  "constructor": function () {},
  "applyFilter": function () {},
  "getShader": function () {},
  "syncUniform": function () {}
};
PIXI.filters.BlurYFilter.prototype = {
  "constructor": function () {},
  "applyFilter": function () {},
  "getShader": function () {},
  "syncUniform": function () {}
};
PIXI.filters.BlurDirFilter.prototype = {
  "constructor": function () {},
  "applyFilter": function () {},
  "getShader": function () {},
  "syncUniform": function () {}
};
PIXI.filters.ColorMatrixFilter.prototype = {
  "constructor": function () {},
  "_loadMatrix": function () {},
  "_multiply": function () {},
  "_colorMatrix": function () {},
  "brightness": function () {},
  "greyscale": function () {},
  "grayscale": function () {},
  "blackAndWhite": function () {},
  "hue": function () {},
  "contrast": function () {},
  "saturate": function () {},
  "desaturate": function () {},
  "negative": function () {},
  "sepia": function () {},
  "technicolor": function () {},
  "polaroid": function () {},
  "toBGR": function () {},
  "kodachrome": function () {},
  "browni": function () {},
  "vintage": function () {},
  "colorTone": function () {},
  "night": function () {},
  "predator": function () {},
  "lsd": function () {},
  "reset": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.ColorStepFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.ConvolutionFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.CrossHatchFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.DisplacementFilter.prototype = {
  "constructor": function () {},
  "applyFilter": function () {},
  "getShader": function () {},
  "syncUniform": function () {}
};
PIXI.filters.DotScreenFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.GrayFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.DropShadowFilter.prototype = {
  "constructor": function () {},
  "applyFilter": function () {},
  "getShader": function () {},
  "syncUniform": function () {}
};
PIXI.filters.InvertFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.NoiseFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.PixelateFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.RGBSplitFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.ShockwaveFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.SepiaFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.SmartBlurFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.TiltShiftFilter.prototype = {
  "constructor": function () {},
  "applyFilter": function () {},
  "getShader": function () {},
  "syncUniform": function () {}
};
PIXI.filters.TiltShiftXFilter.prototype = {
  "constructor": function () {},
  "updateDelta": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.TiltShiftYFilter.prototype = {
  "constructor": function () {},
  "updateDelta": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.filters.TwistFilter.prototype = {
  "constructor": function () {},
  "getShader": function () {},
  "applyFilter": function () {},
  "syncUniform": function () {}
};
PIXI.interaction.InteractionData.prototype = {
  "getLocalPosition": function () {}
};
PIXI.interaction.InteractionManager.prototype = {
  "setTargetElement": function () {},
  "addEvents": function () {},
  "removeEvents": function () {},
  "update": function () {},
  "dispatchEvent": function () {},
  "mapPositionToPoint": function () {},
  "processInteractive": function () {},
  "onMouseDown": function () {},
  "processMouseDown": function () {},
  "onMouseUp": function () {},
  "processMouseUp": function () {},
  "onMouseMove": function () {},
  "processMouseMove": function () {},
  "onMouseOut": function () {},
  "processMouseOverOut": function () {},
  "onTouchStart": function () {},
  "processTouchStart": function () {},
  "onTouchEnd": function () {},
  "processTouchEnd": function () {},
  "onTouchMove": function () {},
  "processTouchMove": function () {},
  "getTouchData": function () {},
  "returnTouchData": function () {},
  "destroy": function () {}
};
PIXI.loaders.Loader.prototype = {
  "constructor": function () {},
  "enqueue": function () {},
  "add": function () {},
  "_handleBaseUrl": function () {},
  "pre": function () {},
  "before": function () {},
  "use": function () {},
  "after": function () {},
  "reset": function () {},
  "load": function () {},
  "_loadResource": function () {},
  "_onComplete": function () {},
  "_onLoad": function () {},
  "_runMiddleware": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.loaders.Resource.prototype = {
  "constructor": function () {},
  "complete": function () {},
  "load": function () {},
  "_loadImage": function () {},
  "_loadElement": function () {},
  "_loadXhr": function () {},
  "_loadXdr": function () {},
  "_createSource": function () {},
  "_onError": function () {},
  "_onProgress": function () {},
  "_xhrOnError": function () {},
  "_xhrOnAbort": function () {},
  "_xdrOnTimeout": function () {},
  "_xhrOnLoad": function () {},
  "_determineCrossOrigin": function () {},
  "_determineXhrType": function () {},
  "_determineLoadType": function () {},
  "_getExtension": function () {},
  "_getMimeFromXhrType": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.mesh.Mesh.prototype = {
  "constructor": function () {},
  "_renderWebGL": function () {},
  "_renderCanvas": function () {},
  "_renderCanvasTriangleMesh": function () {},
  "_renderCanvasTriangles": function () {},
  "_renderCanvasDrawTriangle": function () {},
  "renderMeshFlat": function () {},
  "_onTextureUpdate": function () {},
  "getBounds": function () {},
  "containsPoint": function () {},
  "onChildrenChange": function () {},
  "addChild": function () {},
  "addChildAt": function () {},
  "swapChildren": function () {},
  "getChildIndex": function () {},
  "setChildIndex": function () {},
  "getChildAt": function () {},
  "removeChild": function () {},
  "removeChildAt": function () {},
  "removeChildren": function () {},
  "generateTexture": function () {},
  "updateTransform": function () {},
  "containerUpdateTransform": function () {},
  "containerGetBounds": function () {},
  "getLocalBounds": function () {},
  "renderWebGL": function () {},
  "renderCanvas": function () {},
  "destroy": function () {},
  "getChildByName": function () {},
  "displayObjectUpdateTransform": function () {},
  "toGlobal": function () {},
  "toLocal": function () {},
  "setParent": function () {},
  "setTransform": function () {},
  "_cacheAsBitmap": function () {},
  "_originalRenderWebGL": function () {},
  "_originalRenderCanvas": function () {},
  "_originalUpdateTransform": function () {},
  "_originalHitTest": function () {},
  "_originalDestroy": function () {},
  "_cachedSprite": function () {},
  "_renderCachedWebGL": function () {},
  "_initCachedDisplayObject": function () {},
  "_renderCachedCanvas": function () {},
  "_initCachedDisplayObjectCanvas": function () {},
  "_getCachedBounds": function () {},
  "_destroyCachedDisplayObject": function () {},
  "_cacheAsBitmapDestroy": function () {},
  "name": function () {},
  "getGlobalPosition": function () {},
  "interactive": function () {},
  "buttonMode": function () {},
  "interactiveChildren": function () {},
  "defaultCursor": function () {},
  "_over": function () {},
  "_touchDown": function () {},
  "accessible": function () {},
  "accessibleTitle": function () {},
  "tabIndex": function () {},
  "_accessibleActive": function () {},
  "_accessibleDiv": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.mesh.Plane.prototype = {
  "constructor": function () {},
  "refresh": function () {},
  "_onTextureUpdate": function () {},
  "_renderWebGL": function () {},
  "_renderCanvas": function () {},
  "_renderCanvasTriangleMesh": function () {},
  "_renderCanvasTriangles": function () {},
  "_renderCanvasDrawTriangle": function () {},
  "renderMeshFlat": function () {},
  "getBounds": function () {},
  "containsPoint": function () {},
  "onChildrenChange": function () {},
  "addChild": function () {},
  "addChildAt": function () {},
  "swapChildren": function () {},
  "getChildIndex": function () {},
  "setChildIndex": function () {},
  "getChildAt": function () {},
  "removeChild": function () {},
  "removeChildAt": function () {},
  "removeChildren": function () {},
  "generateTexture": function () {},
  "updateTransform": function () {},
  "containerUpdateTransform": function () {},
  "containerGetBounds": function () {},
  "getLocalBounds": function () {},
  "renderWebGL": function () {},
  "renderCanvas": function () {},
  "destroy": function () {},
  "getChildByName": function () {},
  "displayObjectUpdateTransform": function () {},
  "toGlobal": function () {},
  "toLocal": function () {},
  "setParent": function () {},
  "setTransform": function () {},
  "_cacheAsBitmap": function () {},
  "_originalRenderWebGL": function () {},
  "_originalRenderCanvas": function () {},
  "_originalUpdateTransform": function () {},
  "_originalHitTest": function () {},
  "_originalDestroy": function () {},
  "_cachedSprite": function () {},
  "_renderCachedWebGL": function () {},
  "_initCachedDisplayObject": function () {},
  "_renderCachedCanvas": function () {},
  "_initCachedDisplayObjectCanvas": function () {},
  "_getCachedBounds": function () {},
  "_destroyCachedDisplayObject": function () {},
  "_cacheAsBitmapDestroy": function () {},
  "name": function () {},
  "getGlobalPosition": function () {},
  "interactive": function () {},
  "buttonMode": function () {},
  "interactiveChildren": function () {},
  "defaultCursor": function () {},
  "_over": function () {},
  "_touchDown": function () {},
  "accessible": function () {},
  "accessibleTitle": function () {},
  "tabIndex": function () {},
  "_accessibleActive": function () {},
  "_accessibleDiv": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.mesh.Rope.prototype = {
  "constructor": function () {},
  "refresh": function () {},
  "_onTextureUpdate": function () {},
  "updateTransform": function () {},
  "_renderWebGL": function () {},
  "_renderCanvas": function () {},
  "_renderCanvasTriangleMesh": function () {},
  "_renderCanvasTriangles": function () {},
  "_renderCanvasDrawTriangle": function () {},
  "renderMeshFlat": function () {},
  "getBounds": function () {},
  "containsPoint": function () {},
  "onChildrenChange": function () {},
  "addChild": function () {},
  "addChildAt": function () {},
  "swapChildren": function () {},
  "getChildIndex": function () {},
  "setChildIndex": function () {},
  "getChildAt": function () {},
  "removeChild": function () {},
  "removeChildAt": function () {},
  "removeChildren": function () {},
  "generateTexture": function () {},
  "containerUpdateTransform": function () {},
  "containerGetBounds": function () {},
  "getLocalBounds": function () {},
  "renderWebGL": function () {},
  "renderCanvas": function () {},
  "destroy": function () {},
  "getChildByName": function () {},
  "displayObjectUpdateTransform": function () {},
  "toGlobal": function () {},
  "toLocal": function () {},
  "setParent": function () {},
  "setTransform": function () {},
  "_cacheAsBitmap": function () {},
  "_originalRenderWebGL": function () {},
  "_originalRenderCanvas": function () {},
  "_originalUpdateTransform": function () {},
  "_originalHitTest": function () {},
  "_originalDestroy": function () {},
  "_cachedSprite": function () {},
  "_renderCachedWebGL": function () {},
  "_initCachedDisplayObject": function () {},
  "_renderCachedCanvas": function () {},
  "_initCachedDisplayObjectCanvas": function () {},
  "_getCachedBounds": function () {},
  "_destroyCachedDisplayObject": function () {},
  "_cacheAsBitmapDestroy": function () {},
  "name": function () {},
  "getGlobalPosition": function () {},
  "interactive": function () {},
  "buttonMode": function () {},
  "interactiveChildren": function () {},
  "defaultCursor": function () {},
  "_over": function () {},
  "_touchDown": function () {},
  "accessible": function () {},
  "accessibleTitle": function () {},
  "tabIndex": function () {},
  "_accessibleActive": function () {},
  "_accessibleDiv": function () {},
  "_events": function () {},
  "listeners": function () {},
  "emit": function () {},
  "on": function () {},
  "once": function () {},
  "removeListener": function () {},
  "removeAllListeners": function () {},
  "off": function () {},
  "addListener": function () {},
  "setMaxListeners": function () {}
};
PIXI.mesh.MeshRenderer.prototype = {
  "constructor": function () {},
  "onContextChange": function () {},
  "render": function () {},
  "_initWebGL": function () {},
  "flush": function () {},
  "start": function () {},
  "destroy": function () {},
  "stop": function () {}
};
PIXI.mesh.MeshShader.prototype = {
  "constructor": function () {},
  "init": function () {},
  "cacheUniformLocations": function () {},
  "cacheAttributeLocations": function () {},
  "compile": function () {},
  "syncUniform": function () {},
  "syncUniforms": function () {},
  "initSampler2D": function () {},
  "destroy": function () {},
  "_glCompile": function () {}
};
PIXI.accessibility.AccessibilityManager.prototype = {
  "activate": function () {},
  "deactivate": function () {},
  "updateAccessibleObjects": function () {},
  "update": function () {},
  "capHitArea": function () {},
  "addChild": function () {},
  "_onClick": function () {},
  "_onFocus": function () {},
  "_onFocusOut": function () {},
  "_onKeyDown": function () {},
  "_onMouseMove": function () {},
  "destroy": function () {}
};
