var PIXI = {
    "VERSION": {},
    "PI_2": {},
    "RAD_TO_DEG": {},
    "DEG_TO_RAD": {},
    "TARGET_FPMS": {},
    "RENDERER_TYPE": {
        "UNKNOWN": {},
        "WEBGL": {},
        "CANVAS": {}
    },
    "BLEND_MODES": {
        "NORMAL": {},
        "ADD": {},
        "MULTIPLY": {},
        "SCREEN": {},
        "OVERLAY": {},
        "DARKEN": {},
        "LIGHTEN": {},
        "COLOR_DODGE": {},
        "COLOR_BURN": {},
        "HARD_LIGHT": {},
        "SOFT_LIGHT": {},
        "DIFFERENCE": {},
        "EXCLUSION": {},
        "HUE": {},
        "SATURATION": {},
        "COLOR": {},
        "LUMINOSITY": {}
    },
    "DRAW_MODES": {
        "POINTS": {},
        "LINES": {},
        "LINE_LOOP": {},
        "LINE_STRIP": {},
        "TRIANGLES": {},
        "TRIANGLE_STRIP": {},
        "TRIANGLE_FAN": {}
    },
    "SCALE_MODES": {
        "DEFAULT": {},
        "LINEAR": {},
        "NEAREST": {}
    },
    "WRAP_MODES": {
        "DEFAULT": {},
        "CLAMP": {},
        "REPEAT": {},
        "MIRRORED_REPEAT": {}
    },
    "GC_MODES": {
        "DEFAULT": {},
        "AUTO": {},
        "MANUAL": {}
    },
    "MIPMAP_TEXTURES": {},
    "RETINA_PREFIX": function () {},
    "RESOLUTION": {},
    "FILTER_RESOLUTION": {},
    "DEFAULT_RENDER_OPTIONS": {
        "view": function () {},
        "resolution": {},
        "antialias": {},
        "forceFXAA": {},
        "autoResize": {},
        "transparent": {},
        "backgroundColor": {},
        "clearBeforeRender": {},
        "preserveDrawingBuffer": {},
        "roundPixels": {}
    },
    "SHAPES": {
        "POLY": {},
        "RECT": {},
        "CIRC": {},
        "ELIP": {},
        "RREC": {}
    },
    "PRECISION": {
        "DEFAULT": {},
        "LOW": {},
        "MEDIUM": {},
        "HIGH": {}
    },
    "TRANSFORM_MODE": {
        "DEFAULT": {},
        "STATIC": {},
        "DYNAMIC": {}
    },
    "TEXT_GRADIENT": {
        "LINEAR_VERTICAL": {},
        "LINEAR_HORIZONTAL": {}
    },
    "SPRITE_BATCH_SIZE": {},
    "SPRITE_MAX_TEXTURES": {},
    "Point": function () {},
    "ObservablePoint": function () {},
    "Matrix": function () {},
    "GroupD8": {
        "E": {},
        "SE": {},
        "S": {},
        "SW": {},
        "W": {},
        "NW": {},
        "N": {},
        "NE": {},
        "MIRROR_VERTICAL": {},
        "MIRROR_HORIZONTAL": {},
        "uX": function () {},
        "uY": function () {},
        "vX": function () {},
        "vY": function () {},
        "inv": function () {},
        "add": function () {},
        "sub": function () {},
        "rotate180": function () {},
        "isSwapWidthHeight": function () {},
        "byDirection": function () {},
        "matrixAppendRotationInv": function () {}
    },
    "Circle": function () {},
    "Ellipse": function () {},
    "Polygon": function () {},
    "Rectangle": function () {},
    "RoundedRectangle": function () {},
    "utils": {
        "_uid": {},
        "_saidHello": {},
        "EventEmitter": function () {},
        "pluginTarget": {
            "mixin": function () {}
        },
        "uid": function () {},
        "hex2rgb": function () {},
        "hex2string": function () {},
        "rgb2hex": function () {},
        "getResolutionOfUrl": function () {},
        "sayHello": function () {},
        "isWebGLSupported": function () {},
        "sign": function () {},
        "removeItems": function () {},
        "TextureCache": function () {},
        "BaseTextureCache": function () {},
        "uuid": function () {},
        "canUseNewCanvasBlendModes": function () {}
    },
    "ticker": {
        "shared": {
            "_tick": function () {},
            "_emitter": {
                "_events": {},
                "eventNames": function () {},
                "listeners": function () {},
                "emit": function () {},
                "on": function () {},
                "once": function () {},
                "removeListener": function () {},
                "removeAllListeners": function () {},
                "off": function () {},
                "addListener": function () {},
                "setMaxListeners": function () {}
            },
            "_requestId": function () {},
            "_maxElapsedMS": {},
            "autoStart": {},
            "deltaTime": {},
            "elapsedMS": {},
            "lastTime": {},
            "speed": {},
            "started": {},
            "_requestIfNeeded": function () {},
            "_cancelIfNeeded": function () {},
            "_startIfPossible": function () {},
            "add": function () {},
            "addOnce": function () {},
            "remove": function () {},
            "start": function () {},
            "stop": function () {},
            "update": function () {}
        },
        "Ticker": function () {}
    },
    "DisplayObject": function () {},
    "Container": function () {},
    "Transform": function () {},
    "TransformStatic": function () {},
    "TransformBase": function () {},
    "Sprite": function () {},
    "CanvasSpriteRenderer": function () {},
    "CanvasTinter": {
        "getTintedTexture": function () {},
        "tintWithMultiply": function () {},
        "tintWithOverlay": function () {},
        "tintWithPerPixel": function () {},
        "roundColor": function () {},
        "cacheStepsPerColorChannel": {},
        "convertTintToImage": {},
        "canUseMultiply": {},
        "tintMethod": function () {}
    },
    "SpriteRenderer": function () {},
    "Text": function () {},
    "TextStyle": function () {},
    "Graphics": function () {},
    "GraphicsData": function () {},
    "GraphicsRenderer": function () {},
    "CanvasGraphicsRenderer": function () {},
    "Texture": function () {},
    "BaseTexture": function () {},
    "RenderTexture": function () {},
    "BaseRenderTexture": function () {},
    "VideoBaseTexture": function () {},
    "TextureUvs": function () {},
    "CanvasRenderer": function () {},
    "CanvasRenderTarget": function () {},
    "Shader": function () {},
    "WebGLRenderer": function () {},
    "WebGLManager": function () {},
    "ObjectRenderer": function () {},
    "RenderTarget": function () {},
    "Quad": function () {},
    "SpriteMaskFilter": function () {},
    "Filter": function () {},
    "glCore": {
        "createContext": function () {},
        "setVertexAttribArrays": function () {},
        "GLBuffer": function () {},
        "GLFramebuffer": function () {},
        "GLShader": function () {},
        "GLTexture": function () {},
        "VertexArrayObject": function () {},
        "shader": {
            "compileProgram": function () {},
            "defaultValue": function () {},
            "extractAttributes": function () {},
            "extractUniforms": function () {},
            "generateUniformAccessObject": function () {},
            "mapSize": function () {},
            "mapType": function () {}
        }
    },
    "autoDetectRenderer": function () {},
    "extras": {
        "MovieClip": function () {},
        "TilingSprite": function () {},
        "BitmapText": function () {}
    },
    "filters": {
        "FXAAFilter": function () {},
        "NoiseFilter": function () {},
        "DisplacementFilter": function () {},
        "BlurFilter": function () {},
        "BlurXFilter": function () {},
        "BlurYFilter": function () {},
        "ColorMatrixFilter": function () {},
        "VoidFilter": function () {}
    },
    "interaction": {
        "InteractionData": function () {},
        "InteractionManager": function () {},
        "interactiveTarget": {
            "interactive": {},
            "interactiveChildren": {},
            "hitArea": function () {},
            "buttonMode": {},
            "defaultCursor": {},
            "_over": {},
            "_isLeftDown": {},
            "_isRightDown": {},
            "_touchDown": {}
        }
    },
    "loaders": {
        "Loader": function () {},
        "bitmapFontParser": function () {},
        "spritesheetParser": function () {},
        "textureParser": function () {},
        "Resource": function () {}
    },
    "mesh": {
        "Mesh": function () {},
        "Plane": function () {},
        "NineSlicePlane": function () {},
        "Rope": function () {},
        "MeshShader": function () {}
    },
    "particles": {
        "ParticleContainer": function () {},
        "ParticleRenderer": function () {}
    },
    "accessibility": {
        "accessibleTarget": {
            "accessible": {},
            "accessibleTitle": function () {},
            "accessibleHint": function () {},
            "tabIndex": {},
            "_accessibleActive": {},
            "_accessibleDiv": {}
        },
        "AccessibilityManager": function () {}
    },
    "extract": {
        "webGL": function () {},
        "canvas": function () {}
    },
    "prepare": {
        "webGL": function () {},
        "canvas": function () {}
    },
    "loader": {
        "_events": function () {},
        "_eventsCount": {},
        "baseUrl": {},
        "progress": {},
        "loading": {},
        "_progressChunk": {},
        "_beforeMiddleware": function () {},
        "_afterMiddleware": {
            "0": function () {},
            "1": function () {},
            "2": function () {},
            "3": function () {}
        },
        "_boundLoadResource": function () {},
        "_buffer": function () {},
        "_numToLoad": {},
        "_queue": {
            "_tasks": function () {},
            "concurrency": {},
            "saturated": function () {},
            "unsaturated": function () {},
            "buffer": {},
            "empty": function () {},
            "drain": function () {},
            "error": function () {},
            "started": {},
            "paused": {},
            "push": function () {},
            "kill": function () {},
            "unshift": function () {},
            "process": function () {},
            "length": function () {},
            "running": function () {},
            "idle": function () {},
            "pause": function () {},
            "resume": function () {}
        },
        "resources": function () {},
        "constructor": function () {},
        "enqueue": function () {},
        "add": function () {},
        "pre": function () {},
        "before": function () {},
        "use": function () {},
        "after": function () {},
        "reset": function () {},
        "load": function () {},
        "_prepareUrl": function () {},
        "_loadResource": function () {},
        "_onComplete": function () {},
        "_onLoad": function () {},
        "eventNames": function () {},
        "listeners": function () {},
        "emit": function () {},
        "on": function () {},
        "once": function () {},
        "removeListener": function () {},
        "removeAllListeners": function () {},
        "off": function () {},
        "addListener": function () {},
        "setMaxListeners": function () {}
    },
    "SpriteBatch": function () {},
    "AssetLoader": function () {}
}

