{:foreign-libs [{:provides ["cljsjs.snabbdom"]
                 :file "cljsjs/snabbdom/development/snabbdom.inc.js"
                 :file-min "cljsjs/snabbdom/production/snabbdom.min.inc.js"}
                {:provides ["cljsjs.snabbdom.attributes"]
                 :file "cljsjs/snabbdom/development/snabbdom-attributes.inc.js"
                 :file-min "cljsjs/snabbdom/development/snabbdom-attributes.min.inc.js"}
                {:provides ["cljsjs.snabbdom.class"]
                 :file "cljsjs/snabbdom/development/snabbdom-class.inc.js"
                 :file-min "cljsjs/snabbdom/development/snabbdom-class.min.inc.js"}
                {:provides ["cljsjs.snabbdom.eventlisteners"]
                 :file "cljsjs/snabbdom/development/snabbdom-eventlisteners.inc.js"
                 :file-min "cljsjs/snabbdom/development/snabbdom-eventlisteners.min.inc.js"}
                {:provides ["cljsjs.snabbdom.props"]
                 :file "cljsjs/snabbdom/development/snabbdom-props.inc.js"
                 :file-min "cljsjs/snabbdom/development/snabbdom-props.min.inc.js"}
                {:provides ["cljsjs.snabbdom.style"]
                 :file "cljsjs/snabbdom/development/snabbdom-style.inc.js"
                 :file-min "cljsjs/snabbdom/development/snabbdom-style.min.inc.js"}]
 :externs ["cljsjs/snabbdom/common/snabbdom.ext.js"]}
