// Generated via http://jmmk.github.io/javascript-externs-generator/
// Loaded JavaScripts:
// https://rawgit.com/NextStepWebs/simplemde-markdown-editor/master/dist/simplemde.min.js
// extern the 'SimpleMDE' object

var SimpleMDE = {
  "toggleBold": function () {},
  "toggleItalic": function () {},
  "toggleStrikethrough": function () {},
  "toggleBlockquote": function () {},
  "toggleHeadingSmaller": function () {},
  "toggleHeadingBigger": function () {},
  "toggleHeading1": function () {},
  "toggleHeading2": function () {},
  "toggleHeading3": function () {},
  "toggleCodeBlock": function () {},
  "toggleUnorderedList": function () {},
  "toggleOrderedList": function () {},
  "cleanBlock": function () {},
  "drawLink": function () {},
  "drawImage": function () {},
  "drawTable": function () {},
  "drawHorizontalRule": function () {},
  "undo": function () {},
  "redo": function () {},
  "togglePreview": function () {},
  "toggleSideBySide": function () {},
  "toggleFullScreen": function () {}
};
SimpleMDE.prototype = {
  "markdown": function () {},
  "render": function () {},
  "autosave": function () {},
  "clearAutosavedValue": function () {},
  "createSideBySide": function () {},
  "createToolbar": function () {},
  "createStatusbar": function () {},
  "value": function () {},
  "toggleBold": function () {},
  "toggleItalic": function () {},
  "toggleStrikethrough": function () {},
  "toggleBlockquote": function () {},
  "toggleHeadingSmaller": function () {},
  "toggleHeadingBigger": function () {},
  "toggleHeading1": function () {},
  "toggleHeading2": function () {},
  "toggleHeading3": function () {},
  "toggleCodeBlock": function () {},
  "toggleUnorderedList": function () {},
  "toggleOrderedList": function () {},
  "cleanBlock": function () {},
  "drawLink": function () {},
  "drawImage": function () {},
  "drawTable": function () {},
  "drawHorizontalRule": function () {},
  "undo": function () {},
  "redo": function () {},
  "togglePreview": function () {},
  "toggleSideBySide": function () {},
  "toggleFullScreen": function () {},
  "isPreviewActive": function () {},
  "isSideBySideActive": function () {},
  "isFullscreenActive": function () {},
  "getState": function () {},
  "toTextArea": function () {}
};