/**********************************************************************
 * Extern for Inferno
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Inferno = {
    Component: function() {},
    EMPTY_OBJ: {},
    JSX: {},
    NO_OP: {},
    createClass: function() {},
    createComponentVNode: function() {},
    createElement: function() {},
    createPortal: function() {},
    createRenderer: function() {},
    createTextVNode: function() {},
    createVNode: function() {},
    directClone: function() {},
    getFlagsForElementVnode: function() {},
    getNumberStyleValue: function() {},
    h: function() {},
    hydrate: function() {},
    linkEvent: function() {},
    normalizeProps: function() {},
    options: {
        afterRender: {},
        beforeRender: {},
        createVNode: {},
        renderComplete: {},
    },
    render: function() {},
    version: {},
};
Inferno.Component.prototype = {
    forceUpdate: function() {},
    render: function() {},
    setState: function() {},
};
/**********************************************************************
 * End Generated Extern for Inferno
 **********************************************************************/
