var FlipMove = {
  "displayName": {},
  "propTypes": {
    "children": {},
    "easing": {},
    "duration": {},
    "delay": {},
    "staggerDurationBy": {},
    "staggerDelayBy": {},
    "onStart": {},
    "onFinish": {},
    "onStartAll": {},
    "onFinishAll": {},
    "typeName": {},
    "enterAnimation": {},
    "leaveAnimation": {},
    "disableAllAnimations": {},
    "getPosition": {},
    "maintainContainerHeight": {},
  },
  "getDefaultProps": function () {},
  "defaultProps": {
    "easing": {},
    "duration": {},
    "delay": {},
    "staggerDurationBy": {},
    "staggerDelayBy": {},
    "typeName": {},
    "enterAnimation": {},
    "leaveAnimation": {},
    "disableAllAnimations": {},
    "getPosition": {},
    "maintainContainerHeight": {}
  }    
}
