/**********************************************************************
 * Extern for hljs
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var hljs = {
    "APOS_STRING_MODE": {
        "begin": {},
        "contains": {},
        "end": {},
        "illegal": {},
        "scope": {}
    },
    "BACKSLASH_ESCAPE": {
        "begin": {},
        "relevance": {}
    },
    "BINARY_NUMBER_MODE": {
        "begin": {},
        "relevance": {},
        "scope": {}
    },
    "BINARY_NUMBER_RE": {},
    "COMMENT": function () { },
    "C_BLOCK_COMMENT_MODE": {
        "begin": {},
        "contains": {},
        "end": {},
        "scope": {}
    },
    "C_LINE_COMMENT_MODE": {
        "begin": {},
        "contains": {},
        "end": {},
        "scope": {}
    },
    "C_NUMBER_MODE": {
        "begin": {},
        "relevance": {},
        "scope": {}
    },
    "C_NUMBER_RE": {},
    "END_SAME_AS_BEGIN": function () { },
    "HASH_COMMENT_MODE": {
        "begin": {},
        "contains": {},
        "end": {},
        "scope": {}
    },
    "IDENT_RE": {},
    "MATCH_NOTHING_RE": {},
    "METHOD_GUARD": {
        "begin": {},
        "relevance": {}
    },
    "NUMBER_MODE": {
        "begin": {},
        "relevance": {},
        "scope": {}
    },
    "NUMBER_RE": {},
    "PHRASAL_WORDS_MODE": {
        "begin": {}
    },
    "QUOTE_STRING_MODE": {
        "begin": {},
        "contains": {},
        "end": {},
        "illegal": {},
        "scope": {}
    },
    "REGEXP_MODE": {
        "begin": {},
        "contains": {}
    },
    "RE_STARTERS_RE": {},
    "SHEBANG": function () { },
    "TITLE_MODE": {
        "begin": {},
        "relevance": {},
        "scope": {}
    },
    "UNDERSCORE_IDENT_RE": {},
    "UNDERSCORE_TITLE_MODE": {
        "begin": {},
        "relevance": {},
        "scope": {}
    },
    "addPlugin": function () { },
    "autoDetection": function () { },
    "configure": function () { },
    "debugMode": function () { },
    "getLanguage": function () { },
    "highlight": function () { },
    "highlightAll": function () { },
    "highlightAuto": function () { },
    "highlightBlock": function () { },
    "highlightElement": function () { },
    "inherit": function () { },
    "initHighlighting": function () { },
    "initHighlightingOnLoad": function () { },
    "listLanguages": function () { },
    "regex": {
        "anyNumberOfTimes": function () { },
        "concat": function () { },
        "either": function () { },
        "lookahead": function () { },
        "optional": function () { }
    },
    "registerAliases": function () { },
    "registerLanguage": function () { },
    "safeMode": function () { },
    "unregisterLanguage": function () { },
    "versionString": {}
};
  /**********************************************************************
 * End Generated Extern for hljs
/**********************************************************************/