/**********************************************************************
 * Extern for vegaEmbed
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var vegaEmbed = {
  "container": function () {},
  "default": function () {},
  "embed": function () {},
  "vega": {
    "default": {}
  },
  "vegaLite": {
    "default": {}
  },
  "version": {},
  "vl": {
    "default": {}
  }
};
/**********************************************************************
 * End Generated Extern for vegaEmbed
/**********************************************************************/
