var Autosuggest = {
    "displayName": {},
    "propTypes": {
	"suggestions": {},
	"onSuggestionsFetchRequested": {},
	"onSuggestionsClearRequested": {},
	"getSuggestionValue": {},
	"renderSuggestion": {},
	"inputProps": {},
	"onSuggestionSelected": {},
    "onSuggestionHighlighted": {},
	"shouldRenderSuggestions": {},
	"alwaysRenderSuggestions": {},
	"focusFirstSuggestion": {},
	"focusInputOnSuggestionClick": {},
	"multiSection": {},
	"renderSectionTitle": {},
	"getSectionSuggestions": {},
	"renderInputComponent": {},
	"renderSuggestionsContainer": {},
	"theme": {},
	"id": {}
    },
    "getDefaultProps": function () {},
    "defaultProps": {
	"suggestions": {},
	"onSuggestionsFetchRequested": {},
	"onSuggestionsClearRequested": {},
	"getSuggestionValue": {},
	"renderSuggestion": {},
	"inputProps": {},
	"onSuggestionSelected": {},
    "onSuggestionHighlighted": {},
	"shouldRenderSuggestions": {},
	"alwaysRenderSuggestions": {},
	"focusFirstSuggestion": {},
	"focusInputOnSuggestionClick": {},
	"multiSection": {},
	"renderSectionTitle": {},
	"getSectionSuggestions": {},
	"renderInputComponent": {},
	"renderSuggestionsContainer": {},
	"theme": {},
	"id": {}
    }
}
