var localforage = {
    "INDEXEDDB": {},
    "LOCALSTORAGE": {},
    "WEBSQL": {},
    "_config": {
      "description": {},
      "driver": {},
      "name": {},
      "size": {},
      "storeName": {},
      "version": {}
    },
    "_dbInfo": {},
    "_defaultConfig": {
      "description": {},
      "driver": {},
      "name": {},
      "size": {},
      "storeName": {},
      "version": {}
    },
    "_driverSet": {},
    "_extend": function () {},
    "_getSupportedDrivers": function () {},
    "_initDriver": {},
    "_ready": {},
    "_wrapLibraryMethodsWithReady": function () {},
    "clear": function () {},
    "config": function () {},
    "createInstance": function () {},
    "defineDriver": function () {},
    "driver": function () {},
    "getDriver": function () {},
    "getItem": function () {},
    "getSerializer": function () {},
    "iterate": function () {},
    "key": function () {},
    "keys": function () {},
    "length": function () {},
    "ready": function () {},
    "removeItem": function () {},
    "setDriver": function () {},
    "setItem": function () {},
    "supports": function () {}
}
