var localforage = {
    "INDEXEDDB": {},
    "LOCALSTORAGE": {},
    "WEBSQL": {},
    "_config": {
        "description": {},
        "driver": {},
        "name": {},
        "size": {},
        "storeName": {},
        "version": {}
    },
    "_driverSet": function () {},
    "_ready": function () {},
    "_dbInfo": function () {},
    "clear": function () {},
    "getItem": function () {},
    "iterate": function () {},
    "key": function () {},
    "keys": function () {},
    "length": function () {},
    "removeItem": function () {},
    "setItem": function () {},
    "_driver": {},
    "_initStorage": function () {},
    "config": function () {},
    "defineDriver": function () {},
    "driver": function () {},
    "ready": function () {},
    "setDriver": function () {},
    "supports": function () {},
    "_extend": function () {},
    "_getFirstSupportedDriver": function () {},
    "createInstance": function () {}
}
