/**********************************************************************
 * Extern for GoogleMapReact
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var GoogleMapReact = {
  "propTypes": {
    "apiKey": {
      "isRequired": function () {}
    },
    "bootstrapURLKeys": {
      "isRequired": function () {}
    },
    "defaultCenter": {
      "isRequired": function () {}
    },
    "center": {
      "isRequired": function () {}
    },
    "defaultZoom": {
      "isRequired": function () {}
    },
    "zoom": {
      "isRequired": function () {}
    },
    "onBoundsChange": {
      "isRequired": function () {}
    },
    "onChange": {
      "isRequired": function () {}
    },
    "onClick": {
      "isRequired": function () {}
    },
    "onChildClick": {
      "isRequired": function () {}
    },
    "onChildMouseDown": {
      "isRequired": function () {}
    },
    "onChildMouseUp": {
      "isRequired": function () {}
    },
    "onChildMouseMove": {
      "isRequired": function () {}
    },
    "onChildMouseEnter": {
      "isRequired": function () {}
    },
    "onChildMouseLeave": {
      "isRequired": function () {}
    },
    "onZoomAnimationStart": {
      "isRequired": function () {}
    },
    "onZoomAnimationEnd": {
      "isRequired": function () {}
    },
    "onDrag": {
      "isRequired": function () {}
    },
    "onMapTypeIdChange": {
      "isRequired": function () {}
    },
    "options": {
      "isRequired": function () {}
    },
    "distanceToMouse": {
      "isRequired": function () {}
    },
    "hoverDistance": {
      "isRequired": function () {}
    },
    "debounced": {
      "isRequired": function () {}
    },
    "margin": {
      "isRequired": function () {}
    },
    "googleMapLoader": {
      "isRequired": function () {}
    },
    "onGoogleApiLoaded": {
      "isRequired": function () {}
    },
    "yesIWantToUseGoogleMapApiInternals": {
      "isRequired": function () {}
    },
    "draggable": {
      "isRequired": function () {}
    },
    "style": {
      "isRequired": function () {}
    },
    "resetBoundsOnResize": {
      "isRequired": function () {}
    },
    "layerTypes": {
      "isRequired": function () {}
    }
  },
  "defaultProps": {
    "distanceToMouse": function () {},
    "hoverDistance": {},
    "debounced": {},
    "options": function () {},
    "googleMapLoader": function () {},
    "yesIWantToUseGoogleMapApiInternals": {},
    "style": {
      "width": {},
      "height": {},
      "margin": {},
      "padding": {},
      "position": {}
    },
    "layerTypes": {}
  },
  "googleMapLoader": function () {}
};
GoogleMapReact.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
/**********************************************************************
 * End Generated Extern for GoogleMapReact
/**********************************************************************/
