// topojson.ext.js ---
//
// Filename: topojson.ext.js
// Description: Using topojson in ClojureScript
// Author: Peter C. Norton
// Maintainer: Peter C. Norton
// Created: Monday Feb 23 11:51:00 2015 (-0500)
//
// Version: 0.1.0-SNAPSHOT
// Last-Updated: Monday Feb 23 11:51:00 2015 (-0500)
//           By: Federico Boniardi
//     Update #: 1
// Commentary:
//     autogenerated by http://www.dotnetwise.com/Code/Externs/
//     from pointing it at http://d3js.org/topojson.v1.min.js and
//     externing the name "topojson"

var topojson = {
    "version": {},
    "mesh": function () {},
    "meshArcs": function () {},
    "merge": function () {},
    "mergeArcs": function () {},
    "feature": function () {},
    "neighbors": function () {},
    "presimplify": function () {}
}
