// generated manually via the propTypes listing in source
var FixedDataTable = {
    "ColumnGroup": {
            isScrolling: function() {},
            align: function() {},
            className: function() {},
            highlighted: function() {},
            width: function() {},
            minWidth: function() {},
            maxWidth: function() {},
            height: function() {},
            cell: function() {},
            columnKey: function() {},
            rowIndex: function() {},
            onColumnResize: function() {},
            left: function() {},
    },
    "Column": {
            align: function() {},
            fixed: function() {},
            header: function() {},
            cell: function() {},
            footer: function() {},
            columnKey: function() {},
            width: function() {},
            minWidth: function() {},
            maxWidth: function() {},
            flexGrow: function() {},
            isResizable: function() {},
            allowCellsRecycling: function() {},
    },
    "Table": {
            width: function() {},
            height: function() {},
            maxHeight: function() {},
            ownerHeight: function() {},
            overflowX: function() {},
            overflowY: function() {},
            rowsCount: function() {},
            rowHeight: function() {},
            rowHeightGetter: function() {},
            rowGetter: function() {},
            rowClassNameGetter: function() {},
            groupHeaderHeight: function() {},
            headerHeight: function() {},
            headerDataGetter: function() {},
            footerHeight: function() {},
            footerData: function() {},
            footerDataGetter: function() {},
            scrollLeft: function() {},
            scrollToColumn: function() {},
            scrollTop: function() {},
            scrollToRow: function() {},
            onScrollStart: function() {},
            onScrollEnd: function() {},
            onContentHeightChange: function() {},
            onRowClick: function() {},
            onRowDoubleClick: function() {},
            onRowMouseDown: function() {},
            onRowMouseEnter: function() {},
            onRowMouseLeave: function() {},
            onColumnResizeEndCallback: function() {},
            isColumnResizing: function() {},
    },
    "Cell": {
            height: function() {},
            width: function() {},
            columnKey: function() {},
    },
    "version": {}
}
