/**********************************************************************
 * Extern for Delaunator
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Delaunator = {
  "from": function () {}
};
Delaunator.prototype = {
  "_addTriangle": function () {},
  "_hashEdge": function () {},
  "_hashKey": function () {},
  "_legalize": function () {},
  "_link": function () {}
};
/**********************************************************************
 * End Generated Extern for Delaunator
/**********************************************************************/
