/**********************************************************************
 * Extern for Sentry
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Sentry = {
  "BrowserClient": function () {},
  "Hub": function () {},
  "Integrations": {
    "Breadcrumbs": {
      "id": {}
    },
    "Dedupe": {
      "id": {}
    },
    "FunctionToString": {
      "id": {}
    },
    "GlobalHandlers": {
      "id": {}
    },
    "InboundFilters": {
      "id": {}
    },
    "LinkedErrors": {
      "id": {}
    },
    "TryCatch": {
      "id": {}
    },
    "UserAgent": {
      "id": {}
    }
  },
  "SDK_NAME": {},
  "SDK_VERSION": {},
  "Scope": {
    "clone": function () {}
  },
  "Severity": {
    "Critical": {},
    "Debug": {},
    "Error": {},
    "Fatal": {},
    "Info": {},
    "Log": {},
    "Warning": {},
    "fromString": function () {}
  },
  "Status": {
    "Failed": {},
    "Invalid": {},
    "RateLimit": {},
    "Skipped": {},
    "Success": {},
    "Unknown": {},
    "fromHttpCode": function () {}
  },
  "Transports": {
    "BaseTransport": function () {},
    "FetchTransport": function () {},
    "XHRTransport": function () {}
  },
  "addBreadcrumb": function () {},
  "addGlobalEventProcessor": function () {},
  "captureEvent": function () {},
  "captureException": function () {},
  "captureMessage": function () {},
  "close": function () {},
  "configureScope": function () {},
  "defaultIntegrations": {},
  "eventFromException": function () {},
  "eventFromMessage": function () {},
  "flush": function () {},
  "forceLoad": function () {},
  "getCurrentHub": function () {},
  "getHubFromCarrier": function () {},
  "init": function () {},
  "injectReportDialog": function () {},
  "lastEventId": function () {},
  "makeMain": function () {},
  "onLoad": function () {},
  "setContext": function () {},
  "setExtra": function () {},
  "setExtras": function () {},
  "setTag": function () {},
  "setTags": function () {},
  "setUser": function () {},
  "showReportDialog": function () {},
  "startTransaction": function () {},
  "withScope": function () {},
  "wrap": function () {}
};
Sentry.BrowserClient.prototype = {
  "Et": function () {},
  "St": function () {},
  "bt": function () {},
  "captureEvent": function () {},
  "captureException": function () {},
  "captureMessage": function () {},
  "captureSession": function () {},
  "close": function () {},
  "constructor": function () {},
  "dt": function () {},
  "flush": function () {},
  "ft": function () {},
  "getDsn": function () {},
  "getIntegration": function () {},
  "getOptions": function () {},
  "gt": function () {},
  "ht": function () {},
  "jt": function () {},
  "kt": function () {},
  "lt": function () {},
  "pt": function () {},
  "setupIntegrations": function () {},
  "showReportDialog": function () {},
  "vt": function () {},
  "wt": function () {},
  "yt": function () {}
};
Sentry.Hub.prototype = {
  "V": function () {},
  "Y": function () {},
  "Z": function () {},
  "addBreadcrumb": function () {},
  "bindClient": function () {},
  "captureEvent": function () {},
  "captureException": function () {},
  "captureMessage": function () {},
  "captureSession": function () {},
  "configureScope": function () {},
  "endSession": function () {},
  "getClient": function () {},
  "getIntegration": function () {},
  "getScope": function () {},
  "getStack": function () {},
  "getStackTop": function () {},
  "isOlderThan": function () {},
  "lastEventId": function () {},
  "popScope": function () {},
  "pushScope": function () {},
  "run": function () {},
  "setContext": function () {},
  "setExtra": function () {},
  "setExtras": function () {},
  "setTag": function () {},
  "setTags": function () {},
  "setUser": function () {},
  "startSession": function () {},
  "startSpan": function () {},
  "startTransaction": function () {},
  "traceHeaders": function () {},
  "withScope": function () {}
};
Sentry.Integrations.Breadcrumbs.prototype = {
  "addSentryBreadcrumb": function () {},
  "en": function () {},
  "in": function () {},
  "on": function () {},
  "rn": function () {},
  "setupOnce": function () {},
  "un": function () {}
};
Sentry.Integrations.Dedupe.prototype = {
  "Dt": function () {},
  "dn": function () {},
  "hn": function () {},
  "ln": function () {},
  "pn": function () {},
  "setupOnce": function () {},
  "vn": function () {},
  "yn": function () {}
};
Sentry.Integrations.FunctionToString.prototype = {
  "setupOnce": function () {}
};
Sentry.Integrations.GlobalHandlers.prototype = {
  "Gt": function () {},
  "Kt": function () {},
  "Qt": function () {},
  "Vt": function () {},
  "setupOnce": function () {},
  "zt": function () {}
};
Sentry.Integrations.InboundFilters.prototype = {
  "At": function () {},
  "Ct": function () {},
  "Dt": function () {},
  "It": function () {},
  "Mt": function () {},
  "Nt": function () {},
  "Rt": function () {},
  "Tt": function () {},
  "_mergeOptions": function () {},
  "setupOnce": function () {}
};
Sentry.Integrations.LinkedErrors.prototype = {
  "an": function () {},
  "cn": function () {},
  "setupOnce": function () {}
};
Sentry.Integrations.TryCatch.prototype = {
  "Yt": function () {},
  "Zt": function () {},
  "nn": function () {},
  "setupOnce": function () {},
  "tn": function () {}
};
Sentry.Integrations.UserAgent.prototype = {
  "setupOnce": function () {}
};
Sentry.Scope.prototype = {
  "B": function () {},
  "J": function () {},
  "W": function () {},
  "addBreadcrumb": function () {},
  "addEventProcessor": function () {},
  "addScopeListener": function () {},
  "applyToEvent": function () {},
  "clear": function () {},
  "clearBreadcrumbs": function () {},
  "getRequestSession": function () {},
  "getSession": function () {},
  "getSpan": function () {},
  "getTransaction": function () {},
  "getUser": function () {},
  "setContext": function () {},
  "setExtra": function () {},
  "setExtras": function () {},
  "setFingerprint": function () {},
  "setLevel": function () {},
  "setRequestSession": function () {},
  "setSession": function () {},
  "setSpan": function () {},
  "setTag": function () {},
  "setTags": function () {},
  "setTransaction": function () {},
  "setTransactionName": function () {},
  "setUser": function () {},
  "update": function () {}
};
Sentry.Transports.BaseTransport.prototype = {
  "Ft": function () {},
  "Ht": function () {},
  "Pt": function () {},
  "Xt": function () {},
  "close": function () {},
  "sendEvent": function () {}
};
Sentry.Transports.FetchTransport.prototype = {
  "Ft": function () {},
  "Ht": function () {},
  "Jt": function () {},
  "Pt": function () {},
  "Xt": function () {},
  "close": function () {},
  "constructor": function () {},
  "sendEvent": function () {},
  "sendSession": function () {}
};
Sentry.Transports.XHRTransport.prototype = {
  "Ft": function () {},
  "Ht": function () {},
  "Jt": function () {},
  "Pt": function () {},
  "Xt": function () {},
  "close": function () {},
  "constructor": function () {},
  "sendEvent": function () {},
  "sendSession": function () {}
};
/**********************************************************************
 * End Generated Extern for Sentry
/**********************************************************************/
