/**********************************************************************
 * Extern for pica
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var pica = function () {};
pica.prototype = {
  "debug": function () {},
  "init": function () {},
  "resize": function () {},
  "resizeBuffer": function () {},
  "toBlob": function () {}
};
/**********************************************************************
 * End Generated Extern for pica
 /**********************************************************************/
