var mixpanel = {
    "init": function () {},
    "_": {
        "trim": function () {},
        "bind": function () {},
        "bind_instance_methods": function () {},
        "each": function () {},
        "escapeHTML": function () {},
        "extend": function () {},
        "isArray": function () {},
        "isFunction": function () {},
        "isArguments": function () {},
        "toArray": function () {},
        "keys": function () {},
        "values": function () {},
        "identity": function () {},
        "include": function () {},
        "includes": function () {},
        "inherit": function () {},
        "isObject": function () {},
        "isEmptyObject": function () {},
        "isUndefined": function () {},
        "isString": function () {},
        "isDate": function () {},
        "isNumber": function () {},
        "isElement": function () {},
        "encodeDates": function () {},
        "timestamp": function () {},
        "formatDate": function () {},
        "safewrap": function () {},
        "safewrap_class": function () {},
        "safewrap_instance_methods": function () {},
        "strip_empty_properties": function () {},
        "truncate": function () {},
        "JSONEncode": function () {},
        "JSONDecode": function () {},
        "base64Encode": function () {},
        "utf8Encode": function () {},
        "UUID": function () {},
        "isBlockedUA": function () {},
        "HTTPBuildQuery": function () {},
        "getQueryParam": function () {},
        "getHashParam": function () {},
        "cookie": {
            "get": function () {},
            "parse": function () {},
            "set_seconds": function () {},
            "set": function () {},
            "remove": function () {}
        },
        "localStorage": {
            "error": function () {},
            "get": function () {},
            "parse": function () {},
            "set": function () {},
            "remove": function () {}
        },
        "register_event": function () {},
        "dom_query": function () {},
        "info": {
            "campaignParams": function () {},
            "searchEngine": function () {},
            "searchInfo": function () {},
            "browser": function () {},
            "browserVersion": function () {},
            "os": function () {},
            "device": function () {},
            "referringDomain": function () {},
            "properties": function () {},
            "people_properties": function () {},
            "pageviewInfo": function () {}
        },
        "people": {
            "set": function () {},
            "set_once": function () {},
            "unset": function () {},
            "increment": function () {},
            "append": function () {},
            "union": function () {},
            "track_charge": function () {},
            "clear_charge": function () {},
            "delete_user": function () {}
        }
    },
    "_init": function () {},
    "_loaded": function () {},
    "_dom_loaded": function () {},
    "_track_dom": function () {},
    "_prepare_callback": function () {},
    "_send_request": function () {},
    "_execute_array": function () {},
    "push": function () {},
    "disable": function () {},
    "track": function () {},
    "track_pageview": function () {},
    "track_links": function () {},
    "track_forms": function () {},
    "time_event": function () {},
    "register": function () {},
    "register_once": function () {},
    "unregister": function () {},
    "_register_single": function () {},
    "identify": function () {},
    "reset": function () {},
    "get_distinct_id": function () {},
    "alias": function () {},
    "name_tag": function () {},
    "set_config": function () {},
    "get_config": function () {},
    "get_property": function () {},
    "toString": function () {},
    "_event_is_disabled": function () {},
    "_check_and_handle_notifications": function () {},
    "_show_notification": function () {}
};
