/**********************************************************************
 * Extern for katex
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var katex = {
  "ParseError": function () {},
  "__defineMacro": function () {},
  "__defineSymbol": function () {},
  "__domTree": {
    "Anchor": function () {},
    "LineNode": function () {},
    "PathNode": function () {},
    "Span": function () {},
    "SvgNode": function () {},
    "SymbolNode": function () {}
  },
  "__parse": function () {},
  "__renderToDomTree": function () {},
  "__renderToHTMLTree": function () {},
  "__setFontMetrics": function () {},
  "render": function () {},
  "renderToString": function () {},
  "version": {}
};
katex.__domTree.Anchor.prototype = {
  "hasClass": function () {},
  "setAttribute": function () {},
  "toMarkup": function () {},
  "toNode": function () {}
};
katex.__domTree.LineNode.prototype = {
  "toMarkup": function () {},
  "toNode": function () {}
};
katex.__domTree.PathNode.prototype = {
  "toMarkup": function () {},
  "toNode": function () {}
};
katex.__domTree.Span.prototype = {
  "hasClass": function () {},
  "setAttribute": function () {},
  "toMarkup": function () {},
  "toNode": function () {}
};
katex.__domTree.SvgNode.prototype = {
  "toMarkup": function () {},
  "toNode": function () {}
};
katex.__domTree.SymbolNode.prototype = {
  "hasClass": function () {},
  "toMarkup": function () {},
  "toNode": function () {}
};
/**********************************************************************
 * End Generated Extern for katex
/**********************************************************************/
