/**********************************************************************
 * Extern for katex
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var katex = {
    "version": {},
    "render": function () {},
    "renderToString": function () {},
    "ParseError": function () {},
    "__parse": function () {},
    "__renderToDomTree": function () {},
    "__renderToHTMLTree": function () {},
    "__setFontMetrics": function () {},
    "__defineSymbol": function () {},
    "__defineMacro": function () {},
    "__domTree": {
        "Span": function () {},
        "Anchor": function () {},
        "SymbolNode": function () {},
        "SvgNode": function () {},
        "PathNode": function () {},
        "LineNode": function () {}
    }
}
/**********************************************************************
 * End Generated Extern for katex
/**********************************************************************/
