var FieldKit = {
  "AdaptiveCardFormatter": function () {},
  "AmexCardFormatter": function () {},
  "CardTextField": function () {},
  "CardUtils": {},
  "DefaultCardFormatter": function () {},
  "DelimitedTextFormatter": function () {},
  "EmployerIdentificationNumberFormatter": function () {},
  "ExpiryDateField": function () {},
  "ExpiryDateFormatter": function () {},
  "Formatter": function () {},
  "NumberFormatter": {
    "Rounding": {},
    "Style": {}
  },
  "NumberFormatterSettingsFormatter": function () {},
  "PhoneFormatter": function () {},
  "SocialSecurityNumberFormatter": function () {},
  "TextField": {
    "delegate": function () {},
    "setDelegate": function () {},
    "destroy": function () {},
    "formatter": function () {},
    "setFormatter": function () {},
    "hasChangesAndIsValid": function () {},
    "insertNewline": function () {},
    "inspect": function () {},
    "readSelectionFromPasteboard": function () {},
    "rollbackInvalidChanges": function () {},
    "value": function () {},
    "setValue": function () {},
    "text": function () {},
    "setText": function () {},
    "selectedRange": function () {},
    "setSelectedRangeWithAffinity": function () {},
    "allowsUndo": function () {},
    "setAllowsUndo": function () {},
    "redo": function () {},
    "undo": function () {},
    "undoManager": function () {},
    "becomeFirstResponder": function () {},
    "hasFocus": function () {},
    "isEnabled": function () {},
    "setEnabled": function () {},
    "resignFirstResponder": function () {},
    "disabledPlaceholder": function () {},
    "setDisabledPlaceholder": function () {},
    "focusedPlaceholder": function () {},
    "setFocusedPlaceholder": function () {},
    "placeholder": function () {},
    "setPlaceholder": function () {},
    "unfocusedPlaceholder": function () {},
    "setUnfocusedPlaceholder": function () {}
  },
  "UndoManager": function () {}
};
FieldKit.NumberFormatter.prototype = {
  "_allowsFloats": function () {},
  "_alwaysShowsDecimalSeparator": function () {},
  "_countryCode": function () {},
  "_currencyCode": function () {},
  "_exponent": function () {},
  "_groupingSeparator": function () {},
  "_groupingSize": function () {},
  "_lenient": function () {},
  "_locale": function () {},
  "_internationalCurrencySymbol": function () {},
  "_maximumFractionDigits": function () {},
  "_minimumFractionDigits": function () {},
  "_maximumIntegerDigits": function () {},
  "_minimumIntegerDigits": function () {},
  "_maximum": function () {},
  "_minimum": function () {},
  "_notANumberSymbol": function () {},
  "_nullSymbol": function () {},
  "_numberStyle": function () {},
  "_roundingMode": function () {},
  "_usesGroupingSeparator": function () {},
  "_zeroSymbol": function () {},
  "stringFromNumber": function () {},
  "numberFromString": function () {}
};
