/**********************************************************************
 * Extern for MG
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var MG = {
    "version": {},
    "convert": {
        "date": function () {},
        "number": function () {}
    },
    "time_format": function () {},
    "merge_with_defaults": function () {},
    "clone": function () {},
    "arr_diff": function () {},
    "warn_deprecation": function () {},
    "truncate_text": function () {},
    "wrap_text": function () {},
    "register": function () {},
    "_hooks": {},
    "add_hook": function () {},
    "call_hook": function () {},
    "globals": {
        "link": {},
        "version": {}
    },
    "deprecations": {
        "rollover_callback": {
            "replacement": {},
            "version": {}
        },
        "rollout_callback": {
            "replacement": {},
            "version": {}
        },
        "x_rollover_format": {
            "replacement": {},
            "version": {}
        },
        "y_rollover_format": {
            "replacement": {},
            "version": {}
        },
        "show_years": {
            "replacement": {},
            "version": {}
        },
        "xax_start_at_min": {
            "replacement": {},
            "version": {}
        },
        "interpolate_tension": {
            "replacement": {},
            "version": {}
        }
    },
    "charts": {
        "line": {
            "descriptor": function () {},
            "defaults": {}
        },
        "histogram": {
            "descriptor": function () {},
            "defaults": {
                "binned": {},
                "bins": {},
                "processed_x_accessor": {},
                "processed_y_accessor": {},
                "processed_dx_accessor": {},
                "bar_margin": {}
            }
        },
        "point": {
            "descriptor": function () {},
            "defaults": {
                "y_padding_percentage": {},
                "y_outer_padding_percentage": {},
                "ygroup_padding_percentage": {},
                "ygroup_outer_padding_percentage": {},
                "x_padding_percentage": {},
                "x_outer_padding_percentage": {},
                "xgroup_padding_percentage": {},
                "xgroup_outer_padding_percentage": {},
                "y_categorical_show_guides": {},
                "x_categorical_show_guides": {},
                "buffer": {},
                "ls": {},
                "lowess": {},
                "point_size": {},
                "label_accessor": {},
                "size_accessor": {},
                "color_accessor": {},
                "size_range": {},
                "color_range": {},
                "size_domain": {},
                "color_domain": {},
                "active_point_size_increase": {},
                "color_type": {}
            }
        },
        "bar": {
            "descriptor": function () {},
            "defaults": {
                "y_padding_percentage": {},
                "y_outer_padding_percentage": {},
                "ygroup_padding_percentage": {},
                "ygroup_outer_padding_percentage": {},
                "x_padding_percentage": {},
                "x_outer_padding_percentage": {},
                "xgroup_padding_percentage": {},
                "xgroup_outer_padding_percentage": {},
                "buffer": {},
                "y_accessor": {},
                "x_accessor": {},
                "secondary_label_accessor": {},
                "color_accessor": {},
                "color_type": {},
                "color_domain": {},
                "legend": {},
                "legend_target": {},
                "mouseover_align": {},
                "baseline_accessor": {},
                "predictor_accessor": {},
                "predictor_proportion": {},
                "show_bar_zero": {},
                "binned": {},
                "truncate_x_labels": {},
                "truncate_y_labels": {}
            }
        },
        "missing-data": {
            "descriptor": function () {},
            "defaults": {
                "top": {},
                "bottom": {},
                "right": {},
                "left": {},
                "buffer": {},
                "legend_target": {},
                "width": {},
                "height": {},
                "missing_text": {},
                "scalefns": {},
                "scales": {},
                "show_tooltips": {},
                "show_missing_background": {}
            }
        }
    },
    "data_graphic": function () {},
    "chart_title": function () {},
    "scale_factory": function () {},
    "axis_factory": function () {},
    "y_rug": function () {},
    "y_axis": function () {},
    "y_axis_categorical": function () {},
    "x_rug": function () {},
    "x_axis": function () {},
    "x_axis_categorical": function () {},
    "init": function () {},
    "markers": function () {},
    "button_layout": function () {},
    "data_table": function () {},
    "raw_data_transformation": function () {},
    "process_line": function () {},
    "process_histogram": function () {},
    "process_categorical_variables": function () {},
    "process_point": function () {},
    "add_ls": function () {},
    "add_lowess": function () {},
    "lowess_robust": function () {},
    "lowess": function () {},
    "least_squares": function () {},
    "format_rollover_number": function () {},
    "path_tween": function () {},
    "error": function () {}
};
/**********************************************************************
 * End Generated Extern for MG
 /**********************************************************************/