var FixedDataTable = {
    "ColumnGroup": {
        align: function() {},
        fixed: function() {},
        header: function() {}
    },
    "Column": {
        align: function() {},
        fixed: function() {},
        header: function() {},
        cell: function() {},
        footer: function() {},
        columnKey: function() {},
        width: function() {},
        minWidth: function() {},
        maxWidth: function() {},
        flexGrow: function() {},
        isResizable: function() {},
        isReorderable: function() {},
        allowCellsRecycling: function() {},
        pureRendering: function() {}
    },
    "Table": {
        width: function() {},
        height: function() {},
        className: function() {},
        maxHeight: function() {},
        ownerHeight: function() {},
        overflowX: function() {},
        overflowY: function() {},
        touchScrollEnabled: function() {},
        showScrollBarX: function() {},
        showScrollBarY: function() {},
        onHorizontalScroll: function() {},
        onVerticalScroll: function() {},
        rowsCount: function() {},
        rowHeight: function() {},
        rowHeightGetter: function() {},
        rowClassNameGetter: function() {},
        rowKeyGetter: function() {},
        groupHeaderHeight: function() {},
        headerHeight: function() {},
        footerHeight: function() {},
        scrollLeft: function() {},
        scrollToColumn: function() {},
        scrollTop: function() {},
        scrollToRow: function() {},
        onScrollStart: function() {},
        onScrollEnd: function() {},
        onContentHeightChange: function() {},
        onRowClick: function() {},
        onRowDoubleClick: function() {},
        onRowMouseDown: function() {},
        onRowMouseEnter: function() {},
        onRowMouseLeave: function() {},
        onColumnResizeEndCallback: function() {},
        onColumnReorderEndCallback: function() {},
        isColumnResizing: function() {},
        isColumnReordering: function() {}
    },
    "Cell": {
        height: function() {},
        width: function() {},
        columnKey: function() {},
        rowIndex: function() {}
    },
    "version": {}
};
