var FixedDataTable = {
    "ColumnGroup": {
        "groupHeaderRenderer": function () {},
        "label": {},
        "columnGroupData": {},
        "fixed": {},
        "align": {}
    },
    "Column": {
        "align": {},
        "columnData": {},
        "dataKey": {},
        "fixed": {},
        "label": {},
        "width": {},
        "minWidth": {},
        "allowCellsRecycling": {},
        "cellRenderer": function () {},
        "flexGrow": {},
        "cellDataGetter": function () {},
        "isResizable": {},
        "footerRenderer": function () {},
        "cellClassName": {},
        "maxWidth": {},
        "headerRenderer": function () {}
    },
    "Table": {
        "width": {},
        "height": {},
        "maxHeight": {},
        "ownerHeight": {},
        "overflowX": {},
        "overflowY": {},
        "rowsCount": {},
        "rowHeight": {},
        "rowHeightGetter": function () {},
        "rowGetter": function () {},
        "rowClassNameGetter": function () {},
        "groupHeaderHeight": {},
        "headerHeight": {},
        "headerDataGetter": function () {},
        "footerHeight": {},
        "footerData": function () {},
        "footerDataGetter": function() {},
        "scrollLeft": {},
        "scrollToColumn": {},
        "scrollTop": {},
        "scrollToRow": {},
        "onScrollEnd": function () {},
        "onContentHeightChange": function() {},
        "onRowClick": function () {},
        "onRowDoubleClick": function () {},
        "onRowMouseDown": function () {},
        "onRowMouseEnter": function () {},
        "onRowMouseLeave": function () {},
        "onColumnResizeEndCallback": function () {},
        "isColumnResizing": {}
    }
};
