var anime = {
    "version": {},
    "speed": {},
    "running": function () {},
    "remove": function () {},
    "getValue": function () {},
    "path": function () {},
    "setDashoffset": function () {},
    "bezier": function () {},
    "easings": {
        "linear": function () {},
        "easeInQuad": function () {},
        "easeInCubic": function () {},
        "easeInQuart": function () {},
        "easeInQuint": function () {},
        "easeInSine": function () {},
        "easeInExpo": function () {},
        "easeInCirc": function () {},
        "easeInBack": function () {},
        "easeInElastic": function () {},
        "easeOutQuad": function () {},
        "easeOutCubic": function () {},
        "easeOutQuart": function () {},
        "easeOutQuint": function () {},
        "easeOutSine": function () {},
        "easeOutExpo": function () {},
        "easeOutCirc": function () {},
        "easeOutBack": function () {},
        "easeOutElastic": function () {},
        "easeInOutQuad": function () {},
        "easeInOutCubic": function () {},
        "easeInOutQuart": function () {},
        "easeInOutQuint": function () {},
        "easeInOutSine": function () {},
        "easeInOutExpo": function () {},
        "easeInOutCirc": function () {},
        "easeInOutBack": function () {},
        "easeInOutElastic": function () {}
    },
    "timeline": function () {},
    "random": function () {}
}