/**********************************************************************
 * Extern for ReactVisForce
 * Generated by http://jmmk.github.io/javascript-externs-generator
 * Loaded JavaScripts:
 * https://fb.me/react-15.0.2.js
 * https://fb.me/react-dom-15.0.2.js
 * https://unpkg.com/react-vis-force@0.1.4/dist/react-vis-force.js
 **********************************************************************/
var ReactVisForce = {
  "createSimulation": function () {},
  "updateSimulation": function () {},
  "ForceGraph": function () {},
  "ForceGraphLink": function () {},
  "ForceGraphNode": function () {},
  "InteractiveForceGraph": function () {}
};
ReactVisForce.ForceGraph.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
ReactVisForce.ForceGraphLink.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
ReactVisForce.ForceGraphNode.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
ReactVisForce.InteractiveForceGraph.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactVisForce
/**********************************************************************/