var Slider = {
  "propTypes": {
    "className": {},
    "min": {},
    "max": {},
    "marks": {},
    "step": {},
    "range": {},
    "allowCross": {},
    "pushable": {},
    "vertical": {},
    "defaultValue": {},
    "value": {},
    "handle": {},
    "included": {},
    "disabled": {},
    "tipTransitionName": {},
    "tipFormatter": {},
    "dots": {},
    "onChange": function () {},
    "onAfterChange": function () {}
  },
  "getDefaultProps": function () {},
  "defaultProps": {
    "className": {},
    "min": {},
    "max": {},
    "marks": {},
    "step": {},
    "range": {},
    "allowCross": {},
    "pushable": {},
    "vertical": {},
    "defaultValue": {},
    "value": {},
    "handle": {},
    "included": {},
    "disabled": {},
    "tipTransitionName": {},
    "tipFormatter": {},
    "dots": {},
    "onChange": function () {},
    "onAfterChange": function () {}
  }
}