/**********************************************************************
 * Extern for anime
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var anime = {
  "convertPx": function () {},
  "easing": function () {},
  "get": function () {},
  "path": function () {},
  "penner": {
    "easeInBack": {},
    "easeInCirc": {},
    "easeInCubic": {},
    "easeInElastic": function () {},
    "easeInExpo": {},
    "easeInOutBack": {},
    "easeInOutCirc": {},
    "easeInOutCubic": {},
    "easeInOutElastic": function () {},
    "easeInOutExpo": {},
    "easeInOutQuad": {},
    "easeInOutQuart": {},
    "easeInOutQuint": {},
    "easeInOutSine": {},
    "easeInQuad": {},
    "easeInQuart": {},
    "easeInQuint": {},
    "easeInSine": {},
    "easeOutBack": {},
    "easeOutCirc": {},
    "easeOutCubic": {},
    "easeOutElastic": function () {},
    "easeOutExpo": {},
    "easeOutQuad": {},
    "easeOutQuart": {},
    "easeOutQuint": {},
    "easeOutSine": {},
    "linear": {}
  },
  "random": function () {},
  "remove": function () {},
  "running": {},
  "set": function () {},
  "setDashoffset": function () {},
  "speed": {},
  "stagger": function () {},
  "timeline": function () {},
  "version": {}
};
/**********************************************************************
 * End Generated Extern for anime
/**********************************************************************/
