var nv = {
    "dev": {},
    "tooltip": function () {},
    "utils": {
        "windowSize": function () {},
        "windowResize": function () {},
        "getColor": function () {},
        "defaultColor": function () {},
        "customTheme": function () {},
        "pjax": function () {},
        "calcApproxTextWidth": function () {},
        "NaNtoZero": function () {},
        "renderWatch": function () {},
        "deepExtend": function () {},
        "state": function () {},
        "optionsFunc": function () {},
        "calcTicksX": function () {},
        "calcTicksY": function () {},
        "initOption": function () {},
        "initOptions": function () {},
        "inheritOptionsD3": function () {},
        "arrayUnique": function () {},
        "symbolMap": {
            "_": function () {}
        },
        "symbol": function () {},
        "inheritOptions": function () {},
        "initSVG": function () {},
        "sanitizeHeight": function () {},
        "sanitizeWidth": function () {},
        "availableHeight": function () {},
        "availableWidth": function () {},
        "noData": function () {}
    },
    "models": {
        "tooltip": function () {},
        "axis": function () {},
        "boxPlot": function () {},
        "boxPlotChart": function () {},
        "bullet": function () {},
        "bulletChart": function () {},
        "candlestickBar": function () {},
        "cumulativeLineChart": function () {},
        "discreteBar": function () {},
        "discreteBarChart": function () {},
        "distribution": function () {},
        "furiousLegend": function () {},
        "historicalBar": function () {},
        "historicalBarChart": function () {},
        "ohlcBarChart": function () {},
        "candlestickBarChart": function () {},
        "legend": function () {},
        "line": function () {},
        "lineChart": function () {},
        "linePlusBarChart": function () {},
        "lineWithFocusChart": function () {},
        "multiBar": function () {},
        "multiBarChart": function () {},
        "multiBarHorizontal": function () {},
        "multiBarHorizontalChart": function () {},
        "multiChart": function () {},
        "ohlcBar": function () {},
        "parallelCoordinates": function () {},
        "pie": function () {},
        "pieChart": function () {},
        "scatter": function () {},
        "scatterChart": function () {},
        "sparkline": function () {},
        "sparklinePlus": function () {},
        "stackedArea": function () {},
        "stackedAreaChart": function () {},
        "sunburst": function () {},
        "sunburstChart": function () {}
    },
    "charts": function () {},
    "logs": function () {},
    "dom": {
        "write": function () {},
        "read": function () {}
    },
    "dispatch": {
        "render_start": function () {},
        "render_end": function () {},
        "on": function () {}
    },
    "log": function () {},
    "deprecated": function () {},
    "render": function () {},
    "addGraph": function () {},
    "interactiveGuideline": function () {},
    "interactiveBisect": function () {},
    "nearestValueIndex": function () {},
    "version": {}
}