/**********************************************************************
 * Extern for Ajv
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Ajv = {
  "$dataMetaSchema": function () {},
  "MissingRefError": {
    "message": function () {}
  },
  "ValidationError": function () {}
};
Ajv.prototype = {
  "_addSchema": function () {},
  "_compile": function () {},
  "addFormat": function () {},
  "addKeyword": function () {},
  "addMetaSchema": function () {},
  "addSchema": function () {},
  "compile": function () {},
  "compileAsync": function () {},
  "errorsText": function () {},
  "getKeyword": function () {},
  "getSchema": function () {},
  "removeKeyword": function () {},
  "removeSchema": function () {},
  "validate": function () {},
  "validateKeyword": function () {},
  "validateSchema": function () {}
};
Ajv.MissingRefError.prototype = {
  "constructor": function () {}
};
Ajv.ValidationError.prototype = {
  "constructor": function () {}
};
/**********************************************************************
 * End Generated Extern for Ajv
/**********************************************************************/
