L.MarkerClusterGroup.prototype = {
  "addLayer": function () {},
  "addLayers": function () {},
  "callInitHooks": function () {},
  "clearLayers": function () {},
  "constructor": function () {},
  "eachLayer": function () {},
  "fire": function () {},
  "getBounds": function () {},
  "getLayer": function () {},
  "getLayers": function () {},
  "getVisibleParent": function () {},
  "hasLayer": function () {},
  "initialize": function () {},
  "listens": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "options": {},
  "refreshClusters": function () {},
  "removeLayer": function () {},
  "removeLayers": function () {},
  "unspiderfy": function () {},
  "zoomToShowLayer": function () {},
  "_addLayer": function () {},
  "_animationAddLayerNonAnimated": function () {},
  "_animationEnd": function () {},
  "_animationZoomOutSingle": function () {},
  "_arraySplice": function () {},
  "_bindEvents": function () {},
  "_checkBoundsMaxLat": function () {},
  "_childMarkerDragEnd": function () {},
  "_childMarkerDragStart": function () {},
  "_childMarkerMoved": function () {},
  "_defaultIconCreateFunction": function () {},
  "_enqueue": function () {},
  "_extractNonGroupLayers": function () {},
  "_flagParentsIconsNeedUpdate": function () {},
  "_forceLayout": function () {},
  "_generateInitialClusters": function () {},
  "_getExpandedVisibleBounds": function () {},
  "_hideCoverage": function () {},
  "_initHooks": {},
  "_isOrIsParent": function () {},
  "_mapBoundsInfinite": {},
  "_mergeSplitClusters": function () {},
  "_moveChild": function () {},
  "_moveEnd": function () {},
  "_noAnimation": {},
  "_noanimationUnspiderfy": function () {},
  "_overrideMarkerIcon": function () {},
  "_processQueue": function () {},
  "_refreshClustersIcons": function () {},
  "_refreshSingleMarkerModeMarkers": function () {},
  "_removeFromGridUnclustered": function () {},
  "_removeLayer": function () {},
  "_showCoverage": function () {},
  "_spiderfied" : {},
  "_spiderfierOnAdd": function () {},
  "_spiderfierOnRemove": function () {},
  "_unbindEvents": function () {},
  "_unspiderfy": function () {},
  "_unspiderfyLayer": function (layer) {},
  "_unspiderfyWrapper": function () {},
  "_unspiderfyZoomAnim": function () {},
  "_unspiderfyZoomStart": function () {},
  "_withAnimation": {},
  "_zoomEnd": function () {},
  "_zoomOrSpiderfy": function () {},
  "freezeAtZoom": function() {},
  "unfreeze": function() {},
  "disableClustering": function() {},
  "disableClusteringKeepSpiderfy": function() {},
  "enableClustering": function() {},
};