var ReactPIXI = {
  "Stage": {
    "displayName": {}
  },
  "DisplayObjectContainer": {
    "displayName": {}
  },
  "SpriteBatch": {
    "displayName": {}
  },
  "Sprite": {
    "displayName": {}
  },
  "Text": {
    "displayName": {}
  },
  "BitmapText": {
    "displayName": {}
  },
  "TilingSprite": {
    "displayName": {}
  },
  "factories": {},
  "CustomPIXIComponent": function () {},
  "render": function () {},
  "unmountComponentAtNode": function () {}
};
ReactPIXI.Stage.prototype = {
  "constructor": function () {},
  "__reactAutoBindPairs": function () {},
  "construct": function () {},
  "getPublicInstance": function () {},
  "transferDisplayObjectPropsByName": function () {},
  "applyDisplayObjectProps": function () {},
  "mountComponentIntoNode": function () {},
  "getNativeNode": function () {},
  "_reconcilerInstantiateChildren": function () {},
  "_reconcilerUpdateChildren": function () {},
  "mountChildren": function () {},
  "updateTextContent": function () {},
  "updateMarkup": function () {},
  "updateChildren": function () {},
  "_updateChildren": function () {},
  "unmountChildren": function () {},
  "moveChild": function () {},
  "createChild": function () {},
  "removeChild": function () {},
  "_mountChildAtIndex": function () {},
  "_unmountChild": function () {},
  "mountAndAddChildren": function () {},
  "setApprovedDOMProperties": function () {},
  "componentDidMount": function () {},
  "componentDidUpdate": function () {},
  "componentWillUnmount": function () {},
  "renderStage": function () {},
  "render": function () {},
  "mixins": function () {},
  "statics": function () {},
  "propTypes": function () {},
  "contextTypes": function () {},
  "childContextTypes": function () {},
  "getDefaultProps": function () {},
  "getInitialState": function () {},
  "getChildContext": function () {},
  "componentWillMount": function () {},
  "componentWillReceiveProps": function () {},
  "shouldComponentUpdate": function () {},
  "componentWillUpdate": function () {},
  "updateComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {},
  "replaceState": function () {},
  "isMounted": function () {}
};
ReactPIXI.DisplayObjectContainer.prototype = {
  "construct": function () {},
  "getPublicInstance": function () {},
  "transferDisplayObjectPropsByName": function () {},
  "applyDisplayObjectProps": function () {},
  "mountComponentIntoNode": function () {},
  "getNativeNode": function () {},
  "_reconcilerInstantiateChildren": function () {},
  "_reconcilerUpdateChildren": function () {},
  "mountChildren": function () {},
  "updateTextContent": function () {},
  "updateMarkup": function () {},
  "updateChildren": function () {},
  "_updateChildren": function () {},
  "unmountChildren": function () {},
  "moveChild": function () {},
  "createChild": function () {},
  "removeChild": function () {},
  "_mountChildAtIndex": function () {},
  "_unmountChild": function () {},
  "mountAndAddChildren": function () {},
  "mountComponent": function () {},
  "receiveComponent": function () {},
  "unmountComponent": function () {},
  "createDisplayObject": function () {},
  "applySpecificDisplayObjectProps": function () {}
};
ReactPIXI.SpriteBatch.prototype = {
  "construct": function () {},
  "getPublicInstance": function () {},
  "transferDisplayObjectPropsByName": function () {},
  "applyDisplayObjectProps": function () {},
  "mountComponentIntoNode": function () {},
  "getNativeNode": function () {},
  "_reconcilerInstantiateChildren": function () {},
  "_reconcilerUpdateChildren": function () {},
  "mountChildren": function () {},
  "updateTextContent": function () {},
  "updateMarkup": function () {},
  "updateChildren": function () {},
  "_updateChildren": function () {},
  "unmountChildren": function () {},
  "moveChild": function () {},
  "createChild": function () {},
  "removeChild": function () {},
  "_mountChildAtIndex": function () {},
  "_unmountChild": function () {},
  "mountAndAddChildren": function () {},
  "mountComponent": function () {},
  "receiveComponent": function () {},
  "unmountComponent": function () {},
  "createDisplayObject": function () {},
  "applySpecificDisplayObjectProps": function () {}
};
ReactPIXI.Sprite.prototype = {
  "construct": function () {},
  "getPublicInstance": function () {},
  "transferDisplayObjectPropsByName": function () {},
  "applyDisplayObjectProps": function () {},
  "mountComponentIntoNode": function () {},
  "getNativeNode": function () {},
  "_reconcilerInstantiateChildren": function () {},
  "_reconcilerUpdateChildren": function () {},
  "mountChildren": function () {},
  "updateTextContent": function () {},
  "updateMarkup": function () {},
  "updateChildren": function () {},
  "_updateChildren": function () {},
  "unmountChildren": function () {},
  "moveChild": function () {},
  "createChild": function () {},
  "removeChild": function () {},
  "_mountChildAtIndex": function () {},
  "_unmountChild": function () {},
  "mountAndAddChildren": function () {},
  "mountComponent": function () {},
  "receiveComponent": function () {},
  "unmountComponent": function () {},
  "createDisplayObject": function () {},
  "applySpecificDisplayObjectProps": function () {}
};
ReactPIXI.Text.prototype = {
  "construct": function () {},
  "getPublicInstance": function () {},
  "transferDisplayObjectPropsByName": function () {},
  "applyDisplayObjectProps": function () {},
  "mountComponentIntoNode": function () {},
  "getNativeNode": function () {},
  "_reconcilerInstantiateChildren": function () {},
  "_reconcilerUpdateChildren": function () {},
  "mountChildren": function () {},
  "updateTextContent": function () {},
  "updateMarkup": function () {},
  "updateChildren": function () {},
  "_updateChildren": function () {},
  "unmountChildren": function () {},
  "moveChild": function () {},
  "createChild": function () {},
  "removeChild": function () {},
  "_mountChildAtIndex": function () {},
  "_unmountChild": function () {},
  "mountAndAddChildren": function () {},
  "mountComponent": function () {},
  "receiveComponent": function () {},
  "unmountComponent": function () {},
  "createDisplayObject": function () {},
  "applySpecificDisplayObjectProps": function () {}
};
ReactPIXI.BitmapText.prototype = {
  "construct": function () {},
  "getPublicInstance": function () {},
  "transferDisplayObjectPropsByName": function () {},
  "applyDisplayObjectProps": function () {},
  "mountComponentIntoNode": function () {},
  "getNativeNode": function () {},
  "_reconcilerInstantiateChildren": function () {},
  "_reconcilerUpdateChildren": function () {},
  "mountChildren": function () {},
  "updateTextContent": function () {},
  "updateMarkup": function () {},
  "updateChildren": function () {},
  "_updateChildren": function () {},
  "unmountChildren": function () {},
  "moveChild": function () {},
  "createChild": function () {},
  "removeChild": function () {},
  "_mountChildAtIndex": function () {},
  "_unmountChild": function () {},
  "mountAndAddChildren": function () {},
  "mountComponent": function () {},
  "receiveComponent": function () {},
  "unmountComponent": function () {},
  "createDisplayObject": function () {},
  "applySpecificDisplayObjectProps": function () {}
};
ReactPIXI.TilingSprite.prototype = {
  "construct": function () {},
  "getPublicInstance": function () {},
  "transferDisplayObjectPropsByName": function () {},
  "applyDisplayObjectProps": function () {},
  "mountComponentIntoNode": function () {},
  "getNativeNode": function () {},
  "_reconcilerInstantiateChildren": function () {},
  "_reconcilerUpdateChildren": function () {},
  "mountChildren": function () {},
  "updateTextContent": function () {},
  "updateMarkup": function () {},
  "updateChildren": function () {},
  "_updateChildren": function () {},
  "unmountChildren": function () {},
  "moveChild": function () {},
  "createChild": function () {},
  "removeChild": function () {},
  "_mountChildAtIndex": function () {},
  "_unmountChild": function () {},
  "mountAndAddChildren": function () {},
  "mountComponent": function () {},
  "receiveComponent": function () {},
  "unmountComponent": function () {},
  "createDisplayObject": function () {},
  "applySpecificDisplayObjectProps": function () {}
};
