/**********************************************************************
 * Extern for MaterialUI
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var MaterialUI = {
  "AppBar": {
    "$$typeof": {},
    "render": function () {}
  },
  "Avatar": {
    "$$typeof": {},
    "render": function () {}
  },
  "Backdrop": {
    "$$typeof": {},
    "render": function () {}
  },
  "Badge": {
    "$$typeof": {},
    "render": function () {}
  },
  "BottomNavigation": {
    "$$typeof": {},
    "render": function () {}
  },
  "BottomNavigationAction": {
    "$$typeof": {},
    "render": function () {}
  },
  "Box": {
    "$$typeof": {},
    "render": function () {}
  },
  "Breadcrumbs": {
    "$$typeof": {},
    "render": function () {}
  },
  "Button": {
    "$$typeof": {},
    "render": function () {}
  },
  "ButtonBase": {
    "$$typeof": {},
    "render": function () {}
  },
  "Card": {
    "$$typeof": {},
    "render": function () {}
  },
  "CardActionArea": {
    "$$typeof": {},
    "render": function () {}
  },
  "CardActions": {
    "$$typeof": {},
    "render": function () {}
  },
  "CardContent": {
    "$$typeof": {},
    "render": function () {}
  },
  "CardHeader": {
    "$$typeof": {},
    "render": function () {}
  },
  "CardMedia": {
    "$$typeof": {},
    "render": function () {}
  },
  "Checkbox": {
    "$$typeof": {},
    "render": function () {}
  },
  "Chip": {
    "$$typeof": {},
    "render": function () {}
  },
  "CircularProgress": {
    "$$typeof": {},
    "render": function () {}
  },
  "ClickAwayListener": function () {},
  "Collapse": {
    "$$typeof": {},
    "muiSupportAuto": {},
    "render": function () {}
  },
  "Container": {
    "$$typeof": {},
    "render": function () {}
  },
  "CssBaseline": function () {},
  "Dialog": {
    "$$typeof": {},
    "render": function () {}
  },
  "DialogActions": {
    "$$typeof": {},
    "render": function () {}
  },
  "DialogContent": {
    "$$typeof": {},
    "render": function () {}
  },
  "DialogContentText": {
    "$$typeof": {},
    "render": function () {}
  },
  "DialogTitle": {
    "$$typeof": {},
    "render": function () {}
  },
  "Divider": {
    "$$typeof": {},
    "render": function () {}
  },
  "Drawer": {
    "$$typeof": {},
    "render": function () {}
  },
  "ExpansionPanel": {
    "$$typeof": {},
    "render": function () {}
  },
  "ExpansionPanelActions": {
    "$$typeof": {},
    "render": function () {}
  },
  "ExpansionPanelDetails": {
    "$$typeof": {},
    "render": function () {}
  },
  "ExpansionPanelSummary": {
    "$$typeof": {},
    "render": function () {}
  },
  "Fab": {
    "$$typeof": {},
    "render": function () {}
  },
  "Fade": {
    "$$typeof": {},
    "render": function () {}
  },
  "FilledInput": {
    "$$typeof": {},
    "muiName": {},
    "render": function () {}
  },
  "FormControl": {
    "$$typeof": {},
    "render": function () {}
  },
  "FormControlLabel": {
    "$$typeof": {},
    "render": function () {}
  },
  "FormGroup": {
    "$$typeof": {},
    "render": function () {}
  },
  "FormHelperText": {
    "$$typeof": {},
    "render": function () {}
  },
  "FormLabel": {
    "$$typeof": {},
    "render": function () {}
  },
  "Grid": {
    "$$typeof": {},
    "render": function () {}
  },
  "GridList": {
    "$$typeof": {},
    "render": function () {}
  },
  "GridListTile": {
    "$$typeof": {},
    "render": function () {}
  },
  "GridListTileBar": {
    "$$typeof": {},
    "render": function () {}
  },
  "Grow": {
    "$$typeof": {},
    "muiSupportAuto": {},
    "render": function () {}
  },
  "Hidden": {
    "defaultProps": {
      "implementation": {},
      "lgDown": {},
      "lgUp": {},
      "mdDown": {},
      "mdUp": {},
      "smDown": {},
      "smUp": {},
      "xlDown": {},
      "xlUp": {},
      "xsDown": {},
      "xsUp": {}
    }
  },
  "Icon": {
    "$$typeof": {},
    "muiName": {},
    "render": function () {}
  },
  "IconButton": {
    "$$typeof": {},
    "render": function () {}
  },
  "Input": {
    "$$typeof": {},
    "muiName": {},
    "render": function () {}
  },
  "InputAdornment": {
    "$$typeof": {},
    "render": function () {}
  },
  "InputBase": {
    "$$typeof": {},
    "render": function () {}
  },
  "InputLabel": {
    "$$typeof": {},
    "render": function () {}
  },
  "LinearProgress": {
    "$$typeof": {},
    "render": function () {}
  },
  "Link": {
    "$$typeof": {},
    "render": function () {}
  },
  "List": {
    "$$typeof": {},
    "render": function () {}
  },
  "ListItem": {
    "$$typeof": {},
    "render": function () {}
  },
  "ListItemAvatar": {
    "$$typeof": {},
    "render": function () {}
  },
  "ListItemIcon": {
    "$$typeof": {},
    "render": function () {}
  },
  "ListItemSecondaryAction": {
    "$$typeof": {},
    "muiName": {},
    "render": function () {}
  },
  "ListItemText": {
    "$$typeof": {},
    "render": function () {}
  },
  "ListSubheader": {
    "$$typeof": {},
    "render": function () {}
  },
  "Menu": {
    "$$typeof": {},
    "render": function () {}
  },
  "MenuItem": {
    "$$typeof": {},
    "render": function () {}
  },
  "MenuList": {
    "$$typeof": {},
    "render": function () {}
  },
  "MobileStepper": {
    "$$typeof": {},
    "render": function () {}
  },
  "Modal": {
    "$$typeof": {},
    "render": function () {}
  },
  "ModalManager": function () {},
  "MuiThemeProvider": function () {},
  "NativeSelect": {
    "$$typeof": {},
    "muiName": {},
    "render": function () {}
  },
  "NoSsr": function () {},
  "OutlinedInput": {
    "$$typeof": {},
    "muiName": {},
    "render": function () {}
  },
  "Paper": {
    "$$typeof": {},
    "render": function () {}
  },
  "Popover": {
    "$$typeof": {},
    "render": function () {}
  },
  "Popper": {
    "$$typeof": {},
    "render": function () {}
  },
  "Portal": {
    "$$typeof": {},
    "defaultProps": {
      "disablePortal": {}
    },
    "render": function () {}
  },
  "Radio": {
    "$$typeof": {},
    "render": function () {}
  },
  "RadioGroup": {
    "$$typeof": {},
    "render": function () {}
  },
  "RootRef": function () {},
  "Select": {
    "$$typeof": {},
    "muiName": {},
    "render": function () {}
  },
  "Slide": {
    "$$typeof": {},
    "render": function () {}
  },
  "Snackbar": {
    "$$typeof": {},
    "render": function () {}
  },
  "SnackbarContent": {
    "$$typeof": {},
    "render": function () {}
  },
  "Step": {
    "$$typeof": {},
    "render": function () {}
  },
  "StepButton": {
    "$$typeof": {},
    "render": function () {}
  },
  "StepConnector": {
    "$$typeof": {},
    "render": function () {}
  },
  "StepContent": {
    "$$typeof": {},
    "render": function () {}
  },
  "StepIcon": {
    "$$typeof": {},
    "render": function () {}
  },
  "StepLabel": {
    "$$typeof": {},
    "muiName": {},
    "render": function () {}
  },
  "Stepper": {
    "$$typeof": {},
    "render": function () {}
  },
  "SvgIcon": {
    "$$typeof": {},
    "muiName": {},
    "render": function () {}
  },
  "SwipeableDrawer": {
    "$$typeof": {},
    "render": function () {}
  },
  "Switch": {
    "$$typeof": {},
    "render": function () {}
  },
  "Tab": {
    "$$typeof": {},
    "render": function () {}
  },
  "Table": {
    "$$typeof": {},
    "render": function () {}
  },
  "TableBody": {
    "$$typeof": {},
    "render": function () {}
  },
  "TableCell": {
    "$$typeof": {},
    "render": function () {}
  },
  "TableFooter": {
    "$$typeof": {},
    "render": function () {}
  },
  "TableHead": {
    "$$typeof": {},
    "render": function () {}
  },
  "TablePagination": {
    "$$typeof": {},
    "render": function () {}
  },
  "TableRow": {
    "$$typeof": {},
    "render": function () {}
  },
  "TableSortLabel": {
    "$$typeof": {},
    "render": function () {}
  },
  "Tabs": {
    "$$typeof": {},
    "render": function () {}
  },
  "TextField": {
    "$$typeof": {},
    "render": function () {}
  },
  "Toolbar": {
    "$$typeof": {},
    "render": function () {}
  },
  "Tooltip": {
    "$$typeof": {},
    "render": function () {}
  },
  "Typography": {
    "$$typeof": {},
    "render": function () {}
  },
  "Zoom": {
    "$$typeof": {},
    "render": function () {}
  },
  "colors": {
    "amber": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "blue": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "blueGrey": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "brown": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "common": {
      "black": {},
      "white": {}
    },
    "cyan": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "deepOrange": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "deepPurple": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "green": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "grey": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "indigo": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "lightBlue": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "lightGreen": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "lime": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "orange": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "pink": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "purple": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "red": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "teal": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    },
    "yellow": {
      "100": {},
      "200": {},
      "300": {},
      "400": {},
      "50": {},
      "500": {},
      "600": {},
      "700": {},
      "800": {},
      "900": {},
      "A100": {},
      "A200": {},
      "A400": {},
      "A700": {}
    }
  },
  "createMuiTheme": function () {},
  "createStyles": function () {},
  "makeStyles": function () {},
  "styled": function () {},
  "withMobileDialog": function () {},
  "withStyles": function () {},
  "withTheme": function () {},
  "withWidth": function () {}
};
MaterialUI.RootRef.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for MaterialUI
/**********************************************************************/