/**********************************************************************
 * Extern for ReactToolTipLite
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactToolTipLite = {
  "default": {
    "defaultProps": {
      "arrow": {},
      "arrowSize": {},
      "background": {},
      "className": {},
      "color": {},
      "direction": {},
      "distance": {},
      "forceDirection": {},
      "hoverDelay": {},
      "padding": {},
      "styles": {},
      "tagName": {},
      "tipContentClassName": {},
      "tipContentHover": {},
      "useDefaultStyles": {},
      "useHover": {}
    },
    "propTypes": {
      "arrow": {
        "isRequired": function () {}
      },
      "arrowSize": {
        "isRequired": function () {}
      },
      "background": {
        "isRequired": function () {}
      },
      "children": function () {},
      "className": {
        "isRequired": function () {}
      },
      "color": {
        "isRequired": function () {}
      },
      "content": function () {},
      "direction": {
        "isRequired": function () {}
      },
      "distance": {
        "isRequired": function () {}
      },
      "eventOff": {
        "isRequired": function () {}
      },
      "eventOn": {
        "isRequired": function () {}
      },
      "eventToggle": {
        "isRequired": function () {}
      },
      "forceDirection": {
        "isRequired": function () {}
      },
      "hoverDelay": {
        "isRequired": function () {}
      },
      "isOpen": {
        "isRequired": function () {}
      },
      "padding": {
        "isRequired": function () {}
      },
      "styles": {
        "isRequired": function () {}
      },
      "tagName": {
        "isRequired": function () {}
      },
      "tipContentClassName": {
        "isRequired": function () {}
      },
      "tipContentHover": {
        "isRequired": function () {}
      },
      "useDefaultStyles": {
        "isRequired": function () {}
      },
      "useHover": {
        "isRequired": function () {}
      }
    }
  }
};
ReactToolTipLite.default.prototype = {
  "forceUpdate": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactToolTipLite
/**********************************************************************/