var Slate = {
  "Block": function() {},
  "Character": function() {},
  "Data": {
    "create": function() {}
  },
  "Document": function() {},
  "Editor": function() {},
  "Html": function() {},
  "Inline": function() {},
  "Mark": function() {},
  "Placeholder": function() {},
  "Plain": {
    "deserialize": function() {},
    "serialize": function() {}
  },
  "Raw": {
    "deserialize": function() {},
    "deserializeBlock": function() {},
    "deserializeDocument": function() {},
    "deserializeInline": function() {},
    "deserializeMark": function() {},
    "deserializeNode": function() {},
    "deserializeRange": function() {},
    "deserializeSelection": function() {},
    "deserializeState": function() {},
    "deserializeText": function() {},
    "serialize": function() {},
    "serializeBlock": function() {},
    "serializeDocument": function() {},
    "serializeInline": function() {},
    "serializeMark": function() {},
    "serializeNode": function() {},
    "serializeRange": function() {},
    "serializeSelection": function() {},
    "serializeState": function() {},
    "serializeText": function() {},
    "tersifyBlock": function() {},
    "tersifyDocument": function() {},
    "tersifyInline": function() {},
    "tersifyMark": function() {},
    "tersifyRange": function() {},
    "tersifySelection": function() {},
    "tersifyState": function() {},
    "tersifyText": function() {},
    "untersifyBlock": function() {},
    "untersifyInline": function() {},
    "untersifyRange": function() {},
    "untersifySelection": function() {},
    "untersifyState": function() {},
    "untersifyText": function() {}
  },
  "Schema": function() {},
  "Selection": function() {},
  "Stack": function() {},
  "State": function() {},
  "Text": function() {},
  "Transforms": function() {},
  "findDOMNode": function() {}
};
