var d3 = {
    "schemeAccent": {},
    "schemeDark2": {},
    "schemePaired": {},
    "schemePastel1": {},
    "schemePastel2": {},
    "schemeSet1": {},
    "schemeSet2": {},
    "schemeSet3": {},
    "interpolateBrBG": function () {},
    "schemeBrBG": {},
    "interpolatePRGn": function () {},
    "schemePRGn": {},
    "interpolatePiYG": function () {},
    "schemePiYG": {},
    "interpolatePuOr": function () {},
    "schemePuOr": {},
    "interpolateRdBu": function () {},
    "schemeRdBu": {},
    "interpolateRdGy": function () {},
    "schemeRdGy": {},
    "interpolateRdYlBu": function () {},
    "schemeRdYlBu": {},
    "interpolateRdYlGn": function () {},
    "schemeRdYlGn": {},
    "interpolateSpectral": function () {},
    "schemeSpectral": {},
    "interpolateBlues": function () {},
    "schemeBlues": {},
    "interpolateGreens": function () {},
    "schemeGreens": {},
    "interpolateGreys": function () {},
    "schemeGreys": {},
    "interpolateOranges": function () {},
    "schemeOranges": {},
    "interpolatePurples": function () {},
    "schemePurples": {},
    "interpolateReds": function () {},
    "schemeReds": {},
    "interpolateBuGn": function () {},
    "schemeBuGn": {},
    "interpolateBuPu": function () {},
    "schemeBuPu": {},
    "interpolateGnBu": function () {},
    "schemeGnBu": {},
    "interpolateOrRd": function () {},
    "schemeOrRd": {},
    "interpolatePuBuGn": function () {},
    "schemePuBuGn": {},
    "interpolatePuBu": function () {},
    "schemePuBu": {},
    "interpolatePuRd": function () {},
    "schemePuRd": {},
    "interpolateRdPu": function () {},
    "schemeRdPu": {},
    "interpolateYlGnBu": function () {},
    "schemeYlGnBu": {},
    "interpolateYlGn": function () {},
    "schemeYlGn": {},
    "interpolateYlOrBr": function () {},
    "schemeYlOrBr": {},
    "interpolateYlOrRd": function () {},
    "schemeYlOrRd": {}
}