var L = {
  "esri": function () {}
};

L.esri.prototype = {
  "VERSION": {},
  "Support": {
    "cors": {},
    "pointerEvents": {}
  },
  "options": {
    "attributionWidthOffset": {}
  },
  "Util": {
    "warn": function () {},
    "cleanUrl": function () {},
    "getUrlParams": function () {},
    "isArcgisOnline": function () {},
    "geojsonTypeToArcGIS": function () {},
    "responseToFeatureCollection": function () {},
    "geojsonToArcGIS": function () {},
    "arcgisToGeoJSON": function () {},
    "boundsToExtent": function () {},
    "extentToBounds": function () {},
    "calcAttributionWidth": function () {},
    "setEsriAttribution": function () {},
    "_setGeometry": function () {},
    "_getAttributionData": function () {},
    "_updateMapAttribution": function () {},
    "_findIdAttributeFromFeature": function () {},
    "_findIdAttributeFromResponse": function () {}
  },
  "get": function () {},
  "post": function () {},
  "request": function () {},
  "Task": function () {},
  "task": function () {},
  "Query": function () {},
  "query": function () {},
  "Find": function () {},
  "find": function () {},
  "Identify": function () {},
  "identify": function () {},
  "IdentifyFeatures": function () {},
  "identifyFeatures": function () {},
  "IdentifyImage": function () {},
  "identifyImage": function () {},
  "Service": function () {},
  "service": function () {},
  "MapService": function () {},
  "mapService": function () {},
  "ImageService": function () {},
  "imageService": function () {},
  "FeatureLayerService": function () {},
  "featureLayerService": function () {},
  "BasemapLayer": function () {},
  "basemapLayer": function () {},
  "TiledMapLayer": function () {},
  "tiledMapLayer": function () {},
  "RasterLayer": function () {},
  "ImageMapLayer": function () {},
  "imageMapLayer": function () {},
  "DynamicMapLayer": function () {},
  "dynamicMapLayer": function () {},
  "FeatureManager": function () {},
  "FeatureLayer": function () {},
  "featureLayer": function () {},
};