// Generated via http://www.dotnetwise.com/Code/Externs/index.html
// Loaded JavaScripts:
// https://cdn.jsdelivr.net/gh/handsontable/handsontable@master/dist/handsontable.full.min.js
// extern the 'Handsontable' object

var Handsontable = {
    "Core": function () {},
    "DefaultSettings": function () {},
    "EventManager": function () {},
    "_getListenersCounter": function () {},
    "packageName": {},
    "buildDate": {},
    "version": {},
    "hooks": {
        "globalBucket": {
            "afterCellMetaReset": function () {},
            "afterChange": function () {},
            "afterChangesObserved": function () {},
            "afterContextMenuDefaultOptions": function () {},
            "beforeContextMenuSetItems": function () {},
            "afterDropdownMenuDefaultOptions": function () {},
            "beforeDropdownMenuSetItems": function () {},
            "afterContextMenuHide": function () {},
            "beforeContextMenuShow": function () {},
            "afterContextMenuShow": function () {},
            "afterCopyLimit": function () {},
            "beforeCreateCol": function () {},
            "afterCreateCol": function () {},
            "beforeCreateRow": function () {},
            "afterCreateRow": function () {},
            "afterDeselect": function () {},
            "afterDestroy": {
                "0": function () {},
                "1": function () {},
                "2": function () {},
                "3": function () {},
                "4": function () {},
                "5": function () {},
                "6": function () {},
                "7": function () {},
                "8": function () {},
                "9": function () {},
                "10": function () {},
                "11": function () {},
                "12": function () {},
                "13": function () {},
                "14": function () {},
                "15": function () {},
                "16": function () {},
                "17": function () {},
                "18": function () {},
                "19": function () {},
                "20": function () {},
                "21": function () {},
                "22": function () {},
                "23": function () {},
                "24": function () {},
                "25": function () {},
                "26": function () {},
                "27": function () {},
                "28": function () {},
                "29": function () {},
                "30": function () {},
                "31": function () {},
                "32": function () {},
                "33": function () {},
                "34": function () {},
                "35": function () {},
                "36": function () {},
                "37": function () {},
                "38": function () {},
                "39": function () {},
                "40": function () {},
                "41": function () {},
                "42": function () {},
                "43": function () {},
                "44": function () {},
                "45": function () {},
                "46": function () {},
                "47": function () {},
                "48": function () {},
                "49": function () {},
                "50": function () {},
                "51": function () {},
                "52": function () {},
                "53": function () {}
            },
            "afterDocumentKeyDown": function () {},
            "afterDrawSelection": function () {},
            "beforeRemoveCellClassNames": function () {},
            "afterGetCellMeta": function () {},
            "afterGetColHeader": function () {},
            "afterGetRowHeader": function () {},
            "afterInit": {
                "0": function () {}
            },
            "afterLoadData": function () {},
            "afterMomentumScroll": function () {},
            "afterOnCellCornerMouseDown": function () {},
            "afterOnCellCornerDblClick": function () {},
            "afterOnCellMouseDown": function () {},
            "afterOnCellMouseUp": function () {},
            "afterOnCellContextMenu": function () {},
            "afterOnCellMouseOver": function () {},
            "afterOnCellMouseOut": function () {},
            "afterRemoveCol": function () {},
            "afterRemoveRow": function () {},
            "afterRender": function () {},
            "beforeRenderer": function () {},
            "afterRenderer": function () {},
            "afterScrollHorizontally": function () {},
            "afterScrollVertically": function () {},
            "afterSelection": function () {},
            "afterSelectionByProp": function () {},
            "afterSelectionEnd": function () {},
            "afterSelectionEndByProp": function () {},
            "afterSetCellMeta": function () {},
            "afterRemoveCellMeta": function () {},
            "afterSetDataAtCell": function () {},
            "afterSetDataAtRowProp": function () {},
            "afterUpdateSettings": {
                "0": function () {}
            },
            "afterValidate": function () {},
            "beforeLanguageChange": function () {},
            "afterLanguageChange": function () {},
            "beforeAutofill": function () {},
            "beforeCellAlignment": function () {},
            "beforeChange": function () {},
            "beforeChangeRender": function () {},
            "beforeDrawBorders": function () {},
            "beforeGetCellMeta": function () {},
            "beforeRemoveCellMeta": function () {},
            "beforeInit": function () {},
            "beforeInitWalkontable": function () {},
            "beforeKeyDown": function () {},
            "beforeOnCellMouseDown": function () {},
            "beforeOnCellMouseUp": function () {},
            "beforeOnCellContextMenu": function () {},
            "beforeOnCellMouseOver": function () {},
            "beforeOnCellMouseOut": function () {},
            "beforeRemoveCol": function () {},
            "beforeRemoveRow": function () {},
            "beforeRender": function () {},
            "beforeSetRangeStartOnly": function () {},
            "beforeSetRangeStart": function () {},
            "beforeSetRangeEnd": function () {},
            "beforeTouchScroll": function () {},
            "beforeValidate": {
                "0": function () {}
            },
            "beforeValueRender": function () {},
            "construct": {
                "0": function () {},
                "1": function () {},
                "2": function () {},
                "3": function () {},
                "4": function () {},
                "5": function () {},
                "6": function () {},
                "7": function () {},
                "8": function () {},
                "9": function () {},
                "10": function () {},
                "11": function () {},
                "12": function () {},
                "13": function () {},
                "14": function () {},
                "15": function () {},
                "16": function () {},
                "17": function () {},
                "18": function () {},
                "19": function () {},
                "20": function () {},
                "21": function () {},
                "22": function () {},
                "23": function () {},
                "24": function () {},
                "25": function () {},
                "26": function () {},
                "27": function () {},
                "28": function () {},
                "29": function () {},
                "30": function () {},
                "31": function () {},
                "32": function () {},
                "33": function () {},
                "34": function () {}
            },
            "init": function () {},
            "modifyCol": function () {},
            "unmodifyCol": function () {},
            "unmodifyRow": function () {},
            "modifyColHeader": function () {},
            "modifyColWidth": function () {},
            "modifyRow": function () {},
            "modifyRowHeader": function () {},
            "modifyRowHeight": function () {},
            "modifyData": function () {},
            "modifyRowData": function () {},
            "modifyGetCellCoords": function () {},
            "persistentStateLoad": function () {},
            "persistentStateReset": function () {},
            "persistentStateSave": function () {},
            "beforeColumnSort": function () {},
            "afterColumnSort": function () {},
            "modifyAutofillRange": function () {},
            "modifyCopyableRange": function () {},
            "beforeCut": function () {},
            "afterCut": function () {},
            "beforeCopy": function () {},
            "afterCopy": function () {},
            "beforePaste": function () {},
            "afterPaste": function () {},
            "beforeColumnMove": function () {},
            "afterColumnMove": function () {},
            "beforeRowMove": function () {},
            "afterRowMove": function () {},
            "beforeColumnResize": function () {},
            "afterColumnResize": function () {},
            "beforeRowResize": function () {},
            "afterRowResize": function () {},
            "afterGetColumnHeaderRenderers": function () {},
            "afterGetRowHeaderRenderers": function () {},
            "beforeStretchingColumnWidth": function () {},
            "beforeFilter": function () {},
            "afterFilter": function () {},
            "modifyColumnHeaderHeight": function () {},
            "beforeUndo": function () {},
            "afterUndo": function () {},
            "beforeRedo": function () {},
            "afterRedo": function () {},
            "modifyRowHeaderWidth": function () {},
            "beforeAutofillInsidePopulate": function () {},
            "modifyTransformStart": function () {},
            "modifyTransformEnd": function () {},
            "afterModifyTransformStart": function () {},
            "afterModifyTransformEnd": function () {},
            "afterViewportRowCalculatorOverride": function () {},
            "afterViewportColumnCalculatorOverride": function () {},
            "afterPluginsInitialized": function () {},
            "skipLengthCache": function () {},
            "beforeHideRows": function () {},
            "afterHideRows": function () {},
            "beforeUnhideRows": function () {},
            "afterUnhideRows": function () {},
            "beforeHideColumns": function () {},
            "afterHideColumns": function () {},
            "beforeUnhideColumns": function () {},
            "afterUnhideColumns": function () {},
            "beforeTrimRow": function () {},
            "afterTrimRow": function () {},
            "beforeUntrimRow": function () {},
            "afterUntrimRow": function () {},
            "beforeDropdownMenuShow": function () {},
            "afterDropdownMenuShow": function () {},
            "afterDropdownMenuHide": function () {},
            "hiddenRow": function () {},
            "hiddenColumn": function () {},
            "beforeAddChild": function () {},
            "afterAddChild": function () {},
            "beforeDetachChild": function () {},
            "afterDetachChild": function () {},
            "afterBeginEditing": function () {},
            "beforeMergeCells": function () {},
            "afterMergeCells": function () {},
            "beforeUnmergeCells": function () {},
            "afterUnmergeCells": function () {},
            "afterListen": function () {},
            "afterUnlisten": function () {},
            "afterRefreshDimensions": function () {},
            "beforeRefreshDimensions": function () {}
        }
    },
    "__GhostTable": function () {},
    "helper": {
        "to2dArray": function () {},
        "extendArray": function () {},
        "pivot": function () {},
        "arrayReduce": function () {},
        "arrayFilter": function () {},
        "arrayMap": function () {},
        "arrayEach": function () {},
        "arraySum": function () {},
        "arrayMax": function () {},
        "arrayMin": function () {},
        "arrayAvg": function () {},
        "arrayFlatten": function () {},
        "arrayUnique": function () {},
        "setBrowserMeta": function () {},
        "isChrome": function () {},
        "isEdge": function () {},
        "isIE": function () {},
        "isIE8": function () {},
        "isIE9": function () {},
        "isMSBrowser": function () {},
        "isMobileBrowser": function () {},
        "isSafari": function () {},
        "spreadsheetColumnLabel": function () {},
        "spreadsheetColumnIndex": function () {},
        "createSpreadsheetData": function () {},
        "createSpreadsheetObjectData": function () {},
        "createEmptySpreadsheetData": function () {},
        "translateRowsToColumns": function () {},
        "cellMethodLookupFactory": function () {},
        "getNormalizedDate": function () {},
        "requestAnimationFrame": function () {},
        "isClassListSupported": function () {},
        "isTextContentSupported": function () {},
        "isGetComputedStyleSupported": function () {},
        "cancelAnimationFrame": function () {},
        "isTouchSupported": function () {},
        "isWebComponentSupportedNatively": function () {},
        "hasCaptionProblem": function () {},
        "getComparisonFunction": function () {},
        "isPassiveEventSupported": function () {},
        "isFunction": function () {},
        "throttle": function () {},
        "throttleAfterHits": function () {},
        "debounce": function () {},
        "pipe": function () {},
        "partial": function () {},
        "curry": function () {},
        "curryRight": function () {},
        "stringify": function () {},
        "isDefined": function () {},
        "isUndefined": function () {},
        "isEmpty": function () {},
        "isRegExp": function () {},
        "isNumeric": function () {},
        "rangeEach": function () {},
        "rangeEachReverse": function () {},
        "valueAccordingPercent": function () {},
        "duckSchema": function () {},
        "inherit": function () {},
        "extend": function () {},
        "deepExtend": function () {},
        "deepClone": function () {},
        "clone": function () {},
        "mixin": function () {},
        "isObjectEqual": function () {},
        "isObject": function () {},
        "defineGetter": function () {},
        "objectEach": function () {},
        "getProperty": function () {},
        "deepObjectSize": function () {},
        "createObjectPropListener": function () {},
        "hasOwnProperty": function () {},
        "columnFactory": function () {},
        "toUpperCaseFirst": function () {},
        "equalsIgnoreCase": function () {},
        "randomString": function () {},
        "isPercentValue": function () {},
        "substitute": function () {},
        "stripTags": function () {},
        "isPrintableChar": function () {},
        "isMetaKey": function () {},
        "isCtrlKey": function () {},
        "isCtrlMetaKey": function () {},
        "isKey": function () {},
        "KEY_CODES": {
            "MOUSE_LEFT": {},
            "MOUSE_RIGHT": {},
            "MOUSE_MIDDLE": {},
            "BACKSPACE": {},
            "COMMA": {},
            "INSERT": {},
            "DELETE": {},
            "END": {},
            "ENTER": {},
            "ESCAPE": {},
            "CONTROL": {},
            "COMMAND_LEFT": {},
            "COMMAND_RIGHT": {},
            "COMMAND_FIREFOX": {},
            "ALT": {},
            "HOME": {},
            "PAGE_DOWN": {},
            "PAGE_UP": {},
            "PERIOD": {},
            "SPACE": {},
            "SHIFT": {},
            "CAPS_LOCK": {},
            "TAB": {},
            "ARROW_RIGHT": {},
            "ARROW_LEFT": {},
            "ARROW_UP": {},
            "ARROW_DOWN": {},
            "F1": {},
            "F2": {},
            "F3": {},
            "F4": {},
            "F5": {},
            "F6": {},
            "F7": {},
            "F8": {},
            "F9": {},
            "F10": {},
            "F11": {},
            "F12": {},
            "A": {},
            "C": {},
            "D": {},
            "F": {},
            "L": {},
            "O": {},
            "P": {},
            "S": {},
            "V": {},
            "X": {}
        },
        "instanceToHTML": function () {},
        "htmlToGridSettings": function () {}
    },
    "dom": {
        "getParent": function () {},
        "closest": function () {},
        "closestDown": function () {},
        "isChildOf": function () {},
        "isChildOfWebComponentTable": function () {},
        "polymerWrap": function () {},
        "polymerUnwrap": function () {},
        "index": function () {},
        "overlayContainsElement": function () {},
        "hasClass": function () {},
        "addClass": function () {},
        "removeClass": function () {},
        "removeTextNodes": function () {},
        "empty": function () {},
        "fastInnerHTML": function () {},
        "fastInnerText": function () {},
        "isVisible": function () {},
        "offset": function () {},
        "getWindowScrollTop": function () {},
        "getWindowScrollLeft": function () {},
        "getScrollTop": function () {},
        "getScrollLeft": function () {},
        "getScrollableElement": function () {},
        "getTrimmingContainer": function () {},
        "getStyle": function () {},
        "getComputedStyle": function () {},
        "outerWidth": function () {},
        "outerHeight": function () {},
        "innerHeight": function () {},
        "innerWidth": function () {},
        "addEvent": function () {},
        "removeEvent": function () {},
        "getCaretPosition": function () {},
        "getSelectionEndPosition": function () {},
        "getSelectionText": function () {},
        "clearTextSelection": function () {},
        "setCaretPosition": function () {},
        "getScrollbarWidth": function () {},
        "hasVerticalScrollbar": function () {},
        "hasHorizontalScrollbar": function () {},
        "setOverlayPosition": function () {},
        "getCssTransform": function () {},
        "resetCssTransform": function () {},
        "isInput": function () {},
        "isOutsideInput": function () {},
        "selectElementIfAllowed": function () {},
        "HTML_CHARACTERS": function () {},
        "stopImmediatePropagation": function () {},
        "isImmediatePropagationStopped": function () {},
        "stopPropagation": function () {},
        "pageX": function () {},
        "pageY": function () {},
        "isRightClick": function () {},
        "isLeftClick": function () {}
    },
    "cellTypes": {
        "autocomplete": {
            "editor": function () {},
            "renderer": function () {},
            "validator": function () {}
        },
        "checkbox": {
            "editor": function () {},
            "renderer": function () {}
        },
        "date": {
            "editor": function () {},
            "renderer": function () {},
            "validator": function () {}
        },
        "dropdown": {
            "editor": function () {},
            "renderer": function () {},
            "validator": function () {}
        },
        "handsontable": {
            "editor": function () {},
            "renderer": function () {}
        },
        "numeric": {
            "editor": function () {},
            "renderer": function () {},
            "validator": function () {},
            "dataType": {}
        },
        "password": {
            "editor": function () {},
            "renderer": function () {},
            "copyable": {}
        },
        "text": {
            "editor": function () {},
            "renderer": function () {}
        },
        "time": {
            "editor": function () {},
            "renderer": function () {},
            "validator": function () {}
        },
        "registerCellType": function () {},
        "getCellType": function () {}
    },
    "editors": {
        "BaseEditor": function () {},
        "AutocompleteEditor": function () {},
        "CheckboxEditor": function () {},
        "DateEditor": function () {},
        "DropdownEditor": function () {},
        "HandsontableEditor": function () {},
        "NumericEditor": function () {},
        "PasswordEditor": function () {},
        "SelectEditor": function () {},
        "TextEditor": function () {},
        "TimeEditor": function () {},
        "registerEditor": function () {},
        "getEditor": function () {}
    },
    "renderers": {
        "cellDecorator": function () {},
        "BaseRenderer": function () {},
        "AutocompleteRenderer": function () {},
        "CheckboxRenderer": function () {},
        "HtmlRenderer": function () {},
        "NumericRenderer": function () {},
        "PasswordRenderer": function () {},
        "TextRenderer": function () {},
        "DateRenderer": function () {},
        "DropdownRenderer": function () {},
        "HandsontableRenderer": function () {},
        "TimeRenderer": function () {},
        "registerRenderer": function () {},
        "getRenderer": function () {}
    },
    "validators": {
        "AutocompleteValidator": function () {},
        "DateValidator": function () {},
        "NumericValidator": function () {},
        "TimeValidator": function () {},
        "DropdownValidator": function () {},
        "registerValidator": function () {},
        "getValidator": function () {}
    },
    "plugins": {
        "__esModule": {},
        "PersistentState": function () {},
        "AutoColumnSize": function () {},
        "AutoFill": function () {},
        "AutoRowSize": function () {},
        "ColumnSorting": function () {},
        "Comments": function () {},
        "ContextMenu": function () {},
        "CopyPaste": function () {},
        "CustomBorders": function () {},
        "DragToScroll": function () {},
        "ManualColumnFreeze": function () {},
        "ManualColumnMove": function () {},
        "ManualColumnResize": function () {},
        "ManualRowMove": function () {},
        "ManualRowResize": function () {},
        "MergeCells": function () {},
        "MultipleSelectionHandles": function () {},
        "ObserveChanges": function () {},
        "Search": function () {},
        "TouchScroll": function () {},
        "UndoRedo": function () {},
        "BasePlugin": function () {},
        "BindRowsWithHeaders": function () {},
        "CollapsibleColumns": function () {},
        "ColumnSummary": function () {},
        "DropdownMenu": function () {},
        "ExportFile": function () {},
        "MultiColumnSorting": function () {},
        "Filters": function () {},
        "Formulas": function () {},
        "GanttChart": function () {},
        "HeaderTooltips": function () {},
        "NestedHeaders": function () {},
        "NestedRows": function () {},
        "HiddenColumns": function () {},
        "HiddenRows": function () {},
        "TrimRows": function () {},
        "registerPlugin": function () {}
    },
    "languages": {
        "dictionaryKeys": {
            "__esModule": {},
            "CONTEXT_MENU_ITEMS_NAMESPACE": {},
            "CONTEXTMENU_ITEMS_NO_ITEMS": {},
            "CONTEXTMENU_ITEMS_ROW_ABOVE": {},
            "CONTEXTMENU_ITEMS_ROW_BELOW": {},
            "CONTEXTMENU_ITEMS_INSERT_LEFT": {},
            "CONTEXTMENU_ITEMS_INSERT_RIGHT": {},
            "CONTEXTMENU_ITEMS_REMOVE_ROW": {},
            "CONTEXTMENU_ITEMS_REMOVE_COLUMN": {},
            "CONTEXTMENU_ITEMS_UNDO": {},
            "CONTEXTMENU_ITEMS_REDO": {},
            "CONTEXTMENU_ITEMS_READ_ONLY": {},
            "CONTEXTMENU_ITEMS_CLEAR_COLUMN": {},
            "CONTEXTMENU_ITEMS_COPY": {},
            "CONTEXTMENU_ITEMS_CUT": {},
            "CONTEXTMENU_ITEMS_FREEZE_COLUMN": {},
            "CONTEXTMENU_ITEMS_UNFREEZE_COLUMN": {},
            "CONTEXTMENU_ITEMS_MERGE_CELLS": {},
            "CONTEXTMENU_ITEMS_UNMERGE_CELLS": {},
            "CONTEXTMENU_ITEMS_ADD_COMMENT": {},
            "CONTEXTMENU_ITEMS_EDIT_COMMENT": {},
            "CONTEXTMENU_ITEMS_REMOVE_COMMENT": {},
            "CONTEXTMENU_ITEMS_READ_ONLY_COMMENT": {},
            "CONTEXTMENU_ITEMS_ALIGNMENT": {},
            "CONTEXTMENU_ITEMS_ALIGNMENT_LEFT": {},
            "CONTEXTMENU_ITEMS_ALIGNMENT_CENTER": {},
            "CONTEXTMENU_ITEMS_ALIGNMENT_RIGHT": {},
            "CONTEXTMENU_ITEMS_ALIGNMENT_JUSTIFY": {},
            "CONTEXTMENU_ITEMS_ALIGNMENT_TOP": {},
            "CONTEXTMENU_ITEMS_ALIGNMENT_MIDDLE": {},
            "CONTEXTMENU_ITEMS_ALIGNMENT_BOTTOM": {},
            "CONTEXTMENU_ITEMS_BORDERS": {},
            "CONTEXTMENU_ITEMS_BORDERS_TOP": {},
            "CONTEXTMENU_ITEMS_BORDERS_RIGHT": {},
            "CONTEXTMENU_ITEMS_BORDERS_BOTTOM": {},
            "CONTEXTMENU_ITEMS_BORDERS_LEFT": {},
            "CONTEXTMENU_ITEMS_REMOVE_BORDERS": {},
            "CONTEXTMENU_ITEMS_NESTED_ROWS_INSERT_CHILD": {},
            "CONTEXTMENU_ITEMS_NESTED_ROWS_DETACH_CHILD": {},
            "CONTEXTMENU_ITEMS_HIDE_COLUMN": {},
            "CONTEXTMENU_ITEMS_SHOW_COLUMN": {},
            "CONTEXTMENU_ITEMS_HIDE_ROW": {},
            "CONTEXTMENU_ITEMS_SHOW_ROW": {},
            "FILTERS_NAMESPACE": {},
            "FILTERS_CONDITIONS_NAMESPACE": {},
            "FILTERS_CONDITIONS_NONE": {},
            "FILTERS_CONDITIONS_EMPTY": {},
            "FILTERS_CONDITIONS_NOT_EMPTY": {},
            "FILTERS_CONDITIONS_EQUAL": {},
            "FILTERS_CONDITIONS_NOT_EQUAL": {},
            "FILTERS_CONDITIONS_BEGINS_WITH": {},
            "FILTERS_CONDITIONS_ENDS_WITH": {},
            "FILTERS_CONDITIONS_CONTAINS": {},
            "FILTERS_CONDITIONS_NOT_CONTAIN": {},
            "FILTERS_CONDITIONS_BY_VALUE": {},
            "FILTERS_CONDITIONS_GREATER_THAN": {},
            "FILTERS_CONDITIONS_GREATER_THAN_OR_EQUAL": {},
            "FILTERS_CONDITIONS_LESS_THAN": {},
            "FILTERS_CONDITIONS_LESS_THAN_OR_EQUAL": {},
            "FILTERS_CONDITIONS_BETWEEN": {},
            "FILTERS_CONDITIONS_NOT_BETWEEN": {},
            "FILTERS_CONDITIONS_AFTER": {},
            "FILTERS_CONDITIONS_BEFORE": {},
            "FILTERS_CONDITIONS_TODAY": {},
            "FILTERS_CONDITIONS_TOMORROW": {},
            "FILTERS_CONDITIONS_YESTERDAY": {},
            "FILTERS_DIVS_FILTER_BY_CONDITION": {},
            "FILTERS_DIVS_FILTER_BY_VALUE": {},
            "FILTERS_LABELS_CONJUNCTION": {},
            "FILTERS_LABELS_DISJUNCTION": {},
            "FILTERS_VALUES_BLANK_CELLS": {},
            "FILTERS_BUTTONS_SELECT_ALL": {},
            "FILTERS_BUTTONS_CLEAR": {},
            "FILTERS_BUTTONS_OK": {},
            "FILTERS_BUTTONS_CANCEL": {},
            "FILTERS_BUTTONS_PLACEHOLDER_SEARCH": {},
            "FILTERS_BUTTONS_PLACEHOLDER_VALUE": {},
            "FILTERS_BUTTONS_PLACEHOLDER_SECOND_VALUE": {}
        },
        "getLanguageDictionary": function () {},
        "getLanguagesDictionaries": function () {},
        "registerLanguageDictionary": function () {},
        "getTranslatedPhrase": function () {}
    }
}
