/**********************************************************************
 * Extern for ReactWindow
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactWindow = {
  "FixedSizeGrid": {
    "defaultProps": {
      "direction": {},
      "itemData": {},
      "useIsScrolling": {}
    },
    "getDerivedStateFromProps": function () { }
  },
  "FixedSizeList": {
    "defaultProps": {
      "direction": {},
      "itemData": {},
      "layout": {},
      "overscanCount": {},
      "useIsScrolling": {}
    },
    "getDerivedStateFromProps": function () { }
  },
  "VariableSizeGrid": {
    "defaultProps": {
      "direction": {},
      "itemData": {},
      "useIsScrolling": {}
    },
    "getDerivedStateFromProps": function () { }
  },
  "VariableSizeList": {
    "defaultProps": {
      "direction": {},
      "itemData": {},
      "layout": {},
      "overscanCount": {},
      "useIsScrolling": {}
    },
    "getDerivedStateFromProps": function () { }
  },
  "areEqual": function () { },
  "shouldComponentUpdate": function () { }
};
ReactWindow.FixedSizeGrid.prototype = {
  "_callPropsCallbacks": function () { },
  "_getHorizontalRangeToRender": function () { },
  "_getVerticalRangeToRender": function () { },
  "componentDidMount": function () { },
  "componentDidUpdate": function () { },
  "componentWillUnmount": function () { },
  "constructor": function () { },
  "forceUpdate": function () { },
  "isPureReactComponent": function () { },
  "isReactComponent": function () { },
  "render": function () { },
  "scrollTo": function () { },
  "scrollToItem": function () { },
  "setState": function () { }
};
ReactWindow.FixedSizeList.prototype = {
  "_callPropsCallbacks": function () { },
  "_getRangeToRender": function () { },
  "componentDidMount": function () { },
  "componentDidUpdate": function () { },
  "componentWillUnmount": function () { },
  "constructor": function () { },
  "forceUpdate": function () { },
  "isPureReactComponent": function () { },
  "isReactComponent": function () { },
  "render": function () { },
  "scrollTo": function () { },
  "scrollToItem": function () { },
  "setState": function () { }
};
ReactWindow.VariableSizeGrid.prototype = {
  "_callPropsCallbacks": function () { },
  "_getHorizontalRangeToRender": function () { },
  "_getVerticalRangeToRender": function () { },
  "componentDidMount": function () { },
  "componentDidUpdate": function () { },
  "componentWillUnmount": function () { },
  "constructor": function () { },
  "forceUpdate": function () { },
  "isPureReactComponent": function () { },
  "isReactComponent": function () { },
  "render": function () { },
  "scrollTo": function () { },
  "scrollToItem": function () { },
  "setState": function () { }
};
ReactWindow.VariableSizeList.prototype = {
  "_callPropsCallbacks": function () { },
  "_getRangeToRender": function () { },
  "componentDidMount": function () { },
  "componentDidUpdate": function () { },
  "componentWillUnmount": function () { },
  "constructor": function () { },
  "forceUpdate": function () { },
  "isPureReactComponent": function () { },
  "isReactComponent": function () { },
  "render": function () { },
  "scrollTo": function () { },
  "scrollToItem": function () { },
  "setState": function () { }
};
/**********************************************************************
 * End Generated Extern for ReactWindow
/**********************************************************************/