/**********************************************************************
 * Extern for Vue
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Vue = {
  "cid": {},
  "compile": function () {},
  "component": function () {},
  "delete": function () {},
  "directive": function () {},
  "extend": function () {},
  "filter": function () {},
  "mixin": function () {},
  "nextTick": function () {},
  "options": {
    "_base": {
      "cid": {},
      "compile": function () {},
      "component": function () {},
      "delete": function () {},
      "directive": function () {},
      "extend": function () {},
      "filter": function () {},
      "mixin": function () {},
      "nextTick": function () {},
      "options": {},
      "set": function () {},
      "use": function () {},
      "util": {
        "defineReactive": function () {},
        "extend": function () {},
        "mergeOptions": function () {},
        "warn": function () {}
      },
      "version": {}
    },
    "components": {
      "KeepAlive": {
        "abstract": {},
        "created": function () {},
        "destroyed": function () {},
        "name": {},
        "props": {
          "exclude": {},
          "include": {},
          "max": {}
        },
        "render": function () {},
        "watch": {
          "exclude": function () {},
          "include": function () {}
        }
      },
      "Transition": {
        "abstract": {},
        "name": {},
        "props": {
          "appear": function () {},
          "appearActiveClass": function () {},
          "appearClass": function () {},
          "appearToClass": function () {},
          "css": function () {},
          "duration": {},
          "enterActiveClass": function () {},
          "enterClass": function () {},
          "enterToClass": function () {},
          "leaveActiveClass": function () {},
          "leaveClass": function () {},
          "leaveToClass": function () {},
          "mode": function () {},
          "name": function () {},
          "type": function () {}
        },
        "render": function () {}
      },
      "TransitionGroup": {
        "beforeUpdate": function () {},
        "methods": {
          "hasMove": function () {}
        },
        "props": {
          "appear": function () {},
          "appearActiveClass": function () {},
          "appearClass": function () {},
          "appearToClass": function () {},
          "css": function () {},
          "duration": {},
          "enterActiveClass": function () {},
          "enterClass": function () {},
          "enterToClass": function () {},
          "leaveActiveClass": function () {},
          "leaveClass": function () {},
          "leaveToClass": function () {},
          "moveClass": function () {},
          "name": function () {},
          "tag": function () {},
          "type": function () {}
        },
        "render": function () {},
        "updated": function () {}
      }
    },
    "directives": {
      "model": {
        "componentUpdated": function () {},
        "inserted": function () {}
      },
      "show": {
        "bind": function () {},
        "unbind": function () {},
        "update": function () {}
      }
    },
    "filters": {}
  },
  "set": function () {},
  "use": function () {},
  "util": {
    "defineReactive": function () {},
    "extend": function () {},
    "mergeOptions": function () {},
    "warn": function () {}
  },
  "version": {}
};
Vue.prototype = {
  "$delete": function () {},
  "$destroy": function () {},
  "$emit": function () {},
  "$forceUpdate": function () {},
  "$mount": function () {},
  "$nextTick": function () {},
  "$off": function () {},
  "$on": function () {},
  "$once": function () {},
  "$set": function () {},
  "$watch": function () {},
  "__patch__": function () {},
  "_b": function () {},
  "_e": function () {},
  "_f": function () {},
  "_g": function () {},
  "_i": function () {},
  "_init": function () {},
  "_k": function () {},
  "_l": function () {},
  "_m": function () {},
  "_n": function () {},
  "_o": function () {},
  "_q": function () {},
  "_render": function () {},
  "_s": function () {},
  "_t": function () {},
  "_u": function () {},
  "_update": function () {},
  "_v": function () {}
};
Vue.options._base.prototype = {
  "$delete": function () {},
  "$destroy": function () {},
  "$emit": function () {},
  "$forceUpdate": function () {},
  "$mount": function () {},
  "$nextTick": function () {},
  "$off": function () {},
  "$on": function () {},
  "$once": function () {},
  "$set": function () {},
  "$watch": function () {},
  "__patch__": function () {},
  "_b": function () {},
  "_e": function () {},
  "_f": function () {},
  "_g": function () {},
  "_i": function () {},
  "_init": function () {},
  "_k": function () {},
  "_l": function () {},
  "_m": function () {},
  "_n": function () {},
  "_o": function () {},
  "_q": function () {},
  "_render": function () {},
  "_s": function () {},
  "_t": function () {},
  "_u": function () {},
  "_update": function () {},
  "_v": function () {}
};
/**********************************************************************
 * End Generated Extern for Vue
/**********************************************************************/