/**********************************************************************
 * Extern for humane
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var humane = {
  "queue": {},
  "baseCls": {},
  "addnCls": {},
  "timeout": {},
  "waitForMove": {},
  "clickToClose": {},
  "timeoutAfterMove": {},
  "container": {},
  "el": {},
  "removeEvent": function () {},
  "transEvent": function () {},
  "constructor": function () {},
  "_setupEl": function () {},
  "_afterTimeout": function () {},
  "_run": function () {},
  "_setOpacity": function () {},
  "_showMsg": function () {},
  "_hideMsg": function () {},
  "_afterAnimation": function () {},
  "remove": function () {},
  "log": function () {},
  "spawn": function () {},
  "create": function () {}
};
humane.constructor.prototype = {
  "constructor": function () {},
  "_setupEl": function () {},
  "_afterTimeout": function () {},
  "_run": function () {},
  "_setOpacity": function () {},
  "_showMsg": function () {},
  "_hideMsg": function () {},
  "_afterAnimation": function () {},
  "remove": function () {},
  "log": function () {},
  "spawn": function () {},
  "create": function () {}
};
/**********************************************************************
 * End Generated Extern for humane
/**********************************************************************/
