/**********************************************************************
 * Extern for feathers
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var feathers = {
  "authentication": {
    "default": function () {},
    "defaults": {
      "cookie": {},
      "entity": {},
      "header": {},
      "jwtStrategy": {},
      "path": {},
      "service": {},
      "storageKey": {},
      "timeout": {}
    }
  },
  "default": {
    "authentication": {
      "default": function () {},
      "defaults": {
        "cookie": {},
        "entity": {},
        "header": {},
        "jwtStrategy": {},
        "path": {},
        "service": {},
        "storageKey": {},
        "timeout": {}
      }
    },
    "default": function () {},
    "errors": {
      "400": function () {},
      "401": function () {},
      "402": function () {},
      "403": function () {},
      "404": function () {},
      "405": function () {},
      "406": function () {},
      "408": function () {},
      "409": function () {},
      "411": function () {},
      "422": function () {},
      "429": function () {},
      "500": function () {},
      "501": function () {},
      "502": function () {},
      "503": function () {},
      "BadGateway": function () {},
      "BadRequest": function () {},
      "Conflict": function () {},
      "FeathersError": function () {},
      "Forbidden": function () {},
      "GeneralError": function () {},
      "LengthRequired": function () {},
      "MethodNotAllowed": function () {},
      "NotAcceptable": function () {},
      "NotAuthenticated": function () {},
      "NotFound": function () {},
      "NotImplemented": function () {},
      "PaymentError": function () {},
      "Timeout": function () {},
      "TooManyRequests": function () {},
      "Unavailable": function () {},
      "Unprocessable": function () {},
      "convert": function () {}
    },
    "primus": {
      "default": function () {}
    },
    "rest": {
      "default": function () {}
    },
    "socketio": {
      "default": function () {}
    },
    "version": {}
  },
  "errors": {
    "400": function () {},
    "401": function () {},
    "402": function () {},
    "403": function () {},
    "404": function () {},
    "405": function () {},
    "406": function () {},
    "408": function () {},
    "409": function () {},
    "411": function () {},
    "422": function () {},
    "429": function () {},
    "500": function () {},
    "501": function () {},
    "502": function () {},
    "503": function () {},
    "BadGateway": function () {},
    "BadRequest": function () {},
    "Conflict": function () {},
    "FeathersError": function () {},
    "Forbidden": function () {},
    "GeneralError": function () {},
    "LengthRequired": function () {},
    "MethodNotAllowed": function () {},
    "NotAcceptable": function () {},
    "NotAuthenticated": function () {},
    "NotFound": function () {},
    "NotImplemented": function () {},
    "PaymentError": function () {},
    "Timeout": function () {},
    "TooManyRequests": function () {},
    "Unavailable": function () {},
    "Unprocessable": function () {},
    "convert": function () {}
  },
  "primus": {
    "default": function () {}
  },
  "rest": {
    "default": function () {}
  },
  "socketio": {
    "default": function () {}
  },
  "version": {}
};
/**********************************************************************
 * End Generated Extern for feathers
/**********************************************************************/
