/**********************************************************************
 * Extern for ReactDates
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactDates = {
  "DateRangePicker": {
    "propTypes": {
      "startDate": {
        "isRequired": function () {}
      },
      "endDate": {
        "isRequired": function () {}
      },
      "focusedInput": {
        "isRequired": function () {}
      },
      "minimumNights": {
        "isRequired": function () {}
      },
      "isDayBlocked": {
        "isRequired": function () {}
      },
      "isOutsideRange": {
        "isRequired": function () {}
      },
      "enableOutsideDays": {
        "isRequired": function () {}
      },
      "reopenPickerOnClearDates": {
        "isRequired": function () {}
      },
      "numberOfMonths": {
        "isRequired": function () {}
      },
      "showClearDates": {
        "isRequired": function () {}
      },
      "disabled": {
        "isRequired": function () {}
      },
      "required": {
        "isRequired": function () {}
      },
      "orientation": {
        "isRequired": function () {}
      },
      "anchorDirection": {
        "isRequired": function () {}
      },
      "withPortal": {
        "isRequired": function () {}
      },
      "withFullScreenPortal": {
        "isRequired": function () {}
      },
      "startDateId": {
        "isRequired": function () {}
      },
      "startDatePlaceholderText": {
        "isRequired": function () {}
      },
      "endDateId": {
        "isRequired": function () {}
      },
      "endDatePlaceholderText": {
        "isRequired": function () {}
      },
      "initialVisibleMonth": {
        "isRequired": function () {}
      },
      "onDatesChange": {
        "isRequired": function () {}
      },
      "onFocusChange": {
        "isRequired": function () {}
      },
      "onPrevMonthClick": {
        "isRequired": function () {}
      },
      "onNextMonthClick": {
        "isRequired": function () {}
      },
      "displayFormat": {
        "isRequired": function () {}
      },
      "monthFormat": {
        "isRequired": function () {}
      },
      "phrases": {
        "isRequired": function () {}
      }
    },
    "defaultProps": {
      "startDateId": {},
      "endDateId": {},
      "focusedInput": {},
      "minimumNights": {},
      "isDayBlocked": function () {},
      "disabledDays": {},
      "isOutsideRange": function () {},
      "enableOutsideDays": {},
      "numberOfMonths": {},
      "showClearDates": {},
      "disabled": {},
      "required": {},
      "reopenPickerOnClearDates": {},
      "initialVisibleMonth": function () {},
      "orientation": {},
      "anchorDirection": {},
      "withPortal": {},
      "withFullScreenPortal": {},
      "onDatesChange": function () {},
      "onFocusChange": function () {},
      "onPrevMonthClick": function () {},
      "onNextMonthClick": function () {},
      "displayFormat": function () {},
      "monthFormat": {},
      "phrases": {
        "closeDatePicker": {},
        "clearDates": {}
      }
    }
  },
  "SingleDatePicker": {
    "propTypes": {
      "id": function () {},
      "placeholder": {
        "isRequired": function () {}
      },
      "date": {
        "isRequired": function () {}
      },
      "focused": {
        "isRequired": function () {}
      },
      "disabled": {
        "isRequired": function () {}
      },
      "required": {
        "isRequired": function () {}
      },
      "onDateChange": {
        "isRequired": function () {}
      },
      "onFocusChange": {
        "isRequired": function () {}
      },
      "isDayBlocked": {
        "isRequired": function () {}
      },
      "isOutsideRange": {
        "isRequired": function () {}
      },
      "enableOutsideDays": {
        "isRequired": function () {}
      },
      "numberOfMonths": {
        "isRequired": function () {}
      },
      "orientation": {
        "isRequired": function () {}
      },
      "initialVisibleMonth": {
        "isRequired": function () {}
      },
      "anchorDirection": {
        "isRequired": function () {}
      },
      "withPortal": {
        "isRequired": function () {}
      },
      "withFullScreenPortal": {
        "isRequired": function () {}
      },
      "onPrevMonthClick": {
        "isRequired": function () {}
      },
      "onNextMonthClick": {
        "isRequired": function () {}
      },
      "displayFormat": {
        "isRequired": function () {}
      },
      "monthFormat": {
        "isRequired": function () {}
      },
      "phrases": {
        "isRequired": function () {}
      }
    },
    "defaultProps": {
      "date": {},
      "focused": {},
      "disabled": {},
      "required": {},
      "onDateChange": function () {},
      "onFocusChange": function () {},
      "isDayBlocked": function () {},
      "disabledDays": {},
      "isOutsideRange": function () {},
      "enableOutsideDays": {},
      "numberOfMonths": {},
      "orientation": {},
      "anchorDirection": {},
      "withPortal": {},
      "withFullScreenPortal": {},
      "initialVisibleMonth": function () {},
      "onPrevMonthClick": function () {},
      "onNextMonthClick": function () {},
      "displayFormat": function () {},
      "monthFormat": {},
      "phrases": {
        "closeDatePicker": {}
      }
    }
  },
  "DateRangePickerInput": {
    "propTypes": {
      "startDateId": {
        "isRequired": function () {}
      },
      "startDatePlaceholderText": {
        "isRequired": function () {}
      },
      "endDateId": {
        "isRequired": function () {}
      },
      "endDatePlaceholderText": {
        "isRequired": function () {}
      },
      "onStartDateFocus": {
        "isRequired": function () {}
      },
      "onEndDateFocus": {
        "isRequired": function () {}
      },
      "onStartDateChange": {
        "isRequired": function () {}
      },
      "onEndDateChange": {
        "isRequired": function () {}
      },
      "onStartDateShiftTab": {
        "isRequired": function () {}
      },
      "onEndDateTab": {
        "isRequired": function () {}
      },
      "onClearDates": {
        "isRequired": function () {}
      },
      "startDate": {
        "isRequired": function () {}
      },
      "endDate": {
        "isRequired": function () {}
      },
      "isStartDateFocused": {
        "isRequired": function () {}
      },
      "isEndDateFocused": {
        "isRequired": function () {}
      },
      "showClearDates": {
        "isRequired": function () {}
      },
      "disabled": {
        "isRequired": function () {}
      },
      "required": {
        "isRequired": function () {}
      },
      "showCaret": {
        "isRequired": function () {}
      },
      "phrases": {
        "isRequired": function () {}
      }
    },
    "defaultProps": {
      "startDateId": {},
      "endDateId": {},
      "startDatePlaceholderText": {},
      "endDatePlaceholderText": {},
      "onStartDateFocus": function () {},
      "onEndDateFocus": function () {},
      "onStartDateChange": function () {},
      "onEndDateChange": function () {},
      "onStartDateShiftTab": function () {},
      "onEndDateTab": function () {},
      "onClearDates": function () {},
      "isStartDateFocused": {},
      "isEndDateFocused": {},
      "showClearDates": {},
      "disabled": {},
      "showCaret": {},
      "phrases": {
        "clearDates": {}
      }
    }
  },
  "SingleDatePickerInput": {
    "propTypes": {
      "id": function () {},
      "placeholder": {
        "isRequired": function () {}
      },
      "dateValue": {
        "isRequired": function () {}
      },
      "border": {
        "isRequired": function () {}
      },
      "focused": {
        "isRequired": function () {}
      },
      "disabled": {
        "isRequired": function () {}
      },
      "required": {
        "isRequired": function () {}
      },
      "showCaret": {
        "isRequired": function () {}
      },
      "onChange": {
        "isRequired": function () {}
      },
      "onFocus": {
        "isRequired": function () {}
      },
      "onKeyDownShiftTab": {
        "isRequired": function () {}
      },
      "onKeyDownTab": {
        "isRequired": function () {}
      }
    },
    "defaultProps": {
      "placeholder": {},
      "dateValue": {},
      "border": {},
      "focused": {},
      "disabled": {},
      "required": {},
      "showCaret": {},
      "onChange": function () {},
      "onFocus": function () {},
      "onKeyDownShiftTab": function () {},
      "onKeyDownTab": function () {}
    }
  },
  "DayPicker": {
    "propTypes": {
      "enableOutsideDays": {
        "isRequired": function () {}
      },
      "numberOfMonths": {
        "isRequired": function () {}
      },
      "modifiers": {
        "isRequired": function () {}
      },
      "orientation": {
        "isRequired": function () {}
      },
      "withPortal": {
        "isRequired": function () {}
      },
      "hidden": {
        "isRequired": function () {}
      },
      "initialVisibleMonth": {
        "isRequired": function () {}
      },
      "onDayClick": {
        "isRequired": function () {}
      },
      "onDayMouseDown": {
        "isRequired": function () {}
      },
      "onDayMouseUp": {
        "isRequired": function () {}
      },
      "onDayMouseEnter": {
        "isRequired": function () {}
      },
      "onDayMouseLeave": {
        "isRequired": function () {}
      },
      "onDayTouchStart": {
        "isRequired": function () {}
      },
      "onDayTouchEnd": {
        "isRequired": function () {}
      },
      "onDayTouchTap": {
        "isRequired": function () {}
      },
      "onPrevMonthClick": {
        "isRequired": function () {}
      },
      "onNextMonthClick": {
        "isRequired": function () {}
      },
      "onOutsideClick": {
        "isRequired": function () {}
      },
      "monthFormat": {
        "isRequired": function () {}
      }
    },
    "defaultProps": {
      "enableOutsideDays": {},
      "numberOfMonths": {},
      "modifiers": {},
      "orientation": {},
      "withPortal": {},
      "hidden": {},
      "initialVisibleMonth": function () {},
      "onDayClick": function () {},
      "onDayMouseDown": function () {},
      "onDayMouseUp": function () {},
      "onDayMouseEnter": function () {},
      "onDayMouseLeave": function () {},
      "onDayTouchStart": function () {},
      "onDayTouchTap": function () {},
      "onDayTouchEnd": function () {},
      "onPrevMonthClick": function () {},
      "onNextMonthClick": function () {},
      "onOutsideClick": function () {},
      "monthFormat": {}
    }
  },
  "CalendarMonthGrid": {
    "propTypes": {
      "enableOutsideDays": {
        "isRequired": function () {}
      },
      "firstVisibleMonthIndex": {
        "isRequired": function () {}
      },
      "initialMonth": {
        "isRequired": function () {}
      },
      "isAnimating": {
        "isRequired": function () {}
      },
      "numberOfMonths": {
        "isRequired": function () {}
      },
      "modifiers": {
        "isRequired": function () {}
      },
      "orientation": {
        "isRequired": function () {}
      },
      "onDayClick": {
        "isRequired": function () {}
      },
      "onDayMouseDown": {
        "isRequired": function () {}
      },
      "onDayMouseUp": {
        "isRequired": function () {}
      },
      "onDayMouseEnter": {
        "isRequired": function () {}
      },
      "onDayMouseLeave": {
        "isRequired": function () {}
      },
      "onDayTouchStart": {
        "isRequired": function () {}
      },
      "onDayTouchEnd": {
        "isRequired": function () {}
      },
      "onDayTouchTap": {
        "isRequired": function () {}
      },
      "onMonthTransitionEnd": {
        "isRequired": function () {}
      },
      "transformValue": {
        "isRequired": function () {}
      },
      "monthFormat": {
        "isRequired": function () {}
      }
    },
    "defaultProps": {
      "enableOutsideDays": {},
      "firstVisibleMonthIndex": {},
      "initialMonth": {
        "_isAMomentObject": {},
        "_isUTC": {},
        "_pf": {
          "empty": {},
          "unusedTokens": {},
          "unusedInput": {},
          "overflow": {},
          "charsLeftOver": {},
          "nullInput": {},
          "invalidMonth": {},
          "invalidFormat": {},
          "userInvalidated": {},
          "iso": {},
          "parsedDateParts": {},
          "meridiem": {}
        },
        "_locale": {
          "_calendar": {
            "sameDay": {},
            "nextDay": {},
            "nextWeek": {},
            "lastDay": {},
            "lastWeek": {},
            "sameElse": {}
          },
          "_longDateFormat": {
            "LTS": {},
            "LT": {},
            "L": {},
            "LL": {},
            "LLL": {},
            "LLLL": {}
          },
          "_invalidDate": {},
          "ordinal": function () {},
          "_ordinalParse": {},
          "_relativeTime": {
            "future": {},
            "past": {},
            "s": {},
            "m": {},
            "mm": {},
            "h": {},
            "hh": {},
            "d": {},
            "dd": {},
            "M": {},
            "MM": {},
            "y": {},
            "yy": {}
          },
          "_months": {},
          "_monthsShort": {},
          "_week": {
            "dow": {},
            "doy": {}
          },
          "_weekdays": {},
          "_weekdaysMin": {},
          "_weekdaysShort": {},
          "_meridiemParse": {},
          "_abbr": {},
          "_config": {
            "calendar": {
              "sameDay": {},
              "nextDay": {},
              "nextWeek": {},
              "lastDay": {},
              "lastWeek": {},
              "sameElse": {}
            },
            "longDateFormat": {
              "LTS": {},
              "LT": {},
              "L": {},
              "LL": {},
              "LLL": {},
              "LLLL": {}
            },
            "invalidDate": {},
            "ordinal": function () {},
            "ordinalParse": {},
            "relativeTime": {
              "future": {},
              "past": {},
              "s": {},
              "m": {},
              "mm": {},
              "h": {},
              "hh": {},
              "d": {},
              "dd": {},
              "M": {},
              "MM": {},
              "y": {},
              "yy": {}
            },
            "months": {},
            "monthsShort": {},
            "week": {
              "dow": {},
              "doy": {}
            },
            "weekdays": {},
            "weekdaysMin": {},
            "weekdaysShort": {},
            "meridiemParse": {},
            "abbr": {}
          },
          "_ordinalParseLenient": {},
          "calendar": function () {},
          "longDateFormat": function () {},
          "invalidDate": function () {},
          "preparse": function () {},
          "postformat": function () {},
          "relativeTime": function () {},
          "pastFuture": function () {},
          "set": function () {},
          "months": function () {},
          "monthsShort": function () {},
          "monthsParse": function () {},
          "monthsRegex": function () {},
          "monthsShortRegex": function () {},
          "week": function () {},
          "firstDayOfYear": function () {},
          "firstDayOfWeek": function () {},
          "weekdays": function () {},
          "weekdaysMin": function () {},
          "weekdaysShort": function () {},
          "weekdaysParse": function () {},
          "weekdaysRegex": function () {},
          "weekdaysShortRegex": function () {},
          "weekdaysMinRegex": function () {},
          "isPM": function () {},
          "meridiem": function () {}
        },
        "_d": {},
        "add": function () {},
        "calendar": function () {},
        "clone": function () {},
        "diff": function () {},
        "endOf": function () {},
        "format": function () {},
        "from": function () {},
        "fromNow": function () {},
        "to": function () {},
        "toNow": function () {},
        "get": function () {},
        "invalidAt": function () {},
        "isAfter": function () {},
        "isBefore": function () {},
        "isBetween": function () {},
        "isSame": function () {},
        "isSameOrAfter": function () {},
        "isSameOrBefore": function () {},
        "isValid": function () {},
        "lang": function () {},
        "locale": function () {},
        "localeData": function () {},
        "max": function () {},
        "min": function () {},
        "parsingFlags": function () {},
        "set": function () {},
        "startOf": function () {},
        "subtract": function () {},
        "toArray": function () {},
        "toObject": function () {},
        "toDate": function () {},
        "toISOString": function () {},
        "toJSON": function () {},
        "toString": function () {},
        "unix": function () {},
        "valueOf": function () {},
        "creationData": function () {},
        "year": function () {},
        "isLeapYear": function () {},
        "weekYear": function () {},
        "isoWeekYear": function () {},
        "quarters": function () {},
        "quarter": function () {},
        "month": function () {},
        "daysInMonth": function () {},
        "weeks": function () {},
        "week": function () {},
        "isoWeeks": function () {},
        "isoWeek": function () {},
        "weeksInYear": function () {},
        "isoWeeksInYear": function () {},
        "date": function () {},
        "days": function () {},
        "day": function () {},
        "weekday": function () {},
        "isoWeekday": function () {},
        "dayOfYear": function () {},
        "hours": function () {},
        "hour": function () {},
        "minutes": function () {},
        "minute": function () {},
        "seconds": function () {},
        "second": function () {},
        "milliseconds": function () {},
        "millisecond": function () {},
        "utcOffset": function () {},
        "utc": function () {},
        "local": function () {},
        "parseZone": function () {},
        "hasAlignedHourOffset": function () {},
        "isDST": function () {},
        "isLocal": function () {},
        "isUtcOffset": function () {},
        "isUtc": function () {},
        "isUTC": function () {},
        "zoneAbbr": function () {},
        "zoneName": function () {},
        "dates": function () {},
        "months": function () {},
        "years": function () {},
        "zone": function () {},
        "isDSTShifted": function () {}
      },
      "isAnimating": {},
      "numberOfMonths": {},
      "modifiers": {},
      "orientation": {},
      "onDayClick": function () {},
      "onDayMouseDown": function () {},
      "onDayMouseUp": function () {},
      "onDayMouseEnter": function () {},
      "onDayMouseLeave": function () {},
      "onDayTouchStart": function () {},
      "onDayTouchEnd": function () {},
      "onDayTouchTap": function () {},
      "onMonthTransitionEnd": function () {},
      "transform": {},
      "monthFormat": {}
    }
  },
  "CalendarMonth": {
    "propTypes": {
      "month": {
        "isRequired": function () {}
      },
      "isVisible": {
        "isRequired": function () {}
      },
      "enableOutsideDays": {
        "isRequired": function () {}
      },
      "modifiers": {
        "isRequired": function () {}
      },
      "orientation": {
        "isRequired": function () {}
      },
      "onDayClick": {
        "isRequired": function () {}
      },
      "onDayMouseDown": {
        "isRequired": function () {}
      },
      "onDayMouseUp": {
        "isRequired": function () {}
      },
      "onDayMouseEnter": {
        "isRequired": function () {}
      },
      "onDayMouseLeave": {
        "isRequired": function () {}
      },
      "onDayTouchStart": {
        "isRequired": function () {}
      },
      "onDayTouchEnd": {
        "isRequired": function () {}
      },
      "onDayTouchTap": {
        "isRequired": function () {}
      },
      "monthFormat": {
        "isRequired": function () {}
      }
    },
    "defaultProps": {
      "month": {
        "_isAMomentObject": {},
        "_isUTC": {},
        "_pf": {
          "empty": {},
          "unusedTokens": {},
          "unusedInput": {},
          "overflow": {},
          "charsLeftOver": {},
          "nullInput": {},
          "invalidMonth": {},
          "invalidFormat": {},
          "userInvalidated": {},
          "iso": {},
          "parsedDateParts": {},
          "meridiem": {}
        },
        "_locale": {
          "_calendar": {
            "sameDay": {},
            "nextDay": {},
            "nextWeek": {},
            "lastDay": {},
            "lastWeek": {},
            "sameElse": {}
          },
          "_longDateFormat": {
            "LTS": {},
            "LT": {},
            "L": {},
            "LL": {},
            "LLL": {},
            "LLLL": {}
          },
          "_invalidDate": {},
          "ordinal": function () {},
          "_ordinalParse": {},
          "_relativeTime": {
            "future": {},
            "past": {},
            "s": {},
            "m": {},
            "mm": {},
            "h": {},
            "hh": {},
            "d": {},
            "dd": {},
            "M": {},
            "MM": {},
            "y": {},
            "yy": {}
          },
          "_months": {},
          "_monthsShort": {},
          "_week": {
            "dow": {},
            "doy": {}
          },
          "_weekdays": {},
          "_weekdaysMin": {},
          "_weekdaysShort": {},
          "_meridiemParse": {},
          "_abbr": {},
          "_config": {
            "calendar": {
              "sameDay": {},
              "nextDay": {},
              "nextWeek": {},
              "lastDay": {},
              "lastWeek": {},
              "sameElse": {}
            },
            "longDateFormat": {
              "LTS": {},
              "LT": {},
              "L": {},
              "LL": {},
              "LLL": {},
              "LLLL": {}
            },
            "invalidDate": {},
            "ordinal": function () {},
            "ordinalParse": {},
            "relativeTime": {
              "future": {},
              "past": {},
              "s": {},
              "m": {},
              "mm": {},
              "h": {},
              "hh": {},
              "d": {},
              "dd": {},
              "M": {},
              "MM": {},
              "y": {},
              "yy": {}
            },
            "months": {},
            "monthsShort": {},
            "week": {
              "dow": {},
              "doy": {}
            },
            "weekdays": {},
            "weekdaysMin": {},
            "weekdaysShort": {},
            "meridiemParse": {},
            "abbr": {}
          },
          "_ordinalParseLenient": {},
          "calendar": function () {},
          "longDateFormat": function () {},
          "invalidDate": function () {},
          "preparse": function () {},
          "postformat": function () {},
          "relativeTime": function () {},
          "pastFuture": function () {},
          "set": function () {},
          "months": function () {},
          "monthsShort": function () {},
          "monthsParse": function () {},
          "monthsRegex": function () {},
          "monthsShortRegex": function () {},
          "week": function () {},
          "firstDayOfYear": function () {},
          "firstDayOfWeek": function () {},
          "weekdays": function () {},
          "weekdaysMin": function () {},
          "weekdaysShort": function () {},
          "weekdaysParse": function () {},
          "weekdaysRegex": function () {},
          "weekdaysShortRegex": function () {},
          "weekdaysMinRegex": function () {},
          "isPM": function () {},
          "meridiem": function () {}
        },
        "_d": {},
        "add": function () {},
        "calendar": function () {},
        "clone": function () {},
        "diff": function () {},
        "endOf": function () {},
        "format": function () {},
        "from": function () {},
        "fromNow": function () {},
        "to": function () {},
        "toNow": function () {},
        "get": function () {},
        "invalidAt": function () {},
        "isAfter": function () {},
        "isBefore": function () {},
        "isBetween": function () {},
        "isSame": function () {},
        "isSameOrAfter": function () {},
        "isSameOrBefore": function () {},
        "isValid": function () {},
        "lang": function () {},
        "locale": function () {},
        "localeData": function () {},
        "max": function () {},
        "min": function () {},
        "parsingFlags": function () {},
        "set": function () {},
        "startOf": function () {},
        "subtract": function () {},
        "toArray": function () {},
        "toObject": function () {},
        "toDate": function () {},
        "toISOString": function () {},
        "toJSON": function () {},
        "toString": function () {},
        "unix": function () {},
        "valueOf": function () {},
        "creationData": function () {},
        "year": function () {},
        "isLeapYear": function () {},
        "weekYear": function () {},
        "isoWeekYear": function () {},
        "quarters": function () {},
        "quarter": function () {},
        "month": function () {},
        "daysInMonth": function () {},
        "weeks": function () {},
        "week": function () {},
        "isoWeeks": function () {},
        "isoWeek": function () {},
        "weeksInYear": function () {},
        "isoWeeksInYear": function () {},
        "date": function () {},
        "days": function () {},
        "day": function () {},
        "weekday": function () {},
        "isoWeekday": function () {},
        "dayOfYear": function () {},
        "hours": function () {},
        "hour": function () {},
        "minutes": function () {},
        "minute": function () {},
        "seconds": function () {},
        "second": function () {},
        "milliseconds": function () {},
        "millisecond": function () {},
        "utcOffset": function () {},
        "utc": function () {},
        "local": function () {},
        "parseZone": function () {},
        "hasAlignedHourOffset": function () {},
        "isDST": function () {},
        "isLocal": function () {},
        "isUtcOffset": function () {},
        "isUtc": function () {},
        "isUTC": function () {},
        "zoneAbbr": function () {},
        "zoneName": function () {},
        "dates": function () {},
        "months": function () {},
        "years": function () {},
        "zone": function () {},
        "isDSTShifted": function () {}
      },
      "isVisible": {},
      "enableOutsideDays": {},
      "modifiers": {},
      "orientation": {},
      "onDayClick": function () {},
      "onDayMouseDown": function () {},
      "onDayMouseUp": function () {},
      "onDayMouseEnter": function () {},
      "onDayMouseLeave": function () {},
      "onDayTouchStart": function () {},
      "onDayTouchEnd": function () {},
      "onDayTouchTap": function () {},
      "monthFormat": {}
    }
  },
  "CalendarDay": {
    "propTypes": {
      "day": {
        "isRequired": function () {}
      },
      "modifiers": {
        "isRequired": function () {}
      },
      "onDayClick": {
        "isRequired": function () {}
      },
      "onDayMouseDown": {
        "isRequired": function () {}
      },
      "onDayMouseUp": {
        "isRequired": function () {}
      },
      "onDayMouseEnter": {
        "isRequired": function () {}
      },
      "onDayMouseLeave": {
        "isRequired": function () {}
      },
      "onDayTouchStart": {
        "isRequired": function () {}
      },
      "onDayTouchEnd": {
        "isRequired": function () {}
      },
      "onDayTouchTap": {
        "isRequired": function () {}
      }
    },
    "defaultProps": {
      "day": {
        "_isAMomentObject": {},
        "_isUTC": {},
        "_pf": {
          "empty": {},
          "unusedTokens": {},
          "unusedInput": {},
          "overflow": {},
          "charsLeftOver": {},
          "nullInput": {},
          "invalidMonth": {},
          "invalidFormat": {},
          "userInvalidated": {},
          "iso": {},
          "parsedDateParts": {},
          "meridiem": {}
        },
        "_locale": {
          "_calendar": {
            "sameDay": {},
            "nextDay": {},
            "nextWeek": {},
            "lastDay": {},
            "lastWeek": {},
            "sameElse": {}
          },
          "_longDateFormat": {
            "LTS": {},
            "LT": {},
            "L": {},
            "LL": {},
            "LLL": {},
            "LLLL": {}
          },
          "_invalidDate": {},
          "ordinal": function () {},
          "_ordinalParse": {},
          "_relativeTime": {
            "future": {},
            "past": {},
            "s": {},
            "m": {},
            "mm": {},
            "h": {},
            "hh": {},
            "d": {},
            "dd": {},
            "M": {},
            "MM": {},
            "y": {},
            "yy": {}
          },
          "_months": {},
          "_monthsShort": {},
          "_week": {
            "dow": {},
            "doy": {}
          },
          "_weekdays": {},
          "_weekdaysMin": {},
          "_weekdaysShort": {},
          "_meridiemParse": {},
          "_abbr": {},
          "_config": {
            "calendar": {
              "sameDay": {},
              "nextDay": {},
              "nextWeek": {},
              "lastDay": {},
              "lastWeek": {},
              "sameElse": {}
            },
            "longDateFormat": {
              "LTS": {},
              "LT": {},
              "L": {},
              "LL": {},
              "LLL": {},
              "LLLL": {}
            },
            "invalidDate": {},
            "ordinal": function () {},
            "ordinalParse": {},
            "relativeTime": {
              "future": {},
              "past": {},
              "s": {},
              "m": {},
              "mm": {},
              "h": {},
              "hh": {},
              "d": {},
              "dd": {},
              "M": {},
              "MM": {},
              "y": {},
              "yy": {}
            },
            "months": {},
            "monthsShort": {},
            "week": {
              "dow": {},
              "doy": {}
            },
            "weekdays": {},
            "weekdaysMin": {},
            "weekdaysShort": {},
            "meridiemParse": {},
            "abbr": {}
          },
          "_ordinalParseLenient": {},
          "calendar": function () {},
          "longDateFormat": function () {},
          "invalidDate": function () {},
          "preparse": function () {},
          "postformat": function () {},
          "relativeTime": function () {},
          "pastFuture": function () {},
          "set": function () {},
          "months": function () {},
          "monthsShort": function () {},
          "monthsParse": function () {},
          "monthsRegex": function () {},
          "monthsShortRegex": function () {},
          "week": function () {},
          "firstDayOfYear": function () {},
          "firstDayOfWeek": function () {},
          "weekdays": function () {},
          "weekdaysMin": function () {},
          "weekdaysShort": function () {},
          "weekdaysParse": function () {},
          "weekdaysRegex": function () {},
          "weekdaysShortRegex": function () {},
          "weekdaysMinRegex": function () {},
          "isPM": function () {},
          "meridiem": function () {}
        },
        "_d": {},
        "add": function () {},
        "calendar": function () {},
        "clone": function () {},
        "diff": function () {},
        "endOf": function () {},
        "format": function () {},
        "from": function () {},
        "fromNow": function () {},
        "to": function () {},
        "toNow": function () {},
        "get": function () {},
        "invalidAt": function () {},
        "isAfter": function () {},
        "isBefore": function () {},
        "isBetween": function () {},
        "isSame": function () {},
        "isSameOrAfter": function () {},
        "isSameOrBefore": function () {},
        "isValid": function () {},
        "lang": function () {},
        "locale": function () {},
        "localeData": function () {},
        "max": function () {},
        "min": function () {},
        "parsingFlags": function () {},
        "set": function () {},
        "startOf": function () {},
        "subtract": function () {},
        "toArray": function () {},
        "toObject": function () {},
        "toDate": function () {},
        "toISOString": function () {},
        "toJSON": function () {},
        "toString": function () {},
        "unix": function () {},
        "valueOf": function () {},
        "creationData": function () {},
        "year": function () {},
        "isLeapYear": function () {},
        "weekYear": function () {},
        "isoWeekYear": function () {},
        "quarters": function () {},
        "quarter": function () {},
        "month": function () {},
        "daysInMonth": function () {},
        "weeks": function () {},
        "week": function () {},
        "isoWeeks": function () {},
        "isoWeek": function () {},
        "weeksInYear": function () {},
        "isoWeeksInYear": function () {},
        "date": function () {},
        "days": function () {},
        "day": function () {},
        "weekday": function () {},
        "isoWeekday": function () {},
        "dayOfYear": function () {},
        "hours": function () {},
        "hour": function () {},
        "minutes": function () {},
        "minute": function () {},
        "seconds": function () {},
        "second": function () {},
        "milliseconds": function () {},
        "millisecond": function () {},
        "utcOffset": function () {},
        "utc": function () {},
        "local": function () {},
        "parseZone": function () {},
        "hasAlignedHourOffset": function () {},
        "isDST": function () {},
        "isLocal": function () {},
        "isUtcOffset": function () {},
        "isUtc": function () {},
        "isUTC": function () {},
        "zoneAbbr": function () {},
        "zoneName": function () {},
        "dates": function () {},
        "months": function () {},
        "years": function () {},
        "zone": function () {},
        "isDSTShifted": function () {}
      },
      "modifiers": {},
      "onDayClick": function () {},
      "onDayMouseDown": function () {},
      "onDayMouseUp": function () {},
      "onDayMouseEnter": function () {},
      "onDayMouseLeave": function () {},
      "onDayTouchStart": function () {},
      "onDayTouchEnd": function () {},
      "onDayTouchTap": function () {}
    }
  },
  "DateRangePickerShape": {
    "startDate": {
      "isRequired": function () {}
    },
    "endDate": {
      "isRequired": function () {}
    },
    "focusedInput": {
      "isRequired": function () {}
    },
    "minimumNights": {
      "isRequired": function () {}
    },
    "isDayBlocked": {
      "isRequired": function () {}
    },
    "isOutsideRange": {
      "isRequired": function () {}
    },
    "enableOutsideDays": {
      "isRequired": function () {}
    },
    "reopenPickerOnClearDates": {
      "isRequired": function () {}
    },
    "numberOfMonths": {
      "isRequired": function () {}
    },
    "showClearDates": {
      "isRequired": function () {}
    },
    "disabled": {
      "isRequired": function () {}
    },
    "required": {
      "isRequired": function () {}
    },
    "orientation": {
      "isRequired": function () {}
    },
    "anchorDirection": {
      "isRequired": function () {}
    },
    "withPortal": {
      "isRequired": function () {}
    },
    "withFullScreenPortal": {
      "isRequired": function () {}
    },
    "startDateId": {
      "isRequired": function () {}
    },
    "startDatePlaceholderText": {
      "isRequired": function () {}
    },
    "endDateId": {
      "isRequired": function () {}
    },
    "endDatePlaceholderText": {
      "isRequired": function () {}
    },
    "initialVisibleMonth": {
      "isRequired": function () {}
    },
    "onDatesChange": {
      "isRequired": function () {}
    },
    "onFocusChange": {
      "isRequired": function () {}
    },
    "onPrevMonthClick": {
      "isRequired": function () {}
    },
    "onNextMonthClick": {
      "isRequired": function () {}
    },
    "displayFormat": {
      "isRequired": function () {}
    },
    "monthFormat": {
      "isRequired": function () {}
    },
    "phrases": {
      "isRequired": function () {}
    }
  },
  "SingleDatePickerShape": {
    "id": function () {},
    "placeholder": {
      "isRequired": function () {}
    },
    "date": {
      "isRequired": function () {}
    },
    "focused": {
      "isRequired": function () {}
    },
    "disabled": {
      "isRequired": function () {}
    },
    "required": {
      "isRequired": function () {}
    },
    "onDateChange": {
      "isRequired": function () {}
    },
    "onFocusChange": {
      "isRequired": function () {}
    },
    "isDayBlocked": {
      "isRequired": function () {}
    },
    "isOutsideRange": {
      "isRequired": function () {}
    },
    "enableOutsideDays": {
      "isRequired": function () {}
    },
    "numberOfMonths": {
      "isRequired": function () {}
    },
    "orientation": {
      "isRequired": function () {}
    },
    "initialVisibleMonth": {
      "isRequired": function () {}
    },
    "anchorDirection": {
      "isRequired": function () {}
    },
    "withPortal": {
      "isRequired": function () {}
    },
    "withFullScreenPortal": {
      "isRequired": function () {}
    },
    "onPrevMonthClick": {
      "isRequired": function () {}
    },
    "onNextMonthClick": {
      "isRequired": function () {}
    },
    "displayFormat": {
      "isRequired": function () {}
    },
    "monthFormat": {
      "isRequired": function () {}
    },
    "phrases": {
      "isRequired": function () {}
    }
  },
  "isInclusivelyAfterDay": function () {},
  "isInclusivelyBeforeDay": function () {},
  "isNextDay": function () {},
  "isSameDay": function () {},
  "toISODateString": function () {},
  "toLocalizedDateString": function () {},
  "toMomentObject": function () {}
};
ReactDates.DateRangePicker.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
ReactDates.SingleDatePicker.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
ReactDates.DateRangePickerInput.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
ReactDates.DayPicker.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
ReactDates.CalendarMonthGrid.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
ReactDates.CalendarDay.prototype = {
  "isReactComponent": function () {},
  "setState": function () {},
  "forceUpdate": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactDates
/**********************************************************************/
