/**********************************************************************
 * Extern for AutoSizer
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var AutoSizer = {
  "defaultProps": {
    "disableHeight": {},
    "disableWidth": {},
    "onResize": function () {},
    "style": {}
  }
};
AutoSizer.prototype = {
  "forceUpdate": function () {},
  "isPureReactComponent": function () {},
  "isReactComponent": function () {},
  "setState": function () {}
};
/**********************************************************************
 * End Generated Extern for AutoSizer
/**********************************************************************/
