/**********************************************************************
 * Extern for ReactTooltip
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var ReactTooltip = {
  "defaultProps": {
    "insecure": {},
    "resizeHide": {},
    "wrapper": {}
  },
  "hide": function () {},
  "propTypes": {
    "afterHide": {
      "isRequired": function () {}
    },
    "afterShow": {
      "isRequired": function () {}
    },
    "border": {
      "isRequired": function () {}
    },
    "children": {
      "isRequired": function () {}
    },
    "class": {
      "isRequired": function () {}
    },
    "className": {
      "isRequired": function () {}
    },
    "delayHide": {
      "isRequired": function () {}
    },
    "delayShow": {
      "isRequired": function () {}
    },
    "disable": {
      "isRequired": function () {}
    },
    "effect": {
      "isRequired": function () {}
    },
    "event": {
      "isRequired": function () {}
    },
    "eventOff": {
      "isRequired": function () {}
    },
    "getContent": {
      "isRequired": function () {}
    },
    "globalEventOff": {
      "isRequired": function () {}
    },
    "html": {
      "isRequired": function () {}
    },
    "id": {
      "isRequired": function () {}
    },
    "insecure": {
      "isRequired": function () {}
    },
    "isCapture": {
      "isRequired": function () {}
    },
    "multiline": {
      "isRequired": function () {}
    },
    "offset": {
      "isRequired": function () {}
    },
    "place": {
      "isRequired": function () {}
    },
    "resizeHide": {
      "isRequired": function () {}
    },
    "scrollHide": {
      "isRequired": function () {}
    },
    "type": {
      "isRequired": function () {}
    },
    "watchWindow": {
      "isRequired": function () {}
    },
    "wrapper": {
      "isRequired": function () {}
    }
  },
  "rebuild": function () {},
  "show": function () {},
  "supportedWrappers": {}
};
ReactTooltip.prototype = {
  "bindRemovalTracker": function () {},
  "bindWindowEvents": function () {},
  "customBindListener": function () {},
  "customUnbindListener": function () {},
  "forceUpdate": function () {},
  "getEffect": function () {},
  "globalHide": function () {},
  "globalRebuild": function () {},
  "globalShow": function () {},
  "isCapture": function () {},
  "isCustomEvent": function () {},
  "isReactComponent": function () {},
  "onWindowResize": function () {},
  "setState": function () {},
  "unbindRemovalTracker": function () {},
  "unbindWindowEvents": function () {}
};
/**********************************************************************
 * End Generated Extern for ReactTooltip
/**********************************************************************/