var Slider = {
  "element": {},
  "eventToCallbackMap": {},
  "handle1": {},
  "handle1Keydown": function () {},
  "handle2": {},
  "handle2Keydown": function () {},
  "hideToolTip": function () {},
  "mousePos": {},
  "mousedown": function () {},
  "options": {},
  "resize": function () {},
  "showTooltip": function () {},
  "sizePos": {},
  "sliderElem": {},
  "stylePos": {},
  "tickLabels": {},
  "ticks": {},
  "tooltip": {},
  "tooltipInner": {},
  "tooltipInner_max": {},
  "tooltipInner_min": {},
  "tooltip_max": {},
  "tooltip_min": {},
  "touchCapable": {},
  "touchX": {},
  "touchY": {},
  "touchmove": function () {},
  "touchstart": function () {},
  "trackHigh": {},
  "trackLow": {},
  "trackSelection": {},
  "getValue": function () {},
  "setValue": function () {},
  "disable": function () {},
  "enable": function () {}
};

jQuery.prototype.slider = function () {};
