/**********************************************************************
 * Extern for m
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var m = {
  "trust": function () {},
  "fragment": function () {},
  "mount": function () {},
  "route": {
    "set": function () {},
    "get": function () {},
    "prefix": function () {},
    "link": function () {},
    "param": function () {}
  },
  "withAttr": function () {},
  "render": function () {},
  "redraw": function () {},
  "request": function () {},
  "jsonp": function () {},
  "parseQueryString": function () {},
  "buildQueryString": function () {},
  "version": {},
  "vnode": {
    "normalize": function () {},
    "normalizeChildren": function () {}
  }
};
/**********************************************************************
 * End Generated Extern for m
/**********************************************************************/