var ChemDoodle = {
    "iChemLabs": {
        "SERVER_URL": {},
        "inRelay": {},
        "asynchronous": {},
        "INFO": {
            "userAgent": {},
            "v_cwc": {},
            "v_jQuery": {},
            "v_jQuery_ui": {}
        },
        "useHTTPS": function () {},
        "_contactServer": function () {},
        "authenticate": function () {},
        "calculate": function () {},
        "createLewisDotStructure": function () {},
        "generateImage": function () {},
        "generateIUPACName": function () {},
        "getAd": function () {},
        "getMoleculeFromContent": function () {},
        "getMoleculeFromDatabase": function () {},
        "getOptimizedPDBStructure": function () {},
        "getZeoliteFromIZA": function () {},
        "isGraphIsomorphism": function () {},
        "isSubgraphIsomorphism": function () {},
        "isSupergraphIsomorphism": function () {},
        "getSimilarityMeasure": function () {},
        "kekulize": function () {},
        "optimize": function () {},
        "readIUPACName": function () {},
        "readSMILES": function () {},
        "saveFile": function () {},
        "simulate13CNMR": function () {},
        "simulate1HNMR": function () {},
        "simulateMassParentPeak": function () {},
        "writeSMILES": function () {},
        "version": function () {},
        "checkForUpdates": function () {}
    },
    "informatics": {
        "getPointsPerAngstrom": function () {},
        "BondDeducer": function () {},
        "HydrogenDeducer": function () {},
        "MolecularSurfaceGenerator": function () {},
        "Splitter": function () {},
        "StructureBuilder": function () {},
        "_Counter": function () {},
        "FrerejacqueNumberCounter": function () {},
        "NumberOfMoleculesCounter": function () {},
        "_RingFinder": function () {},
        "EulerFacetRingFinder": function () {},
        "SSSRFinder": function () {}
    },
    "io": {
        "_Interpreter": function () {},
        "CIFInterpreter": function () {},
        "CMLInterpreter": function () {},
        "MOLInterpreter": function () {},
        "PDBInterpreter": function () {},
        "JCAMPInterpreter": function () {},
        "JSONInterpreter": function () {},
        "RXNInterpreter": function () {},
        "XYZInterpreter": function () {},
        "png": {
            "create": function () {}
        },
        "file": {
            "content": function () {}
        }
    },
    "lib": {
        "jQuery": function () {},
        "glMatrixArrayType": function () {},
        "MatrixArray": function () {},
        "setMatrixArrayType": function () {},
        "determineMatrixArrayType": function () {},
        "glMath": {
            "invsqrt": function () {}
        },
        "vec2": {
            "create": function () {},
            "createFrom": function () {},
            "add": function () {},
            "subtract": function () {},
            "multiply": function () {},
            "divide": function () {},
            "scale": function () {},
            "dist": function () {},
            "set": function () {},
            "equal": function () {},
            "negate": function () {},
            "normalize": function () {},
            "cross": function () {},
            "length": function () {},
            "squaredLength": function () {},
            "dot": function () {},
            "direction": function () {},
            "lerp": function () {},
            "str": function () {}
        },
        "vec3": {
            "create": function () {},
            "createFrom": function () {},
            "set": function () {},
            "equal": function () {},
            "add": function () {},
            "subtract": function () {},
            "multiply": function () {},
            "negate": function () {},
            "scale": function () {},
            "normalize": function () {},
            "cross": function () {},
            "length": function () {},
            "squaredLength": function () {},
            "dot": function () {},
            "direction": function () {},
            "lerp": function () {},
            "dist": function () {},
            "unproject": function () {},
            "rotationTo": function () {},
            "str": function () {}
        },
        "vec4": {
            "create": function () {},
            "createFrom": function () {},
            "add": function () {},
            "subtract": function () {},
            "multiply": function () {},
            "divide": function () {},
            "scale": function () {},
            "set": function () {},
            "equal": function () {},
            "negate": function () {},
            "length": function () {},
            "squaredLength": function () {},
            "lerp": function () {},
            "str": function () {}
        },
        "mat2": {
            "create": function () {},
            "createFrom": function () {},
            "set": function () {},
            "equal": function () {},
            "identity": function () {},
            "transpose": function () {},
            "determinant": function () {},
            "inverse": function () {},
            "multiply": function () {},
            "rotate": function () {},
            "multiplyVec2": function () {},
            "scale": function () {},
            "str": function () {}
        },
        "mat3": {
            "create": function () {},
            "createFrom": function () {},
            "determinant": function () {},
            "inverse": function () {},
            "multiply": function () {},
            "multiplyVec2": function () {},
            "multiplyVec3": function () {},
            "set": function () {},
            "equal": function () {},
            "identity": function () {},
            "transpose": function () {},
            "toMat4": function () {},
            "str": function () {},
            "toQuat4": function () {}
        },
        "mat4": {
            "create": function () {},
            "createFrom": function () {},
            "set": function () {},
            "equal": function () {},
            "identity": function () {},
            "transpose": function () {},
            "determinant": function () {},
            "inverse": function () {},
            "toRotationMat": function () {},
            "toMat3": function () {},
            "toInverseMat3": function () {},
            "multiply": function () {},
            "multiplyVec3": function () {},
            "multiplyVec4": function () {},
            "translate": function () {},
            "scale": function () {},
            "rotate": function () {},
            "rotateX": function () {},
            "rotateY": function () {},
            "rotateZ": function () {},
            "frustum": function () {},
            "perspective": function () {},
            "ortho": function () {},
            "lookAt": function () {},
            "fromRotationTranslation": function () {},
            "str": function () {}
        },
        "quat4": {
            "create": function () {},
            "createFrom": function () {},
            "set": function () {},
            "equal": function () {},
            "identity": function () {},
            "calculateW": function () {},
            "dot": function () {},
            "inverse": function () {},
            "conjugate": function () {},
            "length": function () {},
            "normalize": function () {},
            "add": function () {},
            "multiply": function () {},
            "multiplyVec3": function () {},
            "scale": function () {},
            "toMat3": function () {},
            "toMat4": function () {},
            "slerp": function () {},
            "fromRotationMatrix": function () {},
            "fromAxes": function () {},
            "fromAngleAxis": function () {},
            "toAngleAxis": function () {},
            "str": function () {}
        }
    },
    "notations": function () {},
    "structures": {
        "d2": {
            "_Shape": function () {},
            "Bracket": function () {},
            "Line": function () {},
            "Pusher": function () {}
        },
        "d3": {
            "_Mesh": function () {},
            "_Measurement": function () {},
            "Angle": function () {},
            "Arrow": function () {},
            "Box": function () {},
            "LineArrow": function () {},
            "Compass": function () {},
            "Cylinder": function () {},
            "Distance": function () {},
            "Fog": function () {},
            "Label": function () {},
            "Sphere": function () {},
            "Ribbon": function () {},
            "Light": function () {},
            "Line": function () {},
            "Material": function () {},
            "MolecularSurface": function () {},
            "Picker": function () {},
            "Pill": function () {},
            "PipePlank": function () {},
            "Shader": function () {},
            "Shape": function () {},
            "Star": function () {},
            "TextImage": function () {},
            "TextMesh": function () {},
            "Torsion": function () {},
            "Tube": function () {},
            "CatmullTube": function () {},
            "UnitCell": function () {}
        },
        "Queue": function () {},
        "Point": function () {},
        "Query": function () {},
        "Atom": function () {},
        "Bond": function () {},
        "Ring": function () {},
        "Molecule": function () {},
        "Residue": function () {},
        "Spectrum": function () {},
        "Plate": function () {},
        "VisualSpecifications": function () {}
    },
    "getVersion": function () {},
    "animations": {
        "requestInterval": function () {},
        "clearRequestInterval": function () {},
        "requestTimeout": function () {},
        "clearRequestTimeout": function () {}
    },
    "extensions": {
        "stringStartsWith": function () {},
        "vec3AngleFrom": function () {},
        "contextHashTo": function () {},
        "contextRoundRect": function () {},
        "contextEllipse": function () {},
        "getFontString": function () {}
    },
    "math": {
        "angleBetweenLargest": function () {},
        "isBetween": function () {},
        "getRGB": function () {},
        "idx2color": function () {},
        "distanceFromPointToLineInclusive": function () {},
        "calculateDistanceInterior": function () {},
        "intersectLines": function () {},
        "hsl2rgb": function () {},
        "isPointInPoly": function () {},
        "clamp": function () {},
        "rainbowAt": function () {},
        "angleBounds": function () {},
        "Bounds": function () {},
        "jsBezier": {
            "distanceFromCurve": function () {},
            "gradientAtPoint": function () {},
            "gradientAtPointAlongCurveFrom": function () {},
            "nearestPointOnCurve": function () {},
            "pointOnCurve": function () {},
            "pointAlongCurveFrom": function () {},
            "perpendicularToCurveAt": function () {},
            "locationAlongCurveFrom": function () {},
            "getLength": function () {}
        }
    },
    "featureDetection": {
        "supports_canvas": function () {},
        "supports_canvas_text": function () {},
        "supports_webgl": function () {},
        "supports_xhr2": function () {},
        "supports_touch": function () {},
        "supports_gesture": function () {}
    },
    "SYMBOLS": {
        "0": {},
        "1": {},
        "2": {},
        "3": {},
        "4": {},
        "5": {},
        "6": {},
        "7": {},
        "8": {},
        "9": {},
        "10": {},
        "11": {},
        "12": {},
        "13": {},
        "14": {},
        "15": {},
        "16": {},
        "17": {},
        "18": {},
        "19": {},
        "20": {},
        "21": {},
        "22": {},
        "23": {},
        "24": {},
        "25": {},
        "26": {},
        "27": {},
        "28": {},
        "29": {},
        "30": {},
        "31": {},
        "32": {},
        "33": {},
        "34": {},
        "35": {},
        "36": {},
        "37": {},
        "38": {},
        "39": {},
        "40": {},
        "41": {},
        "42": {},
        "43": {},
        "44": {},
        "45": {},
        "46": {},
        "47": {},
        "48": {},
        "49": {},
        "50": {},
        "51": {},
        "52": {},
        "53": {},
        "54": {},
        "55": {},
        "56": {},
        "57": {},
        "58": {},
        "59": {},
        "60": {},
        "61": {},
        "62": {},
        "63": {},
        "64": {},
        "65": {},
        "66": {},
        "67": {},
        "68": {},
        "69": {},
        "70": {},
        "71": {},
        "72": {},
        "73": {},
        "74": {},
        "75": {},
        "76": {},
        "77": {},
        "78": {},
        "79": {},
        "80": {},
        "81": {},
        "82": {},
        "83": {},
        "84": {},
        "85": {},
        "86": {},
        "87": {},
        "88": {},
        "89": {},
        "90": {},
        "91": {},
        "92": {},
        "93": {},
        "94": {},
        "95": {},
        "96": {},
        "97": {},
        "98": {},
        "99": {},
        "100": {},
        "101": {},
        "102": {},
        "103": {},
        "104": {},
        "105": {},
        "106": {},
        "107": {},
        "108": {},
        "109": {},
        "110": {},
        "111": {},
        "112": {},
        "113": {},
        "114": {},
        "115": {},
        "116": {},
        "117": {}
    },
    "ELEMENT": {
        "H": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "He": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Li": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Be": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "B": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "C": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "N": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "O": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "F": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ne": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Na": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Mg": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Al": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Si": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "P": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "S": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Cl": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ar": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "K": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ca": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Sc": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ti": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "V": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Cr": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Mn": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Fe": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Co": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ni": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Cu": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Zn": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ga": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ge": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "As": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Se": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Br": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Kr": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Rb": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Sr": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Y": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Zr": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Nb": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Mo": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Tc": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ru": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Rh": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Pd": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ag": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Cd": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "In": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Sn": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Sb": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Te": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "I": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Xe": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Cs": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ba": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "La": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ce": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Pr": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Nd": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Pm": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Sm": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Eu": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Gd": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Tb": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Dy": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ho": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Er": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Tm": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Yb": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Lu": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Hf": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ta": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "W": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Re": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Os": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ir": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Pt": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Au": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Hg": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Tl": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Pb": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Bi": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Po": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "At": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Rn": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Fr": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ra": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ac": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Th": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Pa": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "U": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Np": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Pu": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Am": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Cm": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Bk": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Cf": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Es": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Fm": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Md": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "No": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Lr": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Rf": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Db": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Sg": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Bh": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Hs": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Mt": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Ds": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Rg": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Cn": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Uut": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Uuq": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Uup": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Uuh": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Uus": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        },
        "Uuo": {
            "symbol": {},
            "name": {},
            "atomicNumber": {},
            "addH": {},
            "pymolColor": {},
            "jmolColor": {},
            "covalentRadius": {},
            "vdWRadius": {},
            "valency": {},
            "mass": {}
        }
    },
    "RESIDUE": {
        "Ala": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Arg": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Asn": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Asp": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Cys": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Gln": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Glu": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Gly": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "His": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Ile": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Leu": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Lys": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Met": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Phe": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Pro": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Ser": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Thr": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Trp": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Tyr": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Val": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Asx": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "Glx": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "*": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "A": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "G": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "I": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "C": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "T": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        },
        "U": {
            "symbol": {},
            "name": {},
            "polar": {},
            "aminoColor": {},
            "shapelyColor": {},
            "acidity": {}
        }
    },
    "default_backgroundColor": {},
    "default_scale": {},
    "default_rotateAngle": {},
    "default_bondLength_2D": {},
    "default_angstromsPerBondLength": {},
    "default_lightDirection_3D": {
        "0": {},
        "1": {},
        "2": {}
    },
    "default_lightDiffuseColor_3D": {},
    "default_lightSpecularColor_3D": {},
    "default_projectionPerspective_3D": {},
    "default_projectionPerspectiveVerticalFieldOfView_3D": {},
    "default_projectionOrthoWidth_3D": {},
    "default_projectionWidthHeightRatio_3D": {},
    "default_projectionFrontCulling_3D": {},
    "default_projectionBackCulling_3D": {},
    "default_cullBackFace_3D": {},
    "default_fog_mode_3D": {},
    "default_fog_color_3D": {},
    "default_fog_start_3D": {},
    "default_fog_end_3D": {},
    "default_fog_density_3D": {},
    "default_atoms_display": {},
    "default_atoms_color": {},
    "default_atoms_font_size_2D": {},
    "default_atoms_font_families_2D": {
        "0": {},
        "1": {},
        "2": {}
    },
    "default_atoms_font_bold_2D": {},
    "default_atoms_font_italic_2D": {},
    "default_atoms_circles_2D": {},
    "default_atoms_circleDiameter_2D": {},
    "default_atoms_circleBorderWidth_2D": {},
    "default_atoms_lonePairDistance_2D": {},
    "default_atoms_lonePairSpread_2D": {},
    "default_atoms_lonePairDiameter_2D": {},
    "default_atoms_useJMOLColors": {},
    "default_atoms_usePYMOLColors": {},
    "default_atoms_resolution_3D": {},
    "default_atoms_sphereDiameter_3D": {},
    "default_atoms_useVDWDiameters_3D": {},
    "default_atoms_vdwMultiplier_3D": {},
    "default_atoms_materialAmbientColor_3D": {},
    "default_atoms_materialSpecularColor_3D": {},
    "default_atoms_materialShininess_3D": {},
    "default_atoms_implicitHydrogens_2D": {},
    "default_atoms_displayTerminalCarbonLabels_2D": {},
    "default_atoms_showHiddenCarbons_2D": {},
    "default_atoms_showAttributedCarbons_2D": {},
    "default_atoms_displayAllCarbonLabels_2D": {},
    "default_atoms_nonBondedAsStars_3D": {},
    "default_atoms_displayLabels_3D": {},
    "default_atoms_HBlack_2D": {},
    "default_bonds_display": {},
    "default_bonds_color": {},
    "default_bonds_width_2D": {},
    "default_bonds_saturationWidth_2D": {},
    "default_bonds_ends_2D": {},
    "default_bonds_useJMOLColors": {},
    "default_bonds_usePYMOLColors": {},
    "default_bonds_colorGradient": {},
    "default_bonds_saturationAngle_2D": {},
    "default_bonds_symmetrical_2D": {},
    "default_bonds_clearOverlaps_2D": {},
    "default_bonds_overlapClearWidth_2D": {},
    "default_bonds_atomLabelBuffer_2D": {},
    "default_bonds_wedgeThickness_2D": {},
    "default_bonds_hashWidth_2D": {},
    "default_bonds_hashSpacing_2D": {},
    "default_bonds_dotSize_2D": {},
    "default_bonds_lewisStyle_2D": {},
    "default_bonds_showBondOrders_3D": {},
    "default_bonds_resolution_3D": {},
    "default_bonds_renderAsLines_3D": {},
    "default_bonds_cylinderDiameter_3D": {},
    "default_bonds_pillLatitudeResolution_3D": {},
    "default_bonds_pillLongitudeResolution_3D": {},
    "default_bonds_pillHeight_3D": {},
    "default_bonds_pillSpacing_3D": {},
    "default_bonds_pillDiameter_3D": {},
    "default_bonds_materialAmbientColor_3D": {},
    "default_bonds_materialSpecularColor_3D": {},
    "default_bonds_materialShininess_3D": {},
    "default_proteins_displayRibbon": {},
    "default_proteins_displayBackbone": {},
    "default_proteins_backboneThickness": {},
    "default_proteins_backboneColor": {},
    "default_proteins_ribbonCartoonize": {},
    "default_proteins_displayPipePlank": {},
    "default_proteins_residueColor": {},
    "default_proteins_primaryColor": {},
    "default_proteins_secondaryColor": {},
    "default_proteins_ribbonCartoonHelixPrimaryColor": {},
    "default_proteins_ribbonCartoonHelixSecondaryColor": {},
    "default_proteins_ribbonCartoonSheetColor": {},
    "default_proteins_tubeColor": {},
    "default_proteins_tubeResolution_3D": {},
    "default_proteins_ribbonThickness": {},
    "default_proteins_tubeThickness": {},
    "default_proteins_plankSheetWidth": {},
    "default_proteins_cylinderHelixDiameter": {},
    "default_proteins_verticalResolution": {},
    "default_proteins_horizontalResolution": {},
    "default_proteins_materialAmbientColor_3D": {},
    "default_proteins_materialSpecularColor_3D": {},
    "default_proteins_materialShininess_3D": {},
    "default_nucleics_display": {},
    "default_nucleics_tubeColor": {},
    "default_nucleics_baseColor": {},
    "default_nucleics_residueColor": {},
    "default_nucleics_tubeThickness": {},
    "default_nucleics_tubeResolution_3D": {},
    "default_nucleics_verticalResolution": {},
    "default_nucleics_materialAmbientColor_3D": {},
    "default_nucleics_materialSpecularColor_3D": {},
    "default_nucleics_materialShininess_3D": {},
    "default_macro_displayAtoms": {},
    "default_macro_displayBonds": {},
    "default_macro_atomToLigandDistance": {},
    "default_macro_showWater": {},
    "default_macro_colorByChain": {},
    "default_macro_rainbowColors": {
        "0": {},
        "1": {},
        "2": {},
        "3": {},
        "4": {}
    },
    "default_surfaces_display": {},
    "default_surfaces_style": {},
    "default_surfaces_color": {},
    "default_surfaces_materialAmbientColor_3D": {},
    "default_surfaces_materialSpecularColor_3D": {},
    "default_surfaces_materialShininess_3D": {},
    "default_plots_color": {},
    "default_plots_width": {},
    "default_plots_showIntegration": {},
    "default_plots_integrationColor": {},
    "default_plots_integrationLineWidth": {},
    "default_plots_showGrid": {},
    "default_plots_gridColor": {},
    "default_plots_gridLineWidth": {},
    "default_plots_showYAxis": {},
    "default_plots_flipXAxis": {},
    "default_text_font_size": {},
    "default_text_font_families": {
        "0": {},
        "1": {},
        "2": {}
    },
    "default_text_font_bold": {},
    "default_text_font_italic": {},
    "default_text_font_stroke_3D": {},
    "default_text_color": {},
    "default_shapes_color": {},
    "default_shapes_lineWidth": {},
    "default_shapes_arrowLength_2D": {},
    "default_compass_display": {},
    "default_compass_axisXColor_3D": {},
    "default_compass_axisYColor_3D": {},
    "default_compass_axisZColor_3D": {},
    "default_compass_size_3D": {},
    "default_compass_resolution_3D": {},
    "default_compass_displayText_3D": {},
    "default_compass_type_3D": {},
    "default_measurement_update_3D": {},
    "default_measurement_angleBands_3D": {},
    "default_measurement_displayText_3D": {},
    "readCIF": function () {},
    "readCML": function () {},
    "writeCML": function () {},
    "readMOL": function () {},
    "writeMOL": function () {},
    "readPDB": function () {},
    "readJCAMP": function () {},
    "readJSON": function () {},
    "writeJSON": function () {},
    "readRXN": function () {},
    "writeRXN": function () {},
    "readXYZ": function () {},
    "monitor": {
        "CANVAS_DRAGGING": {},
        "CANVAS_OVER": {},
        "ALT": {},
        "SHIFT": {},
        "META": {}
    },
    "_Canvas": function () {},
    "_AnimatorCanvas": function () {},
    "FileCanvas": function () {},
    "HyperlinkCanvas": function () {},
    "MolGrabberCanvas": function () {},
    "RotatorCanvas": function () {},
    "SlideshowCanvas": function () {},
    "TransformCanvas": function () {},
    "ViewerCanvas": function () {},
    "_SpectrumCanvas": function () {},
    "ObserverCanvas": function () {},
    "OverlayCanvas": function () {},
    "PerspectiveCanvas": function () {},
    "SeekerCanvas": function () {},
    "_Canvas3D": function () {},
    "MolGrabberCanvas3D": function () {},
    "MovieCanvas3D": function () {},
    "RotatorCanvas3D": function () {},
    "TransformCanvas3D": function () {},
    "ViewerCanvas3D": function () {},
    "PeriodicTableCanvas": function () {}
}
