/**********************************************************************
 * Extern for jQuery
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var jQuery = {
  "Animation": {
    "prefilter": function () {},
    "prefilters": {},
    "tweener": function () {},
    "tweeners": {
      "*": {}
    }
  },
  "Callbacks": function () {},
  "Deferred": {
    "exceptionHook": function () {}
  },
  "Event": function () {},
  "Tween": {
    "propHooks": {
      "_default": {
        "get": function () {},
        "set": function () {}
      },
      "scrollLeft": {
        "set": function () {}
      },
      "scrollTop": {
        "set": function () {}
      }
    }
  },
  "_data": function () {},
  "_evalUrl": function () {},
  "_queueHooks": function () {},
  "_removeData": function () {},
  "active": {},
  "ajax": function () {},
  "ajaxPrefilter": function () {},
  "ajaxSettings": {
    "accepts": {
      "*": {},
      "html": {},
      "json": {},
      "script": {},
      "text": {},
      "xml": {}
    },
    "async": {},
    "contentType": {},
    "contents": {
      "html": {},
      "json": {},
      "script": {},
      "xml": {}
    },
    "converters": {
      "* text": function () {},
      "text html": {},
      "text json": function () {},
      "text script": function () {},
      "text xml": function () {}
    },
    "flatOptions": {
      "context": {},
      "url": {}
    },
    "global": {},
    "isLocal": {},
    "jsonp": {},
    "jsonpCallback": function () {},
    "processData": {},
    "responseFields": {
      "json": {},
      "text": {},
      "xml": {}
    },
    "type": {},
    "url": {},
    "xhr": function () {}
  },
  "ajaxSetup": function () {},
  "ajaxTransport": function () {},
  "attr": function () {},
  "attrHooks": {
    "type": {
      "set": function () {}
    }
  },
  "camelCase": function () {},
  "cleanData": function () {},
  "clone": function () {},
  "contains": function () {},
  "css": function () {},
  "cssHooks": {
    "borderWidth": {
      "expand": function () {},
      "set": function () {}
    },
    "height": {
      "get": function () {},
      "set": function () {}
    },
    "left": {
      "get": function () {}
    },
    "margin": {
      "expand": function () {}
    },
    "marginLeft": {
      "get": function () {}
    },
    "opacity": {
      "get": function () {}
    },
    "padding": {
      "expand": function () {},
      "set": function () {}
    },
    "top": {
      "get": function () {}
    },
    "width": {
      "get": function () {},
      "set": function () {}
    }
  },
  "cssNumber": {
    "animationIterationCount": {},
    "columnCount": {},
    "fillOpacity": {},
    "flexGrow": {},
    "flexShrink": {},
    "fontWeight": {},
    "gridArea": {},
    "gridColumn": {},
    "gridColumnEnd": {},
    "gridColumnStart": {},
    "gridRow": {},
    "gridRowEnd": {},
    "gridRowStart": {},
    "lineHeight": {},
    "opacity": {},
    "order": {},
    "orphans": {},
    "widows": {},
    "zIndex": {},
    "zoom": {}
  },
  "cssProps": {},
  "data": function () {},
  "dequeue": function () {},
  "each": function () {},
  "easing": {
    "_default": {},
    "linear": function () {},
    "swing": function () {}
  },
  "error": function () {},
  "escapeSelector": function () {},
  "etag": {},
  "event": {
    "add": function () {},
    "addProp": function () {},
    "dispatch": function () {},
    "fix": function () {},
    "global": {},
    "handlers": function () {},
    "remove": function () {},
    "simulate": function () {},
    "special": {
      "beforeunload": {
        "postDispatch": function () {}
      },
      "blur": {
        "delegateType": {},
        "setup": function () {},
        "trigger": function () {}
      },
      "click": {
        "_default": function () {},
        "setup": function () {},
        "trigger": function () {}
      },
      "focus": {
        "delegateType": {},
        "setup": function () {},
        "trigger": function () {}
      },
      "focusin": {
        "setup": function () {},
        "teardown": function () {}
      },
      "focusout": {
        "setup": function () {},
        "teardown": function () {}
      },
      "load": {
        "noBubble": {}
      },
      "mouseenter": {
        "bindType": {},
        "delegateType": {},
        "handle": function () {}
      },
      "mouseleave": {
        "bindType": {},
        "delegateType": {},
        "handle": function () {}
      },
      "pointerenter": {
        "bindType": {},
        "delegateType": {},
        "handle": function () {}
      },
      "pointerleave": {
        "bindType": {},
        "delegateType": {},
        "handle": function () {}
      }
    },
    "trigger": function () {}
  },
  "expando": {},
  "expr": {
    ":": {
      "animated": function () {},
      "button": function () {},
      "checkbox": function () {},
      "checked": function () {},
      "contains": {
        "sizzle1556227954583": {}
      },
      "disabled": function () {},
      "empty": function () {},
      "enabled": function () {},
      "eq": {
        "sizzle1556227954583": {}
      },
      "even": {
        "sizzle1556227954583": {}
      },
      "file": function () {},
      "first": {
        "sizzle1556227954583": {}
      },
      "focus": function () {},
      "gt": {
        "sizzle1556227954583": {}
      },
      "has": {
        "sizzle1556227954583": {}
      },
      "header": function () {},
      "hidden": function () {},
      "image": function () {},
      "input": function () {},
      "lang": {
        "sizzle1556227954583": {}
      },
      "last": {
        "sizzle1556227954583": {}
      },
      "lt": {
        "sizzle1556227954583": {}
      },
      "not": {
        "sizzle1556227954583": {}
      },
      "nth": {
        "sizzle1556227954583": {}
      },
      "odd": {
        "sizzle1556227954583": {}
      },
      "parent": function () {},
      "password": function () {},
      "radio": function () {},
      "reset": function () {},
      "root": function () {},
      "selected": function () {},
      "submit": function () {},
      "target": function () {},
      "text": function () {},
      "visible": function () {}
    },
    "attrHandle": {
      "async": function () {},
      "autofocus": function () {},
      "autoplay": function () {},
      "checked": function () {},
      "controls": function () {},
      "defer": function () {},
      "disabled": function () {},
      "hidden": function () {},
      "ismap": function () {},
      "loop": function () {},
      "multiple": function () {},
      "open": function () {},
      "readonly": function () {},
      "required": function () {},
      "scoped": function () {},
      "selected": function () {}
    },
    "cacheLength": {},
    "createPseudo": function () {},
    "filter": {
      "ATTR": function () {},
      "CHILD": function () {},
      "CLASS": function () {},
      "ID": function () {},
      "PSEUDO": function () {},
      "TAG": function () {}
    },
    "filters": {
      "animated": function () {},
      "button": function () {},
      "checkbox": function () {},
      "checked": function () {},
      "contains": {
        "sizzle1556227954583": {}
      },
      "disabled": function () {},
      "empty": function () {},
      "enabled": function () {},
      "eq": {
        "sizzle1556227954583": {}
      },
      "even": {
        "sizzle1556227954583": {}
      },
      "file": function () {},
      "first": {
        "sizzle1556227954583": {}
      },
      "focus": function () {},
      "gt": {
        "sizzle1556227954583": {}
      },
      "has": {
        "sizzle1556227954583": {}
      },
      "header": function () {},
      "hidden": function () {},
      "image": function () {},
      "input": function () {},
      "lang": {
        "sizzle1556227954583": {}
      },
      "last": {
        "sizzle1556227954583": {}
      },
      "lt": {
        "sizzle1556227954583": {}
      },
      "not": {
        "sizzle1556227954583": {}
      },
      "nth": {
        "sizzle1556227954583": {}
      },
      "odd": {
        "sizzle1556227954583": {}
      },
      "parent": function () {},
      "password": function () {},
      "radio": function () {},
      "reset": function () {},
      "root": function () {},
      "selected": function () {},
      "submit": function () {},
      "target": function () {},
      "text": function () {},
      "visible": function () {}
    },
    "find": {
      "CLASS": function () {},
      "ID": function () {},
      "TAG": function () {}
    },
    "match": {
      "ATTR": {},
      "CHILD": {},
      "CLASS": {},
      "ID": {},
      "PSEUDO": {},
      "TAG": {},
      "bool": {},
      "needsContext": {}
    },
    "preFilter": {
      "ATTR": function () {},
      "CHILD": function () {},
      "PSEUDO": function () {}
    },
    "pseudos": {
      "animated": function () {},
      "button": function () {},
      "checkbox": function () {},
      "checked": function () {},
      "contains": {
        "sizzle1556227954583": {}
      },
      "disabled": function () {},
      "empty": function () {},
      "enabled": function () {},
      "eq": {
        "sizzle1556227954583": {}
      },
      "even": {
        "sizzle1556227954583": {}
      },
      "file": function () {},
      "first": {
        "sizzle1556227954583": {}
      },
      "focus": function () {},
      "gt": {
        "sizzle1556227954583": {}
      },
      "has": {
        "sizzle1556227954583": {}
      },
      "header": function () {},
      "hidden": function () {},
      "image": function () {},
      "input": function () {},
      "lang": {
        "sizzle1556227954583": {}
      },
      "last": {
        "sizzle1556227954583": {}
      },
      "lt": {
        "sizzle1556227954583": {}
      },
      "not": {
        "sizzle1556227954583": {}
      },
      "nth": {
        "sizzle1556227954583": {}
      },
      "odd": {
        "sizzle1556227954583": {}
      },
      "parent": function () {},
      "password": function () {},
      "radio": function () {},
      "reset": function () {},
      "root": function () {},
      "selected": function () {},
      "submit": function () {},
      "target": function () {},
      "text": function () {},
      "visible": function () {}
    },
    "relative": {
      " ": {
        "dir": {}
      },
      "+": {
        "dir": {},
        "first": {}
      },
      ">": {
        "dir": {},
        "first": {}
      },
      "~": {
        "dir": {}
      }
    },
    "setFilters": {
      "animated": function () {},
      "button": function () {},
      "checkbox": function () {},
      "checked": function () {},
      "contains": {
        "sizzle1556227954583": {}
      },
      "disabled": function () {},
      "empty": function () {},
      "enabled": function () {},
      "eq": {
        "sizzle1556227954583": {}
      },
      "even": {
        "sizzle1556227954583": {}
      },
      "file": function () {},
      "first": {
        "sizzle1556227954583": {}
      },
      "focus": function () {},
      "gt": {
        "sizzle1556227954583": {}
      },
      "has": {
        "sizzle1556227954583": {}
      },
      "header": function () {},
      "hidden": function () {},
      "image": function () {},
      "input": function () {},
      "lang": {
        "sizzle1556227954583": {}
      },
      "last": {
        "sizzle1556227954583": {}
      },
      "lt": {
        "sizzle1556227954583": {}
      },
      "not": {
        "sizzle1556227954583": {}
      },
      "nth": {
        "sizzle1556227954583": {}
      },
      "odd": {
        "sizzle1556227954583": {}
      },
      "parent": function () {},
      "password": function () {},
      "radio": function () {},
      "reset": function () {},
      "root": function () {},
      "selected": function () {},
      "submit": function () {},
      "target": function () {},
      "text": function () {},
      "visible": function () {}
    }
  },
  "extend": function () {},
  "filter": function () {},
  "find": {
    "attr": function () {},
    "compile": function () {},
    "contains": function () {},
    "error": function () {},
    "escape": function () {},
    "getText": function () {},
    "isXML": function () {},
    "matches": function () {},
    "matchesSelector": function () {},
    "select": function () {},
    "selectors": {
      ":": {
        "animated": function () {},
        "button": function () {},
        "checkbox": function () {},
        "checked": function () {},
        "contains": {
          "sizzle1556227954583": {}
        },
        "disabled": function () {},
        "empty": function () {},
        "enabled": function () {},
        "eq": {
          "sizzle1556227954583": {}
        },
        "even": {
          "sizzle1556227954583": {}
        },
        "file": function () {},
        "first": {
          "sizzle1556227954583": {}
        },
        "focus": function () {},
        "gt": {
          "sizzle1556227954583": {}
        },
        "has": {
          "sizzle1556227954583": {}
        },
        "header": function () {},
        "hidden": function () {},
        "image": function () {},
        "input": function () {},
        "lang": {
          "sizzle1556227954583": {}
        },
        "last": {
          "sizzle1556227954583": {}
        },
        "lt": {
          "sizzle1556227954583": {}
        },
        "not": {
          "sizzle1556227954583": {}
        },
        "nth": {
          "sizzle1556227954583": {}
        },
        "odd": {
          "sizzle1556227954583": {}
        },
        "parent": function () {},
        "password": function () {},
        "radio": function () {},
        "reset": function () {},
        "root": function () {},
        "selected": function () {},
        "submit": function () {},
        "target": function () {},
        "text": function () {},
        "visible": function () {}
      },
      "attrHandle": {
        "async": function () {},
        "autofocus": function () {},
        "autoplay": function () {},
        "checked": function () {},
        "controls": function () {},
        "defer": function () {},
        "disabled": function () {},
        "hidden": function () {},
        "ismap": function () {},
        "loop": function () {},
        "multiple": function () {},
        "open": function () {},
        "readonly": function () {},
        "required": function () {},
        "scoped": function () {},
        "selected": function () {}
      },
      "cacheLength": {},
      "createPseudo": function () {},
      "filter": {
        "ATTR": function () {},
        "CHILD": function () {},
        "CLASS": function () {},
        "ID": function () {},
        "PSEUDO": function () {},
        "TAG": function () {}
      },
      "filters": {
        "animated": function () {},
        "button": function () {},
        "checkbox": function () {},
        "checked": function () {},
        "contains": {
          "sizzle1556227954583": {}
        },
        "disabled": function () {},
        "empty": function () {},
        "enabled": function () {},
        "eq": {
          "sizzle1556227954583": {}
        },
        "even": {
          "sizzle1556227954583": {}
        },
        "file": function () {},
        "first": {
          "sizzle1556227954583": {}
        },
        "focus": function () {},
        "gt": {
          "sizzle1556227954583": {}
        },
        "has": {
          "sizzle1556227954583": {}
        },
        "header": function () {},
        "hidden": function () {},
        "image": function () {},
        "input": function () {},
        "lang": {
          "sizzle1556227954583": {}
        },
        "last": {
          "sizzle1556227954583": {}
        },
        "lt": {
          "sizzle1556227954583": {}
        },
        "not": {
          "sizzle1556227954583": {}
        },
        "nth": {
          "sizzle1556227954583": {}
        },
        "odd": {
          "sizzle1556227954583": {}
        },
        "parent": function () {},
        "password": function () {},
        "radio": function () {},
        "reset": function () {},
        "root": function () {},
        "selected": function () {},
        "submit": function () {},
        "target": function () {},
        "text": function () {},
        "visible": function () {}
      },
      "find": {
        "CLASS": function () {},
        "ID": function () {},
        "TAG": function () {}
      },
      "match": {
        "ATTR": {},
        "CHILD": {},
        "CLASS": {},
        "ID": {},
        "PSEUDO": {},
        "TAG": {},
        "bool": {},
        "needsContext": {}
      },
      "preFilter": {
        "ATTR": function () {},
        "CHILD": function () {},
        "PSEUDO": function () {}
      },
      "pseudos": {
        "animated": function () {},
        "button": function () {},
        "checkbox": function () {},
        "checked": function () {},
        "contains": {
          "sizzle1556227954583": {}
        },
        "disabled": function () {},
        "empty": function () {},
        "enabled": function () {},
        "eq": {
          "sizzle1556227954583": {}
        },
        "even": {
          "sizzle1556227954583": {}
        },
        "file": function () {},
        "first": {
          "sizzle1556227954583": {}
        },
        "focus": function () {},
        "gt": {
          "sizzle1556227954583": {}
        },
        "has": {
          "sizzle1556227954583": {}
        },
        "header": function () {},
        "hidden": function () {},
        "image": function () {},
        "input": function () {},
        "lang": {
          "sizzle1556227954583": {}
        },
        "last": {
          "sizzle1556227954583": {}
        },
        "lt": {
          "sizzle1556227954583": {}
        },
        "not": {
          "sizzle1556227954583": {}
        },
        "nth": {
          "sizzle1556227954583": {}
        },
        "odd": {
          "sizzle1556227954583": {}
        },
        "parent": function () {},
        "password": function () {},
        "radio": function () {},
        "reset": function () {},
        "root": function () {},
        "selected": function () {},
        "submit": function () {},
        "target": function () {},
        "text": function () {},
        "visible": function () {}
      },
      "relative": {
        " ": {
          "dir": {}
        },
        "+": {
          "dir": {},
          "first": {}
        },
        ">": {
          "dir": {},
          "first": {}
        },
        "~": {
          "dir": {}
        }
      },
      "setFilters": {
        "animated": function () {},
        "button": function () {},
        "checkbox": function () {},
        "checked": function () {},
        "contains": {
          "sizzle1556227954583": {}
        },
        "disabled": function () {},
        "empty": function () {},
        "enabled": function () {},
        "eq": {
          "sizzle1556227954583": {}
        },
        "even": {
          "sizzle1556227954583": {}
        },
        "file": function () {},
        "first": {
          "sizzle1556227954583": {}
        },
        "focus": function () {},
        "gt": {
          "sizzle1556227954583": {}
        },
        "has": {
          "sizzle1556227954583": {}
        },
        "header": function () {},
        "hidden": function () {},
        "image": function () {},
        "input": function () {},
        "lang": {
          "sizzle1556227954583": {}
        },
        "last": {
          "sizzle1556227954583": {}
        },
        "lt": {
          "sizzle1556227954583": {}
        },
        "not": {
          "sizzle1556227954583": {}
        },
        "nth": {
          "sizzle1556227954583": {}
        },
        "odd": {
          "sizzle1556227954583": {}
        },
        "parent": function () {},
        "password": function () {},
        "radio": function () {},
        "reset": function () {},
        "root": function () {},
        "selected": function () {},
        "submit": function () {},
        "target": function () {},
        "text": function () {},
        "visible": function () {}
      }
    },
    "setDocument": function () {},
    "support": {
      "attributes": {},
      "detectDuplicates": {},
      "disconnectedMatch": {},
      "getById": {},
      "getElementsByClassName": {},
      "getElementsByTagName": {},
      "matchesSelector": {},
      "qsa": {},
      "sortDetached": {},
      "sortStable": {}
    },
    "tokenize": function () {},
    "uniqueSort": function () {}
  },
  "fn": {
    "add": function () {},
    "addBack": function () {},
    "addClass": function () {},
    "after": function () {},
    "ajaxComplete": function () {},
    "ajaxError": function () {},
    "ajaxSend": function () {},
    "ajaxStart": function () {},
    "ajaxStop": function () {},
    "ajaxSuccess": function () {},
    "animate": function () {},
    "append": function () {},
    "appendTo": function () {},
    "attr": function () {},
    "before": function () {},
    "bind": function () {},
    "blur": function () {},
    "change": function () {},
    "children": function () {},
    "clearQueue": function () {},
    "click": function () {},
    "clone": function () {},
    "closest": function () {},
    "constructor": {
      "Animation": {
        "prefilter": function () {},
        "prefilters": {},
        "tweener": function () {},
        "tweeners": {
          "*": {}
        }
      },
      "Callbacks": function () {},
      "Deferred": {
        "exceptionHook": function () {}
      },
      "Event": function () {},
      "Tween": {
        "propHooks": {
          "_default": {
            "get": function () {},
            "set": function () {}
          },
          "scrollLeft": {
            "set": function () {}
          },
          "scrollTop": {
            "set": function () {}
          }
        }
      },
      "_data": function () {},
      "_evalUrl": function () {},
      "_queueHooks": function () {},
      "_removeData": function () {},
      "active": {},
      "ajax": function () {},
      "ajaxPrefilter": function () {},
      "ajaxSettings": {
        "accepts": {
          "*": {},
          "html": {},
          "json": {},
          "script": {},
          "text": {},
          "xml": {}
        },
        "async": {},
        "contentType": {},
        "contents": {
          "html": {},
          "json": {},
          "script": {},
          "xml": {}
        },
        "converters": {
          "* text": function () {},
          "text html": {},
          "text json": function () {},
          "text script": function () {},
          "text xml": function () {}
        },
        "flatOptions": {
          "context": {},
          "url": {}
        },
        "global": {},
        "isLocal": {},
        "jsonp": {},
        "jsonpCallback": function () {},
        "processData": {},
        "responseFields": {
          "json": {},
          "text": {},
          "xml": {}
        },
        "type": {},
        "url": {},
        "xhr": function () {}
      },
      "ajaxSetup": function () {},
      "ajaxTransport": function () {},
      "attr": function () {},
      "attrHooks": {
        "type": {
          "set": function () {}
        }
      },
      "camelCase": function () {},
      "cleanData": function () {},
      "clone": function () {},
      "contains": function () {},
      "css": function () {},
      "cssHooks": {
        "borderWidth": {
          "expand": function () {},
          "set": function () {}
        },
        "height": {
          "get": function () {},
          "set": function () {}
        },
        "left": {
          "get": function () {}
        },
        "margin": {
          "expand": function () {}
        },
        "marginLeft": {
          "get": function () {}
        },
        "opacity": {
          "get": function () {}
        },
        "padding": {
          "expand": function () {},
          "set": function () {}
        },
        "top": {
          "get": function () {}
        },
        "width": {
          "get": function () {},
          "set": function () {}
        }
      },
      "cssNumber": {
        "animationIterationCount": {},
        "columnCount": {},
        "fillOpacity": {},
        "flexGrow": {},
        "flexShrink": {},
        "fontWeight": {},
        "gridArea": {},
        "gridColumn": {},
        "gridColumnEnd": {},
        "gridColumnStart": {},
        "gridRow": {},
        "gridRowEnd": {},
        "gridRowStart": {},
        "lineHeight": {},
        "opacity": {},
        "order": {},
        "orphans": {},
        "widows": {},
        "zIndex": {},
        "zoom": {}
      },
      "cssProps": {},
      "data": function () {},
      "dequeue": function () {},
      "each": function () {},
      "easing": {
        "_default": {},
        "linear": function () {},
        "swing": function () {}
      },
      "error": function () {},
      "escapeSelector": function () {},
      "etag": {},
      "event": {
        "add": function () {},
        "addProp": function () {},
        "dispatch": function () {},
        "fix": function () {},
        "global": {},
        "handlers": function () {},
        "remove": function () {},
        "simulate": function () {},
        "special": {
          "beforeunload": {
            "postDispatch": function () {}
          },
          "blur": {
            "delegateType": {},
            "setup": function () {},
            "trigger": function () {}
          },
          "click": {
            "_default": function () {},
            "setup": function () {},
            "trigger": function () {}
          },
          "focus": {
            "delegateType": {},
            "setup": function () {},
            "trigger": function () {}
          },
          "focusin": {
            "setup": function () {},
            "teardown": function () {}
          },
          "focusout": {
            "setup": function () {},
            "teardown": function () {}
          },
          "load": {
            "noBubble": {}
          },
          "mouseenter": {
            "bindType": {},
            "delegateType": {},
            "handle": function () {}
          },
          "mouseleave": {
            "bindType": {},
            "delegateType": {},
            "handle": function () {}
          },
          "pointerenter": {
            "bindType": {},
            "delegateType": {},
            "handle": function () {}
          },
          "pointerleave": {
            "bindType": {},
            "delegateType": {},
            "handle": function () {}
          }
        },
        "trigger": function () {}
      },
      "expando": {},
      "expr": {
        ":": {
          "animated": function () {},
          "button": function () {},
          "checkbox": function () {},
          "checked": function () {},
          "contains": {
            "sizzle1556227954583": {}
          },
          "disabled": function () {},
          "empty": function () {},
          "enabled": function () {},
          "eq": {
            "sizzle1556227954583": {}
          },
          "even": {
            "sizzle1556227954583": {}
          },
          "file": function () {},
          "first": {
            "sizzle1556227954583": {}
          },
          "focus": function () {},
          "gt": {
            "sizzle1556227954583": {}
          },
          "has": {
            "sizzle1556227954583": {}
          },
          "header": function () {},
          "hidden": function () {},
          "image": function () {},
          "input": function () {},
          "lang": {
            "sizzle1556227954583": {}
          },
          "last": {
            "sizzle1556227954583": {}
          },
          "lt": {
            "sizzle1556227954583": {}
          },
          "not": {
            "sizzle1556227954583": {}
          },
          "nth": {
            "sizzle1556227954583": {}
          },
          "odd": {
            "sizzle1556227954583": {}
          },
          "parent": function () {},
          "password": function () {},
          "radio": function () {},
          "reset": function () {},
          "root": function () {},
          "selected": function () {},
          "submit": function () {},
          "target": function () {},
          "text": function () {},
          "visible": function () {}
        },
        "attrHandle": {
          "async": function () {},
          "autofocus": function () {},
          "autoplay": function () {},
          "checked": function () {},
          "controls": function () {},
          "defer": function () {},
          "disabled": function () {},
          "hidden": function () {},
          "ismap": function () {},
          "loop": function () {},
          "multiple": function () {},
          "open": function () {},
          "readonly": function () {},
          "required": function () {},
          "scoped": function () {},
          "selected": function () {}
        },
        "cacheLength": {},
        "createPseudo": function () {},
        "filter": {
          "ATTR": function () {},
          "CHILD": function () {},
          "CLASS": function () {},
          "ID": function () {},
          "PSEUDO": function () {},
          "TAG": function () {}
        },
        "filters": {
          "animated": function () {},
          "button": function () {},
          "checkbox": function () {},
          "checked": function () {},
          "contains": {
            "sizzle1556227954583": {}
          },
          "disabled": function () {},
          "empty": function () {},
          "enabled": function () {},
          "eq": {
            "sizzle1556227954583": {}
          },
          "even": {
            "sizzle1556227954583": {}
          },
          "file": function () {},
          "first": {
            "sizzle1556227954583": {}
          },
          "focus": function () {},
          "gt": {
            "sizzle1556227954583": {}
          },
          "has": {
            "sizzle1556227954583": {}
          },
          "header": function () {},
          "hidden": function () {},
          "image": function () {},
          "input": function () {},
          "lang": {
            "sizzle1556227954583": {}
          },
          "last": {
            "sizzle1556227954583": {}
          },
          "lt": {
            "sizzle1556227954583": {}
          },
          "not": {
            "sizzle1556227954583": {}
          },
          "nth": {
            "sizzle1556227954583": {}
          },
          "odd": {
            "sizzle1556227954583": {}
          },
          "parent": function () {},
          "password": function () {},
          "radio": function () {},
          "reset": function () {},
          "root": function () {},
          "selected": function () {},
          "submit": function () {},
          "target": function () {},
          "text": function () {},
          "visible": function () {}
        },
        "find": {
          "CLASS": function () {},
          "ID": function () {},
          "TAG": function () {}
        },
        "match": {
          "ATTR": {},
          "CHILD": {},
          "CLASS": {},
          "ID": {},
          "PSEUDO": {},
          "TAG": {},
          "bool": {},
          "needsContext": {}
        },
        "preFilter": {
          "ATTR": function () {},
          "CHILD": function () {},
          "PSEUDO": function () {}
        },
        "pseudos": {
          "animated": function () {},
          "button": function () {},
          "checkbox": function () {},
          "checked": function () {},
          "contains": {
            "sizzle1556227954583": {}
          },
          "disabled": function () {},
          "empty": function () {},
          "enabled": function () {},
          "eq": {
            "sizzle1556227954583": {}
          },
          "even": {
            "sizzle1556227954583": {}
          },
          "file": function () {},
          "first": {
            "sizzle1556227954583": {}
          },
          "focus": function () {},
          "gt": {
            "sizzle1556227954583": {}
          },
          "has": {
            "sizzle1556227954583": {}
          },
          "header": function () {},
          "hidden": function () {},
          "image": function () {},
          "input": function () {},
          "lang": {
            "sizzle1556227954583": {}
          },
          "last": {
            "sizzle1556227954583": {}
          },
          "lt": {
            "sizzle1556227954583": {}
          },
          "not": {
            "sizzle1556227954583": {}
          },
          "nth": {
            "sizzle1556227954583": {}
          },
          "odd": {
            "sizzle1556227954583": {}
          },
          "parent": function () {},
          "password": function () {},
          "radio": function () {},
          "reset": function () {},
          "root": function () {},
          "selected": function () {},
          "submit": function () {},
          "target": function () {},
          "text": function () {},
          "visible": function () {}
        },
        "relative": {
          " ": {
            "dir": {}
          },
          "+": {
            "dir": {},
            "first": {}
          },
          ">": {
            "dir": {},
            "first": {}
          },
          "~": {
            "dir": {}
          }
        },
        "setFilters": {
          "animated": function () {},
          "button": function () {},
          "checkbox": function () {},
          "checked": function () {},
          "contains": {
            "sizzle1556227954583": {}
          },
          "disabled": function () {},
          "empty": function () {},
          "enabled": function () {},
          "eq": {
            "sizzle1556227954583": {}
          },
          "even": {
            "sizzle1556227954583": {}
          },
          "file": function () {},
          "first": {
            "sizzle1556227954583": {}
          },
          "focus": function () {},
          "gt": {
            "sizzle1556227954583": {}
          },
          "has": {
            "sizzle1556227954583": {}
          },
          "header": function () {},
          "hidden": function () {},
          "image": function () {},
          "input": function () {},
          "lang": {
            "sizzle1556227954583": {}
          },
          "last": {
            "sizzle1556227954583": {}
          },
          "lt": {
            "sizzle1556227954583": {}
          },
          "not": {
            "sizzle1556227954583": {}
          },
          "nth": {
            "sizzle1556227954583": {}
          },
          "odd": {
            "sizzle1556227954583": {}
          },
          "parent": function () {},
          "password": function () {},
          "radio": function () {},
          "reset": function () {},
          "root": function () {},
          "selected": function () {},
          "submit": function () {},
          "target": function () {},
          "text": function () {},
          "visible": function () {}
        }
      },
      "extend": function () {},
      "filter": function () {},
      "find": {
        "attr": function () {},
        "compile": function () {},
        "contains": function () {},
        "error": function () {},
        "escape": function () {},
        "getText": function () {},
        "isXML": function () {},
        "matches": function () {},
        "matchesSelector": function () {},
        "select": function () {},
        "selectors": {
          ":": {
            "animated": function () {},
            "button": function () {},
            "checkbox": function () {},
            "checked": function () {},
            "contains": {
              "sizzle1556227954583": {}
            },
            "disabled": function () {},
            "empty": function () {},
            "enabled": function () {},
            "eq": {
              "sizzle1556227954583": {}
            },
            "even": {
              "sizzle1556227954583": {}
            },
            "file": function () {},
            "first": {
              "sizzle1556227954583": {}
            },
            "focus": function () {},
            "gt": {
              "sizzle1556227954583": {}
            },
            "has": {
              "sizzle1556227954583": {}
            },
            "header": function () {},
            "hidden": function () {},
            "image": function () {},
            "input": function () {},
            "lang": {
              "sizzle1556227954583": {}
            },
            "last": {
              "sizzle1556227954583": {}
            },
            "lt": {
              "sizzle1556227954583": {}
            },
            "not": {
              "sizzle1556227954583": {}
            },
            "nth": {
              "sizzle1556227954583": {}
            },
            "odd": {
              "sizzle1556227954583": {}
            },
            "parent": function () {},
            "password": function () {},
            "radio": function () {},
            "reset": function () {},
            "root": function () {},
            "selected": function () {},
            "submit": function () {},
            "target": function () {},
            "text": function () {},
            "visible": function () {}
          },
          "attrHandle": {
            "async": function () {},
            "autofocus": function () {},
            "autoplay": function () {},
            "checked": function () {},
            "controls": function () {},
            "defer": function () {},
            "disabled": function () {},
            "hidden": function () {},
            "ismap": function () {},
            "loop": function () {},
            "multiple": function () {},
            "open": function () {},
            "readonly": function () {},
            "required": function () {},
            "scoped": function () {},
            "selected": function () {}
          },
          "cacheLength": {},
          "createPseudo": function () {},
          "filter": {
            "ATTR": function () {},
            "CHILD": function () {},
            "CLASS": function () {},
            "ID": function () {},
            "PSEUDO": function () {},
            "TAG": function () {}
          },
          "filters": {
            "animated": function () {},
            "button": function () {},
            "checkbox": function () {},
            "checked": function () {},
            "contains": {
              "sizzle1556227954583": {}
            },
            "disabled": function () {},
            "empty": function () {},
            "enabled": function () {},
            "eq": {
              "sizzle1556227954583": {}
            },
            "even": {
              "sizzle1556227954583": {}
            },
            "file": function () {},
            "first": {
              "sizzle1556227954583": {}
            },
            "focus": function () {},
            "gt": {
              "sizzle1556227954583": {}
            },
            "has": {
              "sizzle1556227954583": {}
            },
            "header": function () {},
            "hidden": function () {},
            "image": function () {},
            "input": function () {},
            "lang": {
              "sizzle1556227954583": {}
            },
            "last": {
              "sizzle1556227954583": {}
            },
            "lt": {
              "sizzle1556227954583": {}
            },
            "not": {
              "sizzle1556227954583": {}
            },
            "nth": {
              "sizzle1556227954583": {}
            },
            "odd": {
              "sizzle1556227954583": {}
            },
            "parent": function () {},
            "password": function () {},
            "radio": function () {},
            "reset": function () {},
            "root": function () {},
            "selected": function () {},
            "submit": function () {},
            "target": function () {},
            "text": function () {},
            "visible": function () {}
          },
          "find": {
            "CLASS": function () {},
            "ID": function () {},
            "TAG": function () {}
          },
          "match": {
            "ATTR": {},
            "CHILD": {},
            "CLASS": {},
            "ID": {},
            "PSEUDO": {},
            "TAG": {},
            "bool": {},
            "needsContext": {}
          },
          "preFilter": {
            "ATTR": function () {},
            "CHILD": function () {},
            "PSEUDO": function () {}
          },
          "pseudos": {
            "animated": function () {},
            "button": function () {},
            "checkbox": function () {},
            "checked": function () {},
            "contains": {
              "sizzle1556227954583": {}
            },
            "disabled": function () {},
            "empty": function () {},
            "enabled": function () {},
            "eq": {
              "sizzle1556227954583": {}
            },
            "even": {
              "sizzle1556227954583": {}
            },
            "file": function () {},
            "first": {
              "sizzle1556227954583": {}
            },
            "focus": function () {},
            "gt": {
              "sizzle1556227954583": {}
            },
            "has": {
              "sizzle1556227954583": {}
            },
            "header": function () {},
            "hidden": function () {},
            "image": function () {},
            "input": function () {},
            "lang": {
              "sizzle1556227954583": {}
            },
            "last": {
              "sizzle1556227954583": {}
            },
            "lt": {
              "sizzle1556227954583": {}
            },
            "not": {
              "sizzle1556227954583": {}
            },
            "nth": {
              "sizzle1556227954583": {}
            },
            "odd": {
              "sizzle1556227954583": {}
            },
            "parent": function () {},
            "password": function () {},
            "radio": function () {},
            "reset": function () {},
            "root": function () {},
            "selected": function () {},
            "submit": function () {},
            "target": function () {},
            "text": function () {},
            "visible": function () {}
          },
          "relative": {
            " ": {
              "dir": {}
            },
            "+": {
              "dir": {},
              "first": {}
            },
            ">": {
              "dir": {},
              "first": {}
            },
            "~": {
              "dir": {}
            }
          },
          "setFilters": {
            "animated": function () {},
            "button": function () {},
            "checkbox": function () {},
            "checked": function () {},
            "contains": {
              "sizzle1556227954583": {}
            },
            "disabled": function () {},
            "empty": function () {},
            "enabled": function () {},
            "eq": {
              "sizzle1556227954583": {}
            },
            "even": {
              "sizzle1556227954583": {}
            },
            "file": function () {},
            "first": {
              "sizzle1556227954583": {}
            },
            "focus": function () {},
            "gt": {
              "sizzle1556227954583": {}
            },
            "has": {
              "sizzle1556227954583": {}
            },
            "header": function () {},
            "hidden": function () {},
            "image": function () {},
            "input": function () {},
            "lang": {
              "sizzle1556227954583": {}
            },
            "last": {
              "sizzle1556227954583": {}
            },
            "lt": {
              "sizzle1556227954583": {}
            },
            "not": {
              "sizzle1556227954583": {}
            },
            "nth": {
              "sizzle1556227954583": {}
            },
            "odd": {
              "sizzle1556227954583": {}
            },
            "parent": function () {},
            "password": function () {},
            "radio": function () {},
            "reset": function () {},
            "root": function () {},
            "selected": function () {},
            "submit": function () {},
            "target": function () {},
            "text": function () {},
            "visible": function () {}
          }
        },
        "setDocument": function () {},
        "support": {
          "attributes": {},
          "detectDuplicates": {},
          "disconnectedMatch": {},
          "getById": {},
          "getElementsByClassName": {},
          "getElementsByTagName": {},
          "matchesSelector": {},
          "qsa": {},
          "sortDetached": {},
          "sortStable": {}
        },
        "tokenize": function () {},
        "uniqueSort": function () {}
      },
      "fn": {},
      "fx": {
        "interval": {},
        "speeds": {
          "_default": {},
          "fast": {},
          "slow": {}
        },
        "start": function () {},
        "step": {},
        "stop": function () {},
        "tick": function () {},
        "timer": function () {}
      },
      "get": function () {},
      "getJSON": function () {},
      "getScript": function () {},
      "globalEval": function () {},
      "grep": function () {},
      "guid": {},
      "hasData": function () {},
      "holdReady": function () {},
      "htmlPrefilter": function () {},
      "inArray": function () {},
      "isArray": function () {},
      "isEmptyObject": function () {},
      "isFunction": function () {},
      "isNumeric": function () {},
      "isPlainObject": function () {},
      "isReady": {},
      "isWindow": function () {},
      "isXMLDoc": function () {},
      "lastModified": {},
      "makeArray": function () {},
      "map": function () {},
      "merge": function () {},
      "noConflict": function () {},
      "nodeName": function () {},
      "noop": function () {},
      "now": function () {},
      "offset": {
        "setOffset": function () {}
      },
      "param": function () {},
      "parseHTML": function () {},
      "parseJSON": function () {},
      "parseXML": function () {},
      "post": function () {},
      "prop": function () {},
      "propFix": {
        "cellpadding": {},
        "cellspacing": {},
        "class": {},
        "colspan": {},
        "contenteditable": {},
        "for": {},
        "frameborder": {},
        "maxlength": {},
        "readonly": {},
        "rowspan": {},
        "tabindex": {},
        "usemap": {}
      },
      "propHooks": {
        "tabIndex": {
          "get": function () {}
        }
      },
      "proxy": function () {},
      "queue": function () {},
      "ready": {
        "then": function () {}
      },
      "readyException": function () {},
      "readyWait": {},
      "removeAttr": function () {},
      "removeData": function () {},
      "removeEvent": function () {},
      "speed": function () {},
      "style": function () {},
      "support": {
        "ajax": {},
        "boxSizingReliable": function () {},
        "checkClone": {},
        "checkOn": {},
        "clearCloneStyle": {},
        "cors": {},
        "createHTMLDocument": {},
        "focusin": {},
        "noCloneChecked": {},
        "optSelected": {},
        "pixelBoxStyles": function () {},
        "pixelPosition": function () {},
        "radioValue": {},
        "reliableMarginLeft": function () {},
        "scrollboxSize": function () {}
      },
      "text": function () {},
      "timers": {},
      "trim": function () {},
      "type": function () {},
      "unique": function () {},
      "uniqueSort": function () {},
      "valHooks": {
        "checkbox": {
          "set": function () {}
        },
        "option": {
          "get": function () {}
        },
        "radio": {
          "set": function () {}
        },
        "select": {
          "get": function () {},
          "set": function () {}
        }
      },
      "when": function () {}
    },
    "contents": function () {},
    "contextmenu": function () {},
    "css": function () {},
    "data": function () {},
    "dblclick": function () {},
    "delay": function () {},
    "delegate": function () {},
    "dequeue": function () {},
    "detach": function () {},
    "each": function () {},
    "empty": function () {},
    "end": function () {},
    "eq": function () {},
    "extend": function () {},
    "fadeIn": function () {},
    "fadeOut": function () {},
    "fadeTo": function () {},
    "fadeToggle": function () {},
    "filter": function () {},
    "find": function () {},
    "finish": function () {},
    "first": function () {},
    "focus": function () {},
    "focusin": function () {},
    "focusout": function () {},
    "get": function () {},
    "has": function () {},
    "hasClass": function () {},
    "height": function () {},
    "hide": function () {},
    "hover": function () {},
    "html": function () {},
    "index": function () {},
    "init": function () {},
    "innerHeight": function () {},
    "innerWidth": function () {},
    "insertAfter": function () {},
    "insertBefore": function () {},
    "is": function () {},
    "jquery": {},
    "keydown": function () {},
    "keypress": function () {},
    "keyup": function () {},
    "last": function () {},
    "length": {},
    "load": function () {},
    "map": function () {},
    "mousedown": function () {},
    "mouseenter": function () {},
    "mouseleave": function () {},
    "mousemove": function () {},
    "mouseout": function () {},
    "mouseover": function () {},
    "mouseup": function () {},
    "next": function () {},
    "nextAll": function () {},
    "nextUntil": function () {},
    "not": function () {},
    "off": function () {},
    "offset": function () {},
    "offsetParent": function () {},
    "on": function () {},
    "one": function () {},
    "outerHeight": function () {},
    "outerWidth": function () {},
    "parent": function () {},
    "parents": function () {},
    "parentsUntil": function () {},
    "position": function () {},
    "prepend": function () {},
    "prependTo": function () {},
    "prev": function () {},
    "prevAll": function () {},
    "prevUntil": function () {},
    "promise": function () {},
    "prop": function () {},
    "push": function () {},
    "pushStack": function () {},
    "queue": function () {},
    "ready": function () {},
    "remove": function () {},
    "removeAttr": function () {},
    "removeClass": function () {},
    "removeData": function () {},
    "removeProp": function () {},
    "replaceAll": function () {},
    "replaceWith": function () {},
    "resize": function () {},
    "scroll": function () {},
    "scrollLeft": function () {},
    "scrollTop": function () {},
    "select": function () {},
    "serialize": function () {},
    "serializeArray": function () {},
    "show": function () {},
    "siblings": function () {},
    "slice": function () {},
    "slideDown": function () {},
    "slideToggle": function () {},
    "slideUp": function () {},
    "sort": function () {},
    "splice": function () {},
    "stop": function () {},
    "submit": function () {},
    "text": function () {},
    "toArray": function () {},
    "toggle": function () {},
    "toggleClass": function () {},
    "trigger": function () {},
    "triggerHandler": function () {},
    "unbind": function () {},
    "undelegate": function () {},
    "unwrap": function () {},
    "val": function () {},
    "width": function () {},
    "wrap": function () {},
    "wrapAll": function () {},
    "wrapInner": function () {}
  },
  "fx": {
    "interval": {},
    "speeds": {
      "_default": {},
      "fast": {},
      "slow": {}
    },
    "start": function () {},
    "step": {},
    "stop": function () {},
    "tick": function () {},
    "timer": function () {}
  },
  "get": function () {},
  "getJSON": function () {},
  "getScript": function () {},
  "globalEval": function () {},
  "grep": function () {},
  "guid": {},
  "hasData": function () {},
  "holdReady": function () {},
  "htmlPrefilter": function () {},
  "inArray": function () {},
  "isArray": function () {},
  "isEmptyObject": function () {},
  "isFunction": function () {},
  "isNumeric": function () {},
  "isPlainObject": function () {},
  "isReady": {},
  "isWindow": function () {},
  "isXMLDoc": function () {},
  "lastModified": {},
  "makeArray": function () {},
  "map": function () {},
  "merge": function () {},
  "noConflict": function () {},
  "nodeName": function () {},
  "noop": function () {},
  "now": function () {},
  "offset": {
    "setOffset": function () {}
  },
  "param": function () {},
  "parseHTML": function () {},
  "parseJSON": function () {},
  "parseXML": function () {},
  "post": function () {},
  "prop": function () {},
  "propFix": {
    "cellpadding": {},
    "cellspacing": {},
    "class": {},
    "colspan": {},
    "contenteditable": {},
    "for": {},
    "frameborder": {},
    "maxlength": {},
    "readonly": {},
    "rowspan": {},
    "tabindex": {},
    "usemap": {}
  },
  "propHooks": {
    "tabIndex": {
      "get": function () {}
    }
  },
  "proxy": function () {},
  "queue": function () {},
  "ready": {
    "then": function () {}
  },
  "readyException": function () {},
  "readyWait": {},
  "removeAttr": function () {},
  "removeData": function () {},
  "removeEvent": function () {},
  "speed": function () {},
  "style": function () {},
  "support": {
    "ajax": {},
    "boxSizingReliable": function () {},
    "checkClone": {},
    "checkOn": {},
    "clearCloneStyle": {},
    "cors": {},
    "createHTMLDocument": {},
    "focusin": {},
    "noCloneChecked": {},
    "optSelected": {},
    "pixelBoxStyles": function () {},
    "pixelPosition": function () {},
    "radioValue": {},
    "reliableMarginLeft": function () {},
    "scrollboxSize": function () {}
  },
  "text": function () {},
  "timers": {},
  "trim": function () {},
  "type": function () {},
  "unique": function () {},
  "uniqueSort": function () {},
  "valHooks": {
    "checkbox": {
      "set": function () {}
    },
    "option": {
      "get": function () {}
    },
    "radio": {
      "set": function () {}
    },
    "select": {
      "get": function () {},
      "set": function () {}
    }
  },
  "when": function () {}
};
jQuery.prototype = {
  "add": function () {},
  "addBack": function () {},
  "addClass": function () {},
  "after": function () {},
  "ajaxComplete": function () {},
  "ajaxError": function () {},
  "ajaxSend": function () {},
  "ajaxStart": function () {},
  "ajaxStop": function () {},
  "ajaxSuccess": function () {},
  "animate": function () {},
  "append": function () {},
  "appendTo": function () {},
  "attr": function () {},
  "before": function () {},
  "bind": function () {},
  "blur": function () {},
  "change": function () {},
  "children": function () {},
  "clearQueue": function () {},
  "click": function () {},
  "clone": function () {},
  "closest": function () {},
  "constructor": function () {},
  "contents": function () {},
  "contextmenu": function () {},
  "css": function () {},
  "data": function () {},
  "dblclick": function () {},
  "delay": function () {},
  "delegate": function () {},
  "dequeue": function () {},
  "detach": function () {},
  "each": function () {},
  "empty": function () {},
  "end": function () {},
  "eq": function () {},
  "extend": function () {},
  "fadeIn": function () {},
  "fadeOut": function () {},
  "fadeTo": function () {},
  "fadeToggle": function () {},
  "filter": function () {},
  "find": function () {},
  "finish": function () {},
  "first": function () {},
  "focus": function () {},
  "focusin": function () {},
  "focusout": function () {},
  "get": function () {},
  "has": function () {},
  "hasClass": function () {},
  "height": function () {},
  "hide": function () {},
  "hover": function () {},
  "html": function () {},
  "index": function () {},
  "init": function () {},
  "innerHeight": function () {},
  "innerWidth": function () {},
  "insertAfter": function () {},
  "insertBefore": function () {},
  "is": function () {},
  "jquery": function () {},
  "keydown": function () {},
  "keypress": function () {},
  "keyup": function () {},
  "last": function () {},
  "length": function () {},
  "load": function () {},
  "map": function () {},
  "mousedown": function () {},
  "mouseenter": function () {},
  "mouseleave": function () {},
  "mousemove": function () {},
  "mouseout": function () {},
  "mouseover": function () {},
  "mouseup": function () {},
  "next": function () {},
  "nextAll": function () {},
  "nextUntil": function () {},
  "not": function () {},
  "off": function () {},
  "offset": function () {},
  "offsetParent": function () {},
  "on": function () {},
  "one": function () {},
  "outerHeight": function () {},
  "outerWidth": function () {},
  "parent": function () {},
  "parents": function () {},
  "parentsUntil": function () {},
  "position": function () {},
  "prepend": function () {},
  "prependTo": function () {},
  "prev": function () {},
  "prevAll": function () {},
  "prevUntil": function () {},
  "promise": function () {},
  "prop": function () {},
  "push": function () {},
  "pushStack": function () {},
  "queue": function () {},
  "ready": function () {},
  "remove": function () {},
  "removeAttr": function () {},
  "removeClass": function () {},
  "removeData": function () {},
  "removeProp": function () {},
  "replaceAll": function () {},
  "replaceWith": function () {},
  "resize": function () {},
  "scroll": function () {},
  "scrollLeft": function () {},
  "scrollTop": function () {},
  "select": function () {},
  "serialize": function () {},
  "serializeArray": function () {},
  "show": function () {},
  "siblings": function () {},
  "slice": function () {},
  "slideDown": function () {},
  "slideToggle": function () {},
  "slideUp": function () {},
  "sort": function () {},
  "splice": function () {},
  "stop": function () {},
  "submit": function () {},
  "text": function () {},
  "toArray": function () {},
  "toggle": function () {},
  "toggleClass": function () {},
  "trigger": function () {},
  "triggerHandler": function () {},
  "unbind": function () {},
  "undelegate": function () {},
  "unwrap": function () {},
  "val": function () {},
  "width": function () {},
  "wrap": function () {},
  "wrapAll": function () {},
  "wrapInner": function () {}
};
jQuery.Event.prototype = {
  "altKey": function () {},
  "bubbles": function () {},
  "button": function () {},
  "buttons": function () {},
  "cancelable": function () {},
  "changedTouches": function () {},
  "char": function () {},
  "charCode": function () {},
  "clientX": function () {},
  "clientY": function () {},
  "code": function () {},
  "constructor": function () {},
  "ctrlKey": function () {},
  "detail": function () {},
  "eventPhase": function () {},
  "isDefaultPrevented": function () {},
  "isImmediatePropagationStopped": function () {},
  "isPropagationStopped": function () {},
  "isSimulated": function () {},
  "key": function () {},
  "keyCode": function () {},
  "metaKey": function () {},
  "offsetX": function () {},
  "offsetY": function () {},
  "pageX": function () {},
  "pageY": function () {},
  "pointerId": function () {},
  "pointerType": function () {},
  "preventDefault": function () {},
  "screenX": function () {},
  "screenY": function () {},
  "shiftKey": function () {},
  "stopImmediatePropagation": function () {},
  "stopPropagation": function () {},
  "targetTouches": function () {},
  "toElement": function () {},
  "touches": function () {},
  "view": function () {},
  "which": function () {}
};
jQuery.Tween.prototype = {
  "constructor": function () {},
  "cur": function () {},
  "init": function () {},
  "run": function () {}
};
jQuery.fn.constructor.prototype = {
  "add": function () {},
  "addBack": function () {},
  "addClass": function () {},
  "after": function () {},
  "ajaxComplete": function () {},
  "ajaxError": function () {},
  "ajaxSend": function () {},
  "ajaxStart": function () {},
  "ajaxStop": function () {},
  "ajaxSuccess": function () {},
  "animate": function () {},
  "append": function () {},
  "appendTo": function () {},
  "attr": function () {},
  "before": function () {},
  "bind": function () {},
  "blur": function () {},
  "change": function () {},
  "children": function () {},
  "clearQueue": function () {},
  "click": function () {},
  "clone": function () {},
  "closest": function () {},
  "constructor": function () {},
  "contents": function () {},
  "contextmenu": function () {},
  "css": function () {},
  "data": function () {},
  "dblclick": function () {},
  "delay": function () {},
  "delegate": function () {},
  "dequeue": function () {},
  "detach": function () {},
  "each": function () {},
  "empty": function () {},
  "end": function () {},
  "eq": function () {},
  "extend": function () {},
  "fadeIn": function () {},
  "fadeOut": function () {},
  "fadeTo": function () {},
  "fadeToggle": function () {},
  "filter": function () {},
  "find": function () {},
  "finish": function () {},
  "first": function () {},
  "focus": function () {},
  "focusin": function () {},
  "focusout": function () {},
  "get": function () {},
  "has": function () {},
  "hasClass": function () {},
  "height": function () {},
  "hide": function () {},
  "hover": function () {},
  "html": function () {},
  "index": function () {},
  "init": function () {},
  "innerHeight": function () {},
  "innerWidth": function () {},
  "insertAfter": function () {},
  "insertBefore": function () {},
  "is": function () {},
  "jquery": function () {},
  "keydown": function () {},
  "keypress": function () {},
  "keyup": function () {},
  "last": function () {},
  "length": function () {},
  "load": function () {},
  "map": function () {},
  "mousedown": function () {},
  "mouseenter": function () {},
  "mouseleave": function () {},
  "mousemove": function () {},
  "mouseout": function () {},
  "mouseover": function () {},
  "mouseup": function () {},
  "next": function () {},
  "nextAll": function () {},
  "nextUntil": function () {},
  "not": function () {},
  "off": function () {},
  "offset": function () {},
  "offsetParent": function () {},
  "on": function () {},
  "one": function () {},
  "outerHeight": function () {},
  "outerWidth": function () {},
  "parent": function () {},
  "parents": function () {},
  "parentsUntil": function () {},
  "position": function () {},
  "prepend": function () {},
  "prependTo": function () {},
  "prev": function () {},
  "prevAll": function () {},
  "prevUntil": function () {},
  "promise": function () {},
  "prop": function () {},
  "push": function () {},
  "pushStack": function () {},
  "queue": function () {},
  "ready": function () {},
  "remove": function () {},
  "removeAttr": function () {},
  "removeClass": function () {},
  "removeData": function () {},
  "removeProp": function () {},
  "replaceAll": function () {},
  "replaceWith": function () {},
  "resize": function () {},
  "scroll": function () {},
  "scrollLeft": function () {},
  "scrollTop": function () {},
  "select": function () {},
  "serialize": function () {},
  "serializeArray": function () {},
  "show": function () {},
  "siblings": function () {},
  "slice": function () {},
  "slideDown": function () {},
  "slideToggle": function () {},
  "slideUp": function () {},
  "sort": function () {},
  "splice": function () {},
  "stop": function () {},
  "submit": function () {},
  "text": function () {},
  "toArray": function () {},
  "toggle": function () {},
  "toggleClass": function () {},
  "trigger": function () {},
  "triggerHandler": function () {},
  "unbind": function () {},
  "undelegate": function () {},
  "unwrap": function () {},
  "val": function () {},
  "width": function () {},
  "wrap": function () {},
  "wrapAll": function () {},
  "wrapInner": function () {}
};
jQuery.fn.constructor.Event.prototype = {
  "altKey": function () {},
  "bubbles": function () {},
  "button": function () {},
  "buttons": function () {},
  "cancelable": function () {},
  "changedTouches": function () {},
  "char": function () {},
  "charCode": function () {},
  "clientX": function () {},
  "clientY": function () {},
  "code": function () {},
  "constructor": function () {},
  "ctrlKey": function () {},
  "detail": function () {},
  "eventPhase": function () {},
  "isDefaultPrevented": function () {},
  "isImmediatePropagationStopped": function () {},
  "isPropagationStopped": function () {},
  "isSimulated": function () {},
  "key": function () {},
  "keyCode": function () {},
  "metaKey": function () {},
  "offsetX": function () {},
  "offsetY": function () {},
  "pageX": function () {},
  "pageY": function () {},
  "pointerId": function () {},
  "pointerType": function () {},
  "preventDefault": function () {},
  "screenX": function () {},
  "screenY": function () {},
  "shiftKey": function () {},
  "stopImmediatePropagation": function () {},
  "stopPropagation": function () {},
  "targetTouches": function () {},
  "toElement": function () {},
  "touches": function () {},
  "view": function () {},
  "which": function () {}
};
jQuery.fn.constructor.Tween.prototype = {
  "constructor": function () {},
  "cur": function () {},
  "init": function () {},
  "run": function () {}
};
jQuery.fn.constructor.fx.prototype = {
  "constructor": function () {},
  "cur": function () {},
  "init": function () {},
  "run": function () {}
};
jQuery.fn.init.prototype = {
  "add": function () {},
  "addBack": function () {},
  "addClass": function () {},
  "after": function () {},
  "ajaxComplete": function () {},
  "ajaxError": function () {},
  "ajaxSend": function () {},
  "ajaxStart": function () {},
  "ajaxStop": function () {},
  "ajaxSuccess": function () {},
  "animate": function () {},
  "append": function () {},
  "appendTo": function () {},
  "attr": function () {},
  "before": function () {},
  "bind": function () {},
  "blur": function () {},
  "change": function () {},
  "children": function () {},
  "clearQueue": function () {},
  "click": function () {},
  "clone": function () {},
  "closest": function () {},
  "constructor": function () {},
  "contents": function () {},
  "contextmenu": function () {},
  "css": function () {},
  "data": function () {},
  "dblclick": function () {},
  "delay": function () {},
  "delegate": function () {},
  "dequeue": function () {},
  "detach": function () {},
  "each": function () {},
  "empty": function () {},
  "end": function () {},
  "eq": function () {},
  "extend": function () {},
  "fadeIn": function () {},
  "fadeOut": function () {},
  "fadeTo": function () {},
  "fadeToggle": function () {},
  "filter": function () {},
  "find": function () {},
  "finish": function () {},
  "first": function () {},
  "focus": function () {},
  "focusin": function () {},
  "focusout": function () {},
  "get": function () {},
  "has": function () {},
  "hasClass": function () {},
  "height": function () {},
  "hide": function () {},
  "hover": function () {},
  "html": function () {},
  "index": function () {},
  "init": function () {},
  "innerHeight": function () {},
  "innerWidth": function () {},
  "insertAfter": function () {},
  "insertBefore": function () {},
  "is": function () {},
  "jquery": function () {},
  "keydown": function () {},
  "keypress": function () {},
  "keyup": function () {},
  "last": function () {},
  "length": function () {},
  "load": function () {},
  "map": function () {},
  "mousedown": function () {},
  "mouseenter": function () {},
  "mouseleave": function () {},
  "mousemove": function () {},
  "mouseout": function () {},
  "mouseover": function () {},
  "mouseup": function () {},
  "next": function () {},
  "nextAll": function () {},
  "nextUntil": function () {},
  "not": function () {},
  "off": function () {},
  "offset": function () {},
  "offsetParent": function () {},
  "on": function () {},
  "one": function () {},
  "outerHeight": function () {},
  "outerWidth": function () {},
  "parent": function () {},
  "parents": function () {},
  "parentsUntil": function () {},
  "position": function () {},
  "prepend": function () {},
  "prependTo": function () {},
  "prev": function () {},
  "prevAll": function () {},
  "prevUntil": function () {},
  "promise": function () {},
  "prop": function () {},
  "push": function () {},
  "pushStack": function () {},
  "queue": function () {},
  "ready": function () {},
  "remove": function () {},
  "removeAttr": function () {},
  "removeClass": function () {},
  "removeData": function () {},
  "removeProp": function () {},
  "replaceAll": function () {},
  "replaceWith": function () {},
  "resize": function () {},
  "scroll": function () {},
  "scrollLeft": function () {},
  "scrollTop": function () {},
  "select": function () {},
  "serialize": function () {},
  "serializeArray": function () {},
  "show": function () {},
  "siblings": function () {},
  "slice": function () {},
  "slideDown": function () {},
  "slideToggle": function () {},
  "slideUp": function () {},
  "sort": function () {},
  "splice": function () {},
  "stop": function () {},
  "submit": function () {},
  "text": function () {},
  "toArray": function () {},
  "toggle": function () {},
  "toggleClass": function () {},
  "trigger": function () {},
  "triggerHandler": function () {},
  "unbind": function () {},
  "undelegate": function () {},
  "unwrap": function () {},
  "val": function () {},
  "width": function () {},
  "wrap": function () {},
  "wrapAll": function () {},
  "wrapInner": function () {}
};
jQuery.fx.prototype = {
  "constructor": function () {},
  "cur": function () {},
  "init": function () {},
  "run": function () {}
};
/**********************************************************************
 * End Generated Extern for jQuery
/**********************************************************************/