var MediumEditor = {
  "extensions": {},
  "util": {},
  "Extension": {
    "extend": function () {}
  },
  "selection": {},
  "Events": function () {},
  "parseVersionString": function () {},
  "version": {}
};
MediumEditor.prototype = {
  "init": function () {},
  "setup": function () {},
  "destroy": function () {},
  "on": function () {},
  "off": function () {},
  "subscribe": function () {},
  "unsubscribe": function () {},
  "trigger": function () {},
  "delay": function () {},
  "serialize": function () {},
  "getExtensionByName": function () {},
  "addBuiltInExtension": function () {},
  "stopSelectionUpdates": function () {},
  "startSelectionUpdates": function () {},
  "checkSelection": function () {},
  "queryCommandState": function () {},
  "execAction": function () {},
  "getSelectedParentElement": function () {},
  "selectAllContents": function () {},
  "selectElement": function () {},
  "getFocusedElement": function () {},
  "exportSelection": function () {},
  "saveSelection": function () {},
  "importSelection": function () {},
  "restoreSelection": function () {},
  "createLink": function () {},
  "cleanPaste": function () {},
  "pasteHTML": function () {},
  "setContent": function () {},
  "defaults": function () {}
};
MediumEditor.Extension.prototype = {
  "init": function () {},
  "base": function () {},
  "name": function () {},
  "checkState": function () {},
  "destroy": function () {},
  "queryCommandState": function () {},
  "isActive": function () {},
  "isAlreadyApplied": function () {},
  "setActive": function () {},
  "setInactive": function () {},
  "window": function () {},
  "document": function () {},
  "getEditorElements": function () {},
  "getEditorId": function () {},
  "getEditorOption": function () {},
  "execAction": function () {},
  "on": function () {},
  "off": function () {},
  "subscribe": function () {},
  "trigger": function () {}
};
MediumEditor.Events.prototype = {
  "InputEventOnContenteditableSupported": function () {},
  "attachDOMEvent": function () {},
  "detachDOMEvent": function () {},
  "indexOfListener": function () {},
  "detachAllDOMEvents": function () {},
  "enableCustomEvent": function () {},
  "disableCustomEvent": function () {},
  "attachCustomEvent": function () {},
  "detachCustomEvent": function () {},
  "indexOfCustomListener": function () {},
  "detachAllCustomEvents": function () {},
  "triggerCustomEvent": function () {},
  "destroy": function () {},
  "attachToExecCommand": function () {},
  "detachExecCommand": function () {},
  "wrapExecCommand": function () {},
  "unwrapExecCommand": function () {},
  "setupListener": function () {},
  "attachToEachElement": function () {},
  "focusElement": function () {},
  "updateFocus": function () {},
  "updateInput": function () {},
  "handleDocumentSelectionChange": function () {},
  "handleDocumentExecCommand": function () {},
  "handleBodyClick": function () {},
  "handleBodyFocus": function () {},
  "handleBodyMousedown": function () {},
  "handleInput": function () {},
  "handleClick": function () {},
  "handleBlur": function () {},
  "handleKeypress": function () {},
  "handleKeyup": function () {},
  "handleMouseover": function () {},
  "handleDragging": function () {},
  "handleDrop": function () {},
  "handlePaste": function () {},
  "handleKeydown": function () {}
};