// Generated via externs generator
// Step 1: add react: https://cdnjs.cloudflare.com/ajax/libs/react/15.3.0/react.js
// Step 2: add react-dom: https://cdnjs.cloudflare.com/ajax/libs/react/15.3.0/react-dom.js
// Step 3: add lib: https://raw.githubusercontent.com/Pomax/react-onclickoutside/v4.9.0/index.js
// Reference ns OnClickOutside
/**********************************************************************
  * Extern for OnClickOutside
  * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var OnClickOutside = {
    "componentDidMount": function () {},
    "componentWillUnmount": function () {},
    "enableOnClickOutside": function () {},
    "disableOnClickOutside": function () {}
};
/**********************************************************************
  * End Generated Extern for OnClickOutside
 /**********************************************************************/
