/**********************************************************************
 * Extern for onClickOutside
 * Generated by http://jmmk.github.io/javascript-externs-generator
 * Loaded JavaScripts:
     https://unpkg.com/react@16.3.1/umd/react.production.min.js
     https://unpkg.com/react-dom@16.3.1/umd/react-dom.production.min.js
     https://unpkg.com/react-onclickoutside@6.7.1/dist/react-onclickoutside.min.js
 **********************************************************************/
var onClickOutside = {
    "IGNORE_CLASS_NAME": {},
    "default": function () {}
};
/**********************************************************************
 * End Generated Extern for onClickOutside
/**********************************************************************/
