// Generated with javascript-externs-generator
// Source: <https://code.createjs.com/soundjs-0.6.2.min.js>
// Main namespace: createjs

var createjs = {
  "SoundJS": {},
  "extend": function () {},
  "promote": function () {},
  "indexOf": function () {},
  "proxy": function () {},
  "BrowserDetect": {
    "agent": {},
    "isWindowPhone": {},
    "isFirefox": {},
    "isOpera": {},
    "isChrome": {},
    "isIOS": {},
    "isAndroid": {},
    "isBlackberry": {}
  },
  "EventDispatcher": {
    "initialize": function () {}
  },
  "Event": function () {},
  "ErrorEvent": function () {},
  "ProgressEvent": function () {},
  "LoadItem": {
    "LOAD_TIMEOUT_DEFAULT": {},
    "create": function () {}
  },
  "RequestUtils": {},
  "AbstractLoader": {
    "POST": {},
    "GET": {},
    "BINARY": {},
    "CSS": {},
    "IMAGE": {},
    "JAVASCRIPT": {},
    "JSON": {},
    "JSONP": {},
    "MANIFEST": {},
    "SOUND": {},
    "VIDEO": {},
    "SPRITESHEET": {},
    "SVG": {},
    "TEXT": {},
    "XML": {}
  },
  "AbstractMediaLoader": function () {},
  "AbstractRequest": function () {},
  "TagRequest": function () {},
  "MediaTagRequest": function () {},
  "XHRRequest": {
    "ACTIVEX_VERSIONS": {}
  },
  "SoundLoader": {
    "canLoadItem": function () {}
  },
  "PlayPropsConfig": {
    "create": function () {}
  },
  "Sound": {
    "INTERRUPT_ANY": {},
    "INTERRUPT_EARLY": {},
    "INTERRUPT_LATE": {},
    "INTERRUPT_NONE": {},
    "PLAY_INITED": {},
    "PLAY_SUCCEEDED": {},
    "PLAY_INTERRUPTED": {},
    "PLAY_FINISHED": {},
    "PLAY_FAILED": {},
    "SUPPORTED_EXTENSIONS": {},
    "EXTENSION_MAP": {},
    "FILE_PATTERN": {},
    "defaultInterruptBehavior": {},
    "alternateExtensions": {},
    "activePlugin": {},
    "_masterVolume": {},
    "_masterMute": {},
    "_pluginsRegistered": {},
    "_lastID": {},
    "_instances": {},
    "_idHash": {},
    "_preloadHash": {},
    "_defaultPlayPropsHash": {},
    "addEventListener": function () {},
    "removeEventListener": function () {},
    "removeAllEventListeners": function () {},
    "dispatchEvent": function () {},
    "hasEventListener": function () {},
    "_listeners": {},
    "on": function () {},
    "off": function () {},
    "_dispatchEvent": function () {},
    "willTrigger": function () {},
    "getPreloadHandlers": function () {},
    "_handleLoadComplete": function () {},
    "_handleLoadError": function () {},
    "_registerPlugin": function () {},
    "registerPlugins": function () {},
    "initializeDefaultPlugins": function () {},
    "isReady": function () {},
    "getCapabilities": function () {},
    "getCapability": function () {},
    "initLoad": function () {},
    "_registerSound": function () {},
    "registerSound": function () {},
    "registerSounds": function () {},
    "removeSound": function () {},
    "removeSounds": function () {},
    "removeAllSounds": function () {},
    "loadComplete": function () {},
    "_parsePath": function () {},
    "_parseSrc": function () {},
    "play": function () {},
    "createInstance": function () {},
    "stop": function () {},
    "setVolume": function () {},
    "getVolume": function () {},
    "setMute": function () {},
    "getMute": function () {},
    "setDefaultPlayProps": function () {},
    "getDefaultPlayProps": function () {},
    "_playInstance": function () {},
    "_beginPlaying": function () {},
    "_getSrcById": function () {},
    "_playFinished": function () {}
  },
  "AbstractSoundInstance": function () {},
  "DefaultSoundInstance": function () {},
  "AbstractPlugin": {
    "_capabilities": {},
    "isSupported": function () {}
  },
  "WebAudioLoader": {
    "context": {}
  },
  "WebAudioSoundInstance": {
    "context": {},
    "_scratchBuffer": {},
    "destinationNode": {},
    "_panningModel": {}
  },
  "WebAudioPlugin": {
    "_capabilities": {},
    "_panningModel": {},
    "context": {},
    "_scratchBuffer": {},
    "_unlocked": {},
    "isSupported": function () {},
    "playEmptySound": function () {},
    "_isFileXHRSupported": function () {},
    "_generateCapabilities": function () {},
    "_compatibilitySetUp": function () {},
    "_unlock": function () {}
  },
  "HTMLAudioTagPool": {
    "_tags": {},
    "_tagPool": {},
    "_tagUsed": {},
    "get": function () {},
    "set": function () {},
    "remove": function () {},
    "getDuration": function () {}
  },
  "HTMLAudioSoundInstance": function () {},
  "HTMLAudioPlugin": {
    "MAX_INSTANCES": {},
    "_AUDIO_READY": {},
    "_AUDIO_ENDED": {},
    "_AUDIO_SEEKED": {},
    "_AUDIO_STALLED": {},
    "_TIME_UPDATE": {},
    "_capabilities": {},
    "isSupported": function () {},
    "_generateCapabilities": function () {}
  }
};
createjs.EventDispatcher.prototype = {
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "toString": function () {},
  "_dispatchEvent": function () {}
};
createjs.Event.prototype = {
  "preventDefault": function () {},
  "stopPropagation": function () {},
  "stopImmediatePropagation": function () {},
  "remove": function () {},
  "clone": function () {},
  "set": function () {},
  "toString": function () {}
};
createjs.ErrorEvent.prototype = {
  "constructor": function () {},
  "clone": function () {},
  "Event_constructor": function () {},
  "Event_clone": function () {},
  "preventDefault": function () {},
  "stopPropagation": function () {},
  "stopImmediatePropagation": function () {},
  "remove": function () {},
  "set": function () {},
  "toString": function () {}
};
createjs.ProgressEvent.prototype = {
  "constructor": function () {},
  "clone": function () {},
  "Event_constructor": function () {},
  "Event_clone": function () {},
  "preventDefault": function () {},
  "stopPropagation": function () {},
  "stopImmediatePropagation": function () {},
  "remove": function () {},
  "set": function () {},
  "toString": function () {}
};
createjs.LoadItem.prototype = {
  "set": function () {}
};
createjs.AbstractLoader.prototype = {
  "constructor": function () {},
  "getItem": function () {},
  "getResult": function () {},
  "getTag": function () {},
  "setTag": function () {},
  "load": function () {},
  "cancel": function () {},
  "destroy": function () {},
  "getLoadedItems": function () {},
  "_createRequest": function () {},
  "_createTag": function () {},
  "_sendLoadStart": function () {},
  "_sendProgress": function () {},
  "_sendComplete": function () {},
  "_sendError": function () {},
  "_isCanceled": function () {},
  "resultFormatter": function () {},
  "handleEvent": function () {},
  "_resultFormatSuccess": function () {},
  "_resultFormatFailed": function () {},
  "buildPath": function () {},
  "toString": function () {},
  "EventDispatcher_constructor": function () {},
  "EventDispatcher_toString": function () {},
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "_dispatchEvent": function () {}
};
createjs.AbstractMediaLoader.prototype = {
  "constructor": function () {},
  "load": function () {},
  "_createTag": function () {},
  "_createRequest": function () {},
  "_updateXHR": function () {},
  "_formatResult": function () {},
  "AbstractLoader_constructor": function () {},
  "AbstractLoader_load": function () {},
  "AbstractLoader__createRequest": function () {},
  "AbstractLoader__createTag": function () {},
  "getItem": function () {},
  "getResult": function () {},
  "getTag": function () {},
  "setTag": function () {},
  "cancel": function () {},
  "destroy": function () {},
  "getLoadedItems": function () {},
  "_sendLoadStart": function () {},
  "_sendProgress": function () {},
  "_sendComplete": function () {},
  "_sendError": function () {},
  "_isCanceled": function () {},
  "resultFormatter": function () {},
  "handleEvent": function () {},
  "_resultFormatSuccess": function () {},
  "_resultFormatFailed": function () {},
  "buildPath": function () {},
  "toString": function () {},
  "EventDispatcher_constructor": function () {},
  "EventDispatcher_toString": function () {},
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "_dispatchEvent": function () {}
};
createjs.AbstractRequest.prototype = {
  "constructor": function () {},
  "load": function () {},
  "destroy": function () {},
  "cancel": function () {},
  "EventDispatcher_constructor": function () {},
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "toString": function () {},
  "_dispatchEvent": function () {}
};
createjs.TagRequest.prototype = {
  "constructor": function () {},
  "load": function () {},
  "destroy": function () {},
  "_handleReadyStateChange": function () {},
  "_handleError": function () {},
  "_handleTagComplete": function () {},
  "_handleTimeout": function () {},
  "_clean": function () {},
  "_hideTag": function () {},
  "_showTag": function () {},
  "_handleStalled": function () {},
  "AbstractRequest_constructor": function () {},
  "AbstractRequest_load": function () {},
  "AbstractRequest_destroy": function () {},
  "cancel": function () {},
  "EventDispatcher_constructor": function () {},
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "toString": function () {},
  "_dispatchEvent": function () {}
};
createjs.MediaTagRequest.prototype = {
  "constructor": function () {},
  "load": function () {},
  "_handleReadyStateChange": function () {},
  "_handleStalled": function () {},
  "_handleProgress": function () {},
  "_clean": function () {},
  "TagRequest_constructor": function () {},
  "TagRequest_load": function () {},
  "TagRequest__handleReadyStateChange": function () {},
  "TagRequest__clean": function () {},
  "TagRequest__handleStalled": function () {},
  "destroy": function () {},
  "_handleError": function () {},
  "_handleTagComplete": function () {},
  "_handleTimeout": function () {},
  "_hideTag": function () {},
  "_showTag": function () {},
  "AbstractRequest_constructor": function () {},
  "AbstractRequest_load": function () {},
  "AbstractRequest_destroy": function () {},
  "cancel": function () {},
  "EventDispatcher_constructor": function () {},
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "toString": function () {},
  "_dispatchEvent": function () {}
};
createjs.XHRRequest.prototype = {
  "constructor": function () {},
  "getResult": function () {},
  "cancel": function () {},
  "load": function () {},
  "setResponseType": function () {},
  "getAllResponseHeaders": function () {},
  "getResponseHeader": function () {},
  "_handleProgress": function () {},
  "_handleLoadStart": function () {},
  "_handleAbort": function () {},
  "_handleError": function () {},
  "_handleReadyStateChange": function () {},
  "_handleLoad": function () {},
  "_handleTimeout": function () {},
  "_checkError": function () {},
  "_getResponse": function () {},
  "_createXHR": function () {},
  "_clean": function () {},
  "toString": function () {},
  "AbstractRequest_constructor": function () {},
  "AbstractRequest_load": function () {},
  "AbstractRequest_cancel": function () {},
  "AbstractRequest_toString": function () {},
  "destroy": function () {},
  "EventDispatcher_constructor": function () {},
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "_dispatchEvent": function () {}
};
createjs.SoundLoader.prototype = {
  "constructor": function () {},
  "_createTag": function () {},
  "AbstractMediaLoader_constructor": function () {},
  "AbstractMediaLoader__createTag": function () {},
  "load": function () {},
  "_createRequest": function () {},
  "_updateXHR": function () {},
  "_formatResult": function () {},
  "AbstractLoader_constructor": function () {},
  "AbstractLoader_load": function () {},
  "AbstractLoader__createRequest": function () {},
  "AbstractLoader__createTag": function () {},
  "getItem": function () {},
  "getResult": function () {},
  "getTag": function () {},
  "setTag": function () {},
  "cancel": function () {},
  "destroy": function () {},
  "getLoadedItems": function () {},
  "_sendLoadStart": function () {},
  "_sendProgress": function () {},
  "_sendComplete": function () {},
  "_sendError": function () {},
  "_isCanceled": function () {},
  "resultFormatter": function () {},
  "handleEvent": function () {},
  "_resultFormatSuccess": function () {},
  "_resultFormatFailed": function () {},
  "buildPath": function () {},
  "toString": function () {},
  "EventDispatcher_constructor": function () {},
  "EventDispatcher_toString": function () {},
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "_dispatchEvent": function () {}
};
createjs.PlayPropsConfig.prototype = {
  "set": function () {},
  "toString": function () {}
};
createjs.AbstractSoundInstance.prototype = {
  "constructor": function () {},
  "play": function () {},
  "stop": function () {},
  "destroy": function () {},
  "applyPlayProps": function () {},
  "toString": function () {},
  "getPaused": function () {},
  "setPaused": function () {},
  "setVolume": function () {},
  "getVolume": function () {},
  "setMuted": function () {},
  "getMuted": function () {},
  "setPan": function () {},
  "getPan": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getStartTime": function () {},
  "setStartTime": function () {},
  "getDuration": function () {},
  "setDuration": function () {},
  "setPlaybackResource": function () {},
  "getPlaybackResource": function () {},
  "getLoop": function () {},
  "setLoop": function () {},
  "_sendEvent": function () {},
  "_cleanUp": function () {},
  "_interrupt": function () {},
  "_beginPlaying": function () {},
  "_playFailed": function () {},
  "_handleSoundComplete": function () {},
  "_handleSoundReady": function () {},
  "_updateVolume": function () {},
  "_updatePan": function () {},
  "_updateStartTime": function () {},
  "_updateDuration": function () {},
  "_setDurationFromSource": function () {},
  "_calculateCurrentPosition": function () {},
  "_updatePosition": function () {},
  "_removeLooping": function () {},
  "_addLooping": function () {},
  "_pause": function () {},
  "_resume": function () {},
  "_handleStop": function () {},
  "_handleCleanUp": function () {},
  "_handleLoop": function () {},
  "EventDispatcher_constructor": function () {},
  "EventDispatcher_toString": function () {},
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "_dispatchEvent": function () {}
};
createjs.DefaultSoundInstance.prototype = {
  "constructor": function () {},
  "play": function () {},
  "stop": function () {},
  "destroy": function () {},
  "applyPlayProps": function () {},
  "toString": function () {},
  "getPaused": function () {},
  "setPaused": function () {},
  "setVolume": function () {},
  "getVolume": function () {},
  "setMuted": function () {},
  "getMuted": function () {},
  "setPan": function () {},
  "getPan": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getStartTime": function () {},
  "setStartTime": function () {},
  "getDuration": function () {},
  "setDuration": function () {},
  "setPlaybackResource": function () {},
  "getPlaybackResource": function () {},
  "getLoop": function () {},
  "setLoop": function () {},
  "_sendEvent": function () {},
  "_cleanUp": function () {},
  "_interrupt": function () {},
  "_beginPlaying": function () {},
  "_playFailed": function () {},
  "_handleSoundComplete": function () {},
  "_handleSoundReady": function () {},
  "_updateVolume": function () {},
  "_updatePan": function () {},
  "_updateStartTime": function () {},
  "_updateDuration": function () {},
  "_setDurationFromSource": function () {},
  "_calculateCurrentPosition": function () {},
  "_updatePosition": function () {},
  "_removeLooping": function () {},
  "_addLooping": function () {},
  "_pause": function () {},
  "_resume": function () {},
  "_handleStop": function () {},
  "_handleCleanUp": function () {},
  "_handleLoop": function () {},
  "EventDispatcher_constructor": function () {},
  "EventDispatcher_toString": function () {},
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "_dispatchEvent": function () {}
};
createjs.AbstractPlugin.prototype = {
  "register": function () {},
  "preload": function () {},
  "isPreloadStarted": function () {},
  "isPreloadComplete": function () {},
  "removeSound": function () {},
  "removeAllSounds": function () {},
  "create": function () {},
  "setVolume": function () {},
  "getVolume": function () {},
  "setMute": function () {},
  "toString": function () {},
  "_handlePreloadComplete": function () {},
  "_handlePreloadError": function () {},
  "_updateVolume": function () {}
};
createjs.WebAudioLoader.prototype = {
  "constructor": function () {},
  "toString": function () {},
  "_createRequest": function () {},
  "_sendComplete": function () {},
  "_handleAudioDecoded": function () {},
  "AbstractLoader_constructor": function () {},
  "AbstractLoader__createRequest": function () {},
  "AbstractLoader__sendComplete": function () {},
  "AbstractLoader_toString": function () {},
  "getItem": function () {},
  "getResult": function () {},
  "getTag": function () {},
  "setTag": function () {},
  "load": function () {},
  "cancel": function () {},
  "destroy": function () {},
  "getLoadedItems": function () {},
  "_createTag": function () {},
  "_sendLoadStart": function () {},
  "_sendProgress": function () {},
  "_sendError": function () {},
  "_isCanceled": function () {},
  "resultFormatter": function () {},
  "handleEvent": function () {},
  "_resultFormatSuccess": function () {},
  "_resultFormatFailed": function () {},
  "buildPath": function () {},
  "EventDispatcher_constructor": function () {},
  "EventDispatcher_toString": function () {},
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "_dispatchEvent": function () {}
};
createjs.WebAudioSoundInstance.prototype = {
  "constructor": function () {},
  "destroy": function () {},
  "toString": function () {},
  "_updatePan": function () {},
  "_removeLooping": function () {},
  "_addLooping": function () {},
  "_setDurationFromSource": function () {},
  "_handleCleanUp": function () {},
  "_cleanUpAudioNode": function () {},
  "_handleSoundReady": function () {},
  "_createAndPlayAudioNode": function () {},
  "_pause": function () {},
  "_resume": function () {},
  "_updateVolume": function () {},
  "_calculateCurrentPosition": function () {},
  "_updatePosition": function () {},
  "_handleLoop": function () {},
  "_updateDuration": function () {},
  "AbstractSoundInstance_constructor": function () {},
  "AbstractSoundInstance_destroy": function () {},
  "AbstractSoundInstance_toString": function () {},
  "AbstractSoundInstance__handleSoundReady": function () {},
  "AbstractSoundInstance__updateVolume": function () {},
  "AbstractSoundInstance__updatePan": function () {},
  "AbstractSoundInstance__updateDuration": function () {},
  "AbstractSoundInstance__setDurationFromSource": function () {},
  "AbstractSoundInstance__calculateCurrentPosition": function () {},
  "AbstractSoundInstance__updatePosition": function () {},
  "AbstractSoundInstance__removeLooping": function () {},
  "AbstractSoundInstance__addLooping": function () {},
  "AbstractSoundInstance__pause": function () {},
  "AbstractSoundInstance__resume": function () {},
  "AbstractSoundInstance__handleCleanUp": function () {},
  "AbstractSoundInstance__handleLoop": function () {},
  "play": function () {},
  "stop": function () {},
  "applyPlayProps": function () {},
  "getPaused": function () {},
  "setPaused": function () {},
  "setVolume": function () {},
  "getVolume": function () {},
  "setMuted": function () {},
  "getMuted": function () {},
  "setPan": function () {},
  "getPan": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getStartTime": function () {},
  "setStartTime": function () {},
  "getDuration": function () {},
  "setDuration": function () {},
  "setPlaybackResource": function () {},
  "getPlaybackResource": function () {},
  "getLoop": function () {},
  "setLoop": function () {},
  "_sendEvent": function () {},
  "_cleanUp": function () {},
  "_interrupt": function () {},
  "_beginPlaying": function () {},
  "_playFailed": function () {},
  "_handleSoundComplete": function () {},
  "_updateStartTime": function () {},
  "_handleStop": function () {},
  "EventDispatcher_constructor": function () {},
  "EventDispatcher_toString": function () {},
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "_dispatchEvent": function () {}
};
createjs.WebAudioPlugin.prototype = {
  "constructor": function () {},
  "toString": function () {},
  "_addPropsToClasses": function () {},
  "_updateVolume": function () {},
  "AbstractPlugin_constructor": function () {},
  "AbstractPlugin_toString": function () {},
  "AbstractPlugin__updateVolume": function () {},
  "register": function () {},
  "preload": function () {},
  "isPreloadStarted": function () {},
  "isPreloadComplete": function () {},
  "removeSound": function () {},
  "removeAllSounds": function () {},
  "create": function () {},
  "setVolume": function () {},
  "getVolume": function () {},
  "setMute": function () {},
  "_handlePreloadComplete": function () {},
  "_handlePreloadError": function () {}
};
createjs.HTMLAudioSoundInstance.prototype = {
  "constructor": function () {},
  "setMasterVolume": function () {},
  "setMasterMute": function () {},
  "toString": function () {},
  "_removeLooping": function () {},
  "_addLooping": function () {},
  "_handleCleanUp": function () {},
  "_beginPlaying": function () {},
  "_handleSoundReady": function () {},
  "_handleTagReady": function () {},
  "_pause": function () {},
  "_resume": function () {},
  "_updateVolume": function () {},
  "_calculateCurrentPosition": function () {},
  "_updatePosition": function () {},
  "_handleSetPositionSeek": function () {},
  "_handleAudioSpriteLoop": function () {},
  "_handleLoop": function () {},
  "_updateStartTime": function () {},
  "_updateDuration": function () {},
  "_setDurationFromSource": function () {},
  "AbstractSoundInstance_constructor": function () {},
  "AbstractSoundInstance_toString": function () {},
  "AbstractSoundInstance__beginPlaying": function () {},
  "AbstractSoundInstance__handleSoundReady": function () {},
  "AbstractSoundInstance__updateVolume": function () {},
  "AbstractSoundInstance__updateStartTime": function () {},
  "AbstractSoundInstance__updateDuration": function () {},
  "AbstractSoundInstance__setDurationFromSource": function () {},
  "AbstractSoundInstance__calculateCurrentPosition": function () {},
  "AbstractSoundInstance__updatePosition": function () {},
  "AbstractSoundInstance__removeLooping": function () {},
  "AbstractSoundInstance__addLooping": function () {},
  "AbstractSoundInstance__pause": function () {},
  "AbstractSoundInstance__resume": function () {},
  "AbstractSoundInstance__handleCleanUp": function () {},
  "AbstractSoundInstance__handleLoop": function () {},
  "play": function () {},
  "stop": function () {},
  "destroy": function () {},
  "applyPlayProps": function () {},
  "getPaused": function () {},
  "setPaused": function () {},
  "setVolume": function () {},
  "getVolume": function () {},
  "setMuted": function () {},
  "getMuted": function () {},
  "setPan": function () {},
  "getPan": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getStartTime": function () {},
  "setStartTime": function () {},
  "getDuration": function () {},
  "setDuration": function () {},
  "setPlaybackResource": function () {},
  "getPlaybackResource": function () {},
  "getLoop": function () {},
  "setLoop": function () {},
  "_sendEvent": function () {},
  "_cleanUp": function () {},
  "_interrupt": function () {},
  "_playFailed": function () {},
  "_handleSoundComplete": function () {},
  "_updatePan": function () {},
  "_handleStop": function () {},
  "EventDispatcher_constructor": function () {},
  "EventDispatcher_toString": function () {},
  "addEventListener": function () {},
  "on": function () {},
  "removeEventListener": function () {},
  "off": function () {},
  "removeAllEventListeners": function () {},
  "dispatchEvent": function () {},
  "hasEventListener": function () {},
  "willTrigger": function () {},
  "_dispatchEvent": function () {}
};
createjs.HTMLAudioPlugin.prototype = {
  "constructor": function () {},
  "register": function () {},
  "removeSound": function () {},
  "create": function () {},
  "toString": function () {},
  "setMute": function () {},
  "getVolume": function () {},
  "setVolume": function () {},
  "AbstractPlugin_constructor": function () {},
  "AbstractPlugin_register": function () {},
  "AbstractPlugin_removeSound": function () {},
  "AbstractPlugin_create": function () {},
  "AbstractPlugin_setVolume": function () {},
  "AbstractPlugin_getVolume": function () {},
  "AbstractPlugin_setMute": function () {},
  "AbstractPlugin_toString": function () {},
  "preload": function () {},
  "isPreloadStarted": function () {},
  "isPreloadComplete": function () {},
  "removeAllSounds": function () {},
  "_handlePreloadComplete": function () {},
  "_handlePreloadError": function () {},
  "_updateVolume": function () {}
};
