var filepicker = {
  "errors": {},
  "setKey": function () {},
  "setResponsiveOptions": function () {},
  "pick": function () {},
  "pickFolder": function () {},
  "pickMultiple": function () {},
  "pickAndStore": function () {},
  "read": function () {},
  "write": function () {},
  "writeUrl": function () {},
  "export": function () {},
  "exportFile": function () {},
  "processImage": function () {},
  "store": function () {},
  "storeUrl": function () {},
  "stat": function () {},
  "metadata": function () {},
  "remove": function () {},
  "convert": function () {},
  "constructWidget": function () {},
  "makeDropPane": function () {},
  "FilepickerException": {
    "isClass": {}
  },
  "responsive": function () {},
  "version": {},
  "services": {},
  "base64": {}
};