var L = {
  "Control": {
    "Locate": {
      "extend": function () {},
      "include": function () {},
      "mergeOptions": function () {},
      "addInitHook": function () {},
      "__super__": {},
      "Zoom": {
        "extend": function () {},
        "include": function () {},
        "mergeOptions": function () {},
        "addInitHook": function () {},
        "__super__": {}
      },
      "Attribution": {
        "extend": function () {},
        "include": function () {},
        "mergeOptions": function () {},
        "addInitHook": function () {},
        "__super__": {},
        "Zoom": {
          "extend": function () {},
          "include": function () {},
          "mergeOptions": function () {},
          "addInitHook": function () {},
          "__super__": {}
        }
      },
      "Scale": {
        "extend": function () {},
        "include": function () {},
        "mergeOptions": function () {},
        "addInitHook": function () {},
        "__super__": {},
        "Zoom": {
          "extend": function () {},
          "include": function () {},
          "mergeOptions": function () {},
          "addInitHook": function () {},
          "__super__": {}
        },
        "Attribution": {
          "extend": function () {},
          "include": function () {},
          "mergeOptions": function () {},
          "addInitHook": function () {},
          "__super__": {},
          "Zoom": {
            "extend": function () {},
            "include": function () {},
            "mergeOptions": function () {},
            "addInitHook": function () {},
            "__super__": {}
          }
        }
      },
      "Layers": {
        "extend": function () {},
        "include": function () {},
        "mergeOptions": function () {},
        "addInitHook": function () {},
        "__super__": {},
        "Zoom": {
          "extend": function () {},
          "include": function () {},
          "mergeOptions": function () {},
          "addInitHook": function () {},
          "__super__": {}
        },
        "Attribution": {
          "extend": function () {},
          "include": function () {},
          "mergeOptions": function () {},
          "addInitHook": function () {},
          "__super__": {},
          "Zoom": {
            "extend": function () {},
            "include": function () {},
            "mergeOptions": function () {},
            "addInitHook": function () {},
            "__super__": {}
          }
        },
        "Scale": {
          "extend": function () {},
          "include": function () {},
          "mergeOptions": function () {},
          "addInitHook": function () {},
          "__super__": {},
          "Zoom": {
            "extend": function () {},
            "include": function () {},
            "mergeOptions": function () {},
            "addInitHook": function () {},
            "__super__": {}
          },
          "Attribution": {
            "extend": function () {},
            "include": function () {},
            "mergeOptions": function () {},
            "addInitHook": function () {},
            "__super__": {},
            "Zoom": {
              "extend": function () {},
              "include": function () {},
              "mergeOptions": function () {},
              "addInitHook": function () {},
              "__super__": {}
            }
          }
        }
      }
    }
  },
  "control": {
    "locate": function () {}
  },
  "Locate": {
    "extend": function () {},
    "include": function () {},
    "mergeOptions": function () {},
    "addInitHook": function () {},
    "__super__": {},
    "Zoom": {
      "extend": function () {},
      "include": function () {},
      "mergeOptions": function () {},
      "addInitHook": function () {},
      "__super__": {}
    },
    "Attribution": {
      "extend": function () {},
      "include": function () {},
      "mergeOptions": function () {},
      "addInitHook": function () {},
      "__super__": {},
      "Zoom": {
        "extend": function () {},
        "include": function () {},
        "mergeOptions": function () {},
        "addInitHook": function () {},
        "__super__": {}
      }
    },
    "Scale": {
      "extend": function () {},
      "include": function () {},
      "mergeOptions": function () {},
      "addInitHook": function () {},
      "__super__": {},
      "Zoom": {
        "extend": function () {},
        "include": function () {},
        "mergeOptions": function () {},
        "addInitHook": function () {},
        "__super__": {}
      },
      "Attribution": {
        "extend": function () {},
        "include": function () {},
        "mergeOptions": function () {},
        "addInitHook": function () {},
        "__super__": {},
        "Zoom": {
          "extend": function () {},
          "include": function () {},
          "mergeOptions": function () {},
          "addInitHook": function () {},
          "__super__": {}
        }
      }
    },
    "Layers": {
      "extend": function () {},
      "include": function () {},
      "mergeOptions": function () {},
      "addInitHook": function () {},
      "__super__": {},
      "Zoom": {
        "extend": function () {},
        "include": function () {},
        "mergeOptions": function () {},
        "addInitHook": function () {},
        "__super__": {}
      },
      "Attribution": {
        "extend": function () {},
        "include": function () {},
        "mergeOptions": function () {},
        "addInitHook": function () {},
        "__super__": {},
        "Zoom": {
          "extend": function () {},
          "include": function () {},
          "mergeOptions": function () {},
          "addInitHook": function () {},
          "__super__": {}
        }
      },
      "Scale": {
        "extend": function () {},
        "include": function () {},
        "mergeOptions": function () {},
        "addInitHook": function () {},
        "__super__": {},
        "Zoom": {
          "extend": function () {},
          "include": function () {},
          "mergeOptions": function () {},
          "addInitHook": function () {},
          "__super__": {}
        },
        "Attribution": {
          "extend": function () {},
          "include": function () {},
          "mergeOptions": function () {},
          "addInitHook": function () {},
          "__super__": {},
          "Zoom": {
            "extend": function () {},
            "include": function () {},
            "mergeOptions": function () {},
            "addInitHook": function () {},
            "__super__": {}
          }
        }
      }
    }
  }
};
L.Control.Locate.prototype = {
  "constructor": function () {},
  "options": function () {},
  "initialize": function () {},
  "_activate": function () {},
  "_deactivate": function () {},
  "drawMarker": function () {},
  "createMarker": function () {},
  "updateMarker": function () {},
  "removeMarker": function () {},
  "onAdd": function () {},
  "bindEvents": function () {},
  "start": function () {},
  "stop": function () {},
  "_onLocationError": function () {},
  "_onLocationFound": function () {},
  "_startFollowing": function () {},
  "_stopFollowing": function () {},
  "_isOutsideMapBounds": function () {},
  "_toggleContainerStyle": function () {},
  "_setClasses": function () {},
  "_cleanClasses": function () {},
  "_resetVariables": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Attribution.prototype = {
  "constructor": function () {},
  "options": function () {},
  "initialize": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "setPrefix": function () {},
  "addAttribution": function () {},
  "removeAttribution": function () {},
  "_update": function () {},
  "_onLayerAdd": function () {},
  "_onLayerRemove": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Attribution.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Scale.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_addScales": function () {},
  "_update": function () {},
  "_updateScales": function () {},
  "_updateMetric": function () {},
  "_updateImperial": function () {},
  "_getScaleWidth": function () {},
  "_getRoundNum": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Scale.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Scale.Attribution.prototype = {
  "constructor": function () {},
  "options": function () {},
  "initialize": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "setPrefix": function () {},
  "addAttribution": function () {},
  "removeAttribution": function () {},
  "_update": function () {},
  "_onLayerAdd": function () {},
  "_onLayerRemove": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Scale.Attribution.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Layers.prototype = {
  "constructor": function () {},
  "options": function () {},
  "initialize": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "addBaseLayer": function () {},
  "addOverlay": function () {},
  "removeLayer": function () {},
  "_initLayout": function () {},
  "_addLayer": function () {},
  "_update": function () {},
  "_onLayerChange": function () {},
  "_createRadioElement": function () {},
  "_addItem": function () {},
  "_onInputClick": function () {},
  "_expand": function () {},
  "_collapse": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Layers.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Layers.Attribution.prototype = {
  "constructor": function () {},
  "options": function () {},
  "initialize": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "setPrefix": function () {},
  "addAttribution": function () {},
  "removeAttribution": function () {},
  "_update": function () {},
  "_onLayerAdd": function () {},
  "_onLayerRemove": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Layers.Attribution.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Layers.Scale.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_addScales": function () {},
  "_update": function () {},
  "_updateScales": function () {},
  "_updateMetric": function () {},
  "_updateImperial": function () {},
  "_getScaleWidth": function () {},
  "_getRoundNum": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Layers.Scale.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Layers.Scale.Attribution.prototype = {
  "constructor": function () {},
  "options": function () {},
  "initialize": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "setPrefix": function () {},
  "addAttribution": function () {},
  "removeAttribution": function () {},
  "_update": function () {},
  "_onLayerAdd": function () {},
  "_onLayerRemove": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Control.Locate.Layers.Scale.Attribution.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.prototype = {
  "constructor": function () {},
  "options": function () {},
  "initialize": function () {},
  "_activate": function () {},
  "_deactivate": function () {},
  "drawMarker": function () {},
  "createMarker": function () {},
  "updateMarker": function () {},
  "removeMarker": function () {},
  "onAdd": function () {},
  "bindEvents": function () {},
  "start": function () {},
  "stop": function () {},
  "_onLocationError": function () {},
  "_onLocationFound": function () {},
  "_startFollowing": function () {},
  "_stopFollowing": function () {},
  "_isOutsideMapBounds": function () {},
  "_toggleContainerStyle": function () {},
  "_setClasses": function () {},
  "_cleanClasses": function () {},
  "_resetVariables": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Attribution.prototype = {
  "constructor": function () {},
  "options": function () {},
  "initialize": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "setPrefix": function () {},
  "addAttribution": function () {},
  "removeAttribution": function () {},
  "_update": function () {},
  "_onLayerAdd": function () {},
  "_onLayerRemove": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Attribution.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Scale.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_addScales": function () {},
  "_update": function () {},
  "_updateScales": function () {},
  "_updateMetric": function () {},
  "_updateImperial": function () {},
  "_getScaleWidth": function () {},
  "_getRoundNum": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Scale.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Scale.Attribution.prototype = {
  "constructor": function () {},
  "options": function () {},
  "initialize": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "setPrefix": function () {},
  "addAttribution": function () {},
  "removeAttribution": function () {},
  "_update": function () {},
  "_onLayerAdd": function () {},
  "_onLayerRemove": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Scale.Attribution.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Layers.prototype = {
  "constructor": function () {},
  "options": function () {},
  "initialize": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "addBaseLayer": function () {},
  "addOverlay": function () {},
  "removeLayer": function () {},
  "_initLayout": function () {},
  "_addLayer": function () {},
  "_update": function () {},
  "_onLayerChange": function () {},
  "_createRadioElement": function () {},
  "_addItem": function () {},
  "_onInputClick": function () {},
  "_expand": function () {},
  "_collapse": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Layers.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Layers.Attribution.prototype = {
  "constructor": function () {},
  "options": function () {},
  "initialize": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "setPrefix": function () {},
  "addAttribution": function () {},
  "removeAttribution": function () {},
  "_update": function () {},
  "_onLayerAdd": function () {},
  "_onLayerRemove": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Layers.Attribution.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Layers.Scale.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_addScales": function () {},
  "_update": function () {},
  "_updateScales": function () {},
  "_updateMetric": function () {},
  "_updateImperial": function () {},
  "_getScaleWidth": function () {},
  "_getRoundNum": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Layers.Scale.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Layers.Scale.Attribution.prototype = {
  "constructor": function () {},
  "options": function () {},
  "initialize": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "setPrefix": function () {},
  "addAttribution": function () {},
  "removeAttribution": function () {},
  "_update": function () {},
  "_onLayerAdd": function () {},
  "_onLayerRemove": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
L.Locate.Layers.Scale.Attribution.Zoom.prototype = {
  "constructor": function () {},
  "options": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "_zoomIn": function () {},
  "_zoomOut": function () {},
  "_createButton": function () {},
  "_updateDisabled": function () {},
  "_initHooks": function () {},
  "callInitHooks": function () {},
  "initialize": function () {},
  "getPosition": function () {},
  "setPosition": function () {},
  "getContainer": function () {},
  "addTo": function () {},
  "removeFrom": function () {},
  "_refocusOnMap": function () {}
};
