/**********************************************************************
 * Extern for WordCloud
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var WordCloud = {
  "isSupported": {},
  "minFontSize": {},
  "stop": function () { }
};
/**********************************************************************
 * End Generated Extern for WordCloud
/**********************************************************************/