var L = {
  "MarkerClusterGroup": function () {},
  "markerClusterGroup": function () {},
  "MarkerCluster": function () {},
  "MarkerClusterNonAnimated": function () {},
  "Marker": function () {},
};

L.MarkerClusterGroup.prototype = {
  "addLayer": function () {},
  "addLayers": function () {},
  "callInitHooks": function () {},
  "clearLayers": function () {},
  "constructor": function () {},
  "eachLayer": function () {},
  "fire": function () {},
  "getBounds": function () {},
  "getLayer": function () {},
  "getLayers": function () {},
  "getVisibleParent": function () {},
  "hasLayer": function () {},
  "initialize": function () {},
  "listens": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "options": {},
  "refreshClusters": function () {},
  "removeLayer": function () {},
  "removeLayers": function () {},
  "unspiderfy": function () {},
  "zoomToShowLayer": function () {},
  "_addLayer": function () {},
  "_animationAddLayerNonAnimated": function () {},
  "_animationEnd": function () {},
  "_animationZoomOutSingle": function () {},
  "_arraySplice": function () {},
  "_bindEvents": function () {},
  "_checkBoundsMaxLat": function () {},
  "_childMarkerDragEnd": function () {},
  "_childMarkerDragStart": function () {},
  "_childMarkerMoved": function () {},
  "_defaultIconCreateFunction": function () {},
  "_enqueue": function () {},
  "_extractNonGroupLayers": function () {},
  "_flagParentsIconsNeedUpdate": function () {},
  "_forceLayout": function () {},
  "_generateInitialClusters": function () {},
  "_getExpandedVisibleBounds": function () {},
  "_hideCoverage": function () {},
  "_initHooks": {},
  "_isOrIsParent": function () {},
  "_mapBoundsInfinite": {},
  "_mergeSplitClusters": function () {},
  "_moveChild": function () {},
  "_moveEnd": function () {},
  "_noAnimation": {},
  "_noanimationUnspiderfy": function () {},
  "_overrideMarkerIcon": function () {},
  "_processQueue": function () {},
  "_refreshClustersIcons": function () {},
  "_refreshSingleMarkerModeMarkers": function () {},
  "_removeFromGridUnclustered": function () {},
  "_removeLayer": function () {},
  "_showCoverage": function () {},
  "_spiderfied" : {},
  "_spiderfierOnAdd": function () {},
  "_spiderfierOnRemove": function () {},
  "_unbindEvents": function () {},
  "_unspiderfy": function () {},
  "_unspiderfyLayer": function (layer) {},
  "_unspiderfyWrapper": function () {},
  "_unspiderfyZoomAnim": function () {},
  "_unspiderfyZoomStart": function () {},
  "_withAnimation": {},
  "_zoomEnd": function () {},
  "_zoomOrSpiderfy": function () {},
};

L.MarkerCluster.prototype = {
  "callInitHooks": function () {},
  "constructor": function () {},
  "createIcon": function () {},
  "createShadow": function () {},
  "getAllChildMarkers": function () {},
  "getBounds": function () {},
  "getChildCount": function () {},
  "getConvexHull": function () {},
  "initialize": function () {},
  "options": {},
  "spiderfy": function () {},
  "unspiderfy": function () {},
  "zoomToBounds": function () {},
  "_2PI": {},
  "_addChild": function () {},
  "_addToMap": function () {},
  "_animationSpiderfy": function () {},
  "_animationUnspiderfy": function () {},
  "_circleFootSeparation": {},
  "_circleSpiralSwitchover": {},
  "_circleStartAngle": {},
  "_generatePointsCircle": function () {},
  "_generatePointsSpiral": function () {},
  "_initHooks": {},
  "_isSingleParent": function () {},
  "_noanimationUnspiderfy": function () {},
  "_recalculateBounds": function () {},
  "_recursively": function () {},
  "_recursivelyAddChildrenToMap": function () {},
  "_recursivelyAnimateChildrenIn": function () {},
  "_recursivelyAnimateChildrenInAndAddSelfToMap": function () {},
  "_recursivelyBecomeVisible": function () {},
  "_recursivelyRemoveChildrenFromMap": function () {},
  "_recursivelyRestoreChildPositions": function () {},
  "_resetBounds": function () {},
  "_restorePosition": function () {},
  "_setClusterCenter": function () {},
  "_spiralFootSeparation": {},
  "_spiralLengthFactor": {},
  "_spiralLengthStart": {},
  "_updateIcon": function () {},
};

L.MarkerClusterNonAnimated.prototype = {
  "callInitHooks": function () {},
  "constructor": function () {},
  "options": {},
  "_animationSpiderfy": function () {},
  "_animationUnspiderfy": function () {},
  "_initHooks": {},
};

L.Marker.prototype = {
  "callInitHooks": function () {},
  "clusterHide": function () {},
  "clusterShow": function () {},
  "constructor": function () {},
  "getElement": function () {},
  "getEvents": function () {},
  "getLatLng": function () {},
  "initialize": function () {},
  "onAdd": function () {},
  "onRemove": function () {},
  "options": {},
  "refreshIconOptions": function () {},
  "setIcon": function () {},
  "setLatLng": function () {},
  "setOpacity": function () {},
  "setZIndexOffset": function () {},
  "toGeoJSON": function () {},
  "update": function () {},
  "_animateZoom": function () {},
  "_bringToFront": function () {},
  "_getPopupAnchor": function () {},
  "_getTooltipAnchor": function () {},
  "_initHooks": {},
  "_initIcon": function () {},
  "_initInteraction": function () {},
  "_removeIcon": function () {},
  "_removeShadow": function () {},
  "_resetZIndex": function () {},
  "_setPos": function () {},
  "_updateOpacity": function () {},
  "_updateZIndex": function () {},
};
