/**********************************************************************
 * Extern for IOTA
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var IOTA = function () {};
IOTA.prototype = {
  "changeNode": function () {},
  "setSettings": function () {}
};
/**********************************************************************
 * End Generated Extern for IOTA
/**********************************************************************/
