var CustomElements = {
  "flags": {},
  "addModule": function () {},
  "initializeModules": function () {},
  "hasNative": {},
  "isIE": {},
  "useNative": {},
  "forDocumentTree": function () {},
  "forSubtree": function () {},
  "hasPolyfillMutations": {},
  "hasThrottledAttached": {},
  "watchShadow": function () {},
  "upgradeDocumentTree": function () {},
  "upgradeDocument": function () {},
  "upgradeSubtree": function () {},
  "upgradeAll": function () {},
  "attached": function () {},
  "takeRecords": function () {},
  "upgrade": function () {},
  "upgradeWithDefinition": function () {},
  "implementPrototype": function () {},
  "registry": {},
  "instanceof": function () {},
  "reservedTagList": {},
  "getRegisteredDefinition": function () {},
  "ready": {},
  "readyTime": {}
};
