// Generated by http://www.dotnetwise.com/Code/Externs/
//
// Loaded JS:
// * https://cdnjs.cloudflare.com/ajax/libs/react/15.0.0/react.js
// * https://rawgit.com/JedWatson/react-input-autosize/master/dist/react-input-autosize.min.js
var AutosizeInput = {
    "displayName": {},
    "propTypes": {
        "value": function () {},
        "defaultValue": function () {},
        "onChange": function () {},
        "style": function () {},
        "className": function () {},
        "minWidth": function () {},
        "inputStyle": function () {},
        "inputClassName": function () {},
        "placeholder": function () {},
        "placeholderIsMinWidth": function () {}
    },
    "getDefaultProps": function () {},
    "defaultProps": {
        "minWidth": {}
    }
}
