// Bignumber.js 2.1.4
// http://mikemcl.github.io/bignumber.js/

var BigNumber = {
  "another": function () {},
  "ROUND_UP": {},
  "ROUND_DOWN": {},
  "ROUND_CEIL": {},
  "ROUND_FLOOR": {},
  "ROUND_HALF_UP": {},
  "ROUND_HALF_DOWN": {},
  "ROUND_HALF_EVEN": {},
  "ROUND_HALF_CEIL": {},
  "ROUND_HALF_FLOOR": {},
  "EUCLID": {},
  "config": function () {},
  "max": function () {},
  "min": function () {},
  "random": function () {}
};

BigNumber.prototype = {
  "abs": function () {},
  "absoluteValue": function () {},
  "ceil": function () {},
  "cmp": function () {},
  "comparedTo": function () {},
  "dp": function () {},
  "decimalPlaces": function () {},
  "div": function () {},
  "dividedBy": function () {},
  "divToInt": function () {},
  "dividedToIntegerBy": function () {},
  "eq": function () {},
  "equals": function () {},
  "floor": function () {},
  "gt": function () {},
  "greaterThan": function () {},
  "gte": function () {},
  "greaterThanOrEqualTo": function () {},
  "isFinite": function () {},
  "isInt": function () {},
  "isInteger": function () {},
  "isNaN": function () {},
  "isNeg": function () {},
  "isNegative": function () {},
  "isZero": function () {},
  "lt": function () {},
  "lessThan": function () {},
  "lte": function () {},
  "lessThanOrEqualTo": function () {},
  "sub": function () {},
  "minus": function () {},
  "mod": function () {},
  "modulo": function () {},
  "neg": function () {},
  "negated": function () {},
  "add": function () {},
  "plus": function () {},
  "sd": function () {},
  "precision": function () {},
  "round": function () {},
  "shift": function () {},
  "sqrt": function () {},
  "squareRoot": function () {},
  "mul": function () {},
  "times": function () {},
  "toDigits": function () {},
  "toExponential": function () {},
  "toFixed": function () {},
  "toFormat": function () {},
  "toFraction": function () {},
  "toNumber": function () {},
  "pow": function () {},
  "toPower": function () {},
  "toPrecision": function () {},
  "toString": function () {},
  "trunc": function () {},
  "truncated": function () {},
  "toJSON": function () {},
  "valueOf": function () {}
};
