// Generated manually following the Javascript Adapter Reference
// https://www.keycloak.org/docs/latest/securing_apps/#javascript-adapter-reference
var Keycloak = {
    "authenticated": {},
    "token": {},
    "tokenParsed": {},
    "subject": {},
    "idToken": {},
    "idTokenParsed": {},
    "realmAccess": {},
    "resourceAccess": {},
    "refreshToken": {},
    "refreshTokenParsed": {},
    "timeSkew": {},
    "responseMode": {},
    "flow": {},
    "adapter": {},
    "responseType": {},
    "init": function(options) {},
    "login": function(options) {},
    "createLoginUrl": function(options) {},
    "logout": function(options) {},
    "createLogoutUrl": function(options) {},
    "register": function(options) {},
    "createRegisterUrl": function(options) {},
    "accountManagement": function() {},
    "createAccountUrl": function(options) {},
    "hasRealmRole": function(role) {},
    "hasResourceRole": function(role,resource) {},
    "loadUserProfile": function() {},
    "isTokenExpired": function(minValidity) {},
    "updateToken": function(minValidity) {},
    "clearToken": function() {},
    "onReady": function(authenticated) {},
    "onAuthSuccess": function() {},
    "onAuthError": function() {},
    "onAuthRefreshSuccess": function() {},
    "onAuthRefreshError": function() {},
    "onAuthLogout": function() {},
    "onTokenExpired": function() {}
};
