
var CSV = {};
CSV.RELAXED;
CSV.IGNORE_RECORD_LENGTH;
CSV.IGNORE_QUOTES;
CSV.LINE_FEED_OK;
CSV.CARRIAGE_RETURN_OK;
CSV.DETECT_TYPES;
CSV.IGNORE_QUOTE_WHITESPACE;
CSV.DEBUG;
CSV.COLUMN_SEPARATOR;
CSV.ERROR_EOF;
CSV.ERROR_CHAR;
CSV.ERROR_EOL;
CSV.WARN_SPACE;
CSV.parse = function(str) {};
CSV.stream = function() {};
